"use client";

import { createClient, type Session } from "@supabase/supabase-js";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./conversion.module.css";

type Prospect={id:string;company_name:string;slug:string;status:string;demo_status:string;demo_config:Record<string,unknown>|null;fit_score:number;industry:string|null;city:string|null;country:string|null};
type ConversionPath="full_system"|"group_platform"|"hold";
type ConversionStatus="draft"|"approved"|"sent";
type Conversion={version:string;status:ConversionStatus;path:ConversionPath;title:string;objective:string;pilotEvidence:string;clientFeedback:string;productionScope:string;modules:string;rolesPermissions:string;integrations:string;migration:string;implementationPhases:string;timeline:string;priceMin:number;priceMax:number;recommendedPrice:number;subscriptionSar:number;commercialNote:string;exclusions:string;groupExpansion:string;nextStep:string;gateOverride:boolean;gateOverrideReason:string;updatedAt?:string;approvedAt?:string;sentAt?:string};

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!;
const supabase=createClient(supabaseUrl,supabaseKey);

function asObject(v:unknown):Record<string,unknown>{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function asString(v:unknown){return typeof v==="string"?v:"";}
function asNumber(v:unknown,fallback=0){return typeof v==="number"&&Number.isFinite(v)?v:fallback;}
function asBool(v:unknown,fallback=false){return typeof v==="boolean"?v:fallback;}
function lines(v:string){return v.split(/\n+/).map(x=>x.trim()).filter(Boolean);}
function money(v:number){return `SAR ${v.toLocaleString("en-US")}`;}

function readConversion(config:Record<string,unknown>|null):Conversion|null{
  const c=asObject(config?.fullSystemConversion); if(!Object.keys(c).length)return null;
  const rawStatus=asString(c.status); const rawPath=asString(c.path);
  return {version:asString(c.version)||"conversion-v1",status:rawStatus==="approved"||rawStatus==="sent"?rawStatus:"draft",path:rawPath==="group_platform"||rawPath==="hold"?rawPath:"full_system",title:asString(c.title),objective:asString(c.objective),pilotEvidence:asString(c.pilotEvidence),clientFeedback:asString(c.clientFeedback),productionScope:asString(c.productionScope),modules:asString(c.modules),rolesPermissions:asString(c.rolesPermissions),integrations:asString(c.integrations),migration:asString(c.migration),implementationPhases:asString(c.implementationPhases),timeline:asString(c.timeline),priceMin:asNumber(c.priceMin),priceMax:asNumber(c.priceMax),recommendedPrice:asNumber(c.recommendedPrice),subscriptionSar:asNumber(c.subscriptionSar),commercialNote:asString(c.commercialNote),exclusions:asString(c.exclusions),groupExpansion:asString(c.groupExpansion),nextStep:asString(c.nextStep),gateOverride:asBool(c.gateOverride),gateOverrideReason:asString(c.gateOverrideReason),updatedAt:asString(c.updatedAt),approvedAt:asString(c.approvedAt),sentAt:asString(c.sentAt)};
}

function inferConversion(prospect:Prospect):Conversion{
  const config=asObject(prospect.demo_config); const d=asObject(config.discovery); const delivery=asObject(config.pilotDelivery); const commercial=asObject(config.commercialRecommendation); const model=asObject(config.commercialModel); const group=asObject(config.groupArchitecture);
  const metricEvidence=asString(delivery.metricEvidence); const clientFeedback=asString(delivery.clientFeedback); const workflow=asString(delivery.pilotWorkflow)||asString(d.pilotWorkflow);
  const modules=asString(d.requestedModules)||"Tenders\nQuotations\nOrders\nWarehouse\nSupply / fulfilment\nInvoices\nCollection\nManagement Overview";
  const groupStatus=asString(group.status); const groupValidated=groupStatus==="validated"||groupStatus==="approved";
  const path:ConversionPath=groupValidated&&asString(delivery.conversionDecision)==="group_platform"?"group_platform":"full_system";
  const min=asNumber(commercial.implementationRangeMin,30000); const max=asNumber(commercial.implementationRangeMax,60000); const estimate=asNumber(commercial.implementationEstimate,Math.round((min+max)/2)); const sub=asNumber(commercial.recommendedProductionSubscriptionSar,750);
  const currentSystems=asString(d.currentSystems); const integrationRequirements=asString(d.integrationRequirements);
  const roles=path==="group_platform"?asString(group.permissionModel):"Company Admin\nOperations / Tenders\nWarehouse / Supply\nFinance / Collection\nRead-only Management\nAccess is restricted by role and approved responsibility.";
  const groupExpansion=Object.keys(group).length?`Group Platform remains a separate expansion path unless explicitly selected and validated. ${asString(group.architectureNotes)}`:"Future branches or companies are scoped separately after the production system is stable.";
  return {version:"conversion-v1",status:"draft",path,title:`${prospect.company_name} — ${path==="group_platform"?"Group Platform":"Full Operational System"}`,objective:`Convert the validated Pilot into a secure production operating system using confirmed Pilot evidence, production requirements and agreed integration boundaries.`,pilotEvidence:metricEvidence,clientFeedback,productionScope:`Productionize the validated workflow: ${workflow||"the agreed operating workflow"}. Add production-grade roles, permissions, auditability, real operating data, exception controls, management visibility, support and the agreed integration boundaries.`,modules,rolesPermissions:roles,integrations:integrationRequirements||currentSystems?`Existing environment: ${currentSystems||"to be confirmed"}. ${integrationRequirements||"Define system-of-record ownership, API direction, synchronization and write-back before implementation."}`:"No live third-party integration is assumed until the production system boundaries are confirmed.",migration:"Pilot data moves into production where appropriate. Historical migration, cleansing and bulk import are scoped separately based on source quality and volume.",implementationPhases:path==="group_platform"?"1. Production scope lock\n2. Core company system productionization\n3. Integrations and permissions\n4. Validate each additional company separately\n5. Group Overview and consolidated KPIs\n6. Production acceptance and support handover":"1. Production scope lock\n2. Roles, permissions and production data model\n3. Core operational modules\n4. Odoo / Zoho / ERP integrations as agreed\n5. QA, user acceptance and training\n6. Production go-live and support handover",timeline:path==="group_platform"?"Estimated after group discovery and final entity scope are validated.":"Estimated 6–10 weeks after production scope, access, data and integration requirements are confirmed.",priceMin:min,priceMax:max,recommendedPrice:estimate,subscriptionSar:sub,commercialNote:"Internal pricing architecture is a working commercial recommendation until the production scope is confirmed. The client-facing proposal should show the agreed fixed price, not an uncontrolled estimate range.",exclusions:"Unvalidated group companies or workflows\nThird-party licenses and vendor/API fees\nLarge historical data cleansing unless explicitly scoped\nCustom modules added after scope lock\nChanges to Odoo/Zoho/ERP outside agreed integration endpoints\nOn-site work or hardware unless explicitly included",groupExpansion,nextStep:"Review Pilot evidence with the client, confirm the production scope and integrations, then approve the fixed full-system proposal at the human gate.",gateOverride:false,gateOverrideReason:""};
}

function Field({label,value,onChange,rows=4,hint,placeholder}:{label:string;value:string;onChange:(v:string)=>void;rows?:number;hint?:string;placeholder?:string}){return <label className={styles.field}><span>{label}</span>{hint?<small>{hint}</small>:null}<textarea rows={rows} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>;}

export default function ConversionBuilder(){
  const[session,setSession]=useState<Session|null>(null);const[authReady,setAuthReady]=useState(false);const[role,setRole]=useState<string|null>(null);const[prospects,setProspects]=useState<Prospect[]>([]);const[selectedId,setSelectedId]=useState("");const[search,setSearch]=useState("");const[conversion,setConversion]=useState<Conversion|null>(null);const[snapshot,setSnapshot]=useState("");const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState("");

  const load=useCallback(async(active:Session)=>{setLoading(true);setNotice("");const{data:roleRow,error:roleError}=await supabase.from("user_roles").select("role").eq("user_id",active.user.id).maybeSingle();if(roleError||roleRow?.role!=="admin"){setRole(roleRow?.role??null);setNotice(roleError?.message??"Administrator access required.");setLoading(false);return;}setRole("admin");const{data,error}=await supabase.from("systems_outreach_prospects").select("id,company_name,slug,status,demo_status,demo_config,fit_score,industry,city,country").order("updated_at",{ascending:false});if(error){setNotice(error.message);setLoading(false);return;}const next=(data??[]) as Prospect[];setProspects(next);const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("prospect"):null;setSelectedId(current=>{if(requested){const match=next.find(x=>x.id===requested||x.slug===requested);if(match)return match.id;}if(current&&next.some(x=>x.id===current))return current;return next.find(x=>Object.keys(asObject(x.demo_config?.pilotDelivery)).length>0)?.id??"";});setLoading(false);},[]);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true);if(data.session)void load(data.session);});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);setAuthReady(true);if(next)void load(next);});return()=>subscription.unsubscribe();},[load]);

  const selected=prospects.find(x=>x.id===selectedId)??null;
  useEffect(()=>{if(!selected){setConversion(null);setSnapshot("");return;}const saved=readConversion(selected.demo_config);const next=saved??inferConversion(selected);setConversion(next);setSnapshot(saved?JSON.stringify(saved):"");setNotice("");},[selectedId,selected?.demo_config]);
  const visible=useMemo(()=>{const q=search.trim().toLowerCase();return prospects.filter(x=>{const hasDelivery=Object.keys(asObject(x.demo_config?.pilotDelivery)).length>0;const hasConversion=Object.keys(asObject(x.demo_config?.fullSystemConversion)).length>0;if(!hasDelivery&&!hasConversion)return false;return !q||[x.company_name,x.industry,x.city,x.country,x.status].filter(Boolean).join(" ").toLowerCase().includes(q);});},[prospects,search]);
  const delivery=asObject(selected?.demo_config?.pilotDelivery);const acceptance=asString(delivery.acceptance);const evidence=asString(delivery.metricEvidence);const gateReady=acceptance==="accepted"&&evidence.trim().length>0;const overrideReady=Boolean(conversion?.gateOverride&&conversion.gateOverrideReason.trim().length>8);const canApprove=gateReady||overrideReady;const dirty=conversion?JSON.stringify(conversion)!==snapshot:false;
  const setField=(key:keyof Conversion,value:string|number|boolean)=>setConversion(current=>current?({...current,[key]:value} as Conversion):current);

  const save=async(status?:ConversionStatus,sent=false)=>{if(!selected||!conversion||!session||saving)return;if((status==="approved"||sent)&&!canApprove){setNotice("Approval is locked until the Pilot is accepted with evidence, or a documented internal override is provided.");return;}setSaving(true);setNotice("");const now=new Date().toISOString();const nextStatus=sent?"sent":status??conversion.status;const next:Conversion={...conversion,version:"conversion-v1",status:nextStatus,updatedAt:now,approvedAt:nextStatus==="approved"||nextStatus==="sent"?(conversion.approvedAt||now):undefined,sentAt:sent?now:conversion.sentAt};const config=asObject(selected.demo_config);const nextConfig={...config,fullSystemConversion:next};const{error}=await supabase.from("systems_outreach_prospects").update({demo_config:nextConfig,updated_at:now}).eq("id",selected.id);if(error){setNotice(error.message);setSaving(false);return;}await supabase.from("systems_outreach_events").insert({prospect_id:selected.id,channel:"internal",event_type:sent?"full_system_proposal_sent_recorded":nextStatus==="approved"?"full_system_proposal_approved":"full_system_conversion_saved",status:"recorded",content:sent?`Full-system proposal recorded as sent. Path=${next.path}; price=${next.recommendedPrice} SAR; subscription=${next.subscriptionSar} SAR/month.`:nextStatus==="approved"?`Full-system proposal approved at human gate. Path=${next.path}; fixed working price=${next.recommendedPrice} SAR.`:`Full-system conversion draft saved. Gate ready=${gateReady}; override=${overrideReady}.`});setConversion(next);setSnapshot(JSON.stringify(next));setNotice(sent?"Recorded as sent. No email or message was sent automatically.":nextStatus==="approved"?"Approved. The private client proposal is now available.":"Conversion draft saved. Nothing was sent to the client.");await load(session);setSaving(false);};

  if(!authReady)return <main className={styles.page}><div className={styles.center}>Preparing Full-System Conversion…</div></main>;
  if(!session)return <main className={styles.page}><div className={styles.center}><h1>Administrator sign-in required.</h1><Link href="/admin">Go to admin →</Link></div></main>;
  if(role!=="admin")return <main className={styles.page}><div className={styles.center}><h1>Administrator permission required.</h1><p>{notice}</p></div></main>;

  return <main className={styles.page}><div className={styles.shell}>
    <header className={styles.header}><div><div className={styles.brand}><span>Lab</span>Narrative</div><p className={styles.eyebrow}>Systems · pilot → production</p><h1>Full-System Conversion Builder</h1><p>Use measured Pilot evidence to convert a validated workflow into a production Full Operational System or, only when group discovery is ready, a Group Platform.</p></div><div className={styles.headerActions}><Link className={styles.secondaryButton} href="/admin/systems-outreach/delivery">Pilot Delivery</Link><Link className={styles.secondaryButton} href="/admin/systems-outreach/discovery/commercial">Pricing</Link><Link className={styles.secondaryButton} href="/admin/systems-outreach/discovery/group">Group Architecture</Link></div></header>
    {notice?<div className={styles.notice}>{notice}</div>:null}
    <section className={styles.layout}><aside className={styles.sidebar}><div className={styles.sideHead}><div><span>Conversion opportunities</span><strong>{visible.length}</strong></div><button disabled={loading} onClick={()=>session&&void load(session)}>{loading?"…":"Refresh"}</button></div><input className={styles.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company…"/><div className={styles.prospectList}>{visible.map(item=>{const c=readConversion(item.demo_config);const d=asObject(item.demo_config?.pilotDelivery);return <button key={item.id} onClick={()=>setSelectedId(item.id)} className={`${styles.prospect} ${item.id===selectedId?styles.prospectActive:""}`}><span><strong>{item.company_name}</strong><b>{item.fit_score}</b></span><small>{c?`conversion ${c.status}`:`pilot ${asString(d.acceptance)||"not accepted"}`}</small></button>;})}</div></aside>
      <section className={styles.workspace}>{selected&&conversion?<>
        <div className={styles.companyHead}><div><p>{selected.industry||"Systems client"}</p><h2>{selected.company_name}</h2><span>{[selected.city,selected.country].filter(Boolean).join(" · ")}</span></div><div className={styles.priceBox}><span>Internal working price</span><strong>{money(conversion.recommendedPrice)}</strong><small>Range {money(conversion.priceMin)} – {money(conversion.priceMax).replace("SAR ","")} · production {money(conversion.subscriptionSar)}/mo</small></div></div>
        <section className={`${styles.gate} ${gateReady?styles.gateReady:overrideReady?styles.gateOverride:""}`}><div><span>{gateReady?"Evidence gate passed":overrideReady?"Internal override active":"Conversion gate locked"}</span><strong>{gateReady?"Pilot acceptance and measurable evidence are present.":overrideReady?"Approval is allowed only because an override reason is documented.":"Do not approve the production proposal yet."}</strong><p>Pilot acceptance: {acceptance||"not recorded"}. Evidence: {evidence.trim()?"recorded":"missing"}. Client proposal stays hidden until human approval.</p></div><div className={styles.gateControl}><label><input type="checkbox" checked={conversion.gateOverride} onChange={e=>setField("gateOverride",e.target.checked)}/> Internal override</label>{conversion.gateOverride?<input type="text" value={conversion.gateOverrideReason} onChange={e=>setField("gateOverrideReason",e.target.value)} placeholder="Document why approval is justified"/>:null}</div></section>
        <section className={styles.snapshot}><div><span>Pilot acceptance</span><strong>{acceptance||"Not ready"}</strong></div><div><span>Evidence</span><strong>{evidence.trim()?"Recorded":"Missing"}</strong></div><div><span>Path</span><strong>{conversion.path.replaceAll("_"," ")}</strong></div><div><span>Status</span><strong>{conversion.status}</strong></div></section>

        <section className={styles.section}><div className={styles.sectionHead}><span>01</span><div><h3>Conversion decision</h3><p>Choose the next production path from confirmed scope, not aspiration.</p></div></div><div className={styles.threeCol}><label className={styles.selectField}><span>Conversion path</span><select value={conversion.path} onChange={e=>setField("path",e.target.value)}><option value="full_system">Full Operational System</option><option value="group_platform">Group Platform</option><option value="hold">Hold / extend validation</option></select></label><label className={styles.inputField}><span>Fixed working price · SAR</span><input type="number" min="0" value={conversion.recommendedPrice} onChange={e=>setField("recommendedPrice",Number(e.target.value)||0)}/></label><label className={styles.inputField}><span>Production subscription · SAR/month</span><input type="number" min="0" value={conversion.subscriptionSar} onChange={e=>setField("subscriptionSar",Number(e.target.value)||0)}/></label></div><div className={styles.twoCol}><Field label="Proposal title" value={conversion.title} onChange={v=>setField("title",v)} rows={2}/><Field label="Objective" value={conversion.objective} onChange={v=>setField("objective",v)} rows={4}/></div></section>

        <section className={styles.section}><div className={styles.sectionHead}><span>02</span><div><h3>Pilot evidence</h3><p>The production sale should be justified by what the Pilot proved.</p></div></div><div className={styles.twoCol}><Field label="Measured Pilot evidence" value={conversion.pilotEvidence} onChange={v=>setField("pilotEvidence",v)} rows={8} placeholder="Evidence copied from Pilot Delivery appears here after measurement."/><Field label="Client feedback" value={conversion.clientFeedback} onChange={v=>setField("clientFeedback",v)} rows={8}/></div></section>

        <section className={styles.section}><div className={styles.sectionHead}><span>03</span><div><h3>Production scope</h3><p>Define what becomes real production software.</p></div></div><Field label="Production scope summary" value={conversion.productionScope} onChange={v=>setField("productionScope",v)} rows={6}/><div className={styles.twoCol}><Field label="Modules · one per line" value={conversion.modules} onChange={v=>setField("modules",v)} rows={10}/><Field label="Roles & permissions" value={conversion.rolesPermissions} onChange={v=>setField("rolesPermissions",v)} rows={10}/><Field label="Integrations" value={conversion.integrations} onChange={v=>setField("integrations",v)} rows={8}/><Field label="Migration / production data" value={conversion.migration} onChange={v=>setField("migration",v)} rows={8}/></div></section>

        <section className={styles.section}><div className={styles.sectionHead}><span>04</span><div><h3>Implementation & commercial boundaries</h3><p>Turn the internal estimate into a controlled fixed proposal after scope confirmation.</p></div></div><div className={styles.twoCol}><Field label="Implementation phases" value={conversion.implementationPhases} onChange={v=>setField("implementationPhases",v)} rows={10}/><Field label="Timeline" value={conversion.timeline} onChange={v=>setField("timeline",v)} rows={5}/><Field label="Commercial note" value={conversion.commercialNote} onChange={v=>setField("commercialNote",v)} rows={6}/><Field label="Exclusions / separately scoped" value={conversion.exclusions} onChange={v=>setField("exclusions",v)} rows={9}/></div><label className={styles.inputField}><span>Internal range · min / max</span><div className={styles.twoCol}><input type="number" min="0" value={conversion.priceMin} onChange={e=>setField("priceMin",Number(e.target.value)||0)}/><input type="number" min="0" value={conversion.priceMax} onChange={e=>setField("priceMax",Number(e.target.value)||0)}/></div></label></section>

        <section className={styles.section}><div className={styles.sectionHead}><span>05</span><div><h3>Expansion path</h3><p>Keep group expansion visible without hiding it inside the first production contract.</p></div></div><div className={styles.twoCol}><Field label="Group / future expansion" value={conversion.groupExpansion} onChange={v=>setField("groupExpansion",v)} rows={7}/><Field label="Recommended next step" value={conversion.nextStep} onChange={v=>setField("nextStep",v)} rows={7}/></div></section>

        <section className={styles.preview}><div className={styles.previewHead}><div><span>Client proposal preview</span><h3>{conversion.title}</h3></div><strong>{money(conversion.recommendedPrice)}</strong></div><p>{conversion.objective}</p><div className={styles.previewGrid}><div><span>Production path</span><strong>{conversion.path.replaceAll("_"," ")}</strong></div><div><span>Recurring production</span><strong>{money(conversion.subscriptionSar)} / month</strong></div><div><span>Modules</span><strong>{lines(conversion.modules).length} scoped areas</strong></div><div><span>Timeline</span><strong>{conversion.timeline}</strong></div></div></section>

        <div className={styles.saveBar}><div><strong>{dirty?"Unsaved conversion changes":`Conversion ${conversion.status}`}</strong><span>Save is internal. Approval unlocks the private proposal. Record Sent never sends outreach automatically.</span></div><div className={styles.saveActions}><button className={styles.secondaryButton} disabled={saving||!dirty} onClick={()=>void save("draft")}>Save Draft</button>{conversion.status==="approved"||conversion.status==="sent"?<Link className={styles.secondaryButton} target="_blank" href={`/systems/proposals/${selected.slug}/full`}>Open client proposal ↗</Link>:null}<button className={styles.primaryButton} disabled={saving||dirty||conversion.status!=="draft"||!canApprove} onClick={()=>void save("approved")}>Approve Full-System Proposal</button><button className={styles.sentButton} disabled={saving||dirty||conversion.status!=="approved"} onClick={()=>void save("sent",true)}>Record Sent</button></div></div>
      </>:<div className={styles.empty}>Select a Pilot delivery opportunity to prepare the production conversion.</div>}</section>
    </section>
  </div></main>;
}
