-- Authorized workflow verification; all fixtures and audit events are rolled back.
begin;
do $test$
declare actor uuid;reviewer uuid;org uuid;company uuid;product uuid;other_company uuid;foreign_product uuid;pid uuid;current_pid uuid;src uuid;checks uuid[];rid uuid;rec uuid;fid uuid;signal_id uuid;rev integer;denied boolean;sources uuid[];r jsonb;collection jsonb;notice_id uuid;
begin
 select user_id,organization_id into actor,org from public.pvos_memberships where role='admin' order by organization_id,user_id limit 1;
 select user_id into reviewer from public.pvos_memberships where organization_id=org and user_id<>actor and role in ('admin','qppv','deputy_qppv') order by user_id limit 1;
 if reviewer is null then
  select user_id into reviewer from public.pvos_memberships where user_id<>actor order by user_id limit 1;
  if reviewer is null then raise exception 'Verification requires two existing accounts';end if;
  insert into public.pvos_memberships(organization_id,user_id,role) values(org,reviewer,'deputy_qppv') on conflict(organization_id,user_id) do update set role='deputy_qppv';
 end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 insert into public.pvos_companies(organization_id,name) values(org,'Rollback authority verification') returning id into company;
 insert into public.pvos_companies(organization_id,name) values(org,'Rollback authority other company') returning id into other_company;
 insert into public.pvos_products(company_id,brand_name,active_ingredient) values(company,'Verification product','Verification ingredient') returning id into product;
 insert into public.pvos_products(company_id,brand_name) values(other_company,'Other verification product') returning id into foreign_product;
 select array_agg(id order by source_key) into sources from public.pvos_authority_sources where organization_id=org and source_key in ('sfda','mhra_dsu');
 denied:=false;begin perform public.pvos_configure_authority_monitoring(company,actor,actor,sources,'Verification SOP v1','Verification form v1','Rollback scope',date_trunc('month',now())::date,true);exception when others then denied:=true;end;
 if not denied then raise exception 'Same owner/reviewer accepted';end if;
 perform public.pvos_configure_authority_monitoring(company,actor,reviewer,sources,'Verification SOP v1','Verification form v1','Rollback applicability rationale',(date_trunc('month',now())-interval '1 month')::date,true);
 if public.pvos_materialize_authority_periods(company)<>0 then raise exception 'Period creation is not idempotent';end if;
 select id,revision into pid,rev from public.pvos_authority_periods where company_id=company and period_start=(date_trunc('month',now())-interval '1 month')::date;
 select id into current_pid from public.pvos_authority_periods where company_id=company and period_start=date_trunc('month',now())::date;
 denied:=false;begin update public.pvos_tasks set status='complete',completed_at=now() where id=(select task_id from public.pvos_authority_periods where id=pid);exception when others then denied:=true;end;
 if not denied then raise exception 'Generic task completion bypassed authority checks and independent review';end if;
 denied:=false;begin perform public.pvos_submit_authority_period(current_pid,1,'Premature conclusion');exception when others then denied:=true;end;
 if not denied then raise exception 'Open period submitted as fully reviewed';end if;
 denied:=false;begin perform public.pvos_submit_authority_period(pid,rev,'Sources unchecked');exception when others then denied:=true;end;
 if not denied then raise exception 'Unchecked sources allowed submission';end if;
 select array_agg(id order by id) into checks from public.pvos_authority_checks where period_id=pid;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);
 denied:=false;begin perform public.pvos_record_authority_check(pid,rev,checks[1],'no_relevant_findings','Reviewer preparing own evidence');exception when others then denied:=true;end;
 if not denied then raise exception 'Assigned reviewer prepared their own source evidence';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform public.pvos_record_authority_check(pid,rev,checks[1],'unavailable','Rollback failure and follow-up note');
 select revision into rev from public.pvos_authority_periods where id=pid;
 denied:=false;begin perform public.pvos_submit_authority_period(pid,rev,'Source unavailable');exception when others then denied:=true;end;
 if not denied then raise exception 'Unavailable source allowed completion';end if;
 denied:=false;begin perform public.pvos_record_authority_finding(pid,rev,checks[1],null,null,'Rollback finding','https://example.invalid/evidence',array[foreign_product],'relevant','Rollback rationale');exception when others then denied:=true;end;
 if not denied then raise exception 'Cross-company product accepted';end if;
 fid:=public.pvos_record_authority_finding(pid,rev,checks[1],null,null,'Rollback finding','https://example.invalid/evidence',array[product],'needs_review','Rollback requires review');
 select revision into rev from public.pvos_authority_periods where id=pid;
 denied:=false;begin perform public.pvos_record_authority_check(pid,rev,checks[1],'no_relevant_findings','Contradictory outcome');exception when others then denied:=true;end;
 if not denied then raise exception 'Unresolved finding hidden as no relevant findings';end if;
 perform public.pvos_record_authority_finding(pid,rev,checks[1],fid,null,'Rollback finding','https://example.invalid/evidence',array[product],'relevant','Rollback human assessment');
 select revision into rev from public.pvos_authority_periods where id=pid;
 signal_id:=public.pvos_escalate_authority_finding(fid,rev);
 if not exists(select 1 from public.pvos_signal_reviews where id=signal_id and authority_finding_id=fid and literature_item_id is null and assessment='unassessed') then raise exception 'Authority escalation fabricated a literature row or signal decision';end if;
 select revision into rev from public.pvos_authority_periods where id=pid;
 denied:=false;begin perform public.pvos_record_authority_finding(pid,rev,checks[1],fid,null,'Changed evidence','https://example.invalid/changed',array[product],'not_relevant','Changed');exception when others then denied:=true;end;
 if not denied then raise exception 'Escalated evidence could change underneath signal assessment';end if;
 perform public.pvos_record_authority_check(pid,rev,checks[1],'findings','Rollback source scope and finding conclusion');
 select revision into rev from public.pvos_authority_periods where id=pid;
 perform public.pvos_record_authority_check(pid,rev,checks[2],'no_relevant_findings','Rollback manual archive/period check');
 select revision into rev from public.pvos_authority_periods where id=pid;
 rid:=public.pvos_submit_authority_period(pid,rev,'Rollback monitoring conclusion');
 denied:=false;begin perform public.pvos_record_authority_check(pid,rev,checks[1],'no_relevant_findings','Submitted evidence overwrite');exception when others then denied:=true;end;
 if not denied then raise exception 'Pending evidence mutable';end if;
 denied:=false;begin perform public.pvos_decide_authority_review(rid,'approved','Self approval');exception when others then denied:=true;end;
 if not denied then raise exception 'Self approval accepted';end if;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',reviewer,'role','authenticated')::text,true);
 perform public.pvos_decide_authority_review(rid,'returned','Rollback return reason');
 if not exists(select 1 from public.pvos_authority_periods where id=pid and status='returned') then raise exception 'Return did not reopen preparation';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 select revision into rev from public.pvos_authority_periods where id=pid;
 denied:=false;begin perform public.pvos_record_authority_check(pid,null,checks[2],'no_relevant_findings','Missing revision');exception when others then denied:=true;end;
 if not denied then raise exception 'Null revision bypassed concurrency guard';end if;
 rid:=public.pvos_submit_authority_period(pid,rev,'Rollback revised conclusion');
 select revision into rev from public.pvos_authority_periods where id=pid;
 perform public.pvos_withdraw_authority_submission(pid,rev,'Rollback reviewer recovery');
 if not exists(select 1 from public.pvos_authority_reviews where id=rid and status='withdrawn' and assigned_to=reviewer and snapshot->'period'->>'id'=pid::text) then raise exception 'Withdrawal did not retain original recipient/evidence';end if;
 select revision into rev from public.pvos_authority_periods where id=pid;
 denied:=false;begin perform public.pvos_change_authority_reviewer(pid,rev,actor,'Self review');exception when others then denied:=true;end;
 if not denied then raise exception 'Reviewer change allowed owner to self-review';end if;
 perform public.pvos_change_authority_reviewer(pid,rev,reviewer,'Rollback recipient reconfirmation');
 select revision into rev from public.pvos_authority_periods where id=pid;
 rid:=public.pvos_submit_authority_period(pid,rev,'Rollback final conclusion');
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',reviewer,'role','authenticated')::text,true);
 rec:=public.pvos_decide_authority_review(rid,'approved','Rollback independent conclusion');
 if not exists(select 1 from public.pvos_authority_records where id=rec and snapshot->'first_review'->>'user_id'=actor::text and snapshot->'second_review'->>'user_id'=reviewer::text and snapshot_sha256=encode(extensions.digest(snapshot::text,'sha256'),'hex')) then raise exception 'Frozen dual-review identities/hash missing';end if;
 if (select count(*) from public.pvos_authority_reviews where period_id=pid)<>3 then raise exception 'Returned review cycle not retained';end if;
 if not exists(select 1 from public.pvos_tasks t join public.pvos_authority_periods p on p.task_id=t.id where p.id=pid and t.status='complete') then raise exception 'Monitoring task did not complete after independent approval';end if;
 denied:=false;begin update public.pvos_tasks set status='in_progress',completed_at=null where id=(select task_id from public.pvos_authority_periods where id=pid);exception when others then denied:=true;end;
 if not denied then raise exception 'Generic task reopening changed the approved monitoring record';end if;
 denied:=false;begin update public.pvos_authority_records set snapshot='{}' where id=rec;exception when others then denied:=true;end;
 if not denied then raise exception 'Approved record mutable';end if;
 denied:=false;begin perform public.pvos_assess_authority_signal(signal_id,'potential_signal','closed','Rollback rationale');exception when others then denied:=true;end;
 if not denied then raise exception 'Potential signal prematurely closed';end if;
 perform public.pvos_assess_authority_signal(signal_id,'needs_more_info','under_review','Rollback additional evidence required');
 -- Atomic collector deduplication and version history use an isolated source fixture.
 insert into public.pvos_authority_sources(organization_id,source_key,name,url,method,feed_url,coverage_note) values(org,'rollback_collector','Rollback source','https://example.invalid','atom','https://example.invalid/feed','Rollback only') returning id into src;
 collection:=public.pvos_register_authority_collection(src,now(),200,repeat('a',64),jsonb_build_array(jsonb_build_object('title','Rollback notice','url','https://example.invalid/notice','published_at',now(),'summary','Rollback summary','content_sha256',repeat('b',64))));
 if (collection->>'new_count')::int<>1 or not (collection->>'baseline')::boolean then raise exception 'Initial collector baseline wrong';end if;
 collection:=public.pvos_register_authority_collection(src,now(),200,repeat('a',64),jsonb_build_array(jsonb_build_object('title','Rollback notice','url','https://example.invalid/notice','published_at',now(),'summary','Rollback summary','content_sha256',repeat('b',64))));
 if (collection->>'new_count')::int<>0 then raise exception 'Unchanged notice duplicated';end if;
 collection:=public.pvos_register_authority_collection(src,now(),200,repeat('c',64),jsonb_build_array(jsonb_build_object('title','Rollback changed notice','url','https://example.invalid/notice','published_at',now(),'summary','Changed summary','content_sha256',repeat('d',64))));
 if (collection->>'new_count')::int<>1 or (select count(*) from public.pvos_authority_notices where source_id=src)<>2 then raise exception 'Changed notice version not retained';end if;
 -- Simulate an earlier committed submission and a later-collected notice; approval must stop.
 insert into public.pvos_authority_reviews(organization_id,company_id,period_id,cycle,sent_by,sent_email,sent_at,submission_note,assigned_to,assigned_email,snapshot)
 values(org,company,current_pid,1,actor,(select email from auth.users where id=actor),now()-interval '1 minute','Rollback earlier submission',reviewer,(select email from auth.users where id=reviewer),'{}') returning id into rid;
 update public.pvos_authority_periods set status='pending_review' where id=current_pid;
 select source_id into src from public.pvos_authority_checks where period_id=current_pid limit 1;
 insert into public.pvos_authority_collection_runs(organization_id,source_id,status,entry_count,new_count) values(org,src,'ok',1,1) returning id into notice_id;
 insert into public.pvos_authority_notices(organization_id,source_id,title,url,published_at,summary,content_sha256,baseline,collection_run_id) values(org,src,'Rollback late notice','https://example.invalid/late',now(),'Rollback new evidence',repeat('e',64),false,notice_id);
 denied:=false;begin perform public.pvos_decide_authority_review(rid,'approved','New notice not reviewed');exception when others then denied:=true;end;
 if not denied then raise exception 'Post-submission notice did not block approval';end if;
 perform set_config('test.authority_foreign_org',(select id::text from public.pvos_organizations o where exists(select 1 from public.pvos_authority_sources where organization_id=o.id) and not exists(select 1 from public.pvos_memberships where organization_id=o.id and user_id=reviewer) limit 1),true);
 perform set_config('test.authority_org',org::text,true);perform set_config('test.authority_company',company::text,true);perform set_config('test.authority_signal',signal_id::text,true);
 perform set_config('test.authority_task',(select task_id::text from public.pvos_authority_periods where id=current_pid),true);
end $test$;
set local role authenticated;
do $test$
declare denied boolean;
begin
 if not exists(select 1 from public.pvos_authority_records where company_id=current_setting('test.authority_company')::uuid) then raise exception 'Authorized record read failed';end if;
 denied:=false;begin update public.pvos_authority_checks set outcome='no_relevant_findings' where company_id=current_setting('test.authority_company')::uuid;exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Client forged source checks directly';end if;
 if exists(select 1 from public.pvos_authority_sources where organization_id=nullif(current_setting('test.authority_foreign_org'),'')::uuid) then raise exception 'Cross-workspace sources visible under RLS';end if;
 denied:=false;begin perform public.pvos_add_manual_authority_source(nullif(current_setting('test.authority_foreign_org'),'')::uuid,'Unauthorized authority','https://example.invalid','Unauthorized scope');exception when others then denied:=true;end;
 if not denied then raise exception 'Cross-workspace authority creation allowed';end if;
 denied:=false;begin update public.pvos_signal_reviews set reviewer_user_id=auth.uid() where id=current_setting('test.authority_signal')::uuid;exception when others then denied:=true;end;
 if not denied then raise exception 'Client forged authority signal actor';end if;
 denied:=false;begin update public.pvos_tasks set status='complete',completed_at=now() where id=current_setting('test.authority_task')::uuid;exception when others then denied:=true;end;
 if not denied then raise exception 'Authenticated task completion bypassed pending authority review';end if;
 if has_function_privilege('anon','public.pvos_submit_authority_period(uuid,integer,text)','EXECUTE') or has_function_privilege('authenticated','public.pvos_register_authority_collection(uuid,timestamptz,integer,text,jsonb)','EXECUTE') or has_function_privilege('authenticated','public.pvos_invoke_authority_monitor(boolean)','EXECUTE') then raise exception 'Function grants too broad';end if;
end $test$;
reset role;
select 'PASS: monthly scope/tasks, source gaps, human relevance, cross-company products, independent review/return/resubmit, retained evidence/hash, signal escalation, immutable versions, atomic deduplication and authenticated API controls' as verification;
rollback;
