import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={
  "Access-Control-Allow-Origin":"https://platform.labnarrative.com",
  "Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods":"POST, OPTIONS",
};
const GATEWAY_ORIGIN="https://trader-gateway.labnarrative.com";
const PROVIDERS=["bybit","okx","coinbase","kraken","kucoin"] as const;
type Provider=typeof PROVIDERS[number];
type Db=ReturnType<typeof createClient>;
type Json=Record<string,unknown>;
type Credentials=Record<string,string>;
let gatewayKey:CryptoKey|null=null;
let lastKrakenNonce=0n;

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}})}
function obj(v:unknown):Json{return v&&typeof v==="object"&&!Array.isArray(v)?v as Json:{}}
function arr(v:unknown):unknown[]{return Array.isArray(v)?v:[]}
function str(v:unknown){return String(v??"")}
function num(v:unknown,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function clean(e:unknown){return e instanceof Error?e.message:String(e||"unknown_error")}
function utf8(v:string){return new TextEncoder().encode(v)}
function base64(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function base64Url(bytes:Uint8Array){return base64(bytes).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"")}
function randomHex(n=16){return Array.from(crypto.getRandomValues(new Uint8Array(n))).map(b=>b.toString(16).padStart(2,"0")).join("")}
function nonceHex(){return randomHex(24)}
async function sha256(v:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",utf8(v)));return Array.from(d).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function hmac(secret:string,message:string,hash:"SHA-256"|"SHA-512"="SHA-256"){const k=await crypto.subtle.importKey("raw",utf8(secret),{name:"HMAC",hash},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",k,utf8(message)))}
async function hmacHex(secret:string,message:string){return Array.from(await hmac(secret,message)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function pemBytes(pem:string){const b64=pem.replace(/\\n/g,"\n").replace(/-----BEGIN [^-]+-----/g,"").replace(/-----END [^-]+-----/g,"").replace(/\s+/g,"");const raw=atob(b64);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function derLen(n:number){if(n<128)return new Uint8Array([n]);const a:number[]=[];while(n){a.unshift(n&255);n>>=8}return new Uint8Array([0x80|a.length,...a])}
function concat(...parts:Uint8Array[]){const out=new Uint8Array(parts.reduce((s,p)=>s+p.length,0));let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function der(tag:number,b:Uint8Array){return concat(new Uint8Array([tag]),derLen(b.length),b)}
function sec1ToPkcs8(sec1:Uint8Array){const version=new Uint8Array([2,1,0]);const ec=new Uint8Array([6,7,42,134,72,206,61,2,1]);const p256=new Uint8Array([6,8,42,134,72,206,61,3,1,7]);return der(0x30,concat(version,der(0x30,concat(ec,p256)),der(4,sec1)))}
function joseSig(sig:Uint8Array){if(sig.length===64)return sig;if(sig[0]!==0x30)throw new Error("coinbase_signature_format_failed");let o=1;let l=sig[o++];if(l&0x80)o+=l&0x7f;if(sig[o++]!==2)throw new Error("coinbase_signature_format_failed");let rl=sig[o++];if(rl&0x80){const c=rl&0x7f;rl=0;for(let i=0;i<c;i++)rl=(rl<<8)|sig[o++]}let r=sig.slice(o,o+rl);o+=rl;if(sig[o++]!==2)throw new Error("coinbase_signature_format_failed");let sl=sig[o++];if(sl&0x80){const c=sl&0x7f;sl=0;for(let i=0;i<c;i++)sl=(sl<<8)|sig[o++]}let s=sig.slice(o,o+sl);while(r.length>32&&r[0]===0)r=r.slice(1);while(s.length>32&&s[0]===0)s=s.slice(1);const out=new Uint8Array(64);out.set(r,32-r.length);out.set(s,64-s.length);return out}

async function realAccount(db:Db,userId:string){const {data,error}=await db.from("trader_accounts").select("id,owner_user_id").eq("owner_user_id",userId).eq("account_kind","real").eq("status","active").limit(1).maybeSingle();if(error)throw error;if(!data)throw new Error("real_account_required");return {id:String(data.id),owner_user_id:String(data.owner_user_id)}}
async function gatewayConfig(db:Db){const {data,error}=await db.from("trader_gateway_config").select("base_url,status,egress_ip,last_health_at,last_error").eq("name","binance").single();if(error)throw error;const x=obj(data);if(str(x.base_url)!==GATEWAY_ORIGIN||str(x.status)!=="ready")throw new Error("gateway_not_ready");return {baseUrl:GATEWAY_ORIGIN,egressIp:str(x.egress_ip),lastHealthAt:x.last_health_at??null,lastError:x.last_error??null}}
async function gatewaySigningKey(db:Db){if(gatewayKey)return gatewayKey;const {data,error}=await db.rpc("trader_gateway_read_signing_private_key");if(error||!data)throw new Error("gateway_signing_key_not_configured");gatewayKey=await crypto.subtle.importKey("pkcs8",pemBytes(String(data)),{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);return gatewayKey}
async function relay(db:Db,payload:Json){const cfg=await gatewayConfig(db);const raw=JSON.stringify(payload),ts=Date.now(),nce=nonceHex(),key=await gatewaySigningKey(db);const sig=new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,utf8(`${ts}\n${nce}\n${raw}`)));const r=await fetch(`${cfg.baseUrl}/relay`,{method:"POST",headers:{"content-type":"application/json","x-ln-timestamp":String(ts),"x-ln-nonce":nce,"x-ln-signature":base64(sig)},body:raw,signal:AbortSignal.timeout(12000)});const env=obj(await r.json().catch(()=>({})));if(!r.ok)throw new Error(`gateway_${r.status}:${str(env.error)||"relay_failed"}`);const status=num(env.upstreamStatus),body=str(env.upstreamBody);let parsed:unknown={};try{parsed=body?JSON.parse(body):{}}catch{parsed=body}return {status,body:parsed,headers:obj(env.upstreamHeaders)}}
async function direct(origin:string,method:string,path:string,headers:Record<string,string>={},body?:string){const r=await fetch(origin+path,{method,headers:{accept:"application/json",...headers},body,signal:AbortSignal.timeout(10000)});return {status:r.status,body:await r.json().catch(()=>({})) as unknown}}
async function transport(db:Db,origin:string,method:string,path:string,headers:Record<string,string>={},body?:string,viaGateway=false){if(viaGateway){return await relay(db,{requestId:crypto.randomUUID(),upstream:origin,method,path,query:"",headers,body:body??null,timeoutMs:10000})}return direct(origin,method,path,headers,body)}
function apiOk(provider:Provider,response:{status:number;body:unknown}){const root=obj(response.body);if(response.status<200||response.status>=300)throw new Error(`${provider}_http_${response.status}`);if(provider==="bybit"&&num(root.retCode)!==0)throw new Error(`bybit_${str(root.retCode)}:${str(root.retMsg)}`);if(provider==="okx"&&str(root.code)!=="0")throw new Error(`okx_${str(root.code)}:${str(root.msg)}`);if(provider==="kucoin"&&str(root.code)!=="200000")throw new Error(`kucoin_${str(root.code)}:${str(root.msg)}`);if(provider==="kraken"){const errors=arr(root.error).map(String).filter(Boolean);if(errors.length)throw new Error(`kraken_api:${errors.join(";")}`)}return root}

async function stored(db:Db,accountId:string,provider:Provider):Promise<Credentials>{const {data,error}=await db.rpc("trader_exchange_read_secret",{p_account_id:accountId,p_provider:provider});if(error||!data)throw new Error("credential_not_found");try{return JSON.parse(String(data)) as Credentials}catch{throw new Error("credential_not_found")}}
async function row(db:Db,accountId:string,provider:Provider){const {data,error}=await db.from("trader_exchange_connections").select("status,environment,api_key_last4,permission_read,permission_trade,permission_withdraw,ip_restricted,external_uid_last4,capabilities,metadata,last_verified_at,last_error").eq("account_id",accountId).eq("provider",provider).maybeSingle();if(error)throw error;return data}
function publicRow(x:any){return x?{status:x.status,environment:x.environment,apiKeyLast4:x.api_key_last4,permissionRead:x.permission_read,permissionTrade:x.permission_trade,permissionWithdraw:x.permission_withdraw,ipRestricted:x.ip_restricted,externalUidLast4:x.external_uid_last4,capabilities:x.capabilities||{},metadata:x.metadata||{},lastVerifiedAt:x.last_verified_at,lastError:x.last_error}:null}
async function persist(db:Db,userId:string,accountId:string,provider:Provider,credentials:Credentials,verified:Json){const now=new Date().toISOString(),key=str(verified.apiKey||credentials.apiKey||credentials.keyName),uid=str(verified.uid||verified.externalUid||"");const metadata={...obj(verified.metadata),gatewayEgressIp:verified.gatewayEgressIp??null,ipMatchesGateway:verified.ipMatchesGateway??null,permissionSummary:verified.permissionSummary??null};const up={account_id:accountId,owner_user_id:userId,provider,environment:str(verified.environment||"mainnet"),status:"pending",api_key_fingerprint:(await sha256(key)).slice(0,16),api_key_last4:key.slice(-4),permission_read:verified.permissionRead===true,permission_trade:verified.permissionTrade===true,permission_withdraw:false,ip_restricted:verified.ipRestricted==null?null:verified.ipRestricted===true,external_uid_last4:uid?uid.slice(-4):null,capabilities:{balances:true,spotOrders:verified.permissionTrade===true,liveExecution:false,readOnly:verified.permissionTrade!==true,tradeCredentialStored:verified.permissionTrade===true},metadata,last_verified_at:now,last_error:null,updated_at:now};const u=await db.from("trader_exchange_connections").upsert(up,{onConflict:"account_id,provider"});if(u.error)throw u.error;const s=await db.rpc("trader_exchange_store_secret",{p_account_id:accountId,p_owner_user_id:userId,p_provider:provider,p_secret:JSON.stringify(credentials)});if(s.error)throw new Error("credential_store_failed");const d=await db.from("trader_exchange_connections").update({status:"connected",updated_at:now}).eq("account_id",accountId).eq("provider",provider);if(d.error)throw d.error;return publicRow(await row(db,accountId,provider))}

async function bybitRequest(db:Db,c:Credentials,method:string,path:string,via=false){const ts=Date.now().toString(),recv="5000",query="",body="";const sign=await hmacHex(c.apiSecret,`${ts}${c.apiKey}${recv}${method==="GET"?query:body}`);return transport(db,"https://api.bybit.com",method,path,{"X-BAPI-API-KEY":c.apiKey,"X-BAPI-TIMESTAMP":ts,"X-BAPI-RECV-WINDOW":recv,"X-BAPI-SIGN":sign,"content-type":"application/json"},method==="GET"?undefined:body,via)}
async function verifyBybit(db:Db,c:Credentials,via=false){const root=apiOk("bybit",await bybitRequest(db,c,"GET","/v5/user/query-api",via));const result=obj(root.result),permissions=obj(result.permissions),spot=arr(permissions.Spot).map(String),wallet=arr(permissions.Wallet).map(String);const trade=num(result.readOnly)===0&&spot.includes("SpotTrade");const forbidden=[...wallet,...arr(permissions.ContractTrade).map(String),...arr(permissions.Options).map(String),...arr(permissions.Exchange).map(String)].filter(Boolean);if(num(result.readOnly)===0&&!trade)throw new Error("bybit_spot_trade_permission_required");if(forbidden.length)throw new Error(`bybit_unsafe_permissions:${forbidden.join(",")}`);const ips=arr(result.ips).map(String).filter(Boolean),g=await gatewayConfig(db);return {apiKey:c.apiKey,permissionRead:true,permissionTrade:trade,ipRestricted:ips.length>0,ipMatchesGateway:ips.includes(g.egressIp),gatewayEgressIp:g.egressIp,externalUid:result.userID||result.parentUid,environment:"mainnet",permissionSummary:trade?"Read + SpotTrade":"Read only",metadata:{readOnly:num(result.readOnly),spotPermissions:spot,ipAllowlist:ips,deadlineDay:result.deadlineDay??null,expiredAt:result.expiredAt??null}}}

async function okxRequest(db:Db,c:Credentials,method:string,path:string,via=false,body=""){const ts=new Date().toISOString(),pre=`${ts}${method}${path}${body}`,sign=base64(await hmac(c.apiSecret,pre));return transport(db,"https://www.okx.com",method,path,{"OK-ACCESS-KEY":c.apiKey,"OK-ACCESS-SIGN":sign,"OK-ACCESS-TIMESTAMP":ts,"OK-ACCESS-PASSPHRASE":c.passphrase,"content-type":"application/json"},body||undefined,via)}
async function verifyOkx(db:Db,c:Credentials,via=false){const root=apiOk("okx",await okxRequest(db,c,"GET","/api/v5/account/config",via)),info=obj(arr(root.data)[0]),perms=str(info.perm).split(",").map(x=>x.trim()).filter(Boolean);if(!perms.includes("read_only")&&!perms.includes("trade"))throw new Error("okx_read_permission_required");if(perms.includes("withdraw"))throw new Error("okx_withdraw_permission_forbidden");const ips=str(info.ip).split(",").map(x=>x.trim()).filter(Boolean),g=await gatewayConfig(db),trade=perms.includes("trade");return {apiKey:c.apiKey,permissionRead:true,permissionTrade:trade,ipRestricted:ips.length>0,ipMatchesGateway:ips.includes(g.egressIp),gatewayEgressIp:g.egressIp,externalUid:info.uid,environment:"mainnet",permissionSummary:perms.join(", "),metadata:{permissions:perms,ipAllowlist:ips,accountLevel:info.acctLv??null,label:info.label??null}}}

function cbPem(secret:string){const normalized=secret.replace(/\\n/g,"\n").trim();const match=normalized.match(/-----BEGIN ([A-Z ]+)-----([\s\S]+?)-----END \1-----/);if(!match)throw new Error("coinbase_invalid_private_key");const raw=atob(match[2].replace(/\s+/g,"")),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return match[1]==="PRIVATE KEY"?bytes:match[1]==="EC PRIVATE KEY"?sec1ToPkcs8(bytes):(()=>{throw new Error("coinbase_invalid_private_key")})()}
async function cbJwt(method:string,path:string,c:Credentials){const key=await crypto.subtle.importKey("pkcs8",cbPem(c.keySecret),{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);const now=Math.floor(Date.now()/1000),h=base64Url(utf8(JSON.stringify({alg:"ES256",typ:"JWT",kid:c.keyName,nonce:randomHex(16)}))),p=base64Url(utf8(JSON.stringify({iss:"cdp",nbf:now,exp:now+120,sub:c.keyName,uri:`${method} api.coinbase.com${path}`}))),input=`${h}.${p}`,sig=joseSig(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,utf8(input))));return `${input}.${base64Url(sig)}`}
async function coinbaseRequest(db:Db,c:Credentials,method:string,path:string,via=false,body=""){const token=await cbJwt(method,path,c);return transport(db,"https://api.coinbase.com",method,path,{Authorization:`Bearer ${token}`,"content-type":"application/json"},body||undefined,via)}
async function verifyCoinbase(db:Db,c:Credentials,via=false){const r=await coinbaseRequest(db,c,"GET","/api/v3/brokerage/key_permissions",via);if(r.status<200||r.status>=300)throw new Error(`coinbase_http_${r.status}`);const p=obj(r.body);if(p.can_view!==true)throw new Error("coinbase_view_permission_required");if(p.can_transfer===true)throw new Error("coinbase_transfer_permission_forbidden");return {apiKey:c.keyName,permissionRead:true,permissionTrade:p.can_trade===true,ipRestricted:null,ipMatchesGateway:null,gatewayEgressIp:(await gatewayConfig(db)).egressIp,externalUid:p.portfolio_uuid,environment:"advanced-trade",permissionSummary:p.can_trade===true?"View + Trade":"View only",metadata:{canView:p.can_view===true,canTrade:p.can_trade===true,canTransfer:p.can_transfer===true,portfolioType:p.portfolio_type??null}}}

function krakenNonce(){const now=BigInt(Date.now())*1000n;lastKrakenNonce=now>lastKrakenNonce?now:lastKrakenNonce+1n;return lastKrakenNonce.toString()}
function fromB64(v:string){const raw=atob(v.trim());return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function krakenRequest(db:Db,c:Credentials,path:string,via=false,extra:Record<string,string>={}){const nonce=krakenNonce(),params=new URLSearchParams({nonce,...extra}),body=params.toString(),hash=new Uint8Array(await crypto.subtle.digest("SHA-256",utf8(nonce+body))),key=await crypto.subtle.importKey("raw",fromB64(c.apiSecret),{name:"HMAC",hash:"SHA-512"},false,["sign"]),sig=new Uint8Array(await crypto.subtle.sign("HMAC",key,concat(utf8(path),hash)));return transport(db,"https://api.kraken.com","POST",path,{"API-Key":c.apiKey,"API-Sign":base64(sig),"content-type":"application/x-www-form-urlencoded"},body,via)}
async function verifyKraken(db:Db,c:Credentials,via=false){const root=apiOk("kraken",await krakenRequest(db,c,"/0/private/GetApiKeyInfo",via)),info=obj(root.result),perms=arr(info.permissions).map(String);if(!perms.includes("query-funds"))throw new Error("kraken_query_funds_required");const forbidden=["add-funds","withdraw-funds","earn-funds","add-withdraw-address","update-withdraw-address"].filter(x=>perms.includes(x));if(forbidden.length)throw new Error(`kraken_unsafe_permissions:${forbidden.join(",")}`);const hasModify=perms.includes("modify-trades"),hasClose=perms.includes("close-trades");if(hasModify!==hasClose)throw new Error("kraken_trade_permissions_must_include_create_and_cancel");const ips=arr(info.ipAllowlist).map(String).filter(Boolean),g=await gatewayConfig(db);return {apiKey:str(info.apiKey||c.apiKey),permissionRead:true,permissionTrade:hasModify&&hasClose,ipRestricted:ips.length>0,ipMatchesGateway:ips.includes(g.egressIp),gatewayEgressIp:g.egressIp,environment:"spot",permissionSummary:perms.join(", "),metadata:{permissions:perms,ipAllowlist:ips,apiKeyName:info.apiKeyName??null}}}

async function kucoinRequest(db:Db,c:Credentials,method:string,path:string,via=false,body=""){const ts=Date.now().toString(),sign=base64(await hmac(c.apiSecret,`${ts}${method}${path}${body}`)),pass=base64(await hmac(c.apiSecret,c.passphrase));return transport(db,"https://api.kucoin.com",method,path,{"KC-API-KEY":c.apiKey,"KC-API-SIGN":sign,"KC-API-TIMESTAMP":ts,"KC-API-PASSPHRASE":pass,"KC-API-KEY-VERSION":c.apiVersion||"3","content-type":"application/json"},body||undefined,via)}
async function verifyKucoinVersion(db:Db,c:Credentials,via=false):Promise<{c:Credentials;info:Json}>{let last="kucoin_invalid_credentials";for(const v of [c.apiVersion,"3","2"].filter(Boolean)){try{const candidate:Credentials={...c,apiVersion:v},root=apiOk("kucoin",await kucoinRequest(db,candidate,"GET","/api/v1/user/api-key",via)),info=obj(root.data);return {c:{...candidate,apiVersion:str(info.apiVersion||v)},info}}catch(e){last=clean(e)}}throw new Error(last)}
async function verifyKucoin(db:Db,c:Credentials,via=false){const found=await verifyKucoinVersion(db,c,via),info=found.info,perms=str(info.permission).split(",").map(x=>x.trim()).filter(Boolean);if(!perms.includes("General"))throw new Error("kucoin_general_permission_required");const allowed=new Set(["General","Spot"]),forbidden=perms.filter(x=>!allowed.has(x));if(forbidden.length)throw new Error(`kucoin_unsafe_permissions:${forbidden.join(",")}`);const trade=perms.includes("Spot"),g=await gatewayConfig(db);return {credentials:found.c,verified:{apiKey:found.c.apiKey,permissionRead:true,permissionTrade:trade,ipRestricted:null,ipMatchesGateway:null,gatewayEgressIp:g.egressIp,externalUid:info.uid,environment:"global",permissionSummary:perms.join(", "),metadata:{permissions:perms,apiVersion:found.c.apiVersion,region:info.region??null,siteType:info.siteType??null,isMaster:info.isMaster===true}}}}

async function verify(provider:Provider,db:Db,c:Credentials,via=false){if(provider==="bybit")return {credentials:c,verified:await verifyBybit(db,c,via)};if(provider==="okx")return {credentials:c,verified:await verifyOkx(db,c,via)};if(provider==="coinbase")return {credentials:c,verified:await verifyCoinbase(db,c,via)};if(provider==="kraken")return {credentials:c,verified:await verifyKraken(db,c,via)};return verifyKucoin(db,c,via)}
function credentialInput(provider:Provider,body:Json):Credentials{if(provider==="coinbase")return {keyName:str(body.keyName).trim(),keySecret:str(body.keySecret).trim()};if(provider==="okx"||provider==="kucoin")return {apiKey:str(body.apiKey).trim(),apiSecret:str(body.apiSecret).trim(),passphrase:str(body.passphrase).trim(),...(provider==="kucoin"?{apiVersion:str(body.apiVersion||"3")}: {})};return {apiKey:str(body.apiKey).trim(),apiSecret:str(body.apiSecret).trim()}}
function validCredentials(provider:Provider,c:Credentials){if(provider==="coinbase")return c.keyName.length>10&&c.keySecret.includes("PRIVATE KEY");if(provider==="okx"||provider==="kucoin")return c.apiKey.length>10&&c.apiSecret.length>10&&c.passphrase.length>=4;return c.apiKey.length>10&&c.apiSecret.length>10}

async function diagnostic(provider:Provider,db:Db,accountId:string){const connection:any=await row(db,accountId,provider);if(!connection||connection.status!=="connected")return {provider,connected:false,permission:false,gateway:false,tradeReady:false,error:"not_connected"};const c=await stored(db,accountId,provider);let directOk=false,gatewayOk=false,verified:Json|null=null,directError="",gatewayError="";try{const v=await verify(provider,db,c,false);verified=v.verified;directOk=true}catch(e){directError=clean(e)}try{const v=await verify(provider,db,c,true);verified=v.verified;gatewayOk=true}catch(e){gatewayError=clean(e)}const trade=Boolean(verified?.permissionTrade??connection.permission_trade),withdraw=Boolean(connection.permission_withdraw),ipMatch=verified?.ipMatchesGateway;const ipNeeded=["bybit","okx","kraken"].includes(provider);const tradeReady=trade&&!withdraw&&gatewayOk&&(!ipNeeded||ipMatch===true);return {provider,connected:true,direct:directOk,gateway:gatewayOk,permission:trade,withdrawalsDisabled:!withdraw,ipRestriction:verified?.ipRestricted??connection.ip_restricted,ipMatchesGateway:ipMatch??null,tradeReady,gatewayEgressIp:(await gatewayConfig(db)).egressIp,directError:directOk?null:directError,gatewayError:gatewayOk?null:gatewayError,permissionSummary:verified?.permissionSummary??obj(connection.metadata).permissionSummary??null}}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
  if(req.method!=="POST")return json({error:"method_not_allowed"},405);
  const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!service)return json({error:"server_configuration_missing"},500);
  const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({error:"unauthorized"},401);
  const {data:u,error:ue}=await db.auth.getUser(token);if(ue||!u.user)return json({error:"unauthorized"},401);
  try{
    const account=await realAccount(db,u.user.id),body=obj(await req.json().catch(()=>({}))),action=str(body.action||"status"),provider=str(body.provider).toLowerCase() as Provider;
    if(action==="gateway")return json({ok:true,gateway:await gatewayConfig(db)});
    if(action==="status_all"){const rows=await Promise.all(PROVIDERS.map(async p=>({provider:p,connection:publicRow(await row(db,account.id,p))})));return json({ok:true,connections:rows,gateway:await gatewayConfig(db)})}
    if(action==="diagnostics_all"){const checks=await Promise.all(PROVIDERS.map(async p=>{try{return await diagnostic(p,db,account.id)}catch(e){return {provider:p,connected:Boolean(await row(db,account.id,p)),tradeReady:false,error:clean(e)}}}));return json({ok:true,checks,gateway:await gatewayConfig(db)})}
    if(!PROVIDERS.includes(provider))return json({error:"unsupported_provider"},400);
    if(action==="status")return json({ok:true,provider,connection:publicRow(await row(db,account.id,provider)),gateway:await gatewayConfig(db)});
    if(action==="connect"||action==="upgrade"){
      const c=credentialInput(provider,body);if(!validCredentials(provider,c))return json({error:"invalid_credentials_format"},400);
      let result;try{result=await verify(provider,db,c,false)}catch(directError){try{result=await verify(provider,db,c,true)}catch(gatewayError){throw new Error(`${clean(directError)}|gateway:${clean(gatewayError)}`)}}
      const connection=await persist(db,u.user.id,account.id,provider,result.credentials,result.verified);return json({ok:true,provider,connection,gateway:await gatewayConfig(db)});
    }
    if(action==="diagnostics")return json({ok:true,check:await diagnostic(provider,db,account.id)});
    if(action==="disconnect"){const r=await db.from("trader_exchange_connections").update({status:"disconnected",permission_read:false,permission_trade:false,permission_withdraw:false,last_error:null,updated_at:new Date().toISOString()}).eq("account_id",account.id).eq("provider",provider);if(r.error)throw r.error;return json({ok:true,provider,connection:publicRow(await row(db,account.id,provider))})}
    return json({error:"unknown_action"},400);
  }catch(e){const m=clean(e);console.error("trader-multiexchange-control",m);return json({error:m.startsWith("bybit_")||m.startsWith("okx_")||m.startsWith("coinbase_")||m.startsWith("kraken_")||m.startsWith("kucoin_")||m.startsWith("gateway_")||m.includes("credential_")||m.includes("real_account_")?m:"multiexchange_control_failed"},400)}
});
