"use client";

import { createClient, type Session } from "@supabase/supabase-js";
import { useEffect, useMemo, useState } from "react";
import styles from "./supplier-quote-intake.module.css";

type Org={id:string;name:string};
type Tender={id:string;org_id:string;ref:string;buyer:string;title:string;deadline_at:string|null;status:string};
type Rfq={id:string;ref:string;supplier_name:string;supplier_vendor_no:string|null;status:string;item_count:number;reviewed_at:string|null};
type Intake={id:string;ref:string;rfq_id:string|null;supplier_name:string;supplier_vendor_no:string|null;supplier_quote_ref:string|null;quote_date:string|null;currency:string;valid_until:string|null;source_url:string|null;source_file_path:string|null;source_file_name:string|null;note:string|null;status:string;item_count:number;total_cost:number;reviewed_at:string|null;approved_at:string|null;created_at:string};
type SourceRow={sourcing_id:string;requirement_id:string;item_code:string|null;requested_item:string;quantity:number|null;unit:string|null;status:string;supplier_name:string|null;supplier_vendor_no:string|null;supplier_reference:string|null;quoted_unit_cost:number|null;currency:string;lead_time_days:number|null;moq:number|null;valid_until:string|null;source_url:string|null;note:string|null;suggested_manufacturer:string|null;suggested_catalog_no:string|null};
type QuoteItem={id:string;sourcing_id:string;requirement_id:string;item_code:string|null;requested_item:string;requested_quantity:number|null;unit:string|null;quoted_unit_cost:number;offered_quantity:number|null;moq:number|null;lead_time_days:number|null;manufacturer:string|null;manufacturer_catalog_no:string|null;note:string|null};
type CustomerQuote={id:string;ref:string;amount:number;items_count:number;priced_count:number;costed_count:number;gross_cost:number;gross_profit:number|null;gross_margin_pct:number|null;status:string;next_action:string|null};
type Draft={cost:string;offered:string;moq:string;lead:string;manufacturer:string;catalog:string;note:string};

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const money=(v:number|null|undefined,c="SAR")=>new Intl.NumberFormat("en-SA",{style:"currency",currency:c||"SAR",maximumFractionDigits:2}).format(Number(v||0));
const num=(v:number|null|undefined)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(Number(v||0));
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const safe=(s:string)=>s.replace(/[^a-zA-Z0-9._-]+/g,"-").slice(0,120);

export default function SupplierQuoteIntakeWorkspace(){
 const[session,setSession]=useState<Session|null>(null),[open,setOpen]=useState(false),[orgs,setOrgs]=useState<Org[]>([]),[orgId,setOrgId]=useState(""),[tenders,setTenders]=useState<Tender[]>([]),[tenderId,setTenderId]=useState("");
 const[rfqs,setRfqs]=useState<Rfq[]>([]),[intakes,setIntakes]=useState<Intake[]>([]),[quoteId,setQuoteId]=useState(""),[sourceRows,setSourceRows]=useState<SourceRow[]>([]),[items,setItems]=useState<QuoteItem[]>([]),[customerQuote,setCustomerQuote]=useState<CustomerQuote|null>(null);
 const[selectedRfq,setSelectedRfq]=useState(""),[manualSupplier,setManualSupplier]=useState(""),[manualVendor,setManualVendor]=useState(""),[supplierQuoteRef,setSupplierQuoteRef]=useState(""),[quoteDate,setQuoteDate]=useState(""),[validUntil,setValidUntil]=useState(""),[currency,setCurrency]=useState("SAR"),[sourceUrl,setSourceUrl]=useState(""),[note,setNote]=useState("");
 const[drafts,setDrafts]=useState<Record<string,Draft>>({}),[loading,setLoading]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const selectedTender=useMemo(()=>tenders.find(t=>t.id===tenderId)??null,[tenders,tenderId]);
 const active=useMemo(()=>intakes.find(q=>q.id===quoteId)??null,[intakes,quoteId]);
 const selectedRfqRow=useMemo(()=>rfqs.find(r=>r.id===selectedRfq)??null,[rfqs,selectedRfq]);
 const supplier=active?.supplier_name||selectedRfqRow?.supplier_name||manualSupplier.trim();
 const eligibleRows=useMemo(()=>sourceRows.filter(r=>r.supplier_name&&supplier&&r.supplier_name.trim().toLowerCase()===supplier.trim().toLowerCase()),[sourceRows,supplier]);
 const itemMap=useMemo(()=>Object.fromEntries(items.map(i=>[i.sourcing_id,i])),[items]);

 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(open&&session)void loadOrgs()},[open,session]);
 useEffect(()=>{if(open&&orgId)void loadTenders(orgId)},[open,orgId]);
 useEffect(()=>{if(open&&tenderId)void loadWorkspace(tenderId)},[open,tenderId]);
 useEffect(()=>{if(quoteId)void loadItems(quoteId);else{setItems([]);setDrafts({})}},[quoteId]);

 async function loadOrgs(){const{data:m,error:e}=await supabase.from("ln_organization_members").select("org_id").eq("status","active");if(e)return setError(e.message);const ids=[...new Set((m??[]).map(x=>String(x.org_id)))];if(!ids.length)return;const{data,error}=await supabase.from("ln_organizations").select("id,name").in("id",ids).order("created_at");if(error)return setError(error.message);const next=(data??[]) as Org[];setOrgs(next);setOrgId(v=>v&&next.some(o=>o.id===v)?v:next[0]?.id??"")}
 async function loadTenders(nextOrg:string){const{data,error}=await supabase.from("ln_tenders").select("id,org_id,ref,buyer,title,deadline_at,status").eq("org_id",nextOrg).not("opportunity_id","is",null).order("created_at",{ascending:false});if(error)return setError(error.message);const next=(data??[]) as Tender[];setTenders(next);setTenderId(v=>v&&next.some(t=>t.id===v)?v:next[0]?.id??"")}
 async function loadWorkspace(nextTender=tenderId){if(!nextTender)return;setLoading(true);setError("");try{const[r,s,q,c]=await Promise.all([supabase.rpc("ln_get_supplier_rfq_drafts",{p_ln_tender_id:nextTender}),supabase.rpc("ln_get_sourcing_queue",{p_ln_tender_id:nextTender,p_status:null,p_search:null,p_limit:500,p_offset:0}),supabase.rpc("ln_get_supplier_quote_intakes",{p_ln_tender_id:nextTender}),supabase.from("ln_quotations").select("id,ref,amount,items_count,priced_count,costed_count,gross_cost,gross_profit,gross_margin_pct,status,next_action").eq("tender_id",nextTender).order("created_at",{ascending:false}).limit(1).maybeSingle()]);if(r.error)throw r.error;if(s.error)throw s.error;if(q.error)throw q.error;if(c.error)throw c.error;const rs=(r.data??[]) as Rfq[],qs=(q.data??[]) as Intake[];setRfqs(rs);setSourceRows((s.data??[]) as SourceRow[]);setIntakes(qs);setCustomerQuote((c.data as CustomerQuote|null)??null);setSelectedRfq(v=>v&&rs.some(x=>x.id===v)?v:(rs.find(x=>x.status==="reviewed")?.id??rs[0]?.id??""));setQuoteId(v=>v&&qs.some(x=>x.id===v)?v:(qs[0]?.id??""))}catch(x){setError(x instanceof Error?x.message:"Unable to load supplier quote intake.")}finally{setLoading(false)}}
 async function loadItems(id:string){const{data,error}=await supabase.rpc("ln_get_supplier_quote_items",{p_quote_id:id});if(error)return setError(error.message);const next=(data??[]) as QuoteItem[];setItems(next);setDrafts(Object.fromEntries(next.map(i=>[i.sourcing_id,{cost:String(i.quoted_unit_cost??""),offered:i.offered_quantity==null?"":String(i.offered_quantity),moq:i.moq==null?"":String(i.moq),lead:i.lead_time_days==null?"":String(i.lead_time_days),manufacturer:i.manufacturer??"",catalog:i.manufacturer_catalog_no??"",note:i.note??""}])))}
 function draftFor(r:SourceRow):Draft{return drafts[r.sourcing_id]??{cost:"",offered:r.quantity==null?"":String(r.quantity),moq:r.moq==null?"":String(r.moq),lead:r.lead_time_days==null?"":String(r.lead_time_days),manufacturer:r.suggested_manufacturer??"",catalog:r.suggested_catalog_no??"",note:""}}
 function patchDraft(id:string,p:Partial<Draft>){setDrafts(d=>({...d,[id]:{...draftFor(sourceRows.find(r=>r.sourcing_id===id)!),...(d[id]??{}),...p}}))}
 async function createIntake(){if(!tenderId)return;const chosen=selectedRfqRow;const supplierName=chosen?.supplier_name||manualSupplier.trim();if(!supplierName)return setError("Choose an RFQ or enter a supplier name.");setBusy("create");setError("");setNotice("");try{const vendorNo=(chosen?.supplier_vendor_no??manualVendor.trim())||null;const{data,error}=await supabase.rpc("ln_create_supplier_quote_intake",{p_ln_tender_id:tenderId,p_rfq_id:chosen?.id??null,p_supplier_name:supplierName,p_supplier_vendor_no:vendorNo,p_supplier_quote_ref:supplierQuoteRef.trim()||null,p_quote_date:quoteDate||null,p_currency:currency||"SAR",p_valid_until:validUntil||null,p_source_url:sourceUrl.trim()||null,p_source_file_path:null,p_source_file_name:null,p_note:note.trim()||null});if(error)throw error;setNotice("Supplier quote intake created. Add only values actually present in the supplier offer.");await loadWorkspace(tenderId);if(data)setQuoteId(String(data))}catch(x){setError(x instanceof Error?x.message:"Unable to create supplier quote intake.")}finally{setBusy("")}}
 async function saveLine(r:SourceRow){if(!active)return;const d=draftFor(r),cost=Number(d.cost);if(!Number.isFinite(cost)||cost<=0)return setError("Quoted unit cost must be greater than zero.");setBusy(r.sourcing_id);setError("");setNotice("");try{const{error}=await supabase.rpc("ln_upsert_supplier_quote_item",{p_quote_id:active.id,p_sourcing_id:r.sourcing_id,p_quoted_unit_cost:cost,p_offered_quantity:d.offered?Number(d.offered):null,p_moq:d.moq?Number(d.moq):null,p_lead_time_days:d.lead?Number(d.lead):null,p_manufacturer:d.manufacturer.trim()||null,p_manufacturer_catalog_no:d.catalog.trim()||null,p_note:d.note.trim()||null});if(error)throw error;setNotice(`${r.item_code||"Tender line"} saved to ${active.ref}.`);await loadWorkspace(tenderId);await loadItems(active.id)}catch(x){setError(x instanceof Error?x.message:"Unable to save supplier quote line.")}finally{setBusy("")}}
 async function uploadFile(file:File){if(!active||!orgId)return;setBusy("file");setError("");try{const path=`${orgId}/${active.id}/${Date.now()}-${safe(file.name)}`;const up=await supabase.storage.from("ln-supplier-quotes").upload(path,file,{upsert:false});if(up.error)throw up.error;const{error}=await supabase.rpc("ln_update_supplier_quote_header",{p_quote_id:active.id,p_supplier_quote_ref:active.supplier_quote_ref,p_quote_date:active.quote_date,p_currency:active.currency,p_valid_until:active.valid_until,p_source_url:active.source_url,p_source_file_path:path,p_source_file_name:file.name,p_note:active.note});if(error)throw error;setNotice("Private supplier quote file attached. Any prior review was reset because the evidence changed.");await loadWorkspace(tenderId)}catch(x){setError(x instanceof Error?x.message:"Unable to attach supplier quote file.")}finally{setBusy("")}}
 async function openFile(){if(!active?.source_file_path)return;const{data,error}=await supabase.storage.from("ln-supplier-quotes").createSignedUrl(active.source_file_path,300);if(error)return setError(error.message);window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 async function review(){if(!active)return;setBusy("review");setError("");try{const{error}=await supabase.rpc("ln_mark_supplier_quote_reviewed",{p_quote_id:active.id});if(error)throw error;setNotice(`${active.ref} reviewed. Costs have not been pushed into the customer quotation yet.`);await loadWorkspace(tenderId)}catch(x){setError(x instanceof Error?x.message:"Unable to review supplier quote.")}finally{setBusy("")}}
 async function approve(){if(!active)return;setBusy("approve");setError("");try{const{data,error}=await supabase.rpc("ln_approve_supplier_quote",{p_quote_id:active.id});if(error)throw error;setNotice(`${active.ref} approved. Real supplier costs are now synced into the customer quotation.`);await loadWorkspace(tenderId);if(data)await loadItems(active.id)}catch(x){setError(x instanceof Error?x.message:"Unable to approve supplier quote.")}finally{setBusy("")}}
 async function reject(){if(!active)return;setBusy("reject");setError("");try{const{error}=await supabase.rpc("ln_reject_supplier_quote",{p_quote_id:active.id,p_reason:"Rejected during supplier quote review"});if(error)throw error;setNotice(`${active.ref} rejected. No costs were synced.`);await loadWorkspace(tenderId)}catch(x){setError(x instanceof Error?x.message:"Unable to reject supplier quote.")}finally{setBusy("")}}

 if(!session)return null;
 return <><button className={styles.launcher} onClick={()=>{setOpen(true);setError("");setNotice("")}}>▤ Supplier Quotes</button>{open?<div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className={styles.modal}><header className={styles.head}><div><div className={styles.eyebrow}>LabNarrative · Tender Commercials</div><h2>Supplier Quote Intake</h2><p>Record the supplier offer exactly as received. Review first; only an explicit approval can push supplier cost into the customer quotation and margin model.</p></div><button className={styles.close} onClick={()=>setOpen(false)}>×</button></header><div className={styles.body}>
 <div className={styles.toolbar}><label><span>Organization</span><select value={orgId} onChange={e=>{setOrgId(e.target.value);setTenderId("")}}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label><span>Operational tender</span><select value={tenderId} onChange={e=>setTenderId(e.target.value)}>{tenders.map(t=><option key={t.id} value={t.id}>{t.ref} · {t.title}</option>)}</select></label><button className={styles.refresh} disabled={loading} onClick={()=>void loadWorkspace()}>{loading?"Syncing…":"Refresh"}</button></div>
 {selectedTender?<div className={styles.hero}><div><span>{selectedTender.ref} · {selectedTender.buyer}</span><strong>{selectedTender.title}</strong></div><article><span>Supplier quotes</span><strong>{intakes.length}</strong><small>recorded</small></article><article><span>Approved costs</span><strong>{customerQuote?.costed_count??0}/{customerQuote?.items_count??0}</strong><small>customer quote lines</small></article><article><span>Gross cost</span><strong>{money(customerQuote?.gross_cost??0)}</strong><small>{customerQuote?.gross_margin_pct==null?"margin incomplete":`${num(customerQuote.gross_margin_pct)}% margin`}</small></article></div>:null}
 {error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}
 <section className={styles.create}><div className={styles.sectionHead}><div><span>New supplier quote</span><strong>Create an intake from a reviewed RFQ or a manually verified supplier</strong></div></div><div className={styles.createGrid}><label><span>RFQ</span><select value={selectedRfq} onChange={e=>setSelectedRfq(e.target.value)}><option value="">Manual supplier quote</option>{rfqs.map(r=><option key={r.id} value={r.id}>{r.ref} · {r.supplier_name} · {label(r.status)}</option>)}</select></label><label><span>Manual supplier</span><input disabled={!!selectedRfq} value={manualSupplier} onChange={e=>setManualSupplier(e.target.value)} placeholder="Supplier company"/></label><label><span>Vendor no.</span><input disabled={!!selectedRfq} value={manualVendor} onChange={e=>setManualVendor(e.target.value)} placeholder="Optional"/></label><label><span>Supplier quote ref.</span><input value={supplierQuoteRef} onChange={e=>setSupplierQuoteRef(e.target.value)} placeholder="e.g. Q-4587"/></label><label><span>Quote date</span><input type="date" value={quoteDate} onChange={e=>setQuoteDate(e.target.value)}/></label><label><span>Valid until</span><input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><label><span>Currency</span><input value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label><label className={styles.wide}><span>Source URL</span><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="Optional supplier portal/email evidence URL"/></label><label className={styles.wide}><span>Internal note</span><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional"/></label><button disabled={busy==="create"} onClick={()=>void createIntake()}>{busy==="create"?"Creating…":"Create Intake"}</button></div></section>
 <div className={styles.tabs}>{intakes.length?<label><span>Supplier quote intake</span><select value={quoteId} onChange={e=>setQuoteId(e.target.value)}>{intakes.map(q=><option key={q.id} value={q.id}>{q.ref} · {q.supplier_name} · {label(q.status)}</option>)}</select></label>:<div className={styles.empty}>No supplier quote intakes yet. Create one above after a supplier responds.</div>}</div>
 {active?<><section className={styles.summary}><div><span>{active.ref}</span><strong>{active.supplier_name}</strong><small>{active.supplier_quote_ref||"No supplier reference"} · {active.currency} · {label(active.status)}</small></div><article><span>Quoted lines</span><strong>{active.item_count}</strong></article><article><span>Quoted cost</span><strong>{money(active.total_cost,active.currency)}</strong></article><article><span>Validity</span><strong>{active.valid_until||"—"}</strong></article></section>
 <section className={styles.fileRow}><div><strong>Supplier evidence</strong><span>{active.source_file_name||active.source_url||"No file or URL attached"}</span></div><label className={styles.upload}>{busy==="file"?"Uploading…":"Attach private PDF/XLSX"}<input type="file" accept=".pdf,.xlsx,.xls,.csv,.png,.jpg,.jpeg" disabled={busy==="file"||active.status==="approved"||active.status==="rejected"} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadFile(f);e.currentTarget.value=""}}/></label>{active.source_file_path?<button onClick={()=>void openFile()}>Open file</button>:null}{active.source_url?<a href={active.source_url} target="_blank" rel="noreferrer">Open source URL</a>:null}</section>
 <div className={styles.tableWrap}><table><thead><tr><th>Tender line</th><th>Requested</th><th>Supplier unit cost</th><th>Offered qty</th><th>MOQ</th><th>Lead days</th><th>Manufacturer / catalog</th><th></th></tr></thead><tbody>{eligibleRows.map(r=>{const d=draftFor(r),saved=itemMap[r.sourcing_id];return <tr key={r.sourcing_id}><td><strong>{r.item_code||"No code"}</strong><small>{r.requested_item}</small></td><td><strong>{r.quantity==null?"—":num(r.quantity)}</strong><small>{r.unit||"—"}</small></td><td><input inputMode="decimal" value={d.cost} disabled={active.status==="approved"||active.status==="rejected"} onChange={e=>patchDraft(r.sourcing_id,{cost:e.target.value})} placeholder="0.00"/>{saved?<small className={styles.saved}>Saved</small>:null}</td><td><input inputMode="decimal" value={d.offered} disabled={active.status==="approved"||active.status==="rejected"} onChange={e=>patchDraft(r.sourcing_id,{offered:e.target.value})}/></td><td><input inputMode="decimal" value={d.moq} disabled={active.status==="approved"||active.status==="rejected"} onChange={e=>patchDraft(r.sourcing_id,{moq:e.target.value})}/></td><td><input inputMode="numeric" value={d.lead} disabled={active.status==="approved"||active.status==="rejected"} onChange={e=>patchDraft(r.sourcing_id,{lead:e.target.value})}/></td><td><input value={d.manufacturer} disabled={active.status==="approved"||active.status==="rejected"} onChange={e=>patchDraft(r.sourcing_id,{manufacturer:e.target.value})} placeholder="Manufacturer"/><input value={d.catalog} disabled={active.status==="approved"||active.status==="rejected"} onChange={e=>patchDraft(r.sourcing_id,{catalog:e.target.value})} placeholder="Catalog no."/></td><td><button disabled={busy===r.sourcing_id||active.status==="approved"||active.status==="rejected"} onClick={()=>void saveLine(r)}>{busy===r.sourcing_id?"Saving…":"Save line"}</button></td></tr>})}</tbody></table>{!eligibleRows.length?<div className={styles.empty}>No sourcing lines are assigned to {active.supplier_name}. Use Supplier Intelligence / External Sourcing first.</div>:null}</div>
 <section className={styles.gates}><div><strong>Commercial gates</strong><span>Draft changes do not affect customer cost. Review validates the captured offer. Approve pushes only these supplier costs into external-sourcing quotation lines.</span></div><div>{active.status==="draft"?<button disabled={!active.item_count||busy==="review"} onClick={()=>void review()}>{busy==="review"?"Reviewing…":"Mark Reviewed"}</button>:null}{active.status==="reviewed"?<><button className={styles.approve} disabled={busy==="approve"} onClick={()=>void approve()}>{busy==="approve"?"Approving…":"Approve Supplier Offer"}</button><button className={styles.secondary} disabled={busy==="reject"} onClick={()=>void reject()}>Reject</button></>:null}{active.status==="approved"?<span className={styles.approved}>Approved · costs synced</span>:null}{active.status==="rejected"?<span className={styles.rejected}>Rejected · no cost sync</span>:null}</div></section></>:null}
 {customerQuote?<section className={styles.customer}><div><span>Customer quotation</span><strong>{customerQuote.ref}</strong><small>{customerQuote.next_action||label(customerQuote.status)}</small></div><article><span>Lines</span><strong>{customerQuote.items_count}</strong></article><article><span>Priced</span><strong>{customerQuote.priced_count}/{customerQuote.items_count}</strong></article><article><span>Costed</span><strong>{customerQuote.costed_count}/{customerQuote.items_count}</strong></article><article><span>Amount</span><strong>{money(customerQuote.amount)}</strong></article><article><span>Gross cost</span><strong>{money(customerQuote.gross_cost)}</strong></article><article><span>Margin</span><strong>{customerQuote.gross_margin_pct==null?"—":`${num(customerQuote.gross_margin_pct)}%`}</strong></article></section>:null}
 <p className={styles.caveat}>LabNarrative never infers a supplier price, availability, MOQ or lead time from historical awards. Supplier quote values enter the customer cost model only after a human review and approval.</p>
 </div></section></div>:null}</>;
}
