"use client";

import { createClient, type Session } from "@supabase/supabase-js";
import { useEffect, useMemo, useState } from "react";
import styles from "./supplier-quote-extraction.module.css";

type Org={id:string;name:string};
type Tender={id:string;org_id:string;ref:string;buyer:string;title:string};
type Intake={id:string;ref:string;supplier_name:string;status:string;source_file_name:string|null;currency:string;item_count:number};
type Run={id:string;source_file_name:string;parser:string;status:string;row_count:number;matched_count:number;quality:number;parser_metadata:Record<string,unknown>;created_at:string};
type Proposal={id:string;source_row_number:number;source_sheet:string|null;source_page:number|null;raw_text:string;extracted_item_code:string|null;extracted_description:string|null;extracted_quantity:number|null;extracted_unit:string|null;extracted_unit_cost:number|null;extracted_moq:number|null;extracted_lead_time_days:number|null;extracted_manufacturer:string|null;extracted_catalog_no:string|null;matched_sourcing_id:string|null;matched_requirement_id:string|null;matched_item_code:string|null;matched_requested_item:string|null;matched_requested_quantity:number|null;matched_unit:string|null;match_method:string|null;match_confidence:number;extraction_confidence:number;status:string};
type Sourcing={sourcing_id:string;requirement_id:string;item_code:string|null;requested_item:string;quantity:number|null;unit:string|null;status:string;supplier_name:string|null};

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const pct=(v:number|null|undefined)=>`${Math.round(Number(v||0)*100)}%`;
const money=(v:number|null|undefined,c="SAR")=>new Intl.NumberFormat("en-SA",{style:"currency",currency:c||"SAR",maximumFractionDigits:2}).format(Number(v||0));
const num=(v:number|null|undefined)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(Number(v||0));
const label=(v:string|null|undefined)=>String(v||"unmatched").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function SupplierQuoteExtractionWorkspace(){
 const[session,setSession]=useState<Session|null>(null),[open,setOpen]=useState(false),[orgs,setOrgs]=useState<Org[]>([]),[orgId,setOrgId]=useState(""),[tenders,setTenders]=useState<Tender[]>([]),[tenderId,setTenderId]=useState(""),[quotes,setQuotes]=useState<Intake[]>([]),[quoteId,setQuoteId]=useState("");
 const[runs,setRuns]=useState<Run[]>([]),[runId,setRunId]=useState(""),[proposals,setProposals]=useState<Proposal[]>([]),[sourcing,setSourcing]=useState<Sourcing[]>([]),[mapping,setMapping]=useState<Record<string,string>>({});
 const[loading,setLoading]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const selectedTender=useMemo(()=>tenders.find(x=>x.id===tenderId)??null,[tenders,tenderId]);
 const selectedQuote=useMemo(()=>quotes.find(x=>x.id===quoteId)??null,[quotes,quoteId]);
 const activeRun=useMemo(()=>runs.find(x=>x.id===runId)??null,[runs,runId]);
 const pending=proposals.filter(p=>p.status==="proposed").length,confirmed=proposals.filter(p=>p.status==="confirmed").length,rejected=proposals.filter(p=>p.status==="rejected").length;

 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(open&&session)void loadOrgs()},[open,session]);
 useEffect(()=>{if(open&&orgId)void loadTenders(orgId)},[open,orgId]);
 useEffect(()=>{if(open&&tenderId)void loadQuotes(tenderId)},[open,tenderId]);
 useEffect(()=>{if(open&&quoteId)void loadQuoteWorkspace(quoteId)},[open,quoteId]);
 useEffect(()=>{if(runId)void loadProposals(runId);else setProposals([])},[runId]);

 async function loadOrgs(){const{data:m,error:e}=await supabase.from("ln_organization_members").select("org_id").eq("status","active");if(e)return setError(e.message);const ids=[...new Set((m??[]).map(x=>String(x.org_id)))];if(!ids.length)return;const{data,error}=await supabase.from("ln_organizations").select("id,name").in("id",ids).order("created_at");if(error)return setError(error.message);const next=(data??[]) as Org[];setOrgs(next);setOrgId(v=>v&&next.some(o=>o.id===v)?v:next[0]?.id??"")}
 async function loadTenders(nextOrg:string){const{data,error}=await supabase.from("ln_tenders").select("id,org_id,ref,buyer,title").eq("org_id",nextOrg).not("opportunity_id","is",null).order("created_at",{ascending:false});if(error)return setError(error.message);const next=(data??[]) as Tender[];setTenders(next);setTenderId(v=>v&&next.some(t=>t.id===v)?v:next[0]?.id??"")}
 async function loadQuotes(nextTender:string){const{data,error}=await supabase.rpc("ln_get_supplier_quote_intakes",{p_ln_tender_id:nextTender});if(error)return setError(error.message);const next=(data??[]) as Intake[];setQuotes(next);setQuoteId(v=>v&&next.some(q=>q.id===v)?v:next[0]?.id??"")}
 async function loadQuoteWorkspace(nextQuote=quoteId){if(!nextQuote||!tenderId)return;setLoading(true);setError("");try{const[r,s]=await Promise.all([supabase.rpc("ln_get_supplier_quote_extraction_runs",{p_quote_id:nextQuote}),supabase.rpc("ln_get_sourcing_queue",{p_ln_tender_id:tenderId,p_status:"all",p_search:null,p_limit:500,p_offset:0})]);if(r.error)throw r.error;if(s.error)throw s.error;const rr=(r.data??[]) as Run[];setRuns(rr);setSourcing((s.data??[]) as Sourcing[]);setRunId(v=>v&&rr.some(x=>x.id===v)?v:rr[0]?.id??"")}catch(x){setError(x instanceof Error?x.message:"Unable to load extraction workspace.")}finally{setLoading(false)}}
 async function loadProposals(nextRun:string){const{data,error}=await supabase.rpc("ln_get_supplier_quote_extraction_proposals",{p_run_id:nextRun});if(error)return setError(error.message);const next=(data??[]) as Proposal[];setProposals(next);setMapping(Object.fromEntries(next.map(p=>[p.id,p.matched_sourcing_id??""])))}

 async function extract(file:File){if(!quoteId||!session)return;setBusy("extract");setError("");setNotice("");try{const form=new FormData();form.set("quoteId",quoteId);form.set("file",file);const response=await fetch("/api/platform/supplier-quotes/extract",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`},body:form});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to extract supplier quote.");setNotice(`Extraction created ${payload.rows} proposal${payload.rows===1?"":"s"}; ${payload.matched} mapped automatically. Nothing has changed in sourcing yet.`);await loadQuoteWorkspace(quoteId);if(payload.run_id)setRunId(String(payload.run_id))}catch(x){setError(x instanceof Error?x.message:"Unable to extract supplier quote.")}finally{setBusy("")}}
 async function confirm(p:Proposal){const selected=mapping[p.id]||p.matched_sourcing_id||"";if(!selected)return setError("Choose the tender sourcing line before confirming this proposal.");setBusy(p.id);setError("");setNotice("");try{const{error}=await supabase.rpc("ln_confirm_supplier_quote_extraction_proposal",{p_proposal_id:p.id,p_sourcing_id:selected});if(error)throw error;setNotice(`Row ${p.source_row_number} confirmed into the supplier quote. It is still not approved for customer-cost use.`);await loadProposals(runId)}catch(x){setError(x instanceof Error?x.message:"Unable to confirm proposal.")}finally{setBusy("")}}
 async function reject(p:Proposal){setBusy(p.id);setError("");setNotice("");try{const{error}=await supabase.rpc("ln_reject_supplier_quote_extraction_proposal",{p_proposal_id:p.id});if(error)throw error;setNotice(`Row ${p.source_row_number} rejected; no commercial data was written.`);await loadProposals(runId)}catch(x){setError(x instanceof Error?x.message:"Unable to reject proposal.")}finally{setBusy("")}}

 if(!session)return null;
 return <><button className={styles.launcher} onClick={()=>{setOpen(true);setError("");setNotice("")}}>⌁ Quote Extract</button>{open?<div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className={styles.modal}><header className={styles.head}><div><div className={styles.eyebrow}>LabNarrative · Tender Commercials</div><h2>Supplier Quote Extraction</h2><p>Extract priced supplier lines from text-based PDF, XLSX or CSV evidence. Every extracted value is a proposal only until a human maps and confirms it.</p></div><button className={styles.close} onClick={()=>setOpen(false)}>×</button></header><div className={styles.body}>
 <div className={styles.toolbar}><label><span>Organization</span><select value={orgId} onChange={e=>{setOrgId(e.target.value);setTenderId("");setQuoteId("")}}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label><span>Operational tender</span><select value={tenderId} onChange={e=>{setTenderId(e.target.value);setQuoteId("")}}>{tenders.map(t=><option key={t.id} value={t.id}>{t.ref} · {t.title}</option>)}</select></label><label><span>Supplier quote intake</span><select value={quoteId} onChange={e=>setQuoteId(e.target.value)}><option value="">Choose quote…</option>{quotes.map(q=><option key={q.id} value={q.id}>{q.ref} · {q.supplier_name} · {label(q.status)}</option>)}</select></label><button className={styles.refresh} disabled={loading||!quoteId} onClick={()=>void loadQuoteWorkspace()}>{loading?"Syncing…":"Refresh"}</button></div>
 {selectedTender&&selectedQuote?<div className={styles.hero}><div><span>{selectedTender.ref} · {selectedTender.buyer}</span><strong>{selectedQuote.ref} · {selectedQuote.supplier_name}</strong><small>Quote status: {label(selectedQuote.status)}</small></div><article><span>Extraction runs</span><strong>{runs.length}</strong><small>audited attempts</small></article><article><span>Latest quality</span><strong>{activeRun?pct(activeRun.quality):"—"}</strong><small>parser confidence</small></article><article><span>Review state</span><strong>{confirmed}/{proposals.length}</strong><small>{pending} pending · {rejected} rejected</small></article></div>:null}
 {error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}
 <section className={styles.uploadBox}><div><span>Automatic extraction</span><strong>Upload the same supplier quote evidence</strong><p>Structured XLSX/CSV is strongest. Text-based PDFs are supported conservatively. Scanned images stay manual in V1.</p></div><label className={styles.upload}>{busy==="extract"?"Extracting…":"Choose file + extract"}<input type="file" accept=".pdf,.xlsx,.csv,.tsv,.txt,application/pdf,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv,text/plain" disabled={busy==="extract"||!quoteId||["approved","rejected"].includes(selectedQuote?.status??"")} onChange={e=>{const f=e.target.files?.[0];if(f)void extract(f);e.currentTarget.value=""}}/></label></section>
 {runs.length?<section className={styles.runbar}><label><span>Extraction run</span><select value={runId} onChange={e=>setRunId(e.target.value)}>{runs.map(r=><option key={r.id} value={r.id}>{new Date(r.created_at).toLocaleString()} · {r.source_file_name} · {r.row_count} rows · {label(r.status)}</option>)}</select></label>{activeRun?<div><b>{activeRun.parser}</b><span>{activeRun.matched_count}/{activeRun.row_count} auto-mapped · {pct(activeRun.quality)} extraction quality</span></div>:null}</section>:<div className={styles.empty}>No extraction run yet. Create a supplier quote intake first, then upload the supplier's actual quote file here.</div>}
 {proposals.length?<div className={styles.tableWrap}><table><thead><tr><th>Extracted supplier row</th><th>Commercial values</th><th>Proposed tender mapping</th><th>Evidence</th><th>Human action</th></tr></thead><tbody>{proposals.map(p=><tr key={p.id} className={p.status!=="proposed"?styles[p.status]||"":""}><td><strong>{p.extracted_item_code||p.extracted_catalog_no||`Row ${p.source_row_number}`}</strong><span>{p.extracted_description||"Description not extracted"}</span><small>{p.source_sheet?`${p.source_sheet} · `:""}row {p.source_row_number} · extraction {pct(p.extraction_confidence)}</small></td><td><strong>{p.extracted_unit_cost!=null?money(p.extracted_unit_cost,selectedQuote?.currency||"SAR"):"No unit cost"}</strong><span>{p.extracted_quantity!=null?`Offered qty ${num(p.extracted_quantity)}`:"Qty —"} · {p.extracted_moq!=null?`MOQ ${num(p.extracted_moq)}`:"MOQ —"}</span><small>{p.extracted_lead_time_days!=null?`${p.extracted_lead_time_days} day lead time · `:""}{p.extracted_manufacturer||"Manufacturer —"}{p.extracted_catalog_no?` · ${p.extracted_catalog_no}`:""}</small></td><td>{p.status==="proposed"?<><select value={mapping[p.id]??p.matched_sourcing_id??""} onChange={e=>setMapping(m=>({...m,[p.id]:e.target.value}))}><option value="">Unmapped — choose manually</option>{sourcing.map(s=><option key={s.sourcing_id} value={s.sourcing_id}>{s.item_code||"No code"} · {s.requested_item.slice(0,100)} · {num(s.quantity)} {s.unit||""}</option>)}</select><small>{p.match_method?`${label(p.match_method)} · ${pct(p.match_confidence)}`:"No automatic match"}</small></>:<><strong>{p.matched_item_code||"No code"}</strong><span>{p.matched_requested_item||"—"}</span><small>{label(p.status)}</small></>}</td><td><details><summary>Raw row</summary><p>{p.raw_text}</p></details></td><td>{p.status==="proposed"?<div className={styles.actions}><button disabled={busy===p.id||!p.extracted_unit_cost} onClick={()=>void confirm(p)}>Confirm</button><button className={styles.secondary} disabled={busy===p.id} onClick={()=>void reject(p)}>Reject</button></div>:<b className={styles.state}>{label(p.status)}</b>}</td></tr>)}</tbody></table></div>:runId?<div className={styles.empty}>This extraction run contains no proposals.</div>:null}
 <p className={styles.caveat}>Automatic extraction never approves a supplier offer. Confirming a proposal only writes it into the supplier quote intake. The separate Supplier Quotes workspace still requires Review and then Approve Supplier Offer before any cost can reach the customer quotation or margin calculation.</p>
 </div></section></div>:null}</>;
}
