"use client";

import { createClient, type Session } from "@supabase/supabase-js";
import { useEffect, useMemo, useState } from "react";
import styles from "./supplier-contact-email.module.css";

type Org={id:string;name:string};
type Tender={id:string;org_id:string;ref:string;buyer:string;title:string;status:string};
type Rfq={id:string;ref:string;supplier_name:string;supplier_vendor_no:string|null;status:string;subject:string;body:string;item_count:number;created_at:string;reviewed_at:string|null};
type Contact={contact_id:string;supplier_name:string;supplier_vendor_no:string|null;contact_name:string|null;role:string|null;email:string;phone:string|null;website_url:string|null;source_url:string|null;source_kind:string;source_confidence:number};
type EmailDraft={email_draft_id:string;rfq_id:string;rfq_ref:string;supplier_name:string;supplier_vendor_no:string|null;contact_id:string;contact_name:string|null;contact_role:string|null;to_email:string;status:string;subject:string;body:string;contact_source_url:string|null;created_at:string;reviewed_at:string|null;ready_at:string|null};
type DraftEdit={subject:string;body:string};

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const pct=(v:number)=>`${Math.round(Number(v||0)*100)}%`;

export default function SupplierContactEmailWorkspace(){
 const[session,setSession]=useState<Session|null>(null),[open,setOpen]=useState(false),[orgs,setOrgs]=useState<Org[]>([]),[orgId,setOrgId]=useState(""),[tenders,setTenders]=useState<Tender[]>([]),[tenderId,setTenderId]=useState("");
 const[rfqs,setRfqs]=useState<Rfq[]>([]),[rfqId,setRfqId]=useState(""),[contacts,setContacts]=useState<Contact[]>([]),[emails,setEmails]=useState<EmailDraft[]>([]),[mode,setMode]=useState<"contacts"|"email">("contacts");
 const[edits,setEdits]=useState<Record<string,DraftEdit>>({}),[busy,setBusy]=useState<string|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const[manual,setManual]=useState({name:"",role:"",email:"",phone:"",source:""});
 const selectedRfq=useMemo(()=>rfqs.find(r=>r.id===rfqId)??null,[rfqs,rfqId]);

 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(open&&session)void loadOrgs()},[open,session]);
 useEffect(()=>{if(open&&orgId)void loadTenders(orgId)},[open,orgId]);
 useEffect(()=>{if(open&&tenderId)void loadTenderData(tenderId)},[open,tenderId]);
 useEffect(()=>{if(open&&selectedRfq)void loadContacts(selectedRfq)},[open,rfqId]);

 async function loadOrgs(){setError("");const{data:m,error:e}=await supabase.from("ln_organization_members").select("org_id").eq("status","active");if(e){setError(e.message);return}const ids=[...new Set((m??[]).map(x=>String(x.org_id)))];if(!ids.length)return;const{data,error}=await supabase.from("ln_organizations").select("id,name").in("id",ids).order("created_at");if(error){setError(error.message);return}const next=(data??[]) as Org[];setOrgs(next);setOrgId(v=>v&&next.some(o=>o.id===v)?v:next[0]?.id??"")}
 async function loadTenders(nextOrg:string){const{data,error}=await supabase.from("ln_tenders").select("id,org_id,ref,buyer,title,status").eq("org_id",nextOrg).not("opportunity_id","is",null).order("created_at",{ascending:false});if(error){setError(error.message);return}const next=(data??[]) as Tender[];setTenders(next);setTenderId(v=>v&&next.some(t=>t.id===v)?v:next[0]?.id??"")}
 async function loadTenderData(nextTender=tenderId){if(!nextTender)return;setLoading(true);setError("");try{const[r,e]=await Promise.all([supabase.rpc("ln_get_supplier_rfq_drafts",{p_ln_tender_id:nextTender}),supabase.rpc("ln_get_rfq_email_drafts",{p_ln_tender_id:nextTender})]);if(r.error)throw r.error;if(e.error)throw e.error;const nextRfqs=(r.data??[]) as Rfq[];const nextEmails=(e.data??[]) as EmailDraft[];setRfqs(nextRfqs);setEmails(nextEmails);setEdits(Object.fromEntries(nextEmails.map(x=>[x.email_draft_id,{subject:x.subject,body:x.body}])));setRfqId(v=>v&&nextRfqs.some(x=>x.id===v)?v:(nextRfqs.find(x=>x.status==="reviewed")?.id??nextRfqs[0]?.id??""));if(!nextRfqs.length){setContacts([]);setRfqId("")}}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load RFQ email workspace.")}finally{setLoading(false)}}
 async function loadContacts(rfq:Rfq){if(!orgId)return;const{data,error}=await supabase.rpc("ln_get_supplier_contacts",{p_org_id:orgId,p_supplier_name:rfq.supplier_name,p_supplier_vendor_no:rfq.supplier_vendor_no});if(error){setError(error.message);return}setContacts((data??[]) as Contact[])}
 async function reviewRfq(){if(!selectedRfq)return;setBusy(selectedRfq.id);setError("");setNotice("");try{const{error}=await supabase.rpc("ln_mark_supplier_rfq_reviewed",{p_rfq_id:selectedRfq.id});if(error)throw error;setNotice(`${selectedRfq.ref} reviewed. You can now choose a recipient and prepare the email.`);await loadTenderData()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to review RFQ.")}finally{setBusy(null)}}
 async function addManualContact(){if(!selectedRfq||!orgId)return;setBusy("manual");setError("");setNotice("");try{const{error}=await supabase.rpc("ln_upsert_supplier_contact",{p_org_id:orgId,p_supplier_name:selectedRfq.supplier_name,p_supplier_vendor_no:selectedRfq.supplier_vendor_no,p_contact_name:manual.name.trim()||null,p_role:manual.role.trim()||null,p_email:manual.email.trim(),p_phone:manual.phone.trim()||null,p_website_url:null,p_source_url:manual.source.trim()||null,p_source_kind:"manual",p_source_confidence:0.60});if(error)throw error;setManual({name:"",role:"",email:"",phone:"",source:""});setNotice("Manual supplier contact saved. Verify the address before preparing the RFQ email.");await loadContacts(selectedRfq)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save supplier contact.")}finally{setBusy(null)}}
 async function prepareEmail(contact:Contact){if(!selectedRfq)return;setBusy(contact.contact_id);setError("");setNotice("");try{const{error}=await supabase.rpc("ln_create_rfq_email_draft",{p_rfq_id:selectedRfq.id,p_contact_id:contact.contact_id});if(error)throw error;setNotice(`Email draft prepared for ${contact.email}. Nothing was sent.`);setMode("email");await loadTenderData()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to prepare RFQ email draft.")}finally{setBusy(null)}}
 async function saveEmail(row:EmailDraft){const d=edits[row.email_draft_id];if(!d)return;setBusy(row.email_draft_id);setError("");setNotice("");try{const{error}=await supabase.rpc("ln_update_rfq_email_draft",{p_email_draft_id:row.email_draft_id,p_subject:d.subject,p_body:d.body});if(error)throw error;setNotice(`${row.rfq_ref} email draft saved. Review status was reset because the content changed.`);await loadTenderData()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save email draft.")}finally{setBusy(null)}}
 async function reviewEmail(row:EmailDraft){setBusy(row.email_draft_id);setError("");setNotice("");try{const{error}=await supabase.rpc("ln_mark_rfq_email_reviewed",{p_email_draft_id:row.email_draft_id});if(error)throw error;setNotice("Email content reviewed. One final human gate remains before it is ready to send.");await loadTenderData()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to review email draft.")}finally{setBusy(null)}}
 async function readyEmail(row:EmailDraft){setBusy(row.email_draft_id);setError("");setNotice("");try{const{error}=await supabase.rpc("ln_mark_rfq_email_ready",{p_email_draft_id:row.email_draft_id});if(error)throw error;setNotice("Email marked ready to send. LabNarrative still has not sent it.");await loadTenderData()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to mark email ready.")}finally{setBusy(null)}}
 async function copy(text:string,what:string){try{await navigator.clipboard.writeText(text);setNotice(`${what} copied. No email was sent.`)}catch{setError("Clipboard access is unavailable in this browser.")}}

 if(!session)return null;
 return <><button className={styles.launcher} onClick={()=>{setOpen(true);setError("");setNotice("")}}>✉ RFQ Email</button>{open?<div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className={styles.modal}><header className={styles.head}><div><div className={styles.eyebrow}>LabNarrative · Supplier Communication</div><h2>Supplier Contacts & RFQ Email Gate</h2><p>Choose a sourced business contact, prepare an editable RFQ email, review it, then mark it ready to send. This workspace does not send email.</p></div><button className={styles.close} onClick={()=>setOpen(false)}>×</button></header><div className={styles.body}>
  <div className={styles.toolbar}><label><span>Organization</span><select value={orgId} onChange={e=>{setOrgId(e.target.value);setTenderId("");setRfqId("")}}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label><span>Operational tender</span><select value={tenderId} onChange={e=>{setTenderId(e.target.value);setRfqId("")}}>{tenders.map(t=><option key={t.id} value={t.id}>{t.ref} · {t.title}</option>)}</select></label><label><span>Supplier RFQ</span><select value={rfqId} onChange={e=>setRfqId(e.target.value)}><option value="">Select RFQ</option>{rfqs.map(r=><option key={r.id} value={r.id}>{r.ref} · {r.supplier_name} · {label(r.status)}</option>)}</select></label><button className={styles.refresh} disabled={loading||!tenderId} onClick={()=>void loadTenderData()}>{loading?"Syncing…":"Refresh"}</button></div>
  {selectedRfq?<div className={styles.hero}><div><span>{selectedRfq.ref}</span><strong>{selectedRfq.supplier_name}</strong><small>{selectedRfq.item_count} item{selectedRfq.item_count===1?"":"s"} · {label(selectedRfq.status)}</small></div><article><span>Contacts</span><strong>{contacts.length}</strong><small>sourced + manual</small></article><article><span>Email drafts</span><strong>{emails.filter(e=>e.rfq_id===selectedRfq.id).length}</strong><small>for selected RFQ</small></article><article><span>Ready to send</span><strong>{emails.filter(e=>e.rfq_id===selectedRfq.id&&e.status==="ready_to_send").length}</strong><small>still unsent</small></article></div>:null}
  {error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}
  {!rfqs.length&&!loading?<div className={styles.empty}>No supplier RFQ drafts exist for this tender yet. Create and review one in Supplier Intelligence first.</div>:null}
  {selectedRfq?<><div className={styles.tabs}><button className={mode==="contacts"?styles.active:""} onClick={()=>setMode("contacts")}>Contacts</button><button className={mode==="email"?styles.active:""} onClick={()=>setMode("email")}>Email Drafts</button></div>
  {selectedRfq.status!=="reviewed"?<div className={styles.gate}><div><strong>RFQ review gate</strong><span>The RFQ itself must be reviewed before LabNarrative can prepare an addressed email.</span></div><button disabled={busy===selectedRfq.id} onClick={()=>void reviewRfq()}>{busy===selectedRfq.id?"Reviewing…":"Mark RFQ Reviewed"}</button></div>:null}
  {mode==="contacts"?<><div className={styles.contactGrid}>{contacts.map(c=><article className={styles.contact} key={c.contact_id}><div className={styles.contactTop}><div><strong>{c.contact_name||c.email}</strong><span>{c.role||"Business contact"}</span></div><b>{pct(c.source_confidence)}</b></div><div className={styles.contactData}><span>{c.email}</span>{c.phone?<span>{c.phone}</span>:null}<span>{label(c.source_kind)}</span></div><div className={styles.contactActions}>{c.source_url?<a href={c.source_url} target="_blank" rel="noreferrer">Source evidence ↗</a>:<span>Manual contact</span>}<button disabled={selectedRfq.status!=="reviewed"||busy===c.contact_id} onClick={()=>void prepareEmail(c)}>{busy===c.contact_id?"Preparing…":"Prepare Email Draft"}</button></div></article>)}</div>{!contacts.length?<div className={styles.empty}>No business contacts are stored for this supplier yet. Add one manually below after verifying it.</div>:null}
   <section className={styles.manual}><div><span>Add verified contact manually</span><strong>{selectedRfq.supplier_name}</strong></div><div className={styles.manualGrid}><input placeholder="Contact name" value={manual.name} onChange={e=>setManual({...manual,name:e.target.value})}/><input placeholder="Role / department" value={manual.role} onChange={e=>setManual({...manual,role:e.target.value})}/><input type="email" placeholder="Business email *" value={manual.email} onChange={e=>setManual({...manual,email:e.target.value})}/><input placeholder="Phone" value={manual.phone} onChange={e=>setManual({...manual,phone:e.target.value})}/><input className={styles.wide} placeholder="Source URL or verification note" value={manual.source} onChange={e=>setManual({...manual,source:e.target.value})}/><button disabled={!manual.email.trim()||busy==="manual"} onClick={()=>void addManualContact()}>{busy==="manual"?"Saving…":"Save Contact"}</button></div></section></>:<div className={styles.emailList}>{emails.filter(e=>e.rfq_id===selectedRfq.id).map(row=>{const d=edits[row.email_draft_id]??{subject:row.subject,body:row.body};return <article className={styles.emailCard} key={row.email_draft_id}><div className={styles.emailHead}><div><span>To</span><strong>{row.contact_name||row.to_email}</strong><small>{row.to_email}{row.contact_role?` · ${row.contact_role}`:""}</small></div><b className={`${styles.status} ${styles[row.status]||""}`}>{label(row.status)}</b></div><label><span>Subject</span><input value={d.subject} disabled={row.status==="sent"} onChange={e=>setEdits(x=>({...x,[row.email_draft_id]:{...d,subject:e.target.value}}))}/></label><label><span>Message</span><textarea value={d.body} disabled={row.status==="sent"} onChange={e=>setEdits(x=>({...x,[row.email_draft_id]:{...d,body:e.target.value}}))}/></label><div className={styles.emailActions}><button className={styles.secondary} onClick={()=>void copy(row.to_email,"Recipient")}>Copy To</button><button className={styles.secondary} onClick={()=>void copy(d.subject,"Subject")}>Copy Subject</button><button className={styles.secondary} onClick={()=>void copy(d.body,"Message")}>Copy Message</button><span className={styles.spacer}/><button disabled={busy===row.email_draft_id||row.status==="sent"} onClick={()=>void saveEmail(row)}>Save Draft</button>{row.status==="draft"?<button disabled={busy===row.email_draft_id} onClick={()=>void reviewEmail(row)}>Mark Reviewed</button>:null}{row.status==="reviewed"?<button disabled={busy===row.email_draft_id} onClick={()=>void readyEmail(row)}>Mark Ready to Send</button>:null}</div>{row.contact_source_url?<div className={styles.provenance}>Recipient source: <a href={row.contact_source_url} target="_blank" rel="noreferrer">open evidence ↗</a></div>:null}</article>})}{!emails.some(e=>e.rfq_id===selectedRfq.id)?<div className={styles.empty}>No addressed email drafts yet. Choose a contact first.</div>:null}</div>}</>:null}
  <p className={styles.caveat}>Safety gate: historical supplier evidence is not current availability. Public contact evidence is not proof that a person handles this tender. RFQ and email review are separate human gates. LabNarrative does not send from this workspace.</p>
 </div></section></div>:null}</>;
}
