import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const EXPECTED_GATEWAY_ORIGIN = "https://trader-gateway.labnarrative.com";
const PUBLIC_BINANCE = "https://data-api.binance.vision";
const cors = {
  "Access-Control-Allow-Origin": "https://platform.labnarrative.com",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

type Db = ReturnType<typeof createClient>;
type Json = Record<string, unknown>;
type Creds = { apiKey:string; apiSecret:string };
type Controls = { global_live_enabled:boolean; kill_switch:boolean; max_live_capital:number|string; max_single_order:number|string };
type Trade = { id:string; account_id:string; bot_id:string; client_id:string; pair:string; status:string; entry_price:number|string; averaging_filled:number; max_averaging:number; active_orders_limit:number; take_profit_pct:number|string; stop_enabled:boolean; stop_pct:number|string; client_state:Json; execution_mode:string };
type Bot = { id:string; safety_order:number|string; deviation:number|string; step_scale:number|string; volume_scale:number|string };
type Rule = { symbol:string; minQty:number; maxQty:number; stepSize:number; minNotional:number; tickSize:number };
let cachedSigningKey: CryptoKey | null = null;

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}})}
function n(value:unknown,fallback=0){const x=Number(value);return Number.isFinite(x)?x:fallback}
function bool(value:unknown,fallback=false){return typeof value==="boolean"?value:fallback}
function obj(value:unknown):Json{return value&&typeof value==="object"&&!Array.isArray(value)?value as Json:{}}
function clean(error:unknown){return error instanceof Error?error.message:String(error||"unknown_error")}
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
function floorStep(value:number,step:number){if(!(step>0))return value;const p=Math.max(0,Math.min(12,(String(step).split(".")[1]??"").replace(/0+$/,"" ).length));return Number((Math.floor((value+1e-14)/step)*step).toFixed(p))}
function priceStep(value:number,step:number){return step>0?floorStep(value,step):value}
function nonce(){const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);return Array.from(bytes).map(x=>x.toString(16).padStart(2,"0")).join("")}
function pemBytes(pem:string){const b64=pem.replace(/-----BEGIN [^-]+-----/g,"").replace(/-----END [^-]+-----/g,"").replace(/\s+/g,"");const bin=atob(b64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes}
function b64(buffer:ArrayBuffer){const bytes=new Uint8Array(buffer);let s="";for(const x of bytes)s+=String.fromCharCode(x);return btoa(s)}
async function hmac(secret:string,message:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(message));return Array.from(new Uint8Array(sig)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function clientId(prefix:string){return `${prefix}-${Date.now().toString(36)}-${crypto.randomUUID().replace(/-/g,"").slice(0,10)}`.slice(0,36)}

async function gatewayConfig(db:Db){const{data,error}=await db.from("trader_gateway_config").select("base_url,status").eq("name","binance").single();if(error||!data)throw new Error("gateway_not_configured");return data as {base_url:string|null;status:string}}
async function signingKey(db:Db){if(cachedSigningKey)return cachedSigningKey;const{data,error}=await db.rpc("trader_gateway_read_signing_private_key");if(error||!data)throw new Error("gateway_signing_key_not_configured");cachedSigningKey=await crypto.subtle.importKey("pkcs8",pemBytes(String(data)),{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);return cachedSigningKey}
async function relay(db:Db,payload:Json){const cfg=await gatewayConfig(db);if(cfg.status!=="ready"||!cfg.base_url)throw new Error("gateway_not_ready");const origin=new URL(cfg.base_url).origin;if(origin!==EXPECTED_GATEWAY_ORIGIN)throw new Error("gateway_origin_not_allowed");const raw=JSON.stringify(payload),timestamp=Date.now(),nce=nonce(),key=await signingKey(db),signature=b64(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,new TextEncoder().encode(`${timestamp}\n${nce}\n${raw}`)));const response=await fetch(`${origin}/relay`,{method:"POST",headers:{"content-type":"application/json","x-ln-timestamp":String(timestamp),"x-ln-nonce":nce,"x-ln-signature":signature},body:raw,signal:AbortSignal.timeout(12000)});const envelope=await response.json().catch(()=>({})) as Json;if(!response.ok)throw new Error(`gateway_${response.status}:${String(envelope.error||"relay_failed")}`);const upstreamStatus=n(envelope.upstreamStatus),rawBody=String(envelope.upstreamBody||"");let body:Json={};try{body=rawBody?JSON.parse(rawBody):{}}catch{throw new Error("binance_invalid_json")}if(upstreamStatus<200||upstreamStatus>=300)throw new Error(`binance_${String(body.code??upstreamStatus)}:${String(body.msg??"request_failed")}`);return body}
async function credentials(db:Db,accountId:string){const{data,error}=await db.rpc("trader_binance_read_secret",{p_account_id:accountId});if(error||!data)throw new Error("credential_not_found");const parsed=JSON.parse(String(data)) as {apiKey?:string;apiSecret?:string};if(!parsed.apiKey||!parsed.apiSecret)throw new Error("credential_not_found");return{apiKey:parsed.apiKey,apiSecret:parsed.apiSecret}}
async function signed(db:Db,creds:Creds,method:"GET"|"POST"|"DELETE",path:string,params:Record<string,string|number|boolean>={}){const time=await relay(db,{requestId:crypto.randomUUID(),method:"GET",path:"/api/v3/time",query:""});const query=new URLSearchParams();for(const[key,value]of Object.entries(params))query.set(key,String(value));query.set("timestamp",String(n(time.serverTime)));query.set("recvWindow","5000");query.set("signature",await hmac(creds.apiSecret,query.toString()));return await relay(db,{requestId:crypto.randomUUID(),method,path,query:query.toString(),apiKey:creds.apiKey})}

async function ownedAccount(db:Db,userId:string,accountId:string){const{data,error}=await db.from("trader_accounts").select("id,mode,status").eq("id",accountId).eq("owner_user_id",userId).eq("account_kind","real").eq("status","active").maybeSingle();if(error)throw error;if(!data)throw new Error("real_account_required");return data}
async function controls(db:Db,accountId:string){const{data,error}=await db.from("trader_execution_controls").select("global_live_enabled,kill_switch,max_live_capital,max_single_order").eq("account_id",accountId).single();if(error||!data)throw new Error("execution_controls_missing");return data as Controls}
async function safeConnection(db:Db,accountId:string){const{data,error}=await db.from("trader_binance_connections").select("status,environment,permission_read,permission_trade,permission_withdraw,permission_internal_transfer,ip_restricted").eq("account_id",accountId).single();if(error||!data)throw new Error("binance_not_connected");if(data.status!=="connected"||data.environment!=="mainnet"||!data.permission_read||!data.permission_trade)throw new Error("binance_trade_permission_required");if(data.permission_withdraw||data.permission_internal_transfer||data.ip_restricted!==true)throw new Error("binance_connection_not_safe")}
async function ownedTrade(db:Db,accountId:string,tradeId:string){const{data,error}=await db.from("trader_trades").select("id,account_id,bot_id,client_id,pair,status,entry_price,averaging_filled,max_averaging,active_orders_limit,take_profit_pct,stop_enabled,stop_pct,client_state,execution_mode").eq("account_id",accountId).eq("client_id",tradeId).maybeSingle();if(error)throw error;if(!data)throw new Error("trade_not_found");return data as Trade}
async function ruleFor(pair:string){const symbol=pair.replace("/","");const response=await fetch(`${PUBLIC_BINANCE}/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`exchange_info_${response.status}`);const payload=await response.json() as {symbols?:Json[]},symbolRow=payload.symbols?.[0];if(!symbolRow||symbolRow.status!=="TRADING"||symbolRow.quoteAsset!=="USDT"||symbolRow.isSpotTradingAllowed===false)throw new Error("spot_symbol_not_tradeable");const filters=(symbolRow.filters??[]) as Json[],find=(type:string)=>filters.find(item=>item.filterType===type),lot=find("LOT_SIZE"),price=find("PRICE_FILTER"),notional=find("NOTIONAL")??find("MIN_NOTIONAL");return{symbol,minQty:n(lot?.minQty),maxQty:n(lot?.maxQty),stepSize:n(lot?.stepSize),minNotional:n(notional?.minNotional),tickSize:n(price?.tickSize)} as Rule}
async function liveExposure(db:Db,accountId:string){const[{data:trades,error:tradeError},{data:orders,error:orderError}]=await Promise.all([db.from("trader_trades").select("invested").eq("account_id",accountId).eq("status","Active").eq("execution_mode","live"),db.from("trader_orders").select("requested_quote").eq("account_id",accountId).eq("exchange","binance").eq("side","BUY").in("status",["OPEN","PENDING","NEW","PARTIALLY_FILLED"])]);if(tradeError)throw tradeError;if(orderError)throw orderError;return(trades??[]).reduce((sum,row)=>sum+n(row.invested),0)+(orders??[]).reduce((sum,row)=>sum+n(row.requested_quote),0)}
async function freeUsdt(db:Db,creds:Creds){const account=await signed(db,creds,"GET","/api/v3/account",{omitZeroBalances:true});const balances=Array.isArray(account.balances)?account.balances as Json[]:[];return n(balances.find(row=>String(row.asset||"")==="USDT")?.free)}
async function brokerEvent(db:Db,trade:Trade,eventType:string,clientOrderId:string|null,payload:Json,orderId?:string|null,exchangeOrderId?:string|null){await db.from("trader_broker_events").insert({account_id:trade.account_id,bot_id:trade.bot_id,trade_id:trade.id,order_id:orderId??null,mode:"live",event_type:eventType,pair:trade.pair,client_order_id:clientOrderId,exchange_order_id:exchangeOrderId??null,payload})}
function orderAmount(bot:Bot,index:number){return n(bot.safety_order)*Math.pow(Math.max(.000001,n(bot.volume_scale,1)),index)}
function orderPrice(bot:Bot,entry:number,index:number){let cumulative=0,step=n(bot.deviation);for(let i=0;i<=index;i++){cumulative+=step;step*=Math.max(.000001,n(bot.step_scale,1))}return entry*(1-cumulative/100)}

async function lookupByClientId(db:Db,creds:Creds,symbol:string,cid:string){let lastError="";for(let attempt=0;attempt<4;attempt++){if(attempt)await sleep(350*(attempt+1));try{return await signed(db,creds,"GET","/api/v3/order",{symbol,origClientOrderId:cid})}catch(error){lastError=clean(error);if(lastError.includes("-2013")||lastError.includes("Order does not exist"))continue;if(lastError.includes("timeout")||lastError.startsWith("gateway_500"))continue;throw error}}if(lastError&&!lastError.includes("-2013"))throw new Error(lastError);return null}
async function cancelRemoteDca(db:Db,trade:Trade,creds:Creds,rule:Rule,order:Json){const status=String(order.status||"").toUpperCase();if(!["OPEN","PENDING","NEW","PARTIALLY_FILLED"].includes(status))return;try{await signed(db,creds,"DELETE","/api/v3/order",{symbol:rule.symbol,origClientOrderId:String(order.client_order_id)})}catch(error){const message=clean(error);if(!message.includes("-2011")&&!message.includes("Unknown order"))throw error}await db.from("trader_orders").update({status:"CANCELED",reserved_quote:0,cancelled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",String(order.id))}
async function createDca(db:Db,trade:Trade,bot:Bot,ctl:Controls,creds:Creds,rule:Rule,sequence:number){const rawQuote=orderAmount(bot,sequence-1);if(rawQuote>n(ctl.max_single_order)+1e-9)throw new Error(`live_order_limit_exceeded:${n(ctl.max_single_order)}`);const price=priceStep(orderPrice(bot,n(trade.entry_price),sequence-1),rule.tickSize),quantity=floorStep(rawQuote/price,rule.stepSize),quote=quantity*price;if(!(quantity>0)||quote<rule.minNotional-1e-9)throw new Error("dca_order_below_exchange_minimum");const exposure=await liveExposure(db,trade.account_id);if(exposure+quote>n(ctl.max_live_capital)+1e-9)throw new Error(`live_capital_limit_exceeded:${n(ctl.max_live_capital)}`);const free=await freeUsdt(db,creds);if(free+1e-8<quote)throw new Error(`insufficient_usdt:${free.toFixed(2)}`);const cid=clientId(`LND${sequence}${trade.id.slice(0,4)}`),now=new Date().toISOString();const{data:ledger,error:ledgerError}=await db.from("trader_orders").insert({account_id:trade.account_id,bot_id:trade.bot_id,trade_id:trade.id,client_order_id:cid,pair:trade.pair,kind:"averaging",side:"BUY",order_type:"LIMIT",status:"PENDING",sequence_no:sequence,price,requested_quote:quote,requested_qty:quantity,reserved_quote:quote,exchange:"binance",opened_at:now,metadata:{planner:"manual_live_edit_v2"}}).select("id").single();if(ledgerError||!ledger)throw ledgerError||new Error("dca_order_ledger_failed");let response:Json|null=null;let placementError="";try{response=await signed(db,creds,"POST","/api/v3/order",{symbol:rule.symbol,side:"BUY",type:"LIMIT",timeInForce:"GTC",quantity,price,newClientOrderId:cid,newOrderRespType:"RESULT"})}catch(error){placementError=clean(error);if(placementError.includes("timeout")||placementError.startsWith("gateway_500")){response=await lookupByClientId(db,creds,rule.symbol,cid)}}if(!response){await db.from("trader_orders").update({status:"REJECTED",reserved_quote:0,updated_at:new Date().toISOString(),metadata:{planner:"manual_live_edit_v2",error:placementError||"dca_order_placement_failed"}}).eq("id",ledger.id);throw new Error(placementError||"dca_order_placement_failed")}const exchangeOrderId=String(response.orderId||"");await db.from("trader_orders").update({status:String(response.status||"NEW"),exchange_order_id:exchangeOrderId||null,updated_at:new Date().toISOString(),metadata:{planner:"manual_live_edit_v2",reconciled_after_timeout:Boolean(placementError)}}).eq("id",ledger.id);await brokerEvent(db,trade,placementError?"manual_dca_reconciled":"manual_dca_open",cid,{sequence,price,quote,reconciledAfterTimeout:Boolean(placementError)},ledger.id,exchangeOrderId||null)}

async function updateTrade(db:Db,trade:Trade,ctl:Controls,body:Json){if(trade.status!=="Active")throw new Error("trade_not_active");const completed=Math.max(0,Math.round(n(trade.averaging_filled))),maxAveraging=Math.max(completed,Math.min(100,Math.round(n(body.maxAveraging,trade.max_averaging)))),remaining=Math.max(0,maxAveraging-completed),requested=Math.max(0,Math.round(n(body.activeOrdersLimit,trade.active_orders_limit))),activeOrdersLimit=Math.min(remaining,requested),stopEnabled=body.stopEnabled===undefined?trade.stop_enabled:bool(body.stopEnabled),stopPct=Math.max(0,n(body.stopPct,trade.stop_pct));if(stopEnabled&&!(stopPct>0))throw new Error("invalid_stop_loss");const state=obj(trade.client_state),v2=state.exitStrategyV2===true,nextState={...state,maxAveraging,activeOrdersLimit,manualEditAt:new Date().toISOString()};if(v2){nextState.stopEnabled=stopEnabled;nextState.stopPct=stopPct;delete nextState.stopLossTriggeredAt}else{nextState.takeProfitPct=Math.max(0,n(body.takeProfitPct,trade.take_profit_pct));nextState.stopEnabled=stopEnabled;nextState.stopPct=stopPct}const update:Json={max_averaging:maxAveraging,active_orders_limit:activeOrdersLimit,stop_enabled:v2?false:stopEnabled,stop_pct:stopPct,client_state:nextState,updated_at:new Date().toISOString()};if(!v2)update.take_profit_pct=Math.max(0,n(body.takeProfitPct,trade.take_profit_pct));const{error:updateError}=await db.from("trader_trades").update(update).eq("id",trade.id).eq("status","Active");if(updateError)throw updateError;const rule=await ruleFor(trade.pair),creds=await credentials(db,trade.account_id),{data:rows,error:orderError}=await db.from("trader_orders").select("id,client_order_id,exchange_order_id,status,sequence_no").eq("trade_id",trade.id).eq("kind","averaging").eq("side","BUY");if(orderError)throw orderError;const desired=new Set<number>();for(let sequence=completed+1;sequence<=Math.min(maxAveraging,completed+activeOrdersLimit);sequence++)desired.add(sequence);const activeBySequence=new Set<number>();for(const row of rows??[]){const sequence=Math.round(n(row.sequence_no)),status=String(row.status||"").toUpperCase();if(desired.has(sequence)&&["OPEN","PENDING","NEW","PARTIALLY_FILLED"].includes(status)){activeBySequence.add(sequence);continue}if(!desired.has(sequence)&&["OPEN","PENDING","NEW","PARTIALLY_FILLED"].includes(status))await cancelRemoteDca(db,trade,creds,rule,row as Json)}const{data:bot,error:botError}=await db.from("trader_bots").select("id,safety_order,deviation,step_scale,volume_scale").eq("id",trade.bot_id).eq("account_id",trade.account_id).single();if(botError||!bot)throw botError||new Error("bot_not_found");for(const sequence of desired)if(!activeBySequence.has(sequence))await createDca(db,trade,bot as Bot,ctl,creds,rule,sequence);await brokerEvent(db,trade,"manual_trade_updated",null,{maxAveraging,activeOrdersLimit,stopEnabled,stopPct,exitStrategyV2:v2});return{maxAveraging,activeOrdersLimit,stopEnabled,stopPct,exitStrategyV2:v2}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);const url=Deno.env.get("SUPABASE_URL"),serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!serviceKey)return json({error:"server_configuration_missing"},500);const db=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({error:"unauthorized"},401);const{data:userData,error:userError}=await db.auth.getUser(token);if(userError||!userData.user)return json({error:"unauthorized"},401);try{const body=await req.json().catch(()=>({})) as Json;if(String(body.action||"")!=="update_trade")throw new Error("unknown_action");const accountId=String(body.accountId||""),tradeId=String(body.tradeId||"");if(!accountId)throw new Error("account_id_required");if(!tradeId)throw new Error("trade_id_required");const account=await ownedAccount(db,userData.user.id,accountId),ctl=await controls(db,accountId);if(account.mode!=="live"||ctl.global_live_enabled!==true||ctl.kill_switch!==false)throw new Error("live_trading_not_enabled");await safeConnection(db,accountId);const trade=await ownedTrade(db,accountId,tradeId);if(trade.execution_mode!=="live")throw new Error("trade_not_live");return json({ok:true,action:"update_trade",result:await updateTrade(db,trade,ctl,body)})}catch(error){const message=clean(error);console.error("trader-live-dca-control",message);const publicErrors=["real_account_required","execution_controls_missing","binance_not_connected","binance_trade_permission_required","binance_connection_not_safe","live_trading_not_enabled","trade_not_found","trade_not_active","trade_not_live","account_id_required","trade_id_required","invalid_stop_loss","bot_not_found","spot_symbol_not_tradeable","dca_order_below_exchange_minimum","dca_order_placement_failed","unknown_action"];const safe=publicErrors.includes(message)||message.startsWith("live_order_limit_exceeded:")||message.startsWith("live_capital_limit_exceeded:")||message.startsWith("insufficient_usdt:")||message.startsWith("binance_")||message.startsWith("gateway_")?message:"live_dca_control_failed";return json({error:safe},safe==="real_account_required"?403:400)}});
