"use client";

import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { browserSupabase as supabase } from "@/lib/supabase-browser";
import styles from "./onboarding.module.css";

type TeamMember={name:string;role:string;bio:string;photo_url:string};
type LinkItem={label:string;url:string};
type HiringItem={title:string;description:string;url:string};
type Asset={id:string;kind:string;label:string;public_url:string;storage_path?:string;original_filename:string;file_size?:number};
type Onboarding={
 id:string;status:string;lab_name:string;preferred_title:string;pi_bio:string;homepage_changes:string;research_changes:string;publication_changes:string;general_changes:string;
 team_members:unknown[];contact_email:string;contact_phone:string;contact_address:string;official_profile_url:string;linkedin_url:string;x_url:string;other_links:unknown[];
 domain_choice:string;preferred_domain:string;domain_notes:string;logo_url:string;brand_colors:string;branding_notes:string;hiring_status:string;hiring_items:unknown[];final_notes:string;
 identity_reviewed:boolean;content_reviewed:boolean;team_reviewed:boolean;contact_reviewed:boolean;domain_reviewed:boolean;branding_reviewed:boolean;hiring_reviewed:boolean;submitted_at?:string|null;last_saved_at?:string|null;
};
type Data={onboarding:Onboarding;progress:number;prospect:{pi_name:string;institution:string;department?:string|null};site?:{slug:string;domain_url?:string|null;headline?:string|null}|null;payment:{amount:number|string;currency:string;paid_at?:string|null};assets:Asset[]};
type Form=Omit<Onboarding,"team_members"|"other_links"|"hiring_items">&{team_members:TeamMember[];other_links:LinkItem[];hiring_items:HiringItem[]};

const sections=[
 ["identity","01","Identity & lab"],["content","02","Website content"],["team","03","Team"],["contact","04","Contact & links"],["domain","05","Domain"],["branding","06","Branding & images"],["hiring","07","Hiring & final notes"],
] as const;
const imageKinds=[["logo","Logo"],["portrait","PI portrait"],["team_photo","Team photo"],["lab_photo","Lab photo"],["research_image","Research image"],["other","Other image"]] as const;
const allowedImageTypes=["image/jpeg","image/png","image/webp","image/gif"];

function teamFrom(value:unknown[]):TeamMember[]{return (value||[]).map((x)=>{const o=(x&&typeof x==="object"?x:{}) as Record<string,unknown>;return{name:String(o.name||""),role:String(o.role||o.title||o.position||""),bio:String(o.bio||o.description||""),photo_url:String(o.photo_url||o.photo||o.image||"")}})}
function linksFrom(value:unknown[]):LinkItem[]{return (value||[]).map((x)=>{const o=(x&&typeof x==="object"?x:{}) as Record<string,unknown>;return{label:String(o.label||o.name||""),url:String(o.url||o.href||"")}})}
function hiringFrom(value:unknown[]):HiringItem[]{return (value||[]).map((x)=>{const o=(x&&typeof x==="object"?x:{}) as Record<string,unknown>;return{title:String(o.title||""),description:String(o.description||o.body||""),url:String(o.url||"")}})}
function formFrom(o:Onboarding):Form{return{...o,team_members:teamFrom(o.team_members),other_links:linksFrom(o.other_links),hiring_items:hiringFrom(o.hiring_items)}}
function fmt(value?:string|null){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function money(value:number|string,currency:string){const n=Number(value||0)||0;try{return new Intl.NumberFormat("en-US",{style:"currency",currency:currency||"USD"}).format(n)}catch{return`${currency} ${n.toFixed(2)}`}}
function imageExt(file:File){return file.type==="image/png"?"png":file.type==="image/webp"?"webp":file.type==="image/gif"?"gif":"jpg"}
function validateImage(file:File){if(file.size>15*1024*1024)return"Images must be 15 MB or smaller.";if(!allowedImageTypes.includes(file.type))return"Please choose a JPEG, PNG, WebP or GIF image.";return""}

export default function ClientOnboardingPage(){
 const params=useParams<{token:string}>();const token=String(params?.token||"");
 const [data,setData]=useState<Data|null>(null);const [form,setForm]=useState<Form|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [teamPhotoUploading,setTeamPhotoUploading]=useState<number|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [active,setActive]=useState("identity");const [uploadKind,setUploadKind]=useState("logo");const [uploadLabel,setUploadLabel]=useState("");const [uploadFile,setUploadFile]=useState<File|null>(null);
 const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");const{data:res,error:e}=await supabase.rpc("sales_client_onboarding_public_get",{p_token:token});if(e)setError(e.message);else if(res&&typeof res==="object"&&"error" in res)setError(String((res as {error?:string}).error||"Onboarding unavailable"));else{const next=res as Data;setData(next);setForm(formFrom(next.onboarding));}setLoading(false)},[token]);
 useEffect(()=>{void load()},[load]);
 const progress=useMemo(()=>form?Math.round(([form.identity_reviewed,form.content_reviewed,form.team_reviewed,form.contact_reviewed,form.domain_reviewed,form.branding_reviewed,form.hiring_reviewed].filter(Boolean).length/7)*100):0,[form]);
 const readonly=form?.status==="completed";
 function set<K extends keyof Form>(key:K,value:Form[K]){setForm((f)=>f?{...f,[key]:value}:f)}
 function scroll(id:string){setActive(id);document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
 async function save(show=true,override?:Form){const current=override||form;if(!current)return false;setSaving(true);setError("");const payload={...current};const{data:res,error:e}=await supabase.rpc("sales_client_onboarding_public_save",{p_token:token,p_payload:payload});setSaving(false);if(e){setError(e.message);return false}if(res&&typeof res==="object"&&"error" in res){setError(String((res as {error?:string}).error));return false}if(show){setNotice("Progress saved.");window.setTimeout(()=>setNotice(""),1800)}return true}
 async function submit(){if(!form)return;if(!(await save(false)))return;setSaving(true);const{data:res,error:e}=await supabase.rpc("sales_client_onboarding_public_submit",{p_token:token});setSaving(false);if(e)setError(e.message);else if(res&&typeof res==="object"&&"error" in res)setError(String((res as {error?:string}).error));else{setNotice("Onboarding submitted. LabNarrative will review your information before making any website changes.");await load()}}
 function updateTeam(index:number,key:keyof TeamMember,value:string){set("team_members",form!.team_members.map((m,i)=>i===index?{...m,[key]:value}:m))}
 function updateLink(index:number,key:keyof LinkItem,value:string){set("other_links",form!.other_links.map((m,i)=>i===index?{...m,[key]:value}:m))}
 function updateHiring(index:number,key:keyof HiringItem,value:string){set("hiring_items",form!.hiring_items.map((m,i)=>i===index?{...m,[key]:value}:m))}
 async function uploadTeamPhoto(index:number,file:File){if(!form)return;const validation=validateImage(file);if(validation){setError(validation);return}setTeamPhotoUploading(index);setError("");const path=`client-onboarding/${token}/${crypto.randomUUID()}.${imageExt(file)}`;const{error:upError}=await supabase.storage.from("labnarrative-images").upload(path,file,{contentType:file.type,upsert:false});if(upError){setError(upError.message);setTeamPhotoUploading(null);return}const publicUrl=supabase.storage.from("labnarrative-images").getPublicUrl(path).data.publicUrl;const member=form.team_members[index];const label=(member?.name||"").trim()||`Team member ${index+1}`;const{data:reg,error:regError}=await supabase.rpc("sales_client_onboarding_register_asset",{p_token:token,p_kind:"team_photo",p_label:label,p_storage_path:path,p_public_url:publicUrl,p_original_filename:file.name,p_mime_type:file.type,p_file_size:file.size});if(regError||reg&&typeof reg==="object"&&"error" in reg){await supabase.storage.from("labnarrative-images").remove([path]);setError(regError?.message||String((reg as {error?:string})?.error||"Could not register team photo"));setTeamPhotoUploading(null);return}const nextTeam=form.team_members.map((m,i)=>i===index?{...m,photo_url:publicUrl}:m);const nextForm={...form,team_members:nextTeam};setForm(nextForm);if(!(await save(false,nextForm))){const asset=(reg as {asset?:Asset}|null)?.asset;if(asset?.id)await supabase.rpc("sales_client_onboarding_remove_asset",{p_token:token,p_asset_id:asset.id});await supabase.storage.from("labnarrative-images").remove([path]);setTeamPhotoUploading(null);return}setNotice(`${label} photo uploaded.`);setTeamPhotoUploading(null);await load()}
 async function removeTeamPhoto(index:number){if(!form)return;const url=form.team_members[index]?.photo_url||"";const asset=data?.assets.find(a=>a.public_url===url);const nextForm={...form,team_members:form.team_members.map((m,i)=>i===index?{...m,photo_url:""}:m)};setForm(nextForm);if(!(await save(false,nextForm)))return;if(asset?.storage_path){await supabase.storage.from("labnarrative-images").remove([asset.storage_path]);await supabase.rpc("sales_client_onboarding_remove_asset",{p_token:token,p_asset_id:asset.id})}setNotice("Team member photo removed.");await load()}
 async function upload(){if(!uploadFile||!form)return;const validation=validateImage(uploadFile);if(validation){setError(validation);return}setUploading(true);setError("");const path=`client-onboarding/${token}/${crypto.randomUUID()}.${imageExt(uploadFile)}`;const{error:upError}=await supabase.storage.from("labnarrative-images").upload(path,uploadFile,{contentType:uploadFile.type,upsert:false});if(upError){setError(upError.message);setUploading(false);return}const publicUrl=supabase.storage.from("labnarrative-images").getPublicUrl(path).data.publicUrl;const{data:reg,error:regError}=await supabase.rpc("sales_client_onboarding_register_asset",{p_token:token,p_kind:uploadKind,p_label:uploadLabel,p_storage_path:path,p_public_url:publicUrl,p_original_filename:uploadFile.name,p_mime_type:uploadFile.type,p_file_size:uploadFile.size});if(regError||reg&&typeof reg==="object"&&"error" in reg){await supabase.storage.from("labnarrative-images").remove([path]);setError(regError?.message||String((reg as {error?:string})?.error||"Could not register image"));setUploading(false);return}setUploadFile(null);setUploadLabel("");setNotice("Image uploaded.");setUploading(false);await load()}
 async function removeAsset(asset:Asset){if(!asset.storage_path)return;setError("");const{error:storageError}=await supabase.storage.from("labnarrative-images").remove([asset.storage_path]);if(storageError){setError(storageError.message);return}const{error:e}=await supabase.rpc("sales_client_onboarding_remove_asset",{p_token:token,p_asset_id:asset.id});if(e)setError(e.message);else await load()}

 if(loading)return <main className={styles.state}><section className={styles.stateBox}><div className={styles.logo}>LabNarrative</div><h1>Opening your project workspace…</h1><p>Loading your approved website project and onboarding information.</p></section></main>;
 if(!data||!form)return <main className={styles.state}><section className={styles.stateBox}><div className={styles.logo}>LabNarrative</div><h1>Onboarding unavailable.</h1><p>{error||"This private onboarding link is unavailable."}</p></section></main>;
 const siteUrl=data.site?.domain_url||(data.site?.slug?`https://${data.site.slug}.labnarrative.com`:"");
 return <main className={styles.page}>
  <header className={styles.header}><div className={styles.headerInner}><div className={styles.logo}>LabNarrative</div><div className={styles.progressWrap}><div className={styles.progressTrack}><div className={styles.progressFill} style={{width:`${progress}%`}}/></div><strong>{progress}%</strong></div></div></header>
  <div className={styles.shell}>
   <aside className={styles.side}><p>Client onboarding</p><h2>{data.prospect.pi_name}</h2><small>{data.prospect.institution}</small><div className={styles.nav}>{sections.map(([id,no,title])=><button key={id} className={active===id?styles.active:""} onClick={()=>scroll(id)}>{no} · {title}</button>)}</div></aside>
   <div>
    <section className={styles.hero}><p className={styles.eyebrow}>Website finalisation</p><span className={styles.status}>{form.status.replaceAll("_"," ")}</span><h1>Help us make the website fully yours.</h1><p>We have already built your LabNarrative concept. Use this workspace to confirm what is correct, provide final corrections, add people and images, and tell us how you would like the finished website to be launched.</p>{siteUrl?<a className={styles.siteLink} href={siteUrl} target="_blank" rel="noreferrer">View your current website concept ↗</a>:null}<p className={styles.helper}>Deposit recorded: {money(data.payment.amount,data.payment.currency)} · {fmt(data.payment.paid_at)}</p></section>
    {form.status==="submitted"||form.status==="reviewing"?<div className={styles.submitted}><strong>Your onboarding has been submitted.</strong><p>LabNarrative is reviewing it. You may still make a correction and resubmit; doing so will reopen the onboarding for review.</p></div>:null}
    {form.status==="changes_requested"?<div className={styles.submitted}><strong>LabNarrative requested changes.</strong><p>Please review the sections below, save your updates and submit again.</p></div>:null}
    {form.status==="completed"?<div className={styles.submitted}><strong>Onboarding complete.</strong><p>This record is now read-only. Your information has been accepted for final website work.</p></div>:null}
    {error?<p className={styles.error}>{error}</p>:null}{notice?<p className={styles.success}>{notice}</p>:null}
    <div className={readonly?styles.readonly:""}>
     <section id="identity" className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionNo}>01</span><h3>Identity & lab</h3><p>Confirm how the laboratory and PI should be presented.</p></div><label className={styles.complete}><input type="checkbox" checked={form.identity_reviewed} onChange={e=>set("identity_reviewed",e.target.checked)}/> Section complete</label></div><div className={styles.grid2}><label className={styles.field}><span>Lab name</span><input value={form.lab_name} onChange={e=>set("lab_name",e.target.value)}/></label><label className={styles.field}><span>Website / academic title</span><input value={form.preferred_title} onChange={e=>set("preferred_title",e.target.value)}/></label></div><label className={styles.field}><span>PI biography or preferred introduction</span><textarea value={form.pi_bio} onChange={e=>set("pi_bio",e.target.value)} placeholder="Optional — leave blank if the current website introduction is already suitable."/></label></section>

     <section id="content" className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionNo}>02</span><h3>Website content</h3><p>Tell us exactly what should change. You do not need to rewrite content that is already correct.</p></div><label className={styles.complete}><input type="checkbox" checked={form.content_reviewed} onChange={e=>set("content_reviewed",e.target.checked)}/> Section complete</label></div><label className={styles.field}><span>Homepage changes</span><textarea value={form.homepage_changes} onChange={e=>set("homepage_changes",e.target.value)} placeholder="Headlines, introduction, emphasis, wording…"/></label><label className={styles.field}><span>Research changes</span><textarea value={form.research_changes} onChange={e=>set("research_changes",e.target.value)} placeholder="Corrections, missing research programmes, terminology, priorities…"/></label><label className={styles.field}><span>Publications changes</span><textarea value={form.publication_changes} onChange={e=>set("publication_changes",e.target.value)} placeholder="Publications to add/remove, preferred ordering, links…"/></label><label className={styles.field}><span>Anything else on the website</span><textarea value={form.general_changes} onChange={e=>set("general_changes",e.target.value)} placeholder="Navigation, contact page, join page, wording anywhere else…"/></label></section>

     <section id="team" className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionNo}>03</span><h3>Team</h3><p>Review the people we currently have and add, remove or correct members.</p></div><label className={styles.complete}><input type="checkbox" checked={form.team_reviewed} onChange={e=>set("team_reviewed",e.target.checked)}/> Section complete</label></div><div className={styles.list}>{form.team_members.map((m,i)=><article className={styles.itemCard} key={i}><div className={styles.grid2}><label className={styles.field}><span>Name</span><input value={m.name} onChange={e=>updateTeam(i,"name",e.target.value)}/></label><label className={styles.field}><span>Role / position</span><input value={m.role} onChange={e=>updateTeam(i,"role",e.target.value)}/></label></div><label className={styles.field}><span>Short bio / research role</span><textarea value={m.bio} onChange={e=>updateTeam(i,"bio",e.target.value)}/></label><div className={styles.teamPhotoField}><span className={styles.teamPhotoLabel}>Member photo</span><div className={styles.teamPhotoRow}>{m.photo_url?<img className={styles.teamPhotoPreview} src={m.photo_url} alt={`${m.name||"Team member"} portrait`}/>:<div className={styles.teamPhotoPlaceholder}>No photo</div>}<div className={styles.photoUploadActions}><label className={styles.photoUploadButton}>{teamPhotoUploading===i?"Uploading…":m.photo_url?"Replace photo":"Upload photo"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={teamPhotoUploading!==null} onChange={e=>{const file=e.target.files?.[0];e.currentTarget.value="";if(file)void uploadTeamPhoto(i,file)}}/></label>{m.photo_url?<button type="button" className={styles.photoRemoveButton} disabled={teamPhotoUploading!==null} onClick={()=>void removeTeamPhoto(i)}>Remove photo</button>:null}<small>Choose from your device · JPEG, PNG, WebP or GIF · max 15 MB</small></div></div><label className={styles.photoUrlFallback}><span>Or paste image URL</span><input value={m.photo_url} onChange={e=>updateTeam(i,"photo_url",e.target.value)} placeholder="https://…"/></label></div><div className={styles.itemActions}><button type="button" className={styles.textButton} onClick={()=>set("team_members",form.team_members.filter((_,x)=>x!==i))}>Remove member</button></div></article>)}</div><button type="button" className={styles.addButton} onClick={()=>set("team_members",[...form.team_members,{name:"",role:"",bio:"",photo_url:""}])}>+ Add team member</button><p className={styles.helper}>Upload each member's photo directly here. Uploaded portraits are also kept in the project image library for LabNarrative review.</p></section>

     <section id="contact" className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionNo}>04</span><h3>Contact & links</h3><p>Provide the public contact details and profiles you want visitors to use.</p></div><label className={styles.complete}><input type="checkbox" checked={form.contact_reviewed} onChange={e=>set("contact_reviewed",e.target.checked)}/> Section complete</label></div><div className={styles.grid2}><label className={styles.field}><span>Public email</span><input type="email" value={form.contact_email} onChange={e=>set("contact_email",e.target.value)}/></label><label className={styles.field}><span>Phone (optional)</span><input value={form.contact_phone} onChange={e=>set("contact_phone",e.target.value)}/></label></div><label className={styles.field}><span>Address</span><textarea value={form.contact_address} onChange={e=>set("contact_address",e.target.value)}/></label><div className={styles.grid2}><label className={styles.field}><span>Official institutional profile</span><input value={form.official_profile_url} onChange={e=>set("official_profile_url",e.target.value)}/></label><label className={styles.field}><span>LinkedIn</span><input value={form.linkedin_url} onChange={e=>set("linkedin_url",e.target.value)}/></label></div><label className={styles.field}><span>X / Twitter</span><input value={form.x_url} onChange={e=>set("x_url",e.target.value)}/></label><div className={styles.list}>{form.other_links.map((m,i)=><article className={styles.itemCard} key={i}><div className={styles.grid2}><label className={styles.field}><span>Label</span><input value={m.label} onChange={e=>updateLink(i,"label",e.target.value)}/></label><label className={styles.field}><span>URL</span><input value={m.url} onChange={e=>updateLink(i,"url",e.target.value)}/></label></div><div className={styles.itemActions}><button className={styles.textButton} onClick={()=>set("other_links",form.other_links.filter((_,x)=>x!==i))}>Remove link</button></div></article>)}</div><button className={styles.addButton} onClick={()=>set("other_links",[...form.other_links,{label:"",url:""}])}>+ Add another link</button></section>

     <section id="domain" className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionNo}>05</span><h3>Domain</h3><p>Tell us how you want people to reach the finished site.</p></div><label className={styles.complete}><input type="checkbox" checked={form.domain_reviewed} onChange={e=>set("domain_reviewed",e.target.checked)}/> Section complete</label></div><div className={styles.domainChoices}>{[["labnarrative","Keep the LabNarrative address","Continue using the current *.labnarrative.com address."],["custom","Use a custom domain","Use or purchase a dedicated lab domain."],["institutional","Institutional domain","Connect or redirect from an institutional university address."],["undecided","Not sure yet","We can decide together before launch."]].map(([value,title,desc])=><label className={styles.choice} key={value}><input type="radio" name="domain" checked={form.domain_choice===value} onChange={()=>set("domain_choice",value)}/><span><strong>{title}</strong><small>{desc}</small></span></label>)}</div><label className={styles.field}><span>Preferred domain (if known)</span><input value={form.preferred_domain} onChange={e=>set("preferred_domain",e.target.value)} placeholder="examplelab.org"/></label><label className={styles.field}><span>Domain notes</span><textarea value={form.domain_notes} onChange={e=>set("domain_notes",e.target.value)} placeholder="Existing domain provider, university IT requirements, alternative ideas…"/></label></section>

     <section id="branding" className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionNo}>06</span><h3>Branding & images</h3><p>Share a logo, portrait, team/lab photographs or research visuals you would like us to consider.</p></div><label className={styles.complete}><input type="checkbox" checked={form.branding_reviewed} onChange={e=>set("branding_reviewed",e.target.checked)}/> Section complete</label></div><div className={styles.grid2}><label className={styles.field}><span>Logo URL (optional)</span><input value={form.logo_url} onChange={e=>set("logo_url",e.target.value)}/></label><label className={styles.field}><span>Preferred colours</span><input value={form.brand_colors} onChange={e=>set("brand_colors",e.target.value)} placeholder="e.g. dark green and warm ivory"/></label></div><label className={styles.field}><span>Branding / design notes</span><textarea value={form.branding_notes} onChange={e=>set("branding_notes",e.target.value)} placeholder="Keep current design, preferred mood, visual references, logo guidance…"/></label><div className={styles.uploadBox}><div className={styles.uploadRow}><label className={styles.field}><span>Image type</span><select value={uploadKind} onChange={e=>setUploadKind(e.target.value)}>{imageKinds.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className={styles.field}><span>Label</span><input value={uploadLabel} onChange={e=>setUploadLabel(e.target.value)} placeholder="e.g. Sarah Chen — postdoc"/></label><label className={styles.field}><span>Image file</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setUploadFile(e.target.files?.[0]||null)}/></label></div><button className={styles.addButton} disabled={!uploadFile||uploading} onClick={()=>void upload()}>{uploading?"Uploading…":"Upload image"}</button><p className={styles.helper}>JPEG, PNG, WebP or GIF · maximum 15 MB each.</p></div>{data.assets.length?<div className={styles.assets}>{data.assets.map(a=><article className={styles.asset} key={a.id}><img src={a.public_url} alt={a.label||a.original_filename}/><div className={styles.assetBody}><strong>{a.label||a.original_filename}</strong><small>{a.kind.replaceAll("_"," ")}</small><button onClick={()=>void removeAsset(a)}>Remove</button></div></article>)}</div>:null}</section>

     <section id="hiring" className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionNo}>07</span><h3>Hiring & final notes</h3><p>Tell us whether the lab is recruiting and add anything we have not asked about.</p></div><label className={styles.complete}><input type="checkbox" checked={form.hiring_reviewed} onChange={e=>set("hiring_reviewed",e.target.checked)}/> Section complete</label></div><label className={styles.field}><span>Hiring status</span><select value={form.hiring_status} onChange={e=>set("hiring_status",e.target.value)}><option value="none">Not currently recruiting</option><option value="opening">We have open positions</option><option value="considering">Open to enquiries / future opportunities</option></select></label>{form.hiring_status!=="none"?<><div className={styles.list}>{form.hiring_items.map((m,i)=><article className={styles.itemCard} key={i}><label className={styles.field}><span>Position title</span><input value={m.title} onChange={e=>updateHiring(i,"title",e.target.value)}/></label><label className={styles.field}><span>Description</span><textarea value={m.description} onChange={e=>updateHiring(i,"description",e.target.value)}/></label><label className={styles.field}><span>Application / advert URL</span><input value={m.url} onChange={e=>updateHiring(i,"url",e.target.value)}/></label><div className={styles.itemActions}><button className={styles.textButton} onClick={()=>set("hiring_items",form.hiring_items.filter((_,x)=>x!==i))}>Remove position</button></div></article>)}</div><button className={styles.addButton} onClick={()=>set("hiring_items",[...form.hiring_items,{title:"",description:"",url:""}])}>+ Add position</button></>:null}<label className={styles.field}><span>Final notes for LabNarrative</span><textarea value={form.final_notes} onChange={e=>set("final_notes",e.target.value)} placeholder="Anything else you would like us to know before we finalise the website?"/></label></section>
    </div>
   </div>
  </div>
  {!readonly?<footer className={styles.footerBar}><div className={styles.footerInner}><span>{form.last_saved_at?`Last saved ${fmt(form.last_saved_at)}`:"Your changes are private until you submit them."}</span><button disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save progress"}</button><button className={styles.primary} disabled={saving||progress<100} onClick={()=>void submit()}>{progress<100?`Review all sections (${progress}%)`:"Submit to LabNarrative"}</button></div></footer>:null}
 </main>
}
