import { NextRequest, NextResponse } from "next/server";

const RESERVED_SUBDOMAINS = new Set(["www", "platform", "admin", "api"]);
const PLATFORM_ALIAS_HOSTS = new Set([
  "labnarrative-platform.vercel.app",
  "labnarrative-platform-lab-narrative.vercel.app",
  "labnarrative-platform-git-main-lab-narrative.vercel.app",
]);
const CANONICAL_PLATFORM_HOST = "platform.labnarrative.com";
const WEBSITE_ADMIN_SEGMENTS = new Set([
  "sites",
  "sites-v3",
  "sites-v4",
  "discovery",
  "review",
  "sales",
  "care",
  "linkedin",
  "outreach",
  "outreach-v2",
  "outreach-setup",
  "preview",
  "recovery",
  "session-import",
  "session-transfer",
]);

export function proxy(request: NextRequest) {
  const host = request.headers.get("host")?.split(":")[0].toLowerCase() ?? "";
  const rootDomain = process.env.NEXT_PUBLIC_ROOT_DOMAIN ?? "labnarrative.com";
  const isAdminHost =
    host === rootDomain ||
    host === `www.${rootDomain}` ||
    host === CANONICAL_PLATFORM_HOST ||
    host === "localhost";

  // Engine v4 machine renderer capability URLs are short-lived private
  // verification surfaces. Prevent the token in the query string from being
  // forwarded as a Referer to remote portrait hosts or indexed/cached.
  if (request.nextUrl.pathname.startsWith("/engine-v4/render/")) {
    const response = NextResponse.next();
    response.headers.set("Referrer-Policy", "no-referrer");
    response.headers.set("X-Robots-Tag", "noindex, nofollow, noarchive");
    response.headers.set("Cache-Control", "private, no-store, max-age=0");
    return response;
  }

  // Keep the administrator session on one browser origin for Vercel aliases.
  // The public LabNarrative domain is intentionally allowed to host the new
  // umbrella admin and its branch namespaces.
  if (request.nextUrl.pathname.startsWith("/admin") && PLATFORM_ALIAS_HOSTS.has(host)) {
    const canonicalUrl = request.nextUrl.clone();
    canonicalUrl.protocol = "https:";
    canonicalUrl.hostname = CANONICAL_PLATFORM_HOST;
    canonicalUrl.port = "";
    return NextResponse.redirect(canonicalUrl, 307);
  }

  // /admin is the LabNarrative umbrella Control Center. It must never resolve
  // into a branch automatically. Keep it uncached so old legacy redirects or
  // landing responses cannot be reused by the browser/CDN.
  if (isAdminHost && request.nextUrl.pathname === "/admin" && request.nextUrl.search === "") {
    const response = NextResponse.next();
    response.headers.set("Cache-Control", "private, no-store, max-age=0, must-revalidate");
    response.headers.set("Pragma", "no-cache");
    response.headers.set("Expires", "0");
    return response;
  }

  // /admin/websites is the Websites branch root and leads into the existing
  // Sites workspace.
  if (isAdminHost && (request.nextUrl.pathname === "/admin/websites" || request.nextUrl.pathname === "/admin/websites/")) {
    const sitesUrl = request.nextUrl.clone();
    sitesUrl.pathname = "/admin/websites/sites";
    return NextResponse.redirect(sitesUrl, 307);
  }

  // Give Websites a clean top-level outreach route while retaining the current
  // outreach setup implementation. Run-specific outreach URLs continue to map
  // through /admin/websites/outreach/[runId].
  if (isAdminHost && request.nextUrl.pathname === "/admin/websites/outreach") {
    const outreachUrl = request.nextUrl.clone();
    outreachUrl.pathname = "/admin/outreach-setup";
    return NextResponse.rewrite(outreachUrl);
  }

  // LabNarrative Websites now lives under /admin/websites/*.
  // Rewrite those clean branch URLs to the existing, proven admin pages while
  // preserving the browser-visible namespace.
  if (isAdminHost && request.nextUrl.pathname.startsWith("/admin/websites/")) {
    const internalUrl = request.nextUrl.clone();
    internalUrl.pathname = `/admin/${request.nextUrl.pathname.slice("/admin/websites/".length)}`;
    return NextResponse.rewrite(internalUrl);
  }

  // Redirect legacy top-level Websites admin URLs on the public root into the
  // new Websites namespace. This also keeps links generated by older internal
  // pages inside /admin/websites/... as the user navigates.
  if (
    (host === rootDomain || host === `www.${rootDomain}` || host === "localhost") &&
    request.nextUrl.pathname.startsWith("/admin/")
  ) {
    const remainder = request.nextUrl.pathname.slice("/admin/".length);
    const firstSegment = remainder.split("/")[0];
    if (WEBSITE_ADMIN_SEGMENTS.has(firstSegment)) {
      const branchUrl = request.nextUrl.clone();
      branchUrl.pathname = `/admin/websites/${remainder}`;
      return NextResponse.redirect(branchUrl, 307);
    }
  }

  // API routes are platform infrastructure and must remain addressable from
  // every custom laboratory subdomain without being rewritten as site pages.
  if (request.nextUrl.pathname === "/api" || request.nextUrl.pathname.startsWith("/api/")) {
    return NextResponse.next();
  }

  // The root LabNarrative brand now acts as an umbrella for Websites and
  // Intelligence. Keep the established Websites implementation available at
  // /websites while serving the umbrella homepage at the public root.
  if (
    request.nextUrl.pathname === "/" &&
    (
      host === rootDomain ||
      host === `www.${rootDomain}` ||
      host === "localhost" ||
      host.endsWith(".vercel.app")
    )
  ) {
    const umbrellaUrl = request.nextUrl.clone();
    umbrellaUrl.pathname = "/umbrella";
    return NextResponse.rewrite(umbrellaUrl);
  }

  if (
    !host ||
    host === rootDomain ||
    host === `www.${rootDomain}` ||
    host === "localhost" ||
    host.endsWith(".vercel.app")
  ) {
    return NextResponse.next();
  }

  if (host.endsWith(`.${rootDomain}`)) {
    const subdomain = host.slice(0, -(rootDomain.length + 1)).split(".")[0];

    if (!subdomain || RESERVED_SUBDOMAINS.has(subdomain)) {
      return NextResponse.next();
    }

    const url = request.nextUrl.clone();
    const internalPrefix = `/sites/${subdomain}`;

    // Public subdomains should expose clean paths such as /research. Older
    // renderer links may already include /sites/{slug}; strip that prefix
    // before applying the hostname rewrite so it is never duplicated.
    const publicPath = url.pathname === internalPrefix
      ? "/"
      : url.pathname.startsWith(`${internalPrefix}/`)
        ? url.pathname.slice(internalPrefix.length)
        : url.pathname;

    const suffix = publicPath === "/" ? "" : publicPath;
    url.pathname = `${internalPrefix}${suffix}`;

    const requestHeaders = new Headers(request.headers);
    requestHeaders.set("x-labnarrative-public-subdomain", subdomain);
    return NextResponse.rewrite(url, { request: { headers: requestHeaders } });
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico|robots.txt).*)"],
};
