"use client";

import { useEffect, useMemo, useState } from "react";
import { browserSupabase } from "@/lib/supabase-browser";
import { formatWealthMoney, type WealthCurrency } from "./wealth-money";
import styles from "./wealth.module.css";
import visuals from "./wealth-visuals.module.css";

type PortfolioKind = "real" | "paper";
type Account = { id:string; provider:string|null; account_name:string|null; connection_mode:string|null; };
type Holding = { id:string; account_id:string; asset_name:string; symbol:string|null; asset_type:string|null; quantity:number|string|null; unit_price:number|string|null; market_value:number|string|null; cost_basis:number|string|null; currency:string|null; };
type Snapshot = { snapshot_date:string; net_worth:number|string|null; };
type DonutItem = { key:string; name:string; value:number; color:string };

const TYPE_LABELS:Record<string,string>={saudi_stock:"الأسهم السعودية",global_stock:"الأسهم العالمية",reit:"الريت",fund:"الصناديق",sukuk:"الصكوك",murabaha:"المرابحات",cash:"النقد",crypto:"الأصول الرقمية",real_estate:"العقار",private_asset:"الاستثمارات الخاصة",other:"أخرى"};
const TYPE_COLORS:Record<string,string>={saudi_stock:"#38bdf8",global_stock:"#6366f1",reit:"#f59e0b",fund:"#8b5cf6",sukuk:"#14b8a6",murabaha:"#06b6d4",cash:"#94a3b8",crypto:"#ec4899",real_estate:"#fb923c",private_asset:"#a78bfa",other:"#64748b"};
const ACCOUNT_COLORS=["#38bdf8","#8b5cf6","#f59e0b","#14b8a6","#ec4899","#6366f1"];
const PROFIT="#22c55e",LOSS="#ef4444";
const numeric=(v:number|string|null|undefined)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
const formatNumber=(v:number,d=2)=>new Intl.NumberFormat("ar-SA-u-nu-arab",{maximumFractionDigits:d}).format(v);
const formatPercent=(v:number)=>`${v>0?"+":""}${formatNumber(v,1)}٪`;

function Donut({items,total,currency}:{items:DonutItem[];total:number;currency:WealthCurrency}){
  const positive=items.filter(i=>i.value>0);const[activeKey,setActiveKey]=useState<string|null>(null);const active=positive.find(i=>i.key===activeKey)??positive[0];let cursor=0;
  if(!positive.length)return<div className={visuals.emptyChart}>لا توجد بيانات بعد.</div>;
  return<div className={visuals.donutLayout}><div className={visuals.donutWrap}><svg className={visuals.donut} viewBox="0 0 120 120"><circle className={visuals.donutTrack} cx="60" cy="60" r="46" pathLength="100"/>{positive.map(item=>{const share=total>0?item.value/total*100:0;const offset=cursor;cursor+=share;return<circle key={item.key} className={visuals.donutSegment} cx="60" cy="60" r="46" pathLength="100" stroke={item.color} strokeDasharray={`${Math.max(share-.8,.5)} ${100-Math.max(share-.8,.5)}`} strokeDashoffset={-offset} onMouseEnter={()=>setActiveKey(item.key)} onMouseLeave={()=>setActiveKey(null)}/>})}</svg><div className={visuals.donutCenter}><small>{active?.name??"الإجمالي"}</small><strong>{formatWealthMoney(active?.value??total,currency)}</strong><span>{active&&total>0?`${formatNumber(active.value/total*100,1)}٪`:"100٪"}</span></div></div><div className={visuals.legend}>{positive.map(item=><button type="button" key={item.key} className={visuals.legendItem} onMouseEnter={()=>setActiveKey(item.key)} onMouseLeave={()=>setActiveKey(null)}><i style={{background:item.color}}/><span><strong>{item.name}</strong><small>{total>0?`${formatNumber(item.value/total*100,1)}٪`:"0٪"}</small></span><b>{formatWealthMoney(item.value,currency)}</b></button>)}</div></div>
}

export default function WealthDashboardV2(){
  const[kind,setKind]=useState<PortfolioKind>("real");const[accounts,setAccounts]=useState<Account[]>([]);const[holdings,setHoldings]=useState<Holding[]>([]);const[snapshots,setSnapshots]=useState<Snapshot[]>([]);const[baseCurrency,setBaseCurrency]=useState<WealthCurrency>("SAR");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{let alive=true;async function load(){try{const mode:PortfolioKind=new URLSearchParams(window.location.search).get("portfolio")==="paper"?"paper":"real";setKind(mode);const{data:userData,error:userError}=await browserSupabase.auth.getUser();if(userError||!userData.user){window.location.replace(`/wealth/login?next=${encodeURIComponent(window.location.pathname+window.location.search)}`);return}const uid=userData.user.id;if(mode==="paper"){const{error:seedError}=await browserSupabase.rpc("ensure_wealth_paper_portfolio");if(seedError)throw seedError}const[a,h,s,p]=await Promise.all([
    browserSupabase.from("wealth_accounts").select("id,provider,account_name,connection_mode").eq("user_id",uid).eq("portfolio_kind",mode).order("created_at"),
    browserSupabase.from("wealth_holdings").select("id,account_id,asset_name,symbol,asset_type,quantity,unit_price,market_value,cost_basis,currency").eq("user_id",uid).eq("portfolio_kind",mode).order("market_value",{ascending:false}),
    browserSupabase.from("wealth_snapshots").select("snapshot_date,net_worth").eq("user_id",uid).eq("portfolio_kind",mode).order("snapshot_date"),
    browserSupabase.from("wealth_profiles").select("base_currency").eq("user_id",uid).maybeSingle()]);
    if(a.error)throw a.error;if(h.error)throw h.error;if(s.error)throw s.error;if(p.error)throw p.error;if(!alive)return;setAccounts((a.data??[]) as Account[]);setHoldings((h.data??[]) as Holding[]);setSnapshots((s.data??[]) as Snapshot[]);setBaseCurrency(p.data?.base_currency==="USD"?"USD":"SAR")
  }catch(e){if(alive)setError(e instanceof Error?e.message:"تعذر تحميل المحفظة.")}finally{if(alive)setLoading(false)}}void load();return()=>{alive=false}},[]);

  async function changeCurrency(currency:WealthCurrency){setBaseCurrency(currency);const{data}=await browserSupabase.auth.getUser();if(data.user)await browserSupabase.from("wealth_profiles").upsert({user_id:data.user.id,base_currency:currency,updated_at:new Date().toISOString()},{onConflict:"user_id"})}
  const money=(v:number)=>formatWealthMoney(v,baseCurrency);
  const m=useMemo(()=>{const total=holdings.reduce((s,h)=>s+numeric(h.market_value),0);const known=holdings.filter(h=>h.cost_basis!==null);const cost=known.reduce((s,h)=>s+numeric(h.cost_basis),0);const knownMarket=known.reduce((s,h)=>s+numeric(h.market_value),0);const pnl=known.length?knownMarket-cost:null;const pnlPct=pnl!==null&&cost>0?pnl/cost*100:null;const cash=holdings.filter(h=>h.asset_type==="cash").reduce((s,h)=>s+numeric(h.market_value),0);const typeMap=new Map<string,number>();const accountMap=new Map<string,number>();holdings.forEach(h=>{const t=h.asset_type||"other";typeMap.set(t,(typeMap.get(t)??0)+numeric(h.market_value));accountMap.set(h.account_id,(accountMap.get(h.account_id)??0)+numeric(h.market_value))});const allocation=[...typeMap].map(([key,value])=>({key,name:TYPE_LABELS[key]??"أخرى",value,color:TYPE_COLORS[key]??TYPE_COLORS.other})).sort((a,b)=>b.value-a.value);const accountItems=accounts.map((a,i)=>({key:a.id,name:a.provider||a.account_name||"حساب",value:accountMap.get(a.id)??0,color:ACCOUNT_COLORS[i%ACCOUNT_COLORS.length]}));const winners=known.filter(h=>numeric(h.market_value)>=numeric(h.cost_basis)).reduce((s,h)=>s+numeric(h.market_value),0);const losers=known.filter(h=>numeric(h.market_value)<numeric(h.cost_basis)).reduce((s,h)=>s+numeric(h.market_value),0);return{total,cost,pnl,pnlPct,cash,allocation,accountItems,accountMap,winners,losers}},[holdings,accounts]);

  const paper=kind==="paper";const portfolioSuffix=paper?"?portfolio=paper":"";const manageHref=paper?"/wealth/assets?portfolio=paper&manage=1":"/wealth/assets?manage=1";const latest=snapshots.at(-1);
  if(loading)return<main className={styles.page} dir="rtl"><section className={styles.loadingState}>جاري تحميل ثروتك…</section></main>;
  if(error)return<main className={styles.page} dir="rtl"><section className={styles.loadingState}><strong>تعذر تحميل البيانات.</strong><span>{error}</span></section></main>;

  return<main className={styles.page} dir="rtl"><aside className={styles.sidebar}><div><div className={styles.brand}>ثروة</div><div className={styles.brandSub}>{paper?"محفظة تجريبية":"إدارة الثروة"}</div></div><nav className={styles.nav}><a href={`/wealth${portfolioSuffix}`} className={`${styles.navItem} ${styles.active}`}>نظرة عامة</a><a href={`/wealth/assets${portfolioSuffix}`} className={styles.navItem}>الأصول</a><a href={`/wealth/income${portfolioSuffix}`} className={styles.navItem}>الدخل</a><span className={styles.navItem}>التحليلات</span><span className={styles.navItem}>الالتزام الشرعي</span><span className={styles.navItem}>الحسابات</span></nav><div className={styles.profile}><span className={styles.avatar}>{paper?"ت":"ث"}</span><span><strong>{paper?"حساب تجريبي":"حساب المستثمر"}</strong><small>{paper?"بيانات اختبار منفصلة":"بياناتك الحقيقية"}</small></span></div></aside>
    <section className={styles.workspace}><header className={styles.topbar}><div><p>{paper?"بيئة اختبار آمنة":"المحفظة الحقيقية"}</p><h1>{paper?"المحفظة التجريبية":"نظرة عامة"}</h1></div><div className={styles.topActions}><div style={currencyToggle}><button type="button" style={baseCurrency==="SAR"?currencyActive:currencyButton} onClick={()=>void changeCurrency("SAR")}>ر.س</button><button type="button" style={baseCurrency==="USD"?currencyActive:currencyButton} onClick={()=>void changeCurrency("USD")}>$</button></div><a href={paper?"/wealth":"/wealth?portfolio=paper"} className={styles.ghostButton}>{paper?"محفظتي الحقيقية":"محفظة تجريبية"}</a><a href={manageHref} className={styles.primaryButton}>إدارة الأصول</a></div></header>
      <div className={styles.content}>{paper&&<div style={{marginBottom:18,padding:"12px 16px",border:"1px solid #3a3a3a",borderRadius:14,color:"#a1a1aa",fontSize:11}}>هذه محفظة اختبار مستقلة بالكامل. أي تعديل هنا لا يؤثر على استثماراتك الحقيقية.</div>}
        <section className={styles.heroGrid}><article className={styles.netWorthCard}><div className={styles.cardHeader}><span>صافي الثروة</span><small>{accounts.length} حساب · {holdings.length} أصل</small></div><div className={styles.netWorth}>{money(m.total)}</div><div className={`${styles.growth} ${m.pnl===null?visuals.neutral:m.pnl>=0?visuals.profit:visuals.loss}`}>{m.pnl===null?"التكلفة غير مكتملة":<>{m.pnl>=0?"↑":"↓"} {money(Math.abs(m.pnl))} <span className={m.pnl>=0?visuals.profit:visuals.loss}>{formatPercent(m.pnlPct??0)} غير محققة</span></>}</div><div className={styles.snapshotArea}><span className={styles.snapshotDot}/><div><strong>{paper?"نقطة اختبار":"آخر Snapshot"}</strong><small>{latest?new Intl.DateTimeFormat("ar-SA-u-nu-arab",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${latest.snapshot_date}T12:00:00`)):"لا يوجد سجل بعد"}</small></div></div></article><div className={styles.metricStack}><article className={styles.metric}><p>الربح / الخسارة</p><strong className={m.pnl===null?visuals.neutral:m.pnl>=0?visuals.profit:visuals.loss}>{m.pnl===null?"—":money(m.pnl)}</strong><small>{m.pnlPct===null?"—":formatPercent(m.pnlPct)}</small></article><article className={styles.metric}><p>عدد الأصول</p><strong>{formatNumber(holdings.length,0)}</strong><small>عبر {formatNumber(accounts.length,0)} حسابات</small></article><article className={styles.metric}><p>السيولة</p><strong>{money(m.cash)}</strong><small>السيولة المسجّلة</small></article></div></section>
        <section className={visuals.visualGrid}><article className={visuals.chartCard}><div className={visuals.chartTitle}><div><small>توزيع الأصول</small><h2>أين توجد الثروة؟</h2></div></div><Donut items={m.allocation} total={m.total} currency={baseCurrency}/></article><article className={visuals.chartCard}><div className={visuals.chartTitle}><div><small>الحسابات</small><h2>التوزيع حسب المصدر</h2></div></div><Donut items={m.accountItems} total={m.total} currency={baseCurrency}/></article><article className={visuals.chartCard}><div className={visuals.chartTitle}><div><small>حالة المراكز</small><h2>رابح مقابل خاسر</h2></div></div><Donut items={[{key:"profit",name:"مراكز رابحة",value:m.winners,color:PROFIT},{key:"loss",name:"مراكز خاسرة",value:m.losers,color:LOSS}]} total={m.winners+m.losers} currency={baseCurrency}/></article></section>
        <section className={styles.gridTwoBottom}><article className={styles.panel}><div className={styles.panelTitle}><div><h2>الحسابات والمحافظ</h2><p>{paper?"حسابات تجريبية متنوعة":"مصادر أصولك الحالية"}</p></div><a href={manageHref}>إدارة</a></div><div className={styles.accountRows}>{accounts.map(a=><div className={styles.accountRow} key={a.id}><div className={styles.accountLogo}>{(a.provider||"ح").slice(0,1)}</div><div className={styles.accountName}><strong>{a.provider||"حساب"}</strong><small>{a.account_name||"محفظة"}</small></div><div className={styles.accountValue}>{money(m.accountMap.get(a.id)??0)}</div><div className={styles.accountStatus}><i/>{paper?"تجريبي":a.connection_mode==="manual"?"يدوي":"متصل"}</div></div>)}</div></article><article className={styles.askPanel}><small>{paper?"مختبر ثروة":"ذكاء الثروة"}</small><h2>{paper?"نبني هنا قبل الربط الحقيقي":"اسأل عن ثروتك"}</h2><p>{paper?"سننفذ الميزات القادمة على هذه المحفظة المتنوعة أولًا: الأسعار، التاريخ، الدخل، التحليلات والالتزام الشرعي.":"ستعمل التحليلات على بياناتك الحقيقية فقط."}</p><div className={styles.question}>ما أكبر تركّز في المحفظة؟</div><div className={styles.question}>ما أكثر أصل رابح وخاسر؟</div><div className={styles.question}>كيف توزعت الثروة بين السعودية والعالم والكريبتو؟</div></article></section>
      </div></section></main>
}

const currencyToggle:React.CSSProperties={display:"flex",gap:3,padding:3,border:"1px solid #3a3a3a",borderRadius:999};
const currencyButton:React.CSSProperties={height:32,minWidth:44,padding:"0 10px",border:0,borderRadius:999,background:"transparent",color:"#a1a1aa",font:"inherit",cursor:"pointer"};
const currencyActive:React.CSSProperties={...currencyButton,background:"#f5f3f0",color:"#1f1f1f"};
