"use client";

import { useParams, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { browserSupabase as supabase } from "@/lib/supabase-browser";
import styles from "./care.module.css";

type Plan={id:string;name:string;description:string;billing_interval:"month"|"year";price_amount:number|string;currency:string;features:string[];provider_ready:boolean};
type Sub={id:string;status:string;plan_name:string;billing_interval:string;price_amount:number|string;currency:string;subscriber_name?:string|null;subscriber_email?:string|null;started_at?:string|null;next_billing_at?:string|null;last_payment_at?:string|null};
type Req={id:string;category:string;subject:string;details:string;status:string;submitted_at:string;completed_at?:string|null};
type Data={offer:{id:string;status:string;valid_until:string;selected_plan_id?:string|null;client_name?:string|null;client_email?:string|null};prospect:{pi_name:string;institution:string;department?:string|null};site?:{slug?:string|null;domain_url?:string|null;status?:string|null;lab_name?:string|null}|null;plans:Plan[];subscription?:Sub|null;requests:Req[]};
function money(v:number|string,c:string){const n=Number(v||0)||0;try{return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD",maximumFractionDigits:2}).format(n)}catch{return`${c||"USD"} ${n.toFixed(2)}`}}
function fmt(v?:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"long",year:"numeric"}).format(d)}
function label(v:string){return(v||"—").replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase())}

export default function CarePortal(){
 const params=useParams<{token:string}>();const search=useSearchParams();const token=String(params?.token||"");const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[category,setCategory]=useState("publication");const[subject,setSubject]=useState("");const[details,setDetails]=useState("");const[name,setName]=useState("");const[email,setEmail]=useState("");const verifyStarted=useRef(false);
 const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");const{data:r,error:e}=await supabase.rpc("care_public_get",{p_token:token});if(e)setError(e.message);else if(r&&typeof r==="object"&&"error" in r)setError(String((r as{error?:string}).error||"Care portal unavailable."));else{const d=r as Data;setData(d);setName(v=>v||d.offer.client_name||d.subscription?.subscriber_name||"");setEmail(v=>v||d.offer.client_email||d.subscription?.subscriber_email||"")}setLoading(false)},[token]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const state=search.get("paypal");if(state==="cancelled")setNotice("PayPal subscription setup was cancelled. No Care subscription was activated.");if(state!=="return"||verifyStarted.current||loading||!data)return;verifyStarted.current=true;setBusy("verify");setNotice("Confirming your LabNarrative Care subscription with PayPal…");void supabase.functions.invoke("paypal-care",{body:{action:"verify_subscription",token}}).then(async({data:r,error:e})=>{if(e)throw e;if(r?.error)throw new Error(String(r.error));if(r?.active){setNotice("LabNarrative Care is active. Welcome.");await load();window.history.replaceState({},"",`/care/${token}`)}else setNotice(`PayPal subscription status: ${String(r?.status||"pending")}.`) }).catch(e=>setError(e instanceof Error?e.message:"Could not verify the subscription.")).finally(()=>setBusy(""))},[data,load,loading,search,token]);
 const siteUrl=useMemo(()=>data?.site?.domain_url||(data?.site?.slug?`https://${data.site.slug}.labnarrative.com`:""),[data]);
 async function subscribe(planId:string){setBusy(planId);setError("");setNotice("");const{data:r,error:e}=await supabase.functions.invoke("paypal-care",{body:{action:"create_subscription",token,planId}});if(e){setError(e.message);setBusy("");return}if(r?.error){setError(String(r.error));setBusy("");return}if(r?.active){await load();setBusy("");return}const url=String(r?.approvalUrl||"");if(!url.startsWith("https://")){setError("PayPal did not return a secure subscription approval URL.");setBusy("");return}window.location.assign(url)}
 async function submitRequest(){if(subject.trim().length<3||details.trim().length<10)return;setBusy("request");setError("");const{data:r,error:e}=await supabase.rpc("care_public_request_submit",{p_token:token,p_category:category,p_subject:subject.trim(),p_details:details.trim(),p_name:name.trim()||null,p_email:email.trim()||null});setBusy("");if(e)setError(e.message);else if(r?.error)setError(String(r.error));else{setNotice("Your website update request has been sent to LabNarrative.");setSubject("");setDetails("");await load()}}
 async function decline(){const client=window.prompt("Please enter your name to decline LabNarrative Care:",name);if(!client||client.trim().length<2)return;setBusy("decline");const{data:r,error:e}=await supabase.rpc("care_public_decline",{p_token:token,p_name:client.trim(),p_email:email.trim()||null});setBusy("");if(e)setError(e.message);else if(r?.error)setError(String(r.error));else{setNotice("Your response has been recorded.");await load()}}
 if(loading)return <main className={styles.state}><section><div className={styles.logo}>LabNarrative</div><h1>Opening LabNarrative Care…</h1><p>Loading your website support and subscription workspace.</p></section></main>;
 if(!data)return <main className={styles.state}><section><div className={styles.logo}>LabNarrative</div><h1>Care portal unavailable.</h1><p>{error||"This private Care link is unavailable."}</p><a href="mailto:khaled@labnarrative.com">Contact LabNarrative</a></section></main>;
 const sub=data.subscription;const active=sub?.status==="active";const pending=sub?.status==="approval_pending";const closed=["declined","cancelled"].includes(data.offer.status)||["cancelled","expired"].includes(sub?.status||"");
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.header}><a className={styles.logo} href="/">LabNarrative</a><span>Client website care</span></header>
  <section className={styles.hero}><div><p className={styles.eyebrow}>{active?"Active website care":"Keep your lab website current"}</p><h1>{active?"LabNarrative Care":"Your website can keep evolving with your lab."}</h1></div><div><p>{data.prospect.pi_name} · {data.prospect.institution}</p>{siteUrl?<a className={styles.siteLink} href={siteUrl} target="_blank" rel="noreferrer">Open your live website ↗</a>:null}</div></section>
  {notice?<p className={styles.notice}>{notice}</p>:null}{error?<p className={styles.error}>{error}</p>:null}
  {active&&sub?<><section className={styles.summary}><article><span>Care status</span><strong>Active</strong><small>Recurring PayPal subscription</small></article><article><span>Your plan</span><strong>{sub.plan_name}</strong><small>{money(sub.price_amount,sub.currency)} / {sub.billing_interval}</small></article><article><span>Next billing</span><strong>{fmt(sub.next_billing_at)}</strong><small>Last payment {fmt(sub.last_payment_at)}</small></article></section>
   <section className={styles.section}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Website maintenance</p><h2>Request an update</h2><p>Send routine changes to publications, team members, opportunities, text, images or domain information directly to LabNarrative.</p></div><span className={styles.badge} data-state="active">Care active</span></div><div className={styles.requestForm}><label><span>Update type</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="publication">Publication</option><option value="team">Team member</option><option value="opportunity">Hiring / opportunity</option><option value="text">Text / content</option><option value="image">Image</option><option value="domain">Domain / contact</option><option value="other">Other</option></select></label><label><span>Your name (optional)</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className={styles.full}><span>Subject</span><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Example: Add our new Nature Cancer paper"/></label><label className={styles.full}><span>Details</span><textarea rows={6} value={details} onChange={e=>setDetails(e.target.value)} placeholder="Tell us exactly what should change and include links or citation details where relevant."/></label><label><span>Email (optional)</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><div style={{display:"flex",alignItems:"end"}}><button className={styles.primary} disabled={busy==="request"||subject.trim().length<3||details.trim().length<10} onClick={()=>void submitRequest()}>{busy==="request"?"Sending…":"Send update request"}</button></div></div>{data.requests.length>0?<div className={styles.requestList}><p className={styles.eyebrow}>Request history</p>{data.requests.map(r=><article className={styles.request} key={r.id}><div className={styles.requestMeta}><span className={styles.badge} data-state={r.status}>{label(r.status)}</span><span>{label(r.category)}</span><span>{fmt(r.submitted_at)}</span></div><h3>{r.subject}</h3><p>{r.details}</p></article>)}</div>:null}</section>
  </>:closed?<section className={styles.section}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Care status</p><h2>{sub?.status==="cancelled"?"Your Care subscription has ended.":"Care was not selected."}</h2><p>You can contact LabNarrative at any time if you would like to discuss website maintenance or restart support.</p></div><span className={styles.badge} data-state="cancelled">{label(sub?.status||data.offer.status)}</span></div><a className={styles.siteLink} href="mailto:khaled@labnarrative.com">Contact LabNarrative →</a></section>:sub?.status==="suspended"?<section className={styles.section}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Subscription attention</p><h2>Care billing needs attention.</h2><p>PayPal has suspended this subscription. Please contact LabNarrative so we can help restore coverage.</p></div><span className={styles.badge} data-state="suspended">Suspended</span></div><a className={styles.siteLink} href="mailto:khaled@labnarrative.com">Contact LabNarrative →</a></section>:<section className={styles.section}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Choose your coverage</p><h2>LabNarrative Care</h2><p>Keep the website technically healthy and make routine scientific updates as your lab changes. Subscriptions renew automatically through PayPal until cancelled.</p></div><span className={styles.badge}>{pending?"PayPal approval pending":`Offer valid until ${fmt(data.offer.valid_until)}`}</span></div><div className={styles.plans}>{data.plans.map(plan=><article className={styles.plan} key={plan.id}><span className={styles.badge}>{label(plan.billing_interval)}</span><h3>{plan.name}</h3><p>{plan.description}</p><div className={styles.price}>{money(plan.price_amount,plan.currency)}</div><div className={styles.interval}>per {plan.billing_interval}</div><ul className={styles.features}>{plan.features.map((f,i)=><li key={i}>{f}</li>)}</ul><button className={styles.primary} disabled={Boolean(busy)} onClick={()=>void subscribe(plan.id)}>{busy===plan.id?"Opening PayPal…":pending&&data.offer.selected_plan_id===plan.id?"Continue PayPal subscription":"Start Care with PayPal"}</button></article>)}</div><div className={styles.decline}><p>Care is optional. Your delivered website remains yours whether or not you subscribe.</p><button disabled={busy==="decline"} onClick={()=>void decline()}>No thanks, decline Care</button></div></section>}
  <footer className={styles.footer}><span>LabNarrative · Scientific websites for research groups</span><a href="mailto:khaled@labnarrative.com">khaled@labnarrative.com</a></footer>
 </div></main>
}
