"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { browserSupabase as supabase } from "@/lib/supabase-browser";
import styles from "./final-review-admin.module.css";

type Review={id:string;share_token:string;version:number;status:string;site_url:string;site_updated_at:string;site_revision_id?:string|null;client_name?:string|null;client_email?:string|null;change_request?:string;admin_note?:string;prepared_at?:string|null;sent_at?:string|null;first_viewed_at?:string|null;last_viewed_at?:string|null;view_count:number;changes_requested_at?:string|null;approved_at?:string|null};
type Data={prospect:{id:string;pi_name:string;institution:string;department?:string|null;email?:string|null};site?:{id:string;slug:string;status:string;domain_url?:string|null;updated_at?:string|null}|null;onboarding?:{id:string;status:string;completed_at?:string|null}|null;proposal?:{id:string;status:string;version:number;price_amount:number|string;currency:string;deposit_percent:number|string}|null;deposit?:{id:string;status:string;amount:number|string;currency:string;paid_at?:string|null}|null;balance?:{id:string;token:string;status:string;amount:number|string;currency:string;paid_at?:string|null}|null;review?:Review|null;eligible:boolean;stale:boolean};
function label(v?:string|null){return(v||"not prepared").replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase())}
function fmt(v?:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function money(v:number|string,c:string){const n=Number(v||0)||0;try{return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD",maximumFractionDigits:2}).format(n)}catch{return`${c||"USD"} ${n.toFixed(2)}`}}

export default function FinalReviewAdminPage(){
 const params=useParams<{prospectId:string}>();const prospectId=String(params?.prospectId||"");
 const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[note,setNote]=useState("");const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!prospectId)return;setLoading(true);setError("");const{data:session}=await supabase.auth.getSession();if(!session.session){setError("Administrator sign-in is required.");setLoading(false);return}const{data:res,error:e}=await supabase.rpc("sales_client_final_review_admin_get",{p_prospect_id:prospectId});if(e)setError(e.message);else{const next=res as Data;setData(next);setNote(next.review?.admin_note||"")}setLoading(false)},[prospectId]);useEffect(()=>{void load()},[load]);
 async function prepare(){setBusy(true);setError("");const{data:res,error:e}=await supabase.rpc("sales_client_final_review_admin_prepare",{p_prospect_id:prospectId,p_admin_note:note||null});setBusy(false);if(e)setError(e.message);else{const reused=Boolean((res as{reused?:boolean})?.reused);setNotice(reused?"The current review link is still valid.":"A new final-review version was prepared.");await load()}}
 async function markSent(){setBusy(true);setError("");const{error:e}=await supabase.rpc("sales_client_final_review_admin_mark_sent",{p_prospect_id:prospectId});setBusy(false);if(e)setError(e.message);else{setNotice("Final review marked as sent.");await load()}}
 async function copyReview(){if(!data?.review)return;await navigator.clipboard.writeText(`https://labnarrative.com/review/${data.review.share_token}`);setNotice("Final-review link copied.");setTimeout(()=>setNotice(""),1800)}
 async function copyPayment(){if(!data?.balance?.token)return;await navigator.clipboard.writeText(`https://labnarrative.com/pay/${data.balance.token}`);setNotice("Final-balance payment link copied.");setTimeout(()=>setNotice(""),1800)}
 if(loading)return <main className={styles.page}><div className={styles.state}><section className={styles.stateBox}>Loading final review…</section></div></main>;
 if(!data)return <main className={styles.page}><div className={styles.state}><section className={styles.stateBox}><h1>Final review unavailable</h1><p>{error||"Could not load this client."}</p><Link href={`/admin/sales/${prospectId}`}>Back to Sales workspace</Link></section></div></main>;
 const r=data.review;const siteUrl=data.site?.domain_url||(data.site?.slug?`https://${data.site.slug}.labnarrative.com`:"");const reviewUrl=r?`https://labnarrative.com/review/${r.share_token}`:"";const balanceUrl=data.balance?.token?`https://labnarrative.com/pay/${data.balance.token}`:"";const canPrepare=data.eligible&&(!r||r.status==="changes_requested"||data.stale);const canMarkSent=!!r&&!data.stale&&["ready","sent","viewed"].includes(r.status);
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.top}><div><p className={styles.eyebrow}>Client delivery · final review</p><h1>{data.prospect.pi_name}</h1><p>{data.prospect.institution}{data.prospect.department?` · ${data.prospect.department}`:""}</p></div><aside className={styles.statusCard}><span>Final review status</span><strong>{label(r?.status)}</strong></aside></header>
  <div className={styles.toolbar}>{data.site?.slug?<Link href={`/admin/sites/${data.site.slug}/edit`}>Open visual editor</Link>:null}{siteUrl?<a href={siteUrl} target="_blank" rel="noreferrer">Open website ↗</a>:null}{r?<><a href={reviewUrl} target="_blank" rel="noreferrer">Open client review ↗</a><button onClick={()=>void copyReview()}>Copy review link</button></>:null}{data.balance?.token?<><a href={balanceUrl} target="_blank" rel="noreferrer">Open final payment ↗</a><button onClick={()=>void copyPayment()}>Copy payment link</button></>:null}</div>
  {notice?<p className={styles.notice}>{notice}</p>:null}{error?<p className={styles.error}>{error}</p>:null}{data.stale&&r?.status!=="changes_requested"?<p className={styles.warning}>The website changed after this review was prepared. The client cannot approve this outdated review. Prepare a fresh review version before sharing it again.</p>:null}
  <section className={styles.meta}><article><span>Onboarding</span><strong>{label(data.onboarding?.status)}</strong></article><article><span>Review version</span><strong>{r?`v${r.version}`:"—"}</strong></article><article><span>Prepared</span><strong>{fmt(r?.prepared_at)}</strong></article><article><span>Views</span><strong>{r?.view_count||0}</strong></article><article><span>Final balance</span><strong>{data.balance?`${money(data.balance.amount,data.balance.currency)} · ${label(data.balance.status)}`:"Not created"}</strong></article></section>
  <div className={styles.grid}>
   <section className={styles.card}><div className={styles.reviewStatus}><div><p className={styles.eyebrow}>Delivery control</p><h2>{r?`Review version ${r.version}`:"Prepare client review"}</h2></div>{r?<span className={styles.badge}>{label(r.status)}</span>:null}</div>
    {!data.eligible&&!r?<p>Client final review becomes available after the deposit is paid and onboarding is marked <strong>Completed</strong>. Apply the approved onboarding changes in the visual editor first, publish that website revision, then complete onboarding.</p>:null}
    {data.eligible&&!r?<p>The website is ready to be locked into a client-review version. Preparing it creates a private link but sends nothing automatically.</p>:null}
    {r?<div className={styles.steps}><div className={styles.step}><span>01</span><div><strong>Website revision locked</strong><p>{fmt(r.site_updated_at)}{r.site_revision_id?` · revision ${r.site_revision_id.slice(0,8)}`:""}</p></div></div><div className={styles.step}><span>02</span><div><strong>Share review link</strong><p>{r.sent_at?`Marked sent ${fmt(r.sent_at)}`:"Not marked sent yet."}</p></div></div><div className={styles.step}><span>03</span><div><strong>Client decision</strong><p>{r.status==="approved"?`Approved ${fmt(r.approved_at)}`:r.status==="changes_requested"?`Changes requested ${fmt(r.changes_requested_at)}`:"Waiting for approval or requested changes."}</p></div></div></div>:null}
    {r?.status==="changes_requested"?<div className={styles.changeRequest}><strong>Client requested changes</strong><p>{r.change_request||"No detail supplied."}</p></div>:null}
    {data.balance?<div className={styles.payment}><dl><div><dt>Final balance</dt><dd>{money(data.balance.amount,data.balance.currency)}</dd></div><div><dt>Status</dt><dd>{label(data.balance.status)}</dd></div><div><dt>Paid</dt><dd>{fmt(data.balance.paid_at)}</dd></div></dl></div>:null}
    <label><p className={styles.eyebrow}>Private admin note</p><textarea className={styles.input} value={note} onChange={e=>setNote(e.target.value)} placeholder="Internal delivery note for this review version…"/></label>
    <div className={styles.toolbar}>{canPrepare?<button className={styles.primary} disabled={busy} onClick={()=>void prepare()}>{r?"Prepare revised review":"Prepare final review"}</button>:null}{canMarkSent?<button className={styles.primary} disabled={busy} onClick={()=>void markSent()}>Mark review sent</button>:null}</div>
    {r?.status==="changes_requested"&&!data.stale?<p className={styles.warning}>The client requested changes, but the live site has not changed yet. Apply and publish the requested revisions in the Site Editor before preparing the next review round.</p>:null}
   </section>
   <section className={styles.preview}>{siteUrl?<iframe src={siteUrl} title={`${data.prospect.pi_name} final website preview`}/>:null}</section>
  </div>
 </div></main>
}
