import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"https://platform.labnarrative.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
type Db=ReturnType<typeof createClient>;
type Json=Record<string,unknown>;
type Account={id:string;owner_user_id:string;account_kind:"paper"|"real";mode:"paper"|"shadow"|"live";status:string};
type ExchangeProvider="binance"|"bybit"|"okx"|"kraken"|"kucoin"|"coinbase";
type Condition={id:string;kind:string;timeframe:string;length:number;comparator:string;signal:number;aux1:number;aux2:number;aux3:number};
type TpTarget={profitPct:number;allocationPct:number};
const PROVIDERS=new Set<ExchangeProvider>(["binance","bybit","okx","kraken","kucoin","coinbase"]);
const KINDS=new Set(["RSI","Stochastic","MACD","Moving Average (MA)","Average Directional Index","Bollinger Bands %B","Money Flow Index","Commodity Channel Index","Ultimate Oscillator","Parabolic SAR","Heikin Ashi"]);
const TIMEFRAMES=new Set(["1 minute","3 minutes","5 minutes","15 minutes","30 minutes","1 hour","2 hours","4 hours","6 hours","8 hours","12 hours","1 day","3 days","1 week","1 month"]);
const COMPARATORS=new Set(["Less Than","Greater Than","Crossing Up","Crossing Down"]);
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}})}
function n(value:unknown,fallback=0){const x=Number(value);return Number.isFinite(x)?x:fallback}
function bool(value:unknown,fallback=false){return typeof value==="boolean"?value:fallback}
function obj(value:unknown):Json{return value&&typeof value==="object"&&!Array.isArray(value)?value as Json:{}}
function provider(value:unknown,fallback:ExchangeProvider="binance"):ExchangeProvider{const raw=String(value??fallback).toLowerCase() as ExchangeProvider;if(!PROVIDERS.has(raw))throw new Error("exchange_provider_invalid");return raw}
function cleanPair(value:unknown){const pair=String(value??"").trim().toUpperCase();if(/^[A-Z0-9]{1,20}\/USDT$/.test(pair))return pair;const compact=pair.replace(/[^A-Z0-9]/g,""),base=compact.endsWith("USDT")?compact.slice(0,-4):compact;return /^[A-Z0-9]{1,20}$/.test(base)?`${base}/USDT`:""}
function cleanPairs(value:unknown){return Array.isArray(value)?Array.from(new Set(value.map(cleanPair).filter(Boolean))).slice(0,1000):[] as string[]}
function defaultCondition(kind:string,index:number):Condition{const base:Condition={id:`condition-${Date.now()}-${index}`,kind,timeframe:"15 minutes",length:14,comparator:"Less Than",signal:30,aux1:0,aux2:0,aux3:0};if(kind==="Stochastic")return{...base,length:2,signal:20,aux1:14,aux2:1,aux3:3};if(kind==="MACD")return{...base,length:1,comparator:"Crossing Up",signal:0,aux1:12,aux2:26,aux3:9};if(kind==="Moving Average (MA)")return{...base,length:0,comparator:"Crossing Up",signal:0,aux1:1,aux2:9,aux3:26};if(kind==="Average Directional Index")return{...base,length:14,comparator:"Greater Than",signal:25};if(kind==="Bollinger Bands %B")return{...base,length:20,signal:0,aux1:2};if(kind==="Money Flow Index")return{...base,length:14,signal:20};if(kind==="Commodity Channel Index")return{...base,length:20,signal:-100};if(kind==="Ultimate Oscillator")return{...base,length:0,signal:30,aux1:7,aux2:14,aux3:28};if(kind==="Parabolic SAR")return{...base,length:0,comparator:"Crossing Up",signal:0,aux1:2,aux2:1};if(kind==="Heikin Ashi")return{...base,length:2,comparator:"Greater Than",signal:0};return base}
function cleanConditions(value:unknown){if(!Array.isArray(value))return[] as Condition[];return value.slice(0,12).map((raw,index)=>{const s=obj(raw),kind=KINDS.has(String(s.kind))?String(s.kind):"RSI",d=defaultCondition(kind,index);return{id:String(s.id||d.id),kind,timeframe:TIMEFRAMES.has(String(s.timeframe))?String(s.timeframe):d.timeframe,length:Math.max(0,Math.min(500,Math.round(n(s.length,d.length)))),comparator:COMPARATORS.has(String(s.comparator))?String(s.comparator):d.comparator,signal:Math.max(-1000000,Math.min(1000000,n(s.signal,d.signal))),aux1:Math.max(0,Math.min(1000,n(s.aux1,d.aux1))),aux2:Math.max(0,Math.min(1000,n(s.aux2,d.aux2))),aux3:Math.max(0,Math.min(1000,n(s.aux3,d.aux3)))}})}
function cleanTargets(value:unknown,fallback:number,strict=false):TpTarget[]{if(!Array.isArray(value)||!value.length){if(strict)throw new Error("invalid_take_profit_targets");return[{profitPct:Math.max(.000001,fallback),allocationPct:100}]}const targets=value.slice(0,8).map(raw=>{const s=obj(raw);return{profitPct:n(s.profitPct),allocationPct:n(s.allocationPct)}});if(!targets.length||targets.some(t=>!(t.profitPct>0)||!(t.allocationPct>0)||t.allocationPct>100))throw new Error("invalid_take_profit_targets");for(let i=1;i<targets.length;i++)if(targets[i].profitPct<=targets[i-1].profitPct)throw new Error("take_profit_targets_must_ascend");const total=targets.reduce((sum,t)=>sum+t.allocationPct,0);if(Math.abs(total-100)>.01)throw new Error("take_profit_allocations_must_total_100");return targets}
function strategyValues(body:Json,current?:Record<string,unknown>){const state=obj(current?.client_state),legacyTp=Math.max(.000001,n(body.takeProfit,n(current?.take_profit_pct,1.5))),rawTargets=body.takeProfitTargets===undefined?state.takeProfitTargets:body.takeProfitTargets,targets=cleanTargets(rawTargets,legacyTp,body.takeProfitTargets!==undefined),trailingPct=Math.max(0,Math.min(99.9,n(body.trailingPct,n(current?.trailing_pct,n(state.trailingPct,0)))));if(trailingPct>0&&targets.length!==1)throw new Error("trailing_take_profit_requires_single_target");const baseOrder=Math.max(0,n(body.baseOrder,n(current?.base_order))),safetyOrder=Math.max(0,n(body.safetyOrder,n(current?.safety_order)));if(!(baseOrder>0)||!(safetyOrder>0))throw new Error("invalid_order_amount");const maxSafetyOrders=Math.max(0,Math.min(50,Math.round(n(body.maxSafetyOrders,n(current?.max_safety_orders,5))))),fallbackLimit=n(current?.limit_safety_orders,maxSafetyOrders>0?1:0),limitSafetyOrders=maxSafetyOrders>0?Math.min(maxSafetyOrders,Math.max(1,Math.round(n(body.limitSafetyOrders,fallbackLimit)))):0;return{baseOrder,safetyOrder,maxSafetyOrders,limitSafetyOrders,maxActiveTrades:Math.max(1,Math.min(20,Math.round(n(body.maxActiveTrades,n(current?.max_active_trades,1))))),deviation:Math.max(.000001,n(body.deviation,n(current?.deviation,1))),stepScale:Math.max(.000001,n(body.stepScale,n(current?.step_scale,1))),volumeScale:Math.max(.000001,n(body.volumeScale,n(current?.volume_scale,1))),takeProfit:targets[0].profitPct,takeProfitTargets:targets,trailingPct,stopEnabled:body.stopEnabled===undefined?current?.stop_enabled===true:bool(body.stopEnabled),stopPct:Math.max(0,n(body.stopPct,n(current?.stop_pct,8))),stopLossTimeoutSeconds:Math.max(0,Math.min(86400,Math.round(n(body.stopLossTimeoutSeconds,n(state.stopLossTimeoutSeconds,0)))))} }
async function ownedAccount(admin:Db,userId:string,accountId:string){const{data,error}=await admin.from("trader_accounts").select("id,owner_user_id,account_kind,mode,status").eq("id",accountId).eq("owner_user_id",userId).eq("status","active").maybeSingle();if(error)throw error;if(!data)throw new Error("trader_account_not_owned");return data as Account}
async function requireRealExchange(admin:Db,account:Account,exchange:ExchangeProvider){if(account.account_kind!=="real")return;if(exchange==="binance"){const{data,error}=await admin.from("trader_binance_connections").select("status").eq("account_id",account.id).maybeSingle();if(error)throw error;if(!data||data.status!=="connected")throw new Error("exchange_connection_required");return}const{data,error}=await admin.from("trader_exchange_connections").select("status,permission_trade,permission_withdraw,capabilities").eq("account_id",account.id).eq("provider",exchange).maybeSingle();if(error)throw error;if(!data||data.status!=="connected")throw new Error("exchange_connection_required");if(data.permission_trade!==true)throw new Error("exchange_trade_permission_required");if(data.permission_withdraw===true)throw new Error("exchange_unsafe_permissions");const capabilities=obj(data.capabilities);if(account.mode==="live"&&capabilities.liveExecution!==true)throw new Error("execution_activation_pending")}
function detail(row:Record<string,unknown>){const conditions=cleanConditions(row.conditions),pairs=Array.isArray(row.pairs)?cleanPairs(row.pairs):[],state=obj(row.client_state),takeProfit=n(row.take_profit_pct);return{id:String(row.client_id),name:String(row.name),status:String(row.status),lifecycle:row.is_archived===true?"closed":"active",exchangeProvider:provider(row.exchange_provider),pair:String(row.pair),pairs,allPairs:row.all_pairs===true,baseOrder:n(row.base_order),safetyOrder:n(row.safety_order),maxSafetyOrders:n(row.max_safety_orders),limitSafetyOrders:n(row.limit_safety_orders),maxActiveTrades:n(row.max_active_trades,1),deviation:n(row.deviation),stepScale:n(row.step_scale),volumeScale:n(row.volume_scale),takeProfit,takeProfitTargets:cleanTargets(state.takeProfitTargets,takeProfit),trailingPct:Math.max(0,n(row.trailing_pct,n(state.trailingPct,0))),stopEnabled:row.stop_enabled===true,stopPct:n(row.stop_pct),stopLossTimeoutSeconds:Math.max(0,Math.round(n(state.stopLossTimeoutSeconds,0))),conditions,startCondition:conditions.length?conditions.map(x=>x.kind).join(" + "):"Immediately",executionMode:String(row.execution_mode||"paper"),createdAt:String(row.created_at),updatedAt:String(row.updated_at)}}
async function botDetail(admin:Db,account:Account,botId:string){const{data,error}=await admin.from("trader_bots").select("*").eq("account_id",account.id).eq("client_id",botId).maybeSingle();if(error)throw error;if(!data)throw new Error("bot_not_found");return{row:data as Record<string,unknown>,detail:detail(data as Record<string,unknown>)}}
async function activeTradesForBot(admin:Db,accountId:string,dbBotId:unknown){const{count,error}=await admin.from("trader_trades").select("id",{count:"exact",head:true}).eq("account_id",accountId).eq("bot_id",String(dbBotId)).eq("status","Active");if(error)throw error;return count??0}
function universeFrom(body:Json,current?:Record<string,unknown>){const allPairs=body.allPairs===undefined?current?.all_pairs===true:bool(body.allPairs),incoming=body.pairs===undefined?cleanPairs(current?.pairs):cleanPairs(body.pairs);let pairs=incoming;if(!allPairs&&!pairs.length){const fallback=cleanPair(body.pair??current?.pair);if(fallback)pairs=[fallback]}if(!allPairs&&!pairs.length)throw new Error("bot_pairs_required");return{allPairs,pairs:allPairs?[]:pairs,primaryPair:pairs[0]||cleanPair(body.pair??current?.pair)||"BTC/USDT"}}
function sameUniverse(row:Record<string,unknown>,u:{allPairs:boolean;pairs:string[]}){if((row.all_pairs===true)!==u.allPairs)return false;if(u.allPairs)return true;const a=cleanPairs(row.pairs).sort(),b=[...u.pairs].sort();return a.length===b.length&&a.every((v,i)=>v===b[i])}
async function createBot(admin:Db,account:Account,body:Json){const exchange=provider(body.exchangeProvider);await requireRealExchange(admin,account,exchange);const name=String(body.name??"").trim();if(!name)throw new Error("bot_name_required");const values=strategyValues(body),u=universeFrom(body),conditions=cleanConditions(body.conditions),clientId=`bot-${Date.now()}-${crypto.randomUUID().slice(0,8)}`,executionMode=account.account_kind==="real"?(account.mode==="live"?"live":"shadow"):"paper",clientState={id:clientId,name,exchangeProvider:exchange,pair:u.primaryPair,pairs:u.pairs,allPairs:u.allPairs,status:"Running",direction:"Long",...values,conditions,startCondition:conditions.length?conditions.map(c=>c.kind).join(" + "):"Immediately",maxHoldEnabled:false,averagingEnabled:true,orderType:"Market",createdAt:new Date().toISOString(),executionMode};const{data,error}=await admin.from("trader_bots").insert({account_id:account.id,client_id:clientId,name,status:"Running",exchange_provider:exchange,pair:u.primaryPair,pairs:u.pairs,all_pairs:u.allPairs,base_order:values.baseOrder,safety_order:values.safetyOrder,max_safety_orders:values.maxSafetyOrders,limit_safety_orders:values.limitSafetyOrders,max_active_trades:values.maxActiveTrades,deviation:values.deviation,step_scale:values.stepScale,volume_scale:values.volumeScale,take_profit_pct:values.takeProfit,stop_enabled:values.stopEnabled,stop_pct:values.stopPct,trailing_pct:values.trailingPct,max_hold_enabled:false,max_hold_hours:null,averaging_enabled:true,order_type:"Market",conditions,client_state:clientState,is_archived:false,scan_cursor:0,next_scan_at:null,execution_mode:executionMode}).select("*").single();if(error||!data)throw error??new Error("bot_create_failed");return detail(data as Record<string,unknown>)}
async function updateBot(admin:Db,account:Account,botId:string,body:Json){const existing=await botDetail(admin,account,botId),row=existing.row;if(row.is_archived===true)throw new Error("bot_closed");const exchange=provider(body.exchangeProvider,row.exchange_provider?provider(row.exchange_provider):"binance"),previous=provider(row.exchange_provider);const name=String(body.name??row.name??"").trim();if(!name)throw new Error("bot_name_required");const values=strategyValues(body,row),u=universeFrom(body,row),conditions=body.conditions===undefined?cleanConditions(row.conditions):cleanConditions(body.conditions),active=await activeTradesForBot(admin,account.id,row.id);if(active>0&&!sameUniverse(row,u))throw new Error("bot_pairs_locked_by_active_trade");if(active>0&&exchange!==previous)throw new Error("bot_exchange_locked_by_active_trade");await requireRealExchange(admin,account,exchange);const clientState={...obj(row.client_state),name,exchangeProvider:exchange,pair:u.primaryPair,pairs:u.pairs,allPairs:u.allPairs,...values,conditions,status:String(row.status),direction:"Long",startCondition:conditions.length?conditions.map(c=>c.kind).join(" + "):"Immediately",averagingEnabled:true,orderType:"Market"};const{data,error}=await admin.from("trader_bots").update({name,exchange_provider:exchange,pair:u.primaryPair,pairs:u.pairs,all_pairs:u.allPairs,base_order:values.baseOrder,safety_order:values.safetyOrder,max_safety_orders:values.maxSafetyOrders,limit_safety_orders:values.limitSafetyOrders,max_active_trades:values.maxActiveTrades,deviation:values.deviation,step_scale:values.stepScale,volume_scale:values.volumeScale,take_profit_pct:values.takeProfit,trailing_pct:values.trailingPct,stop_enabled:values.stopEnabled,stop_pct:values.stopPct,conditions,client_state:clientState,scan_cursor:0,next_scan_at:null,updated_at:new Date().toISOString()}).eq("id",String(row.id)).select("*").single();if(error||!data)throw error??new Error("bot_update_failed");return detail(data as Record<string,unknown>)}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return json({error:"server_configuration_missing"},500);const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({error:"unauthorized"},401);const{data:userData,error:userError}=await admin.auth.getUser(token),user=userData.user;if(userError||!user)return json({error:"unauthorized"},401);try{const body=await req.json().catch(()=>({})) as Json,accountId=String(body.accountId||"").trim();if(!accountId)return json({error:"account_id_required"},400);const account=await ownedAccount(admin,user.id,accountId),action=String(body.action||"bot_detail");if(action==="bot_detail"){const botId=String(body.botId||"").trim();if(!botId)return json({error:"bot_id_required"},400);const result=await botDetail(admin,account,botId);return json({ok:true,bot:result.detail})}if(action==="create_bot"){const bot=await createBot(admin,account,body);return json({ok:true,botId:bot.id,bot})}if(action==="update_bot"){const botId=String(body.botId||"").trim();if(!botId)return json({error:"bot_id_required"},400);const bot=await updateBot(admin,account,botId,body);return json({ok:true,botId:bot.id,bot})}return json({error:"unknown_action"},400)}catch(error){const message=error instanceof Error?error.message:String(error);console.error("trader-dca-control",message);const safe=new Set(["trader_account_not_owned","exchange_provider_invalid","exchange_connection_required","exchange_trade_permission_required","exchange_unsafe_permissions","execution_activation_pending","bot_name_required","invalid_order_amount","bot_pairs_required","bot_not_found","bot_closed","bot_pairs_locked_by_active_trade","bot_exchange_locked_by_active_trade","invalid_take_profit_targets","take_profit_targets_must_ascend","take_profit_allocations_must_total_100","trailing_take_profit_requires_single_target"]);return json({error:safe.has(message)?message:"trader_dca_control_failed"},message==="trader_account_not_owned"?403:400)}});
