import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const PUBLIC_BINANCE="https://data-api.binance.vision";
const LEASE_SECONDS=20;
type Db=ReturnType<typeof createClient>;
type Json=Record<string,unknown>;
type Rule={symbol:string;minQty:number;maxQty:number;stepSize:number;minNotional:number};
type Quote={bid:number;ask:number};
type Trade={id:string;account_id:string;bot_id:string;client_id:string;pair:string;status:string;average_price:number|string;quantity:number|string;invested:number|string;realized_pnl:number|string|null;client_state:Json;execution_mode:string};
type TpTarget={profitPct:number;allocationPct:number};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}})}
function n(v:unknown,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function obj(v:unknown):Json{return v&&typeof v==="object"&&!Array.isArray(v)?v as Json:{}}
function clean(e:unknown){return e instanceof Error?e.message:String(e||"unknown_error")}
function floorStep(value:number,step:number){if(!(step>0))return value;const p=Math.max(0,Math.min(12,(String(step).split(".")[1]??"").replace(/0+$/,"" ).length));return Number((Math.floor((value+1e-14)/step)*step).toFixed(p))}
async function verifySecret(db:Db,value:string){if(!value)return false;const{data,error}=await db.from("trader_worker_secrets").select("secret").eq("name","paper_worker").maybeSingle();return !error&&data?.secret===value}
let rulesCache:{at:number;value:Map<string,Rule>}|null=null;
async function rules(){if(rulesCache&&Date.now()-rulesCache.at<600000)return rulesCache.value;const response=await fetch(`${PUBLIC_BINANCE}/api/v3/exchangeInfo`,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`exchangeInfo_${response.status}`);const payload=await response.json() as{symbols:Array<Json>},map=new Map<string,Rule>();for(const symbol of payload.symbols??[]){if(symbol.status!=="TRADING"||symbol.quoteAsset!=="USDT"||symbol.isSpotTradingAllowed===false)continue;const filters=(symbol.filters??[]) as Json[],find=(type:string)=>filters.find(filter=>filter.filterType===type),lot=find("LOT_SIZE"),notional=find("NOTIONAL")??find("MIN_NOTIONAL");map.set(String(symbol.symbol),{symbol:String(symbol.symbol),minQty:n(lot?.minQty),maxQty:n(lot?.maxQty),stepSize:n(lot?.stepSize),minNotional:n(notional?.minNotional)})}rulesCache={at:Date.now(),value:map};return map}
async function quotes(){const response=await fetch(`${PUBLIC_BINANCE}/api/v3/ticker/bookTicker`,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`bookTicker_${response.status}`);const rows=await response.json() as Array<{symbol:string;bidPrice:string;askPrice:string}>,map=new Map<string,Quote>();for(const row of rows)map.set(row.symbol,{bid:n(row.bidPrice),ask:n(row.askPrice)});return map}
function targets(state:Json):TpTarget[]{if(!Array.isArray(state.takeProfitTargets))return[];return(state.takeProfitTargets as unknown[]).map(raw=>{const row=obj(raw);return{profitPct:n(row.profitPct),allocationPct:n(row.allocationPct)}}).filter(target=>target.profitPct>0&&target.allocationPct>0)}
function filledTargets(state:Json){const values=Array.isArray(state.takeProfitFilled)?state.takeProfitFilled:[];return new Set(values.map(value=>Math.round(n(value))).filter(value=>value>=0))}
async function sell(db:Db,trade:Trade,rule:Rule,bid:number,requestedQty:number,reason:"TP"|"SL",filled:number[]){const sellable=Math.min(Math.max(0,requestedQty),n(trade.quantity)),qty=floorStep(sellable,rule.stepSize);if(!(qty>0)||(rule.minQty>0&&qty<rule.minQty-1e-15))return{executed:false,reason:"quantity_below_minimum",requestedQty};if(rule.maxQty>0&&qty>rule.maxQty+1e-15)return{executed:false,reason:"quantity_above_maximum",requestedQty};if(rule.minNotional>0&&bid*qty<rule.minNotional-1e-9)return{executed:false,reason:"notional_below_minimum",requestedQty};const sequence=reason==="TP"&&filled.length?Math.max(...filled)+1:null,{data,error}=await db.rpc("trader_partial_close_trade",{p_trade_id:trade.id,p_exit_price:bid,p_exit_quantity:qty,p_reason:reason==="TP"?"Take Profit":"Stop Loss",p_order_kind:reason==="TP"?"take_profit":"stop_loss",p_sequence_no:sequence,p_fee_amount:0,p_client_state_patch:{takeProfitFilled:filled}});if(error)throw error;return{executed:true,...obj(data)}}
async function manageAccount(db:Db,accountId:string,actions:unknown[]){const[{data:rows},ruleMap,quoteMap]=await Promise.all([db.from("trader_trades").select("*").eq("account_id",accountId).eq("status","Active").eq("execution_mode","paper"),rules(),quotes()]);for(const raw of rows??[]){const trade=raw as Trade,state=obj(trade.client_state);if(state.exitStrategyV2!==true)continue;const rule=ruleMap.get(trade.pair.replace("/","")),quote=quoteMap.get(trade.pair.replace("/",""));if(!rule||!quote||!(quote.bid>0))continue;await db.from("trader_trades").update({last_price:quote.bid,updated_at:new Date().toISOString()}).eq("id",trade.id);const stopEnabled=state.stopEnabled===true,stopPct=n(state.stopPct),sl=n(trade.average_price)*(1-stopPct/100);if(stopEnabled&&stopPct>0&&quote.bid<=sl){const result=await sell(db,trade,rule,quote.bid,n(trade.quantity),"SL",[...filledTargets(state)]);actions.push({type:"paper_v2_sl",tradeId:trade.id,pair:trade.pair,...result});continue}const tps=targets(state),done=filledTargets(state),unfilled=tps.map((target,index)=>({target,index})).filter(item=>!done.has(item.index));if(!unfilled.length)continue;const reached=unfilled.filter(item=>quote.bid>=n(trade.average_price)*(1+item.target.profitPct/100));if(!reached.length)continue;const remainingAlloc=unfilled.reduce((sum,item)=>sum+item.target.allocationPct,0),dueAlloc=reached.reduce((sum,item)=>sum+item.target.allocationPct,0),final=dueAlloc>=remainingAlloc-.000001,desired=final?n(trade.quantity):n(trade.quantity)*(dueAlloc/remainingAlloc),newFilled=Array.from(new Set([...done,...reached.map(item=>item.index)])).sort((a,b)=>a-b),result=await sell(db,trade,rule,quote.bid,desired,"TP",newFilled);actions.push({type:"paper_v2_tp",tradeId:trade.id,pair:trade.pair,targets:reached.map(item=>item.index+1),...result})}}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return json({error:"server_configuration_missing"},500);const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),secret=(req.headers.get("x-trader-worker-secret")??"").trim();if(!await verifySecret(db,secret))return json({error:"unauthorized"},401);const{data:accounts,error}=await db.from("trader_accounts").select("id").eq("account_kind","paper").eq("status","active");if(error)return json({error:error.message},500);const actions:unknown[]=[],results:unknown[]=[];for(const account of accounts??[]){const lockId=crypto.randomUUID(),{data:locked,error:lockError}=await db.rpc("trader_begin_exit_command",{p_account_id:account.id,p_lock_id:lockId,p_lease_seconds:LEASE_SECONDS});if(lockError){results.push({account:account.id,ok:false,error:lockError.message});continue}if(!locked){results.push({account:account.id,ok:false,error:"exit_busy"});continue}try{await manageAccount(db,account.id,actions);results.push({account:account.id,ok:true})}catch(error){const message=clean(error);console.error("trader-paper-exit-worker",account.id,message);results.push({account:account.id,ok:false,error:message})}finally{try{await db.rpc("trader_release_exit_account",{p_account_id:account.id,p_worker_id:lockId})}catch{}}}let core:unknown=null;try{const response=await fetch(`${url}/functions/v1/trader-paper-worker`,{method:"POST",headers:{"x-trader-worker-secret":secret,"content-type":"application/json"},body:"{}",signal:AbortSignal.timeout(45000)});core=await response.json().catch(()=>({status:response.status}));if(!response.ok)console.error("trader-paper-worker",response.status,core)}catch(error){core={error:clean(error)}}return json({ok:true,accounts:results,actions,core})});
