"use client";

import styles from "./advanced-bot-analytics.module.css";

type Trade={id:string;pair:string;pnl:number;roi:number|null;capital:number;durationMinutes:number|null;openedAt:string|null;closedAt:string|null;averagePrice:number|null};
type SeriesPoint={at:string;pnl:number;cumulative:number};
type Automation={id:string;name:string;realizedRoi:number|null;winRate:number|null;maxDrawdown:number;capitalUsed?:number;maxCapital?:number|null;maxCapitalMode?:"fixed"|"dynamic";series:SeriesPoint[]};
type Detail={recentTrades?:Trade[];analyticsTrades?:Trade[];capital?:{totalUsed?:number|null}}|null;
type Props={range:string;automation:Automation;automations:Automation[];detail:Detail};

const DAYS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const W=600,H=180,L=58,R=12,T=12,B=36;

function finite(v:number|null|undefined,f=0){return v!=null&&Number.isFinite(v)?v:f}
function pct(v:number|null|undefined,d=1){if(v==null||!Number.isFinite(v))return"—";const s=v>0?"+":v<0?"−":"";return`${s}${Math.abs(v).toFixed(d)}%`}
function money(v:number|null|undefined){if(v==null||!Number.isFinite(v))return"—";const s=v>0?"+":v<0?"−":"";return`${s}$${Math.abs(v).toLocaleString("en-US",{maximumFractionDigits:0})}`}
function short(v:number){const a=Math.abs(v);if(a>=1e6)return`${(v/1e6).toFixed(1)}m`;if(a>=1e3)return`${(v/1e3).toFixed(1)}k`;if(a>=100)return v.toFixed(0);return v.toFixed(1)}
function duration(v:number){if(v<60)return`${Math.round(v)}m`;if(v<1440)return`${(v/60).toFixed(v<600?1:0)}h`;return`${(v/1440).toFixed(1)}d`}
function sx(v:number,min:number,max:number){return L+(v-min)/(max-min||1)*(W-L-R)}
function sy(v:number,min:number,max:number){return T+(max-v)/(max-min||1)*(H-T-B)}
function ticks(min:number,max:number,n=4){return Array.from({length:n},(_,i)=>min+(max-min)*i/(n-1))}
function dateLabel(ms:number,span:number){const d=new Date(ms);return span>330*86400000?d.toLocaleDateString("en-US",{month:"short",year:"2-digit"}):d.toLocaleDateString("en-US",{month:"short",day:"numeric"})}
function path(points:Array<{x:number;y:number}>){return points.length?`M${points.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(" L")}`:""}
function capitalUsed(a:Automation){return Math.max(0,finite(a.capitalUsed))}
function ddPct(a:Automation){const c=capitalUsed(a);return c>0?Math.max(0,finite(a.maxDrawdown))/c*100:0}
function rangeStart(range:string){const now=new Date();if(range==="ytd")return Date.UTC(now.getUTCFullYear(),0,1);const days=range==="7d"?7:range==="30d"?30:range==="90d"?90:0;return days?Date.now()-days*86400000:null}
function buildCapitalTimeline(trades:Trade[],range:string){const start=rangeStart(range),events=new Map<number,number>();trades.forEach(t=>{let open=t.openedAt?Date.parse(t.openedAt):NaN;const close=t.closedAt?Date.parse(t.closedAt):NaN,c=Math.max(0,finite(t.capital));if(!c||!Number.isFinite(open)||!Number.isFinite(close))return;if(start!=null){if(close<start)return;open=Math.max(open,start)}if(open>close)return;events.set(open,(events.get(open)||0)+c);events.set(close,(events.get(close)||0)-c)});let cur=0;return[...events.entries()].sort((a,b)=>a[0]-b[0]).map(([at,d])=>({at,value:cur=Math.max(0,cur+d)}))}
function rolling(trades:Trade[],windowSize=20){const sorted=[...trades].filter(t=>t.closedAt).sort((a,b)=>Date.parse(a.closedAt!)-Date.parse(b.closedAt!));if(sorted.length<5)return[];return sorted.map((_,i)=>{const rows=sorted.slice(Math.max(0,i-windowSize+1),i+1),capital=rows.reduce((s,t)=>s+Math.max(0,finite(t.capital)),0),pnl=rows.reduce((s,t)=>s+finite(t.pnl),0),wins=rows.filter(t=>finite(t.pnl)>0).length,gp=rows.reduce((s,t)=>s+Math.max(0,finite(t.pnl)),0),gl=Math.abs(rows.reduce((s,t)=>s+Math.min(0,finite(t.pnl)),0));return{roi:capital>0?pnl/capital*100:0,win:rows.length?wins/rows.length*100:0,pf:gl>0?gp/gl:gp>0?4:0}})}
function histogram(trades:Trade[],bins=12){const values=trades.map(t=>t.roi).filter((v):v is number=>v!=null&&Number.isFinite(v));if(!values.length)return[];let min=Math.min(...values),max=Math.max(...values);if(min===max){min-=.5;max+=.5}const width=(max-min)/bins,out=Array.from({length:bins},(_,i)=>({from:min+i*width,to:min+(i+1)*width,count:0}));values.forEach(v=>{const i=Math.min(bins-1,Math.max(0,Math.floor((v-min)/width)));out[i].count++});return out}
function heat(trades:Trade[]){const cells=Array.from({length:168},()=>({count:0,pnl:0,roi:0,capital:0}));trades.forEach(t=>{if(!t.closedAt)return;const d=new Date(t.closedAt),i=d.getDay()*24+d.getHours();cells[i].count++;cells[i].pnl+=finite(t.pnl);cells[i].capital+=Math.max(0,finite(t.capital))});cells.forEach(c=>c.roi=c.capital>0?c.pnl/c.capital*100:0);return cells}
function underwater(series:SeriesPoint[],den:number){let peak=0;return series.map(p=>{peak=Math.max(peak,finite(p.cumulative));return{at:Date.parse(p.at),value:den>0?-(peak-finite(p.cumulative))/den*100:0}}).filter(p=>Number.isFinite(p.at))}

function Axes({xMin,xMax,yMin,yMax,xLabel,yLabel,xFormat,yFormat}:{xMin:number;xMax:number;yMin:number;yMax:number;xLabel:string;yLabel:string;xFormat:(v:number)=>string;yFormat:(v:number)=>string}){return<>{ticks(yMin,yMax,5).map(v=><g key={`y-${v}`}><line x1={L} x2={W-R} y1={sy(v,yMin,yMax)} y2={sy(v,yMin,yMax)} className={styles.gridLine}/><text x={L-8} y={sy(v,yMin,yMax)+4} textAnchor="end" className={styles.tick}>{yFormat(v)}</text></g>)}{ticks(xMin,xMax,4).map(v=><g key={`x-${v}`}><line x1={sx(v,xMin,xMax)} x2={sx(v,xMin,xMax)} y1={T} y2={H-B} className={styles.verticalGrid}/><text x={sx(v,xMin,xMax)} y={H-B+18} textAnchor="middle" className={styles.tick}>{xFormat(v)}</text></g>)}<line x1={L} x2={W-R} y1={H-B} y2={H-B} className={styles.axis}/><line x1={L} x2={L} y1={T} y2={H-B} className={styles.axis}/><text x={(L+W-R)/2} y={H-4} textAnchor="middle" className={styles.axisTitle}>{xLabel}</text><text x="12" y={(T+H-B)/2} textAnchor="middle" transform={`rotate(-90 12 ${(T+H-B)/2})`} className={styles.axisTitle}>{yLabel}</text></>}
function MiniLine({values,label,current,suffix=""}:{values:number[];label:string;current:string;suffix?:string}){const min=Math.min(0,...values),max=Math.max(1,...values),pts=values.map((v,i)=>({x:34+(values.length===1?.5:i/(values.length-1))*548,y:8+(max-v)/(max-min||1)*54}));return<div className={styles.healthRow}><div><span>{label}</span><strong>{current}</strong></div><div className={styles.miniChart}><svg viewBox="0 0 600 78" preserveAspectRatio="none"><line x1="34" x2="582" y1="62" y2="62" className={styles.axis}/><text x="28" y="13" textAnchor="end" className={styles.tick}>{short(max)}{suffix}</text><text x="28" y="64" textAnchor="end" className={styles.tick}>{short(min)}{suffix}</text><path d={path(pts)} className={styles.drawLine}/><text x="34" y="75" className={styles.tick}>Older</text><text x="582" y="75" textAnchor="end" className={styles.tick}>Latest</text></svg></div></div>}

export default function AdvancedBotAnalytics({range,automation,automations,detail}:Props){
  const trades=(detail?.analyticsTrades?.length?detail.analyticsTrades:detail?.recentTrades)||[];
  const timeline=buildCapitalTimeline(trades,range),peakCapital=Math.max(0,...timeline.map(p=>p.value));
  const maxCapital=automation.maxCapitalMode==="fixed"?finite(automation.maxCapital):0,capitalScale=Math.max(1,maxCapital,peakCapital);
  const utilization=maxCapital>0?peakCapital/maxCapital*100:null;
  const risk=automations.map(a=>({a,x:ddPct(a),y:finite(a.realizedRoi),size:Math.max(capitalUsed(a),finite(a.maxCapital))}));
  const maxRisk=Math.max(1,...risk.map(x=>x.x)),minRoi=Math.min(0,...risk.map(x=>x.y)),maxRoi=Math.max(1,...risk.map(x=>x.y)),maxBubble=Math.max(1,...risk.map(x=>x.size));
  const heatCells=heat(trades),maxHeat=Math.max(.0001,...heatCells.map(c=>Math.abs(c.roi)));
  const roll=rolling(trades),hist=histogram(trades),histMin=hist.length?hist[0].from:0,histMax=hist.length?hist.at(-1)!.to:1,maxHist=Math.max(1,...hist.map(b=>b.count));
  const scatter=trades.filter(t=>t.durationMinutes!=null&&Number.isFinite(t.durationMinutes)&&t.roi!=null&&Number.isFinite(t.roi));
  const maxDur=Math.max(1,...scatter.map(t=>finite(t.durationMinutes))),minScatter=Math.min(0,...scatter.map(t=>finite(t.roi))),maxScatter=Math.max(1,...scatter.map(t=>finite(t.roi))),maxScatterCapital=Math.max(1,...scatter.map(t=>finite(t.capital)));
  const den=capitalUsed(automation)||finite(detail?.capital?.totalUsed),dd=underwater(automation.series,den),ddMin=Math.min(-.01,...dd.map(p=>p.value));
  const seriesTimes=automation.series.map(p=>Date.parse(p.at)).filter(Number.isFinite),seriesStart=Math.min(Date.now()-86400000,...seriesTimes),seriesEnd=Math.max(seriesStart+86400000,...seriesTimes),span=seriesEnd-seriesStart;
  const timelineStart=timeline.length?timeline[0].at:seriesStart,timelineEnd=timeline.length?timeline.at(-1)!.at:seriesEnd,timelineSpan=timelineEnd-timelineStart||86400000;

  return<section key={`${range}-${automation.id}-${trades.length}`} className={styles.suite}>
    <div className={styles.suiteHead}><div><small>ADVANCED ANALYTICS</small><h3>Risk, efficiency & behavioral edge</h3></div><span>{trades.length} closed trades sampled · {range.toUpperCase()}</span></div>
    <div className={styles.grid}>
      <article className={styles.card}><header><div><small>CAPITAL UTILIZATION</small><h4>Capital footprint</h4></div><div className={styles.metrics}><b>{money(peakCapital)}</b><span>{utilization==null?"Dynamic ceiling":`${pct(utilization)} of max`}</span></div></header>{timeline.length?<svg className={styles.chart} viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none"><Axes xMin={timelineStart} xMax={timelineEnd} yMin={0} yMax={capitalScale} xLabel="Date" yLabel="Capital (USD)" xFormat={v=>dateLabel(v,timelineSpan)} yFormat={v=>`$${short(v)}`}/><path d={path(timeline.map(p=>({x:sx(p.at,timelineStart,timelineEnd),y:sy(p.value,0,capitalScale)})))} className={styles.drawBlue}/>{maxCapital>0&&<line x1={L} x2={W-R} y1={sy(maxCapital,0,capitalScale)} y2={sy(maxCapital,0,capitalScale)} className={styles.limitLine}/>}</svg>:<div className={styles.empty}>No closed-trade capital timeline in this range.</div>}<footer><span>Peak simultaneous capital</span><b>{maxCapital>0?`Max configured ${money(maxCapital)}`:"No fixed ceiling"}</b></footer></article>

      <article className={styles.card}><header><div><small>RISK / RETURN MAP</small><h4>Automation quality</h4></div><span>Higher ROI + lower drawdown is stronger</span></header><svg className={styles.chart} viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none"><Axes xMin={0} xMax={maxRisk} yMin={minRoi} yMax={maxRoi} xLabel="Max drawdown (%)" yLabel="Realized ROI (%)" xFormat={v=>`${short(v)}%`} yFormat={v=>`${short(v)}%`}/>{risk.map(({a,x,y,size})=><circle key={a.id} cx={sx(x,0,maxRisk)} cy={sy(y,minRoi,maxRoi)} r={5+Math.sqrt(size/maxBubble)*8} className={a.id===automation.id?styles.focusBubble:styles.bubble}><title>{a.name} · ROI {pct(y)} · Max DD {pct(-x)} · capital {money(size)}</title></circle>)}</svg><footer><span>Left = lower risk · Up = higher return</span><b>Bubble size = capital</b></footer></article>

      <article className={`${styles.card} ${styles.wide}`}><header><div><small>TIME EDGE</small><h4>Day × hour performance</h4></div><span>X = hour of day · Y = weekday · color = realized ROI</span></header><div className={styles.heatWrap}><div className={styles.hourLabels}>{[0,3,6,9,12,15,18,21].map(h=><span key={h} style={{gridColumn:`${h+1}/span 3`}}>{String(h).padStart(2,"0")}:00</span>)}</div>{DAYS.map((day,d)=><div className={styles.heatRow} key={day}><b>{day}</b><div>{Array.from({length:24},(_,h)=>{const c=heatCells[d*24+h],strength=Math.min(1,Math.abs(c.roi)/maxHeat);return<i key={h} className={c.roi>0?styles.heatPos:c.roi<0?styles.heatNeg:styles.heatZero} style={{opacity:c.count?.18+.72*strength:.12}}><title>{day} {String(h).padStart(2,"0")}:00 · {c.count} trades · {pct(c.roi)} ROI · {money(c.pnl)}</title></i>})}</div></div>)}</div><footer><span>Y-axis: weekday</span><b>X-axis: local close hour</b></footer></article>

      <article className={styles.card}><header><div><small>ROLLING STRATEGY HEALTH</small><h4>Last 20 trades</h4></div><span>X = trade sequence</span></header>{roll.length?<div className={styles.health}><MiniLine values={roll.map(x=>x.roi)} label="Rolling ROI" current={pct(roll.at(-1)?.roi)} suffix="%"/><MiniLine values={roll.map(x=>x.win)} label="Win rate" current={pct(roll.at(-1)?.win)} suffix="%"/><MiniLine values={roll.map(x=>x.pf)} label="Profit factor" current={(roll.at(-1)?.pf??0).toFixed(2)}/></div>:<div className={styles.empty}>At least five closed trades are needed.</div>}</article>

      <article className={styles.card}><header><div><small>RETURN DISTRIBUTION</small><h4>Trade ROI shape</h4></div><span>{hist.reduce((s,b)=>s+b.count,0)} trades</span></header>{hist.length?<svg className={styles.chart} viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none"><Axes xMin={histMin} xMax={histMax} yMin={0} yMax={maxHist} xLabel="Trade ROI (%)" yLabel="Trade count" xFormat={v=>`${short(v)}%`} yFormat={v=>`${Math.round(v)}`}/>{hist.map((b,i)=>{const x1=sx(b.from,histMin,histMax),x2=sx(b.to,histMin,histMax),top=sy(b.count,0,maxHist);return<rect key={i} x={x1+1} y={top} width={Math.max(2,x2-x1-2)} height={H-B-top} rx="3" className={b.to<=0?styles.histNeg:b.from>=0?styles.histPos:styles.histFlat}><title>{b.from.toFixed(2)}% to {b.to.toFixed(2)}% · {b.count} trades</title></rect>})}</svg>:<div className={styles.empty}>No ROI distribution available.</div>}</article>

      <article className={styles.card}><header><div><small>CAPITAL TIME EFFICIENCY</small><h4>Holding time × ROI</h4></div><span>Dot size = capital</span></header>{scatter.length?<svg className={styles.chart} viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none"><Axes xMin={0} xMax={maxDur} yMin={minScatter} yMax={maxScatter} xLabel="Holding time" yLabel="Trade ROI (%)" xFormat={v=>duration(v)} yFormat={v=>`${short(v)}%`}/>{scatter.slice(-220).map(t=>{const xv=finite(t.durationMinutes),yv=finite(t.roi),r=2.5+Math.sqrt(finite(t.capital)/maxScatterCapital)*5;return<circle key={t.id} cx={sx(xv,0,maxDur)} cy={sy(yv,minScatter,maxScatter)} r={r} className={yv>=0?styles.scatterPos:styles.scatterNeg}><title>{t.pair} · {duration(xv)} · {pct(yv)} ROI · {money(t.capital)}</title></circle>})}</svg>:<div className={styles.empty}>No holding-time observations available.</div>}<footer><span>Right = longer capital lock</span><b>Up = better trade ROI</b></footer></article>

      <article className={`${styles.card} ${styles.wide}`}><header><div><small>UNDERWATER RISK</small><h4>Drawdown depth & recovery</h4></div><div className={styles.metrics}><b className={styles.loss}>{pct(ddMin)}</b><span>deepest realized drawdown</span></div></header>{dd.length?<svg className={styles.chart} viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none"><Axes xMin={seriesStart} xMax={seriesEnd} yMin={ddMin} yMax={0} xLabel="Date" yLabel="Drawdown (%)" xFormat={v=>dateLabel(v,span)} yFormat={v=>`${short(v)}%`}/><path d={`${path(dd.map(p=>({x:sx(p.at,seriesStart,seriesEnd),y:sy(p.value,ddMin,0)})))} L${sx(dd.at(-1)!.at,seriesStart,seriesEnd)},${sy(0,ddMin,0)} L${sx(dd[0].at,seriesStart,seriesEnd)},${sy(0,ddMin,0)} Z`} className={styles.areaRed}/><path d={path(dd.map(p=>({x:sx(p.at,seriesStart,seriesEnd),y:sy(p.value,ddMin,0)})))} className={styles.drawRed}/></svg>:<div className={styles.empty}>No realized drawdown path in this range.</div>}<footer><span>0% = previous equity peak</span><b>Deeper negative = larger drawdown</b></footer></article>
    </div>
  </section>
}
