"use client";

import { useEffect, useMemo, useState } from "react";
import { browserSupabase } from "../../lib/supabase-browser";
import styles from "./referral-dashboard.module.css";

type Program={currency:string;monthly_l1_bps:number;monthly_l2_bps:number;monthly_l3_bps:number;annual_l1_bps:number;annual_l2_bps:number;annual_l3_bps:number;customer_discount_bps:number;commission_hold_days:number;payout_minimum_cents:number};
type ReferralData={ok?:boolean;referral?:{code:string;url:string;status:string;directReferrals:number;attribution:{referral_code?:string}|null};earnings?:{pending:number;available:number;paid:number;reversed:number;cancelled:number};program?:Program;error?:string};
type CreatorSubmission={id:string;platform:string;package_key:string;content_urls:string[];notes:string|null;status:"pending"|"approved"|"rejected";base_max_months:number;performance_max_months:number;total_max_months:number;review_note:string|null;reviewed_at:string|null;created_at:string};
type PerformanceClaim={id:string;submission_id:string;content_url:string;claimed_views:number;verified_views:number;bonus_months:number;status:"pending"|"approved"|"rejected";review_note:string|null;updated_at:string};
type CreatorDashboard={submissions:CreatorSubmission[];performanceClaims:PerformanceClaim[];grants:Array<{id:string;max_months:number;status:string}>;maxAccess:{access_end?:string}|null;creatorMonthsAwarded:number};
type PackageOption={key:string;label:string;requirement:string;minimum:number};

const PACKAGES:PackageOption[]=[
 {key:"youtube_long",label:"YouTube — long-form",requirement:"1 long-form video (5+ min)",minimum:1},
 {key:"youtube_standard",label:"YouTube — standard",requirement:"2 standard videos (<5 min)",minimum:2},
 {key:"youtube_shorts",label:"YouTube Shorts",requirement:"5 approved Shorts",minimum:5},
 {key:"tiktok",label:"TikTok",requirement:"5 approved videos",minimum:5},
 {key:"instagram_reels",label:"Instagram Reels",requirement:"5 approved Reels",minimum:5},
 {key:"reddit",label:"Reddit",requirement:"2 high-quality original posts; permitted relevant reposts may be included",minimum:2},
 {key:"x_posts",label:"X / Twitter — posts",requirement:"4 substantial posts",minimum:4},
 {key:"x_threads",label:"X / Twitter — threads",requirement:"3 substantial threads",minimum:3},
 {key:"linkedin",label:"LinkedIn",requirement:"4 substantial posts",minimum:4},
 {key:"article",label:"Medium / Substack / Blog",requirement:"1 original detailed article",minimum:1},
 {key:"communities",label:"Telegram / Discord / Facebook",requirement:"5 substantial posts in relevant communities",minimum:5},
];
const percent=(bps=0)=>`${(bps/100).toFixed(bps%100===0?0:2)}%`;
const money=(cents=0,currency="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:2}).format(cents/100);
const date=(value?:string|null)=>value?new Date(value).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}):"—";

async function invokeReferral(body:Record<string,unknown>){
 const{data,error}=await browserSupabase.functions.invoke("trader-referral-control",{body});
 if(error){let message=error.message||"referral_request_failed";const context=(error as{context?:Response}).context;if(context){try{const payload=await context.clone().json() as{error?:string};if(payload.error)message=payload.error}catch{}}throw new Error(message)}
 const payload=(data??{}) as ReferralData;if(payload.error||payload.ok!==true)throw new Error(payload.error||"referral_request_failed");return payload;
}
async function rpc<T>(name:string,args:Record<string,unknown>={}){
 const{data,error}=await (browserSupabase as any).rpc(name,args);if(error)throw error;return data as T;
}

export default function ReferralDashboard(){
 const[data,setData]=useState<ReferralData|null>(null),[creator,setCreator]=useState<CreatorDashboard|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[copied,setCopied]=useState<"link"|"code"|"">(""),[claimCode,setClaimCode]=useState(""),[claimBusy,setClaimBusy]=useState(false),[claimMessage,setClaimMessage]=useState("");
 const[packageKey,setPackageKey]=useState("youtube_long"),[urlsText,setUrlsText]=useState(""),[notes,setNotes]=useState(""),[submitBusy,setSubmitBusy]=useState(false),[submitMessage,setSubmitMessage]=useState("");
 const[performanceValues,setPerformanceValues]=useState<Record<string,string>>({}),[performanceBusy,setPerformanceBusy]=useState("");
 const selectedPackage=useMemo(()=>PACKAGES.find(item=>item.key===packageKey)??PACKAGES[0],[packageKey]);
 const urls=useMemo(()=>urlsText.split(/\n+/).map(item=>item.trim()).filter(Boolean),[urlsText]);

 const load=async()=>{setLoading(true);setError("");try{const[referral,creatorData]=await Promise.all([invokeReferral({action:"dashboard"}),rpc<CreatorDashboard>("creator_rewards_dashboard")]);setData(referral);setCreator(creatorData)}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load Creator & Affiliate dashboard.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const copy=async(value:string,kind:"link"|"code")=>{await navigator.clipboard.writeText(value);setCopied(kind);window.setTimeout(()=>setCopied(""),1500)};
 const claim=async()=>{if(!claimCode.trim()||claimBusy)return;setClaimBusy(true);setClaimMessage("");try{await invokeReferral({action:"claim_code",code:claimCode.trim(),source:"code"});setClaimCode("");setClaimMessage("Referral code applied.");await load()}catch(caught){setClaimMessage(caught instanceof Error?caught.message:"Unable to apply referral code.")}finally{setClaimBusy(false)}};
 const submitPackage=async()=>{if(submitBusy)return;setSubmitMessage("");if(urls.length<selectedPackage.minimum){setSubmitMessage(`Add at least ${selectedPackage.minimum} public content URL${selectedPackage.minimum===1?"":"s"}.`);return}setSubmitBusy(true);try{await rpc("submit_creator_package",{p_package_key:packageKey,p_content_urls:urls,p_notes:notes||null});setUrlsText("");setNotes("");setSubmitMessage("Submitted for review.");setCreator(await rpc<CreatorDashboard>("creator_rewards_dashboard"))}catch(caught){setSubmitMessage(caught instanceof Error?caught.message:"Unable to submit content.")}finally{setSubmitBusy(false)}};
 const submitPerformance=async(submissionId:string,contentUrl:string)=>{const key=`${submissionId}:${contentUrl}`,views=Number(performanceValues[key]||0);if(!Number.isFinite(views)||views<=0)return;setPerformanceBusy(key);try{await rpc("submit_creator_performance_claim",{p_submission_id:submissionId,p_content_url:contentUrl,p_claimed_views:Math.round(views)});setCreator(await rpc<CreatorDashboard>("creator_rewards_dashboard"));setPerformanceValues(current=>({...current,[key]:""}))}catch(caught){setSubmitMessage(caught instanceof Error?caught.message:"Unable to submit performance claim.")}finally{setPerformanceBusy("")}};

 if(loading)return <div className={styles.loading}>Loading Creator & Affiliate dashboard…</div>;
 if(error||!data?.referral||!data.program||!data.earnings)return <div className={styles.loading}><strong>Creator & Affiliate dashboard unavailable</strong><span>{error||"Please try again."}</span><button onClick={()=>void load()}>Retry</button></div>;
 const{referral,program,earnings}=data,currency=program.currency||"USD",totalEarned=earnings.pending+earnings.available+earnings.paid;
 const submissions=creator?.submissions??[],claims=creator?.performanceClaims??[];
 return <div className={styles.page}>
  <div className={styles.heading}><div><small>CREATOR + AFFILIATE PROGRAM</small><h1>Create. Grow. Earn.</h1><p>Earn Max for approved content, more Max for reach, and cash commission from qualifying referrals.</p></div><span className={styles.status}>{referral.status}</span></div>
  <section className={styles.shareCard}><div><small>YOUR AFFILIATE LINK</small><strong>{referral.url}</strong><p>Use this link in your qualifying content so referred customers are attributed to you.</p></div><div className={styles.shareActions}><button onClick={()=>void copy(referral.url,"link")}>{copied==="link"?"Copied":"Copy link"}</button><button onClick={()=>void copy(referral.code,"code")}>{copied==="code"?"Copied":`Code · ${referral.code}`}</button></div></section>
  <div className={styles.metrics}><article><span>Cash earned</span><strong>{money(totalEarned,currency)}</strong><small>Pending + available + paid</small></article><article><span>Creator Max earned</span><strong>{creator?.creatorMonthsAwarded??0} mo</strong><small>Approved creator rewards currently active</small></article><article><span>Max access through</span><strong className={styles.metricDate}>{date(creator?.maxAccess?.access_end)}</strong><small>Creator and referral rewards extend automatically</small></article><article><span>Direct referrals</span><strong>{referral.directReferrals}</strong><small>10 customers = 1 year total Max</small></article></div>

  <section className={styles.panel} id="submit-content"><div className={styles.panelHead}><div><small>SUBMIT CREATOR CONTENT</small><h2>Complete a package → earn 1 month Max</h2></div><a className={styles.guideLink} href="/affiliate#creator-rewards">Full program rules ↗</a></div><div className={styles.submissionForm}><label><span>Content package</span><select value={packageKey} onChange={e=>setPackageKey(e.target.value)}>{PACKAGES.map(item=><option value={item.key} key={item.key}>{item.label} — {item.requirement}</option>)}</select></label><label><span>Public content URLs · one per line</span><textarea value={urlsText} onChange={e=>setUrlsText(e.target.value)} placeholder={`Paste at least ${selectedPackage.minimum} URL${selectedPackage.minimum===1?"":"s"} here`} rows={Math.max(3,selectedPackage.minimum)}/><small>{urls.length}/{selectedPackage.minimum} required · {selectedPackage.requirement}</small></label><label><span>Notes <em>optional</em></span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Anything useful for the review team" rows={2}/></label><div className={styles.submitRow}><button disabled={submitBusy||urls.length<selectedPackage.minimum} onClick={()=>void submitPackage()}>{submitBusy?"Submitting…":"Submit package for review →"}</button>{submitMessage&&<span>{submitMessage}</span>}</div></div></section>

  <section className={styles.panel}><div className={styles.panelHead}><div><small>YOUR CREATOR SUBMISSIONS</small><h2>Review status & performance bonuses</h2></div></div>{submissions.length===0?<p className={styles.empty}>No creator packages submitted yet.</p>:<div className={styles.submissionList}>{submissions.map(submission=><article className={styles.submissionCard} key={submission.id}><div className={styles.submissionTop}><div><strong>{submission.platform}</strong><span>{PACKAGES.find(p=>p.key===submission.package_key)?.requirement??submission.package_key}</span></div><b className={`${styles.reviewStatus} ${styles[`status_${submission.status}`]}`}>{submission.status}</b></div><div className={styles.urlList}>{(submission.content_urls??[]).map(url=><div key={url}><a href={url} target="_blank" rel="noreferrer">{url} ↗</a>{submission.status==="approved"&&<div className={styles.performanceClaim}><input type="number" min="0" placeholder="Current views / impressions" value={performanceValues[`${submission.id}:${url}`]??""} onChange={e=>setPerformanceValues(current=>({...current,[`${submission.id}:${url}`]:e.target.value}))}/><button disabled={performanceBusy===`${submission.id}:${url}`||!performanceValues[`${submission.id}:${url}`]} onClick={()=>void submitPerformance(submission.id,url)}>{performanceBusy===`${submission.id}:${url}`?"Sending…":"Claim performance bonus"}</button></div>}</div>)}</div><div className={styles.submissionMeta}><span>Submitted {date(submission.created_at)}</span><span>Base reward: {submission.base_max_months||0} mo Max</span>{submission.review_note&&<span>Review: {submission.review_note}</span>}</div>{claims.filter(item=>item.submission_id===submission.id).map(item=><div className={styles.claimResult} key={item.id}><span>{item.status.toUpperCase()} · {item.content_url}</span><b>{item.status==="approved"?`+${item.bonus_months} mo Max · ${item.verified_views.toLocaleString()} verified`:`Claimed ${item.claimed_views.toLocaleString()} views/impressions`}</b></div>)}</article>)}</div>}</section>

  <div className={styles.grid}><section className={styles.panel}><div className={styles.panelHead}><div><small>AFFILIATE COMMISSION</small><h2>Cash earnings</h2></div></div><div className={styles.planHead}><span>Level</span><span>Monthly</span><span>Annual prepaid</span></div>{[1,2,3].map(level=><div className={styles.planRow} key={level}><div><b>Level {level}</b><small>{level===1?"Your direct referral":level===2?"Referral of your referral":"Third network level"}</small></div><strong>{percent(program[`monthly_l${level}_bps` as keyof Program] as number)}</strong><strong>{percent(program[`annual_l${level}_bps` as keyof Program] as number)}</strong></div>)}</section><section className={styles.panel}><div className={styles.panelHead}><div><small>EARNINGS</small><h2>Commission balance</h2></div></div><div className={styles.balanceRows}><div><span>Pending</span><b>{money(earnings.pending,currency)}</b></div><div><span>Available for payout</span><b>{money(earnings.available,currency)}</b></div><div><span>Paid</span><b>{money(earnings.paid,currency)}</b></div><div className={styles.muted}><span>Reversed</span><b>{money(earnings.reversed,currency)}</b></div></div><p className={styles.note}>Creator Max rewards and cash commissions stack. Every qualifying paying customer also contributes to your referral Max milestones.</p></section></div>
  <section className={styles.panel}><div className={styles.panelHead}><div><small>YOUR REFERRER</small><h2>{referral.attribution?"You joined through a referral":"No referral attached"}</h2></div></div>{referral.attribution?<p className={styles.referrer}>Referral code <b>{referral.attribution.referral_code}</b> is attached to your user identity.</p>:<div className={styles.claim}><div><p>If someone introduced you to LabNarrative, you can attach their code before your first paid subscription.</p><small>Once attributed, the referral relationship is permanent.</small></div><input value={claimCode} onChange={e=>setClaimCode(e.target.value.toUpperCase())} placeholder="Referral code"/><button disabled={claimBusy||!claimCode.trim()} onClick={()=>void claim()}>{claimBusy?"Applying…":"Apply code"}</button></div>}{claimMessage&&<p className={styles.claimMessage}>{claimMessage}</p>}</section>
 </div>;
}
