"use client";

import { useEffect, useState } from "react";
import { browserSupabase } from "../../lib/supabase-browser";
import styles from "./referral-dashboard.module.css";

type Program={currency:string;monthly_l1_bps:number;monthly_l2_bps:number;monthly_l3_bps:number;annual_l1_bps:number;annual_l2_bps:number;annual_l3_bps:number;customer_discount_bps:number;commission_hold_days:number;payout_minimum_cents:number};
type ReferralData={ok?:boolean;referral?:{code:string;url:string;status:string;directReferrals:number;attribution:{referral_code?:string}|null};earnings?:{pending:number;available:number;paid:number;reversed:number;cancelled:number};program?:Program;error?:string};
const percent=(bps=0)=>`${(bps/100).toFixed(bps%100===0?0:2)}%`;
const money=(cents=0,currency="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:2}).format(cents/100);
const creatorRewards=[["YouTube","1 long-form video (5+ min) or 2 standard videos (<5 min)"],["YouTube Shorts","5 approved Shorts"],["TikTok","5 approved videos"],["Instagram Reels","5 approved Reels"],["Reddit","2 high-quality original posts + permitted relevant reposts"],["X / Twitter","4 substantial posts or 3 threads"],["LinkedIn","4 substantial posts"],["Medium / Substack / Blog","1 original detailed article"],["Telegram / Discord / Facebook","5 substantial community posts"]];

async function invokeReferral(body:Record<string,unknown>){const{data,error}=await browserSupabase.functions.invoke("trader-referral-control",{body});if(error){let message=error.message||"referral_request_failed";const context=(error as{context?:Response}).context;if(context){try{const payload=await context.clone().json() as{error?:string};if(payload.error)message=payload.error}catch{}}throw new Error(message)}const payload=(data??{}) as ReferralData;if(payload.error||payload.ok!==true)throw new Error(payload.error||"referral_request_failed");return payload}

export default function ReferralDashboard(){
 const[data,setData]=useState<ReferralData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[copied,setCopied]=useState<"link"|"code"|"">(""),[claimCode,setClaimCode]=useState(""),[claimBusy,setClaimBusy]=useState(false),[claimMessage,setClaimMessage]=useState("");
 const load=async()=>{setLoading(true);setError("");try{setData(await invokeReferral({action:"dashboard"}))}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load referrals.")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const copy=async(value:string,kind:"link"|"code")=>{await navigator.clipboard.writeText(value);setCopied(kind);window.setTimeout(()=>setCopied(""),1500)};
 const claim=async()=>{if(!claimCode.trim()||claimBusy)return;setClaimBusy(true);setClaimMessage("");try{await invokeReferral({action:"claim_code",code:claimCode.trim(),source:"code"});setClaimCode("");setClaimMessage("Referral code applied.");await load()}catch(caught){setClaimMessage(caught instanceof Error?caught.message:"Unable to apply referral code.")}finally{setClaimBusy(false)}};
 if(loading)return <div className={styles.loading}>Loading Creator & Affiliate dashboard…</div>;if(error||!data?.referral||!data.program||!data.earnings)return <div className={styles.loading}><strong>Creator & Affiliate dashboard unavailable</strong><span>{error||"Please try again."}</span><button onClick={()=>void load()}>Retry</button></div>;
 const{referral,program,earnings}=data,currency=program.currency||"USD",totalEarned=earnings.pending+earnings.available+earnings.paid;
 return <div className={styles.page}>
  <div className={styles.heading}><div><small>CREATOR + AFFILIATE PROGRAM</small><h1>Create. Grow. Earn.</h1><p>Earn Max for approved content, more Max for reach, and cash commission from qualifying referrals.</p></div><span className={styles.status}>{referral.status}</span></div>
  <section className={styles.shareCard}><div><small>YOUR AFFILIATE LINK</small><strong>{referral.url}</strong><p>Share this link in qualifying creator content to track referred customers and commissions.</p></div><div className={styles.shareActions}><button onClick={()=>void copy(referral.url,"link")}>{copied==="link"?"Copied":"Copy link"}</button><button onClick={()=>void copy(referral.code,"code")}>{copied==="code"?"Copied":`Code · ${referral.code}`}</button></div></section>
  <div className={styles.metrics}><article><span>Total earned</span><strong>{money(totalEarned,currency)}</strong><small>Pending + available + paid</small></article><article><span>Available</span><strong>{money(earnings.available,currency)}</strong><small>{money(program.payout_minimum_cents,currency)} payout threshold</small></article><article><span>Pending</span><strong>{money(earnings.pending,currency)}</strong><small>{program.commission_hold_days}-day safety hold</small></article><article><span>Direct referrals</span><strong>{referral.directReferrals}</strong><small>Paying-customer rewards stack with creator rewards</small></article></div>
  <section className={styles.panel}><div className={styles.panelHead}><div><small>CREATOR REWARDS</small><h2>Complete a content package → 1 month Max</h2></div><a className={styles.guideLink} href="https://labnarrative.com/affiliate#creator-rewards" target="_blank" rel="noreferrer">Full program rules ↗</a></div><div className={styles.creatorGrid}>{creatorRewards.map(([platform,requirement])=><div key={platform}><strong>{platform}</strong><span>{requirement}</span><b>1 month Max</b></div>)}</div><div className={styles.performanceNote}><strong>Performance bonuses</strong><span>YouTube long-form: up to +12 months at 100K views · Shorts/Reels/TikTok: up to +12 months at 1M views · Reddit/X/LinkedIn: up to +6 months at 100K verified views/impressions. Highest milestone only; milestones do not stack.</span><a href="mailto:hello@labnarrative.com?subject=LabNarrative%20Creator%20Submission">Submit content for review →</a></div></section>
  <div className={styles.grid}><section className={styles.panel}><div className={styles.panelHead}><div><small>AFFILIATE COMMISSION</small><h2>Cash earnings</h2></div></div><div className={styles.planHead}><span>Level</span><span>Monthly</span><span>Annual prepaid</span></div>{[1,2,3].map(level=><div className={styles.planRow} key={level}><div><b>Level {level}</b><small>{level===1?"Your direct referral":level===2?"Referral of your referral":"Third network level"}</small></div><strong>{percent(program[`monthly_l${level}_bps` as keyof Program] as number)}</strong><strong>{percent(program[`annual_l${level}_bps` as keyof Program] as number)}</strong></div>)}</section><section className={styles.panel}><div className={styles.panelHead}><div><small>EARNINGS</small><h2>Commission balance</h2></div></div><div className={styles.balanceRows}><div><span>Pending</span><b>{money(earnings.pending,currency)}</b></div><div><span>Available for payout</span><b>{money(earnings.available,currency)}</b></div><div><span>Paid</span><b>{money(earnings.paid,currency)}</b></div><div className={styles.muted}><span>Reversed</span><b>{money(earnings.reversed,currency)}</b></div></div><p className={styles.note}>Creator Max rewards are reviewed separately from cash commission balances. Paid, botted, manipulated, spam, or non-compliant content does not qualify.</p></section></div>
  <section className={styles.panel}><div className={styles.panelHead}><div><small>YOUR REFERRER</small><h2>{referral.attribution?"You joined through a referral":"No referral attached"}</h2></div></div>{referral.attribution?<p className={styles.referrer}>Referral code <b>{referral.attribution.referral_code}</b> is attached to your user identity.</p>:<div className={styles.claim}><div><p>If someone introduced you to LabNarrative, you can attach their code before your first paid subscription.</p><small>Once attributed, the referral relationship is permanent.</small></div><input value={claimCode} onChange={e=>setClaimCode(e.target.value.toUpperCase())} placeholder="Referral code"/><button disabled={claimBusy||!claimCode.trim()} onClick={()=>void claim()}>{claimBusy?"Applying…":"Apply code"}</button></div>}{claimMessage&&<p className={styles.claimMessage}>{claimMessage}</p>}</section>
 </div>;
}
