"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { browserSupabase } from "../../lib/supabase-browser";
import cfg from "./dca-bot-configurator.module.css";
import tv from "./dca-tradingview-link.module.css";

type Mode="create"|"view"|"edit";
type SizingMode="tradingview"|"fixed_quote";
type Strategy={id:string;name:string;orderAmount:number|null;sizingMode:SizingMode;status:string;lifecycle:string;executionMode:string;automationType:string;tradingViewEnabled:boolean;maxSingleOrder:number|null};
type LinkState={ok?:boolean;enabled:boolean;token:string;webhookUrl:string;accountKind?:"paper"|"real";maxSingleOrder?:number|null;error?:string};
type Props={mode:Mode;accountId:string;accountKind:"paper"|"real";botId:string|null;onCancel:()=>void;onSaved:(botId:string,action:"create"|"update")=>void;onError:(message:string)=>void};

async function invokeStrategy(body:Record<string,unknown>){const{data,error}=await browserSupabase.functions.invoke("trader-tradingview-strategy-control",{body});if(error){let message=error.message||"tradingview_strategy_control_failed";const context=(error as{context?:Response}).context;if(context){try{const payload=await context.clone().json() as{error?:string};if(payload.error)message=payload.error}catch{}}throw new Error(message)}const result=(data??{}) as{ok?:boolean;strategy?:Strategy;botId?:string;error?:string};if(result.error||result.ok!==true)throw new Error(result.error||"tradingview_strategy_control_failed");return result}
async function invokeLink(body:Record<string,unknown>){const{data,error}=await browserSupabase.functions.invoke("trader-tradingview-control",{body});if(error){let message=error.message||"tradingview_link_failed";const context=(error as{context?:Response}).context;if(context){try{const payload=await context.clone().json() as{error?:string};if(payload.error)message=payload.error}catch{}}throw new Error(message)}const result=(data??{}) as LinkState;if(result.error||result.ok!==true)throw new Error(result.error||"tradingview_link_failed");return result}

function sizingLabel(mode:SizingMode,amount:number|null){return mode==="tradingview"?"From TradingView":`${Number(amount||0).toLocaleString()} USDT per BUY`}

function TradingViewStrategyLink({accountId,botId,sizingMode,orderAmount}:{accountId:string;botId:string;sizingMode:SizingMode;orderAmount:number|null}){
  const[link,setLink]=useState<LinkState|null>(null),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[notice,setNotice]=useState("");
  useEffect(()=>{let alive=true;setLoading(true);void invokeLink({action:"get_link",accountId,botId}).then(r=>{if(alive)setLink(r)}).catch(e=>{if(alive)setNotice(e instanceof Error?e.message:"Unable to load TradingView connection.")}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[accountId,botId]);
  const webhook=link?.webhookUrl||"https://platform.labnarrative.com/api/trader/tradingview";
  const message=useMemo(()=>link?.token?JSON.stringify({token:link.token,action:"{{strategy.order.action}}",pair:"{{ticker}}",contracts:"{{strategy.order.contracts}}",order_price:"{{strategy.order.price}}",signal_id:"{{strategy.order.id}}-{{timenow}}"}):"",[link?.token]);
  const setEnabled=async(enabled:boolean)=>{if(working)return;setWorking(true);setNotice("");try{setLink(await invokeLink({action:"set_enabled",accountId,botId,enabled}))}catch(e){setNotice(e instanceof Error?e.message:"Unable to update TradingView connection.")}finally{setWorking(false)}};
  const reset=async()=>{if(working)return;setWorking(true);setNotice("");try{setLink(await invokeLink({action:"regenerate",accountId,botId}));setNotice("TradingView key reset. Update the alert message in TradingView.")}catch(e){setNotice(e instanceof Error?e.message:"Unable to reset TradingView key.")}finally{setWorking(false)}};
  const copy=async(value:string,label:string)=>{try{await navigator.clipboard.writeText(value);setNotice(`${label} copied.`)}catch{setNotice("Clipboard access was blocked by the browser.")}};
  return <section className={`${cfg.card} ${tv.panel}`}>
    <div className={tv.header}><div><h3 className={tv.title}>TradingView Connection</h3><p className={tv.helper}>One order-fill alert carries the symbol, BUY/SELL action and strategy size.</p></div>{link?.enabled?<div className={tv.headerActions}><button type="button" className={tv.textButton} onClick={()=>void reset()} disabled={working}>Reset key</button><button type="button" className={tv.textButton} onClick={()=>void setEnabled(false)} disabled={working}>Disable</button></div>:<button type="button" className={tv.textButton} onClick={()=>void setEnabled(true)} disabled={working||loading}>{working?"Connecting…":"Connect TradingView"}</button>}</div>
    {notice&&<div className={tv.notice}>{notice}</div>}
    {loading?<div className={tv.loading}>Loading TradingView connection…</div>:link?.enabled&&message?<>
      <div className={tv.webhook}><span className={tv.webhookLabel}>Webhook</span><p className={tv.webhookUrl}>{webhook}</p><button type="button" className={tv.textButton} onClick={()=>void copy(webhook,"Webhook URL")}>Copy URL</button></div>
      <div className={tv.actions} style={{gridTemplateColumns:"1.15fr .85fr .85fr"}}>
        <div className={tv.action}><span className={tv.eyebrow}>Strategy alert</span><b className={tv.actionTitle}>Order fills</b><p className={tv.explanation}>Create one alert on the TradingView strategy, choose order fills, then paste this message.</p><div className={tv.copyLine}><button type="button" className={tv.textButton} onClick={()=>void copy(message,"Strategy message")}>Copy message</button></div></div>
        <div className={tv.action}><span className={tv.eyebrow}>BUY</span><b className={tv.actionTitle}>{sizingMode==="tradingview"?"TradingView strategy size":`${Number(orderAmount||0).toLocaleString()} USDT entry`}</b><p className={tv.explanation}>The symbol comes from TradingView. Extra BUY signals are ignored while this strategy already has an open position.</p></div>
        <div className={tv.action}><span className={tv.eyebrow}>SELL</span><b className={tv.actionTitle}>Full market exit</b><p className={tv.explanation}>Closes the active position for that symbol at market. SELL never opens a short position.</p></div>
      </div>
      <p className={tv.footer}>Only tradeable Binance Spot USDT symbols are accepted. {sizingMode==="tradingview"?"TradingView order contracts determine the requested base-asset quantity.":"LabNarrative uses the fixed USDT amount for BUY."} Account execution and live-capital limits remain enforced{link?.maxSingleOrder?` (current per-order limit: ${Number(link.maxSingleOrder).toLocaleString()} USDT).`:"."}</p>
    </>:<div className={tv.off}>Connect only when the TradingView strategy is ready to send order-fill alerts.</div>}
  </section>
}

export default function TradingViewStrategyConfigurator({mode,accountId,accountKind,botId,onCancel,onSaved,onError}:Props){
  const[name,setName]=useState("My TradingView Strategy"),[sizingMode,setSizingMode]=useState<SizingMode>("tradingview"),[orderAmount,setOrderAmount]=useState(10),[strategy,setStrategy]=useState<Strategy|null>(null),[loading,setLoading]=useState(mode!=="create"),[saving,setSaving]=useState(false),[localError,setLocalError]=useState("");
  useEffect(()=>{let alive=true;if(mode==="create"||!botId){setLoading(false);return()=>{alive=false}}setLoading(true);void invokeStrategy({action:"strategy_detail",accountId,botId}).then(r=>{if(!alive||!r.strategy)return;setStrategy(r.strategy);setName(r.strategy.name);setSizingMode(r.strategy.sizingMode||"tradingview");if(r.strategy.orderAmount&&r.strategy.orderAmount>0)setOrderAmount(r.strategy.orderAmount)}).catch(e=>{if(alive)setLocalError(e instanceof Error?e.message:"Unable to load TradingView Strategy.")}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[accountId,botId,mode]);
  const save=async(event:FormEvent)=>{event.preventDefault();if(saving)return;if(!name.trim())return setLocalError("Add a strategy name.");if(sizingMode==="fixed_quote"&&!(orderAmount>0))return setLocalError("Fixed BUY amount must be greater than zero.");setSaving(true);setLocalError("");try{const action=mode==="create"?"create_strategy":"update_strategy",result=await invokeStrategy({action,accountId,botId:mode==="create"?undefined:botId,name:name.trim(),sizingMode,orderAmount});onSaved(String(result.botId||botId||""),mode==="create"?"create":"update")}catch(e){const raw=e instanceof Error?e.message:"Unable to save TradingView Strategy.",friendly=raw.includes("order_amount_exceeds_execution_limit")?"Fixed BUY amount exceeds this account’s per-order execution limit.":raw.includes("invalid_sizing_mode")?"Choose a valid position-sizing mode.":raw;setLocalError(friendly);onError(friendly)}finally{setSaving(false)}};
  if(loading)return <div className={cfg.loading}>Loading TradingView Strategy…</div>;
  if(mode==="view")return <div className={cfg.body}>{localError&&<div className={cfg.error}>{localError}</div>}<div className={cfg.summaryGrid}><div><span>Market source</span><b>TradingView alert</b></div><div><span>Markets</span><b>Binance Spot · USDT</b></div><div><span>Position sizing</span><b>{sizingLabel(sizingMode,strategy?.orderAmount??orderAmount)}</b></div><div><span>Position model</span><b>One long position</b></div><div><span>Execution</span><b>{strategy?.executionMode||accountKind}</b></div></div>{botId&&<TradingViewStrategyLink accountId={accountId} botId={botId} sizingMode={sizingMode} orderAmount={strategy?.orderAmount??orderAmount}/>}</div>;
  return <form className={cfg.body} onSubmit={save}>{localError&&<div className={cfg.error}>{localError}</div>}<section className={cfg.card}><div className={cfg.cardHead}><div><h3>Strategy</h3><p>TradingView decides what to trade and when; LabNarrative handles account-scoped execution.</p></div></div><div className={cfg.grid}><label><span>Strategy name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Position sizing</span><select value={sizingMode} onChange={e=>setSizingMode(e.target.value as SizingMode)}><option value="tradingview">Use TradingView strategy size</option><option value="fixed_quote">Use fixed USDT amount</option></select><small>{sizingMode==="tradingview"?"Uses strategy.order.contracts as the requested base-asset quantity.":"Every BUY uses the fixed quote amount below."}</small></label>{sizingMode==="fixed_quote"&&<label><span>Fixed BUY amount</span><div className={cfg.unit}><input type="number" min="0.01" step="0.01" value={orderAmount} onChange={e=>setOrderAmount(Number(e.target.value))}/><b>USDT</b></div></label>}</div></section><section className={cfg.card}><div className={cfg.cardHead}><div><h3>Execution</h3><p>The alert supplies the market dynamically. No coin list is configured in LabNarrative.</p></div></div><div className={cfg.rows}><div><span>Account</span><b>{accountKind==="real"?"Real Account · Binance Spot":"Paper Account · Binance Spot prices"}</b></div><div><span>Symbol</span><b>From TradingView · USDT Spot only</b></div><div><span>BUY</span><b>{sizingMode==="tradingview"?"Open TradingView strategy quantity":`Open ${orderAmount>0?orderAmount.toLocaleString():0} USDT long position`}</b></div><div><span>BUY while open</span><b>Ignore</b></div><div><span>SELL</span><b>Close full position at market</b></div><div><span>Short selling</span><b>Not enabled</b></div></div></section>{mode==="edit"&&botId&&<TradingViewStrategyLink accountId={accountId} botId={botId} sizingMode={sizingMode} orderAmount={orderAmount}/>}<div className={cfg.footer}><span>One TradingView order-fill alert controls symbol, BUY and SELL. Binance Spot validation and account execution limits apply at runtime.</span><div><button type="button" onClick={onCancel}>Cancel</button><button className={cfg.save} disabled={saving}>{saving?"Saving…":mode==="create"?"Create Strategy":"Save Changes"}</button></div></div></form>
}
