"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { browserSupabase } from "../../lib/supabase-browser";
import cfg from "./dca-bot-configurator.module.css";
import tv from "./dca-tradingview-link.module.css";

type Mode="create"|"view"|"edit";
type PairInfo={pair:string;symbol:string;baseAsset:string};
type Strategy={id:string;name:string;pair:string;orderAmount:number;status:string;lifecycle:string;executionMode:string;automationType:string;tradingViewEnabled:boolean;maxSingleOrder:number|null};
type LinkState={ok?:boolean;enabled:boolean;token:string;webhookUrl:string;accountKind?:"paper"|"real";maxSingleOrder?:number|null;error?:string};
type Props={mode:Mode;accountId:string;accountKind:"paper"|"real";botId:string|null;onCancel:()=>void;onSaved:(botId:string,action:"create"|"update")=>void;onError:(message:string)=>void};
const FALLBACK=["BTC/USDT","ETH/USDT","BNB/USDT","SOL/USDT","XRP/USDT","ADA/USDT","DOGE/USDT","TRX/USDT","AVAX/USDT","LINK/USDT"];

async function invokeStrategy(body:Record<string,unknown>){const{data,error}=await browserSupabase.functions.invoke("trader-tradingview-strategy-control",{body});if(error){let message=error.message||"tradingview_strategy_control_failed";const context=(error as{context?:Response}).context;if(context){try{const payload=await context.clone().json() as{error?:string};if(payload.error)message=payload.error}catch{}}throw new Error(message)}const result=(data??{}) as{ok?:boolean;strategy?:Strategy;botId?:string;error?:string};if(result.error||result.ok!==true)throw new Error(result.error||"tradingview_strategy_control_failed");return result}
async function invokeLink(body:Record<string,unknown>){const{data,error}=await browserSupabase.functions.invoke("trader-tradingview-control",{body});if(error){let message=error.message||"tradingview_link_failed";const context=(error as{context?:Response}).context;if(context){try{const payload=await context.clone().json() as{error?:string};if(payload.error)message=payload.error}catch{}}throw new Error(message)}const result=(data??{}) as LinkState;if(result.error||result.ok!==true)throw new Error(result.error||"tradingview_link_failed");return result}

function TradingViewStrategyLink({accountId,botId,orderAmount}:{accountId:string;botId:string;orderAmount:number}){
  const[link,setLink]=useState<LinkState|null>(null),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[notice,setNotice]=useState("");
  useEffect(()=>{let alive=true;setLoading(true);void invokeLink({action:"get_link",accountId,botId}).then(r=>{if(alive)setLink(r)}).catch(e=>{if(alive)setNotice(e instanceof Error?e.message:"Unable to load TradingView connection.")}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[accountId,botId]);
  const webhook=link?.webhookUrl||"https://platform.labnarrative.com/api/trader/tradingview";
  const message=useMemo(()=>link?.token?JSON.stringify({token:link.token,action:"{{strategy.order.action}}",pair:"{{ticker}}",signal_id:"{{strategy.order.id}}-{{timenow}}"}):"",[link?.token]);
  const setEnabled=async(enabled:boolean)=>{if(working)return;setWorking(true);setNotice("");try{setLink(await invokeLink({action:"set_enabled",accountId,botId,enabled}))}catch(e){setNotice(e instanceof Error?e.message:"Unable to update TradingView connection.")}finally{setWorking(false)}};
  const reset=async()=>{if(working)return;setWorking(true);setNotice("");try{setLink(await invokeLink({action:"regenerate",accountId,botId}));setNotice("TradingView key reset. Update the alert message in TradingView.")}catch(e){setNotice(e instanceof Error?e.message:"Unable to reset TradingView key.")}finally{setWorking(false)}};
  const copy=async(value:string,label:string)=>{try{await navigator.clipboard.writeText(value);setNotice(`${label} copied.`)}catch{setNotice("Clipboard access was blocked by the browser.")}};
  return <section className={`${cfg.card} ${tv.panel}`}>
    <div className={tv.header}><div><h3 className={tv.title}>TradingView Connection</h3><p className={tv.helper}>One strategy alert handles both entry and exit.</p></div>{link?.enabled?<div className={tv.headerActions}><button type="button" className={tv.textButton} onClick={()=>void reset()} disabled={working}>Reset key</button><button type="button" className={tv.textButton} onClick={()=>void setEnabled(false)} disabled={working}>Disable</button></div>:<button type="button" className={tv.textButton} onClick={()=>void setEnabled(true)} disabled={working||loading}>{working?"Connecting…":"Connect TradingView"}</button>}</div>
    {notice&&<div className={tv.notice}>{notice}</div>}
    {loading?<div className={tv.loading}>Loading TradingView connection…</div>:link?.enabled&&message?<>
      <div className={tv.webhook}><span className={tv.webhookLabel}>Webhook</span><p className={tv.webhookUrl}>{webhook}</p><button type="button" className={tv.textButton} onClick={()=>void copy(webhook,"Webhook URL")}>Copy URL</button></div>
      <div className={tv.actions} style={{gridTemplateColumns:"1.15fr .85fr .85fr"}}>
        <div className={tv.action}><span className={tv.eyebrow}>Strategy alert</span><b className={tv.actionTitle}>Order fills</b><p className={tv.explanation}>Create one alert on the TradingView strategy, choose order fills, then paste this message.</p><div className={tv.copyLine}><button type="button" className={tv.textButton} onClick={()=>void copy(message,"Strategy message")}>Copy message</button></div></div>
        <div className={tv.action}><span className={tv.eyebrow}>BUY</span><b className={tv.actionTitle}>{orderAmount.toLocaleString()} USDT entry</b><p className={tv.explanation}>Opens the long Spot position. Extra BUY signals are ignored while it is already open.</p></div>
        <div className={tv.action}><span className={tv.eyebrow}>SELL</span><b className={tv.actionTitle}>Full market exit</b><p className={tv.explanation}>Closes the active position at market. SELL never opens a short position.</p></div>
      </div>
      <p className={tv.footer}>TradingView decides when to trade; LabNarrative executes the configured amount through this account. Account execution and live-capital limits remain enforced.</p>
    </>:<div className={tv.off}>Connect only when the TradingView strategy is ready to send order-fill alerts.</div>}
  </section>
}

export default function TradingViewStrategyConfigurator({mode,accountId,accountKind,botId,onCancel,onSaved,onError}:Props){
  const[name,setName]=useState("My TradingView Strategy"),[pair,setPair]=useState("BTC/USDT"),[orderAmount,setOrderAmount]=useState(10),[pairs,setPairs]=useState<PairInfo[]>(FALLBACK.map(p=>({pair:p,symbol:p.replace("/",""),baseAsset:p.split("/")[0]}))),[query,setQuery]=useState(""),[strategy,setStrategy]=useState<Strategy|null>(null),[loading,setLoading]=useState(mode!=="create"),[saving,setSaving]=useState(false),[localError,setLocalError]=useState("");
  useEffect(()=>{let alive=true;void fetch("/api/trader/binance-pairs",{cache:"no-store"}).then(r=>r.json()).then((d:{pairs?:PairInfo[]})=>{if(alive&&d.pairs?.length)setPairs(d.pairs)}).catch(()=>{});return()=>{alive=false}},[]);
  useEffect(()=>{let alive=true;if(mode==="create"||!botId){setLoading(false);return()=>{alive=false}}setLoading(true);void invokeStrategy({action:"strategy_detail",accountId,botId}).then(r=>{if(!alive||!r.strategy)return;setStrategy(r.strategy);setName(r.strategy.name);setPair(r.strategy.pair);setOrderAmount(r.strategy.orderAmount)}).catch(e=>{if(alive)setLocalError(e instanceof Error?e.message:"Unable to load TradingView Strategy.")}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[accountId,botId,mode]);
  const visible=useMemo(()=>{const q=query.trim().toUpperCase();return pairs.filter(p=>!q||p.pair.includes(q)||p.baseAsset.includes(q)).slice(0,80)},[pairs,query]);
  const save=async(event:FormEvent)=>{event.preventDefault();if(saving)return;if(!name.trim())return setLocalError("Add a strategy name.");if(!(orderAmount>0))return setLocalError("Order amount must be greater than zero.");setSaving(true);setLocalError("");try{const action=mode==="create"?"create_strategy":"update_strategy",result=await invokeStrategy({action,accountId,botId:mode==="create"?undefined:botId,name:name.trim(),pair,orderAmount});onSaved(String(result.botId||botId||""),mode==="create"?"create":"update")}catch(e){const raw=e instanceof Error?e.message:"Unable to save TradingView Strategy.",friendly=raw.includes("order_amount_exceeds_execution_limit")?"Order amount exceeds this account’s per-order execution limit.":raw.includes("strategy_pair_locked_by_active_position")?"Market cannot be changed while this strategy has an open position.":raw;setLocalError(friendly);onError(friendly)}finally{setSaving(false)}};
  if(loading)return <div className={cfg.loading}>Loading TradingView Strategy…</div>;
  if(mode==="view")return <div className={cfg.body}>{localError&&<div className={cfg.error}>{localError}</div>}<div className={cfg.summaryGrid}><div><span>Market</span><b>{pair}</b></div><div><span>BUY amount</span><b>{orderAmount.toLocaleString()} USDT</b></div><div><span>Position model</span><b>One long position</b></div><div><span>Execution</span><b>{strategy?.executionMode||accountKind}</b></div></div>{botId&&<TradingViewStrategyLink accountId={accountId} botId={botId} orderAmount={orderAmount}/>}</div>;
  return <form className={cfg.body} onSubmit={save}>{localError&&<div className={cfg.error}>{localError}</div>}<section className={cfg.card}><div className={cfg.cardHead}><div><h3>Strategy</h3><p>TradingView decides when to enter and exit; LabNarrative handles execution.</p></div></div><div className={cfg.grid}><label><span>Strategy name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Order amount</span><div className={cfg.unit}><input type="number" min="0.01" step="0.01" value={orderAmount} onChange={e=>setOrderAmount(Number(e.target.value))}/><b>USDT</b></div><small>Used when a TradingView BUY order-fill alert arrives.</small></label></div></section><section className={cfg.card}><div className={cfg.cardHead}><div><h3>Market</h3><p>V1 executes one Binance Spot USDT market per strategy.</p></div></div><div className={cfg.pairTools}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search market"/><span>{pair}</span></div><div className={cfg.pairList}>{visible.map(item=><label key={item.pair} className={item.pair===pair?cfg.pairSelected:""}><input type="radio" name="tv-strategy-pair" checked={item.pair===pair} onChange={()=>setPair(item.pair)}/><span><b>{item.baseAsset}</b><small>{item.pair}</small></span></label>)}</div></section><section className={cfg.card}><div className={cfg.cardHead}><div><h3>Execution model</h3><p>Simple and deterministic for the first strategy version.</p></div></div><div className={cfg.rows}><div><span>BUY</span><b>Open {orderAmount>0?orderAmount.toLocaleString():0} USDT long position</b></div><div><span>BUY while open</span><b>Ignore</b></div><div><span>SELL</span><b>Close full position at market</b></div><div><span>Short selling</span><b>Not enabled</b></div></div></section>{mode==="edit"&&botId&&<TradingViewStrategyLink accountId={accountId} botId={botId} orderAmount={orderAmount}/>}<div className={cfg.footer}><span>One TradingView order-fill alert controls both BUY and SELL after the strategy is saved and connected.</span><div><button type="button" onClick={onCancel}>Cancel</button><button className={cfg.save} disabled={saving}>{saving?"Saving…":mode==="create"?"Create Strategy":"Save Changes"}</button></div></div></form>
}
