"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { browserSupabase } from "@/lib/supabase-browser";
import styles from "./assets.module.css";

type PortfolioKind="real"|"paper";
type Account={id:string;provider:string|null;account_name:string|null;connection_mode:string|null};
type Holding={id:string;account_id:string;asset_name:string;symbol:string|null;asset_type:string|null;quantity:number|string|null;unit_price:number|string|null;market_value:number|string|null;cost_basis:number|string|null;currency:string|null};
const LABELS:Record<string,string>={saudi_stock:"الأسهم السعودية",global_stock:"الأسهم العالمية",reit:"الريت",fund:"الصناديق",sukuk:"الصكوك",murabaha:"المرابحات",cash:"النقد",crypto:"الأصول الرقمية",real_estate:"العقار",private_asset:"الاستثمارات الخاصة",other:"أخرى"};
const COLORS:Record<string,string>={saudi_stock:"#38bdf8",global_stock:"#6366f1",reit:"#f59e0b",fund:"#8b5cf6",sukuk:"#14b8a6",murabaha:"#06b6d4",cash:"#94a3b8",crypto:"#ec4899",real_estate:"#fb923c",private_asset:"#a78bfa",other:"#64748b"};
const numeric=(v:number|string|null|undefined)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
const fmt=(v:number,d=2)=>new Intl.NumberFormat("ar-SA-u-nu-arab",{maximumFractionDigits:d}).format(v);
const sar=(v:number)=>`${fmt(v)} ر.س`; const pct=(v:number)=>`${v>0?"+":""}${fmt(v,1)}٪`;

export default function AssetsClientV2(){
 const [kind,setKind]=useState<PortfolioKind>("real"),[manage,setManage]=useState(false),[accounts,setAccounts]=useState<Account[]>([]),[holdings,setHoldings]=useState<Holding[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [search,setSearch]=useState(""),[typeFilter,setTypeFilter]=useState("all"),[accountFilter,setAccountFilter]=useState("all"),[performanceFilter,setPerformanceFilter]=useState("all");
 const [editing,setEditing]=useState<Holding|null>(null),[saving,setSaving]=useState(false),[editError,setEditError]=useState("");
 const [name,setName]=useState(""),[symbol,setSymbol]=useState(""),[quantity,setQuantity]=useState(""),[unitPrice,setUnitPrice]=useState(""),[marketValue,setMarketValue]=useState(""),[costBasis,setCostBasis]=useState("");

 async function load(mode:PortfolioKind){const {data:userData,error:userError}=await browserSupabase.auth.getUser();if(userError||!userData.user){window.location.replace(`/wealth/login?next=${encodeURIComponent(window.location.pathname+window.location.search)}`);return}if(mode==="paper"){const {error:e}=await browserSupabase.rpc("ensure_wealth_paper_portfolio");if(e)throw e}const uid=userData.user.id;const [a,h]=await Promise.all([browserSupabase.from("wealth_accounts").select("id,provider,account_name,connection_mode").eq("user_id",uid).eq("portfolio_kind",mode).order("created_at"),browserSupabase.from("wealth_holdings").select("id,account_id,asset_name,symbol,asset_type,quantity,unit_price,market_value,cost_basis,currency").eq("user_id",uid).eq("portfolio_kind",mode).order("market_value",{ascending:false})]);if(a.error)throw a.error;if(h.error)throw h.error;setAccounts((a.data??[]) as Account[]);setHoldings((h.data??[]) as Holding[])}
 useEffect(()=>{let alive=true;const q=new URLSearchParams(window.location.search);const mode:PortfolioKind=q.get("portfolio")==="paper"?"paper":"real";setKind(mode);setManage(q.get("manage")==="1");(async()=>{try{await load(mode)}catch(e){if(alive)setError(e instanceof Error?e.message:"تعذر تحميل الأصول.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 const accountMap=useMemo(()=>new Map(accounts.map(a=>[a.id,a])),[accounts]);
 const metrics=useMemo(()=>{const total=holdings.reduce((s,h)=>s+numeric(h.market_value),0);const known=holdings.filter(h=>h.cost_basis!==null);const cost=known.reduce((s,h)=>s+numeric(h.cost_basis),0);const knownMarket=known.reduce((s,h)=>s+numeric(h.market_value),0);const pnl=knownMarket-cost;return{total,cost,pnl,pnlPct:cost>0?pnl/cost*100:0,winners:known.filter(h=>numeric(h.market_value)>numeric(h.cost_basis)).length,losers:known.filter(h=>numeric(h.market_value)<numeric(h.cost_basis)).length}},[holdings]);
 const types=useMemo(()=>Array.from(new Set(holdings.map(h=>h.asset_type||"other"))),[holdings]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return holdings.filter(h=>{const p=h.cost_basis===null?null:numeric(h.market_value)-numeric(h.cost_basis);return(!q||h.asset_name.toLowerCase().includes(q)||(h.symbol||"").toLowerCase().includes(q))&&(typeFilter==="all"||(h.asset_type||"other")===typeFilter)&&(accountFilter==="all"||h.account_id===accountFilter)&&(performanceFilter==="all"||(performanceFilter==="profit"&&p!==null&&p>0)||(performanceFilter==="loss"&&p!==null&&p<0)||(performanceFilter==="no_cost"&&p===null))})},[holdings,search,typeFilter,accountFilter,performanceFilter]);
 function beginEdit(h:Holding){setEditing(h);setName(h.asset_name);setSymbol(h.symbol||"");setQuantity(h.quantity===null?"":String(h.quantity));setUnitPrice(h.unit_price===null?"":String(h.unit_price));setMarketValue(String(h.market_value??""));setCostBasis(h.cost_basis===null?"":String(h.cost_basis));setEditError("");window.scrollTo({top:0,behavior:"smooth"})}
 async function saveEdit(){if(!editing||!name.trim())return;setSaving(true);setEditError("");try{const q=quantity.trim()===""?null:Number(quantity);const p=unitPrice.trim()===""?null:Number(unitPrice);let mv=marketValue.trim()===""?0:Number(marketValue);if(q!==null&&p!==null&&Number.isFinite(q)&&Number.isFinite(p))mv=q*p;const cb=costBasis.trim()===""?null:Number(costBasis);const {error:e}=await browserSupabase.from("wealth_holdings").update({asset_name:name.trim(),symbol:symbol.trim()||null,quantity:q,unit_price:p,market_value:mv,cost_basis:cb,as_of_date:new Date().toISOString().slice(0,10)}).eq("id",editing.id);if(e)throw e;await load(kind);setEditing(null)}catch(e){setEditError(e instanceof Error?e.message:"تعذر حفظ التعديل.")}finally{setSaving(false)}}
 const paper=kind==="paper";const suffix=paper?"?portfolio=paper":"";
 if(loading)return <main className={styles.page}><div className={styles.state}>جاري تحميل الأصول…</div></main>;if(error)return <main className={styles.page}><div className={styles.state}><strong>تعذر تحميل الأصول.</strong><span>{error}</span></div></main>;
 return <main className={styles.page} dir="rtl"><aside className={styles.sidebar}><div><div className={styles.brand}>ثروة</div><div className={styles.brandSub}>{paper?"محفظة تجريبية":"إدارة الثروة"}</div></div><nav className={styles.nav}><Link className={styles.navItem} href={`/wealth${suffix}`}>نظرة عامة</Link><Link className={`${styles.navItem} ${styles.active}`} href={`/wealth/assets${suffix}`}>الأصول</Link><span className={styles.navItem}>الدخل</span><span className={styles.navItem}>التحليلات</span><span className={styles.navItem}>الالتزام الشرعي</span><span className={styles.navItem}>الحسابات</span></nav><div className={styles.profile}><span className={styles.avatar}>{paper?"ت":"ث"}</span><span><strong>{paper?"حساب تجريبي":"حساب المستثمر"}</strong><small>{paper?"بيانات اختبار":"بياناتك الحقيقية"}</small></span></div></aside><section className={styles.workspace}><header className={styles.topbar}><div><p>{paper?"بيئة الاختبار":"المحفظة الحقيقية"}</p><h1>{manage?"إدارة الأصول":"الأصول"}</h1></div><div className={styles.actions}><Link href={paper?"/wealth/assets":"/wealth/assets?portfolio=paper"} className={styles.ghost}>{paper?"محفظتي الحقيقية":"محفظة تجريبية"}</Link>{manage?<Link href={`/wealth/assets${suffix}`} className={styles.primary}>تم</Link>:<Link href={paper?"/wealth/assets?portfolio=paper&manage=1":"/wealth/assets?manage=1"} className={styles.primary}>إدارة الأصول</Link>}</div></header><div className={styles.content}>
 {manage&&<section className={styles.panel} style={{marginBottom:18}}><div className={styles.panelHead}><div><h2>{editing?`تعديل: ${editing.asset_name}`:"إدارة المحفظة"}</h2><p>{paper?"عدّل بيانات المحفظة التجريبية بأمان.":"يمكنك تعديل أصولك الحالية أو إضافة أصل جديد."}</p></div>{!paper&&<Link className={styles.primary} href="/wealth/connect">إضافة أصل</Link>}</div>{editing&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="اسم الأصل" style={inputStyle}/><input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="الرمز" style={inputStyle}/><input value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="الكمية" style={inputStyle}/><input value={unitPrice} onChange={e=>setUnitPrice(e.target.value)} placeholder="سعر الوحدة" style={inputStyle}/><input value={marketValue} onChange={e=>setMarketValue(e.target.value)} placeholder="القيمة الحالية" style={inputStyle}/><input value={costBasis} onChange={e=>setCostBasis(e.target.value)} placeholder="إجمالي التكلفة" style={inputStyle}/><div style={{display:"flex",gap:8,alignItems:"center"}}><button onClick={()=>void saveEdit()} disabled={saving} style={primaryStyle}>{saving?"جارٍ الحفظ…":"حفظ"}</button><button onClick={()=>setEditing(null)} style={ghostStyle}>إلغاء</button></div>{editError&&<div style={{color:"#ef4444",fontSize:11}}>{editError}</div>}</div>}</section>}
 <section className={styles.metricGrid}><article><small>القيمة الإجمالية</small><strong>{sar(metrics.total)}</strong><span>{holdings.length} أصل</span></article><article><small>الربح / الخسارة</small><strong className={metrics.pnl>=0?styles.profit:styles.loss}>{sar(metrics.pnl)}</strong><span className={metrics.pnl>=0?styles.profit:styles.loss}>{pct(metrics.pnlPct)}</span></article><article><small>مراكز رابحة</small><strong className={styles.profit}>{metrics.winners}</strong><span>حسب التكلفة المسجلة</span></article><article><small>مراكز خاسرة</small><strong className={styles.loss}>{metrics.losers}</strong><span>حسب التكلفة المسجلة</span></article></section>
 <section className={styles.tablePanel}><div className={styles.tableHeader}><div><h2>كل الأصول</h2><p>{paper?"محفظة متنوعة لسعودي: محلي + عالمي + كريبتو + نقد + عقار":"أصولك المسجلة حاليًا"}</p></div><div className={styles.filters}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالاسم أو الرمز"/><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="all">كل الأنواع</option>{types.map(t=><option key={t} value={t}>{LABELS[t]??t}</option>)}</select><select value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="all">كل الحسابات</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.provider||a.account_name}</option>)}</select><select value={performanceFilter} onChange={e=>setPerformanceFilter(e.target.value)}><option value="all">كل الأداء</option><option value="profit">رابح</option><option value="loss">خاسر</option><option value="no_cost">بدون تكلفة</option></select></div></div><div className={styles.tableWrap}><div className={`${styles.row} ${styles.headRow}`}><span>الأصل</span><span>الحساب</span><span>الكمية</span><span>سعر الوحدة</span><span>التكلفة</span><span>القيمة</span><span>الربح/الخسارة</span><span>{manage?"إدارة":"عرض"}</span></div>{filtered.map(h=>{const mv=numeric(h.market_value),cb=h.cost_basis===null?null:numeric(h.cost_basis),p=cb===null?null:mv-cb,pp=p!==null&&cb>0?p/cb*100:null;return <div className={styles.row} key={h.id}><span className={styles.assetCell}><i style={{background:COLORS[h.asset_type||"other"]??COLORS.other}}/><b>{h.asset_name}</b><small>{h.symbol||LABELS[h.asset_type||"other"]||"أصل"}</small></span><span><b>{accountMap.get(h.account_id)?.provider||"حساب"}</b><small>{accountMap.get(h.account_id)?.account_name||""}</small></span><span>{h.quantity===null?"—":fmt(numeric(h.quantity),4)}</span><span>{h.unit_price===null?"—":sar(numeric(h.unit_price))}</span><span>{cb===null?"—":sar(cb)}</span><span><b>{sar(mv)}</b></span><span className={p===null?styles.neutral:p>=0?styles.profit:styles.loss}><b>{p===null?"—":`${p>0?"+":""}${sar(p)}`}</b><small>{pp===null?"":pct(pp)}</small></span><span>{manage?<button onClick={()=>beginEdit(h)} style={ghostStyle}>تعديل</button>:<Link href={`/wealth/assets/${h.id}${paper?"?portfolio=paper":""}`} style={{color:"#fafafa",textDecoration:"none"}}>فتح ←</Link>}</span></div>})}</div></section>
 </div></section></main>;
}

const inputStyle:React.CSSProperties={background:"#242424",border:"1px solid #3a3a3a",color:"#fafafa",borderRadius:12,padding:"11px 12px",fontFamily:"Tahoma",outline:"none"};
const primaryStyle:React.CSSProperties={background:"#fafafa",color:"#1f1f1f",border:0,borderRadius:999,padding:"10px 16px",fontFamily:"Tahoma",fontWeight:700,cursor:"pointer"};
const ghostStyle:React.CSSProperties={background:"transparent",color:"#bbb",border:"1px solid #444",borderRadius:999,padding:"8px 12px",fontFamily:"Tahoma",cursor:"pointer"};
