"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./shared-bot.module.css";

type Bot={name:string;status:string;market:string;pairs:string[];allPairs:boolean;baseOrder:number;baseOrderType:string;safetyOrder:number;maxSafetyOrders:number;limitSafetyOrders:number;maxActiveTrades:number;deviation:number;stepScale:number;volumeScale:number;takeProfit:number;takeProfitLevels:Array<{targetPct?:number;closePct?:number}>;takeProfitTrailingEnabled:boolean;takeProfitTrailingDeviation:number;stopEnabled:boolean;stopPct:number;stopLossTrailingEnabled:boolean;stopLossTimeoutEnabled:boolean;stopLossTimeoutSeconds:number;conditions:Array<Record<string,unknown>>};
type Trade={pair:string;status:string;invested_quote:number|string|null;realized_pnl:number|string|null;close_reason:string|null;opened_at:string|null;closed_at:string|null;average_price:number|string|null;averaging_filled:number|string|null};
type Payload={ok:boolean;share:{slug:string;sharedAt:string;views:number;clones:number};bot:Bot;trades:Trade[];message?:string};
type Range="7d"|"30d"|"90d"|"all";type Tab="overview"|"configuration"|"trades";
const COLORS=["#55d99a","#df7b84","#e8b862","#7ea7ff","#b98cff"];
function n(v:unknown,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function money(v:number|null|undefined,d=2){if(v==null||!Number.isFinite(v))return"—";const s=v>0?"+":v<0?"−":"";return`${s}$${Math.abs(v).toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d})}`}
function pct(v:number|null|undefined,d=2,signed=true){if(v==null||!Number.isFinite(v))return"—";const s=signed?(v>0?"+":v<0?"−":""):"";return`${s}${Math.abs(v).toFixed(d)}%`}
function when(v:string|null|undefined){return v?new Date(v).toLocaleString([], {month:"short",day:"numeric",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—"}
function reason(v:string|null){const x=String(v||"").toLowerCase().replaceAll("_"," ");if(x.includes("take profit")||x==="tp")return"Take Profit";if(x.includes("stop"))return"Stop Loss";if(x.includes("manual"))return"Manual";return String(v||"Other")}
function rangeStart(r:Range){const d=r==="7d"?7:r==="30d"?30:r==="90d"?90:0;return d?Date.now()-d*86400000:0}
function gradient(parts:Array<{value:number;color:string}>){const total=parts.reduce((s,x)=>s+Math.max(0,x.value),0);if(!total)return"conic-gradient(#30353b 0 360deg)";let c=0;return`conic-gradient(${parts.map(x=>{const a=c/total*360;c+=Math.max(0,x.value);return`${x.color} ${a}deg ${c/total*360}deg`}).join(",")})`}
function ceiling(b:Bot){let x=Math.max(0,n(b.baseOrder)),so=Math.max(0,n(b.safetyOrder)),scale=Math.max(.000001,n(b.volumeScale,1));for(let i=0;i<Math.max(0,Math.round(n(b.maxSafetyOrders)));i++)x+=so*Math.pow(scale,i);return x*Math.max(1,Math.round(n(b.maxActiveTrades,1)))}
function chart(values:Array<{value:number}>){const W=920,H=250,PX=18,PY=20;if(!values.length)return{line:"",area:"",zero:H/2};let min=Math.min(0,...values.map(x=>x.value)),max=Math.max(0,...values.map(x=>x.value));if(Math.abs(max-min)<1e-9){min-=1;max+=1}const xx=(i:number)=>PX+(values.length===1?.5:i/(values.length-1))*(W-PX*2),yy=(v:number)=>PY+(max-v)/(max-min)*(H-PY*2),pts=values.map((v,i)=>`${xx(i)},${yy(v.value)}`),line=`M${pts.join(" L")}`,zero=yy(0);return{line,area:`${line} L${xx(values.length-1)},${zero} L${xx(0)},${zero} Z`,zero}}

export default function PublicBotAnalyticsProxy({slug}:{slug:string}){
 const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[range,setRange]=useState<Range>("30d"),[tab,setTab]=useState<Tab>("overview"),[copied,setCopied]=useState(false);
 useEffect(()=>{let alive=true;async function load(countView:boolean){try{const r=await fetch(`/api/shared-bot/${encodeURIComponent(slug)}?countView=${countView?"true":"false"}`,{cache:"no-store"}),body=await r.json() as Payload;if(!alive)return;if(!r.ok||!body.ok){setError(body.message||"This shared bot link is unavailable.");return}setData(body);setError("")}catch{if(alive)setError("Could not load this shared bot right now.")}}void load(true);const t=window.setInterval(()=>void load(false),30000);return()=>{alive=false;window.clearInterval(t)}},[slug]);
 const stats=useMemo(()=>{if(!data)return null;const since=rangeStart(range),closed=data.trades.filter(t=>t.status==="closed"&&t.closed_at&&(range==="all"||Date.parse(t.closed_at)>=since)).sort((a,b)=>Date.parse(a.closed_at||"")-Date.parse(b.closed_at||"")),active=data.trades.filter(t=>t.status==="active");let pnl=0,w=0,l=0,be=0,gp=0,gl=0,cum=0,peak=0,dd=0;const series:Array<{value:number}>=[];for(const t of closed){const p=n(t.realized_pnl);pnl+=p;if(p>0){w++;gp+=p}else if(p<0){l++;gl+=Math.abs(p)}else be++;cum+=p;peak=Math.max(peak,cum);dd=Math.max(dd,peak-cum);series.push({value:cum})}const cap=ceiling(data.bot),count=closed.length;return{closed,active,pnl,w,l,be,count,dd,series,cap,roi:cap>0?pnl/cap*100:null,win:count?w/count*100:null,pf:gl>0?gp/gl:gp>0?Infinity:null,exp:count?pnl/count:null}},[data,range]);
 if(error)return<main className={styles.page}><section className={styles.error}><h1>Shared bot unavailable</h1><p>{error}</p><a className={styles.primary} href="https://app.labnarrative.com">Open LabNarrative Trading</a></section></main>;
 if(!data||!stats)return<main className={styles.page}><section className={styles.loading}>Loading live Paper analytics…</section></main>;
 const c=chart(stats.series),publicUrl=`https://labnarrative.com/bot/${encodeURIComponent(slug)}`,cloneUrl=`https://app.labnarrative.com/clone/${encodeURIComponent(slug)}`,pnlClass=stats.pnl>0?styles.positive:stats.pnl<0?styles.negative:styles.neutral,recent=[...data.trades].reverse().slice(0,40);
 return<main className={styles.page}><div className={styles.top}><a className={styles.brand} href="/"><img src="/labnarrative-mark.svg" alt=""/><strong>LabNarrative</strong></a><span className={styles.topNote}>Shared Paper bot analytics · read only</span></div><section className={styles.workspace}>
 <header className={styles.header}><div className={styles.identity}><span className={styles.eyebrow}>LIVE PAPER RESULTS</span><h1>{data.bot.name}</h1><div className={styles.meta}><span>DCA</span><span>{data.bot.market}</span><span>Paper simulation</span><b className={styles.status}>{data.bot.status.toUpperCase()}</b></div></div><div className={styles.actions}><div className={styles.ranges}>{(["7d","30d","90d","all"] as Range[]).map(x=><button key={x} onClick={()=>setRange(x)} className={range===x?styles.rangeActive:""}>{x==="all"?"ALL":x.toUpperCase()}</button>)}</div><button className={styles.ghost} onClick={async()=>{await navigator.clipboard.writeText(publicUrl);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?"Copied ✓":"Share"}</button><a className={styles.primary} href={cloneUrl}>Clone Bot</a></div></header>
 <div className={styles.scroll}><nav className={styles.tabs}>{(["overview","configuration","trades"] as Tab[]).map(x=><button key={x} className={`${styles.tab} ${tab===x?styles.tabActive:""}`} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav><div className={styles.notice}><strong>Forward Paper simulation using virtual funds.</strong><span>Live analytics refresh every 30 seconds · Shared {when(data.share.sharedAt)}</span></div>
 {tab==="overview"?<><section className={styles.kpis}><article><span>Realized PnL</span><strong className={pnlClass}>{money(stats.pnl)}</strong><small>{stats.count} closed</small></article><article><span>ROI</span><strong>{pct(stats.roi)}</strong><small>on max capital</small></article><article><span>Trades</span><strong>{stats.count}</strong><small>{stats.active.length} active</small></article><article><span>Win rate</span><strong>{stats.win==null?"—":pct(stats.win,1,false)}</strong><small>{stats.w}W · {stats.l}L</small></article><article><span>Profit factor</span><strong>{stats.pf===Infinity?"∞":stats.pf==null?"—":stats.pf.toFixed(2)}</strong><small>gross profit ÷ loss</small></article><article><span>Max drawdown</span><strong className={styles.negative}>{money(-stats.dd)}</strong><small>realized curve</small></article><article><span>Expectancy</span><strong>{money(stats.exp)}</strong><small>per closed trade</small></article><article><span>Max capital</span><strong>{money(stats.cap)}</strong><small>configured ceiling</small></article></section>
 <div className={styles.grid}><article className={styles.card}><div className={styles.sectionHead}><div><small>PERFORMANCE EXPLORER</small><h2>Cumulative realized PnL</h2></div><span>{stats.series.length} observations</span></div><div className={styles.chartMeta}><strong className={pnlClass}>{money(stats.pnl)}</strong><span>{range.toUpperCase()}</span></div><div className={styles.chart}>{stats.series.length?<svg viewBox="0 0 920 250" preserveAspectRatio="none"><defs><linearGradient id="p" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#55d99a" stopOpacity=".24"/><stop offset="100%" stopColor="#55d99a" stopOpacity="0"/></linearGradient></defs><line x1="18" x2="902" y1={c.zero} y2={c.zero} className={styles.zeroLine}/><path d={c.area} className={styles.area}/><path d={c.line} className={styles.line}/></svg>:<div className={styles.loading}>No closed trades in this period yet.</div>}</div></article><div className={styles.analyticsSide}><article className={styles.donutCard}><div className={styles.sectionHead}><div><small>OUTCOME MIX</small><h2>Winning behavior</h2></div></div><div className={styles.donutWrap}><div className={styles.donut} style={{background:gradient([{value:stats.w,color:COLORS[0]},{value:stats.l,color:COLORS[1]},{value:stats.be,color:"#777"}])}}><div className={styles.donutCenter}><strong>{stats.count}</strong><small>closed</small></div></div><div className={styles.legend}><div className={styles.legendRow}><i style={{background:COLORS[0]}}/><span>Wins</span><b>{stats.w}</b></div><div className={styles.legendRow}><i style={{background:COLORS[1]}}/><span>Losses</span><b>{stats.l}</b></div></div></div></article></div></div><section className={styles.cloneBand}><div><strong>Like this configuration?</strong><p>Clone the exact setup into your own LabNarrative Paper workspace. The clone starts paused with fresh history.</p></div><a className={styles.primary} href={cloneUrl}>Clone & review →</a></section></>:null}
 {tab==="configuration"?<><div className={styles.sectionHead} style={{marginTop:12}}><div><small>PUBLIC CONFIGURATION</small><h2>Exact DCA setup</h2></div><span>Read only</span></div><section className={styles.config}>{[["Pairs",data.bot.allPairs?"All USDT Spot":data.bot.pairs.join(", ")],["Base order",`${money(data.bot.baseOrder)} · ${data.bot.baseOrderType}`],["DCA order",money(data.bot.safetyOrder)],["Max DCA orders",String(data.bot.maxSafetyOrders)],["Active DCA orders",String(data.bot.limitSafetyOrders)],["Max active trades",String(data.bot.maxActiveTrades)],["Initial deviation",pct(data.bot.deviation,2,false)],["Step scale",String(data.bot.stepScale)],["Volume scale",String(data.bot.volumeScale)],["Take profit",pct(data.bot.takeProfit,2,false)],["Trailing TP",data.bot.takeProfitTrailingEnabled?`On · ${pct(data.bot.takeProfitTrailingDeviation,2,false)}`:"Off"],["Stop loss",data.bot.stopEnabled?pct(data.bot.stopPct,2,false):"Off"]].map(([a,b])=><article className={styles.configItem} key={a}><span>{a}</span><strong>{b}</strong></article>)}</section><div className={styles.sectionHead} style={{marginTop:14}}><div><small>CONDITIONS</small><h2>Entry / exit logic</h2></div><span>{data.bot.conditions.length} configured</span></div><div className={styles.conditions}>{data.bot.conditions.length?data.bot.conditions.map((x,i)=><div className={styles.condition} key={i}><strong>{String(x.purpose||"entry").toUpperCase()} · {String(x.kind||"Condition")}</strong><span>{String(x.timeframe||"—")}</span><span>{String(x.comparator||"")} {x.signal!=null?String(x.signal):""}</span></div>):<div className={styles.configItem}><span>Logic</span><strong>No indicator conditions configured</strong></div>}</div></>:null}
 {tab==="trades"?<><div className={styles.sectionHead} style={{marginTop:12}}><div><small>TRADE HISTORY</small><h2>Recent Paper trades</h2></div><span>Newest first</span></div><div className={styles.tableWrap}><div className={styles.tradeTable}><div className={styles.tradeHead}><span>Pair</span><span>Status</span><span>Capital</span><span>PnL</span><span>Avg entry</span><span>DCA</span><span>Closed</span><span>Reason</span></div>{recent.map((t,i)=><div className={styles.tradeRow} key={i}><strong>{t.pair}</strong><span>{t.status}</span><span>{money(n(t.invested_quote))}</span><span>{t.status==="closed"?money(n(t.realized_pnl)):"—"}</span><span>{n(t.average_price).toLocaleString("en-US",{maximumFractionDigits:6})}</span><span>{Math.round(n(t.averaging_filled))}</span><span>{when(t.closed_at)}</span><span>{t.status==="closed"?reason(t.close_reason):"Open"}</span></div>)}</div></div></>:null}
 </div></section><footer className={styles.footer}><span>Paper simulation uses virtual funds. These results do not represent live-money execution and are not investment advice.</span><span>{data.share.views} views · {data.share.clones} clones</span></footer></main>
}
