"use client";

import { useEffect, useMemo, useState } from "react";
import { browserSupabase } from "@/lib/supabase-browser";
import styles from "./shared-bot.module.css";

type PublicBot = {
  name: string; status: string; lifecycle: string; strategyType: string; market: string; pairs: string[]; allPairs: boolean;
  baseOrder: number; baseOrderType: string; safetyOrder: number; maxSafetyOrders: number; limitSafetyOrders: number; maxActiveTrades: number;
  deviation: number; stepScale: number; volumeScale: number; takeProfit: number; takeProfitLevels: Array<{targetPct?:number;closePct?:number}>;
  takeProfitTrailingEnabled: boolean; takeProfitTrailingDeviation: number; stopEnabled: boolean; stopPct: number; stopLossTrailingEnabled: boolean;
  stopLossTimeoutEnabled: boolean; stopLossTimeoutSeconds: number; conditions: Array<Record<string,unknown>>; createdAt: string; updatedAt: string | null;
};
type PublicTrade = { pair:string;status:string;invested_quote:number|string|null;realized_pnl:number|string|null;close_reason:string|null;opened_at:string|null;closed_at:string|null;entry_price:number|string|null;average_price:number|string|null;last_price:number|string|null;exit_price:number|string|null;averaging_filled:number|string|null };
type Payload = { share:{slug:string;sharedAt:string;updatedAt:string;views:number;clones:number}; bot:PublicBot; trades:PublicTrade[] };
type Range = "7d"|"30d"|"90d"|"all";
type Tab = "overview"|"configuration"|"trades";
const COLORS=["#55d99a","#df7b84","#e8b862","#7ea7ff","#b98cff","#61c8d6"];
function n(v:unknown,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function money(v:number|null|undefined,d=2){if(v==null||!Number.isFinite(v))return"—";const s=v>0?"+":v<0?"−":"";return`${s}$${Math.abs(v).toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d})}`}
function pct(v:number|null|undefined,d=2){if(v==null||!Number.isFinite(v))return"—";const s=v>0?"+":v<0?"−":"";return`${s}${Math.abs(v).toFixed(d)}%`}
function duration(v:number|null){if(v==null||!Number.isFinite(v))return"—";if(v<60)return`${Math.round(v)}m`;if(v<1440)return`${(v/60).toFixed(v<600?1:0)}h`;return`${(v/1440).toFixed(1)}d`}
function when(v:string|null|undefined){return v?new Date(v).toLocaleString([], {month:"short",day:"numeric",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—"}
function reason(v:string|null){const x=String(v||"").toLowerCase().replaceAll("_"," ");if(x.includes("take profit")||x==="tp")return"Take Profit";if(x.includes("stop"))return"Stop Loss";if(x.includes("manual"))return"Manual";if(x.includes("cancel"))return"Cancelled";return String(v||"Other")}
function rangeStart(range:Range){const days=range==="7d"?7:range==="30d"?30:range==="90d"?90:0;return days?Date.now()-days*86400000:0}
function gradient(parts:Array<{value:number;color:string}>){const total=parts.reduce((s,x)=>s+Math.max(0,x.value),0);if(!total)return"conic-gradient(#30353b 0 360deg)";let c=0;return`conic-gradient(${parts.map(x=>{const a=c/total*360;c+=Math.max(0,x.value);return`${x.color} ${a}deg ${c/total*360}deg`}).join(",")})`}
function capitalCeiling(bot:PublicBot){let perTrade=Math.max(0,n(bot.baseOrder)),so=Math.max(0,n(bot.safetyOrder)),scale=Math.max(.000001,n(bot.volumeScale,1));for(let i=0;i<Math.max(0,Math.round(n(bot.maxSafetyOrders)));i++)perTrade+=so*Math.pow(scale,i);return perTrade*Math.max(1,Math.round(n(bot.maxActiveTrades,1)))}
function lineData(values:Array<{at:string;value:number}>){const W=920,H=250,PX=18,PY=20;if(!values.length)return{line:"",area:"",zero:H/2,min:0,max:0};let min=Math.min(0,...values.map(x=>x.value)),max=Math.max(0,...values.map(x=>x.value));if(Math.abs(max-min)<1e-9){min-=1;max+=1}const x=(i:number)=>PX+(values.length===1?.5:i/(values.length-1))*(W-PX*2),y=(v:number)=>PY+(max-v)/(max-min)*(H-PY*2);const pts=values.map((v,i)=>`${x(i)},${y(v.value)}`),line=`M${pts.join(" L")}`,zero=y(0),area=`${line} L${x(values.length-1)},${zero} L${x(0)},${zero} Z`;return{line,area,zero,min,max}}
function statusText(v:string){return v==="running"?"RUNNING":v==="stopped"?"PAUSED":String(v||"").toUpperCase()}

export default function PublicBotAnalytics({slug}:{slug:string}){
 const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[range,setRange]=useState<Range>("30d"),[tab,setTab]=useState<Tab>("overview"),[copied,setCopied]=useState(false);
 useEffect(()=>{let live=true;async function load(countView:boolean){const{data:body,error:fn}=await browserSupabase.functions.invoke("paper-bot-share",{body:{action:"get",slug,countView}});if(!live)return;if(fn||!body?.ok){setError(body?.message||fn?.message||"This shared bot link is unavailable.");return}setData(body as Payload);setError("")}void load(true);const timer=window.setInterval(()=>void load(false),30000);return()=>{live=false;window.clearInterval(timer)}},[slug]);
 const stats=useMemo(()=>{if(!data)return null;const since=rangeStart(range),closed=data.trades.filter(t=>t.status==="closed"&&t.closed_at&&(range==="all"||Date.parse(t.closed_at)>=since)).sort((a,b)=>Date.parse(a.closed_at||"")-Date.parse(b.closed_at||"")),active=data.trades.filter(t=>t.status==="active");let pnl=0,wins=0,losses=0,be=0,gp=0,gl=0,cum=0,peak=0,maxDd=0,hold=0,holdN=0;const series:Array<{at:string;value:number}>=[];for(const t of closed){const p=n(t.realized_pnl);pnl+=p;if(p>0){wins++;gp+=p}else if(p<0){losses++;gl+=Math.abs(p)}else be++;cum+=p;peak=Math.max(peak,cum);maxDd=Math.max(maxDd,peak-cum);series.push({at:t.closed_at!,value:cum});if(t.opened_at&&t.closed_at){const mins=(Date.parse(t.closed_at)-Date.parse(t.opened_at))/60000;if(Number.isFinite(mins)&&mins>=0){hold+=mins;holdN++}}}const ceiling=capitalCeiling(data.bot),count=closed.length,winRate=count?wins/count*100:null,pf=gl>0?gp/gl:gp>0?Infinity:null,roi=ceiling>0?pnl/ceiling*100:null;const exits=new Map<string,number>();closed.forEach(t=>exits.set(reason(t.close_reason),(exits.get(reason(t.close_reason))||0)+1));return{closed,active,pnl,wins,losses,be,gp,gl,maxDd,series,ceiling,count,winRate,pf,roi,expectancy:count?pnl/count:null,avgHold:holdN?hold/holdN:null,exits:[...exits.entries()].sort((a,b)=>b[1]-a[1])}},[data,range]);
 if(error)return<main className={styles.page}><section className={styles.error}><h1>Shared bot unavailable</h1><p>{error}</p><a className={styles.primary} href="https://app.labnarrative.com">Open LabNarrative Trading</a></section></main>;
 if(!data||!stats)return<main className={styles.page}><section className={styles.loading}>Loading live Paper analytics…</section></main>;
 const chart=lineData(stats.series),cloneUrl=`https://app.labnarrative.com/clone/${encodeURIComponent(slug)}`,publicUrl=`https://labnarrative.com/bot/${encodeURIComponent(slug)}`;
 const pnlClass=stats.pnl>0?styles.positive:stats.pnl<0?styles.negative:styles.neutral;
 const recent=[...data.trades].sort((a,b)=>Date.parse(b.opened_at||"")-Date.parse(a.opened_at||"")).slice(0,40);
 const outcomeGradient=gradient([{value:stats.wins,color:COLORS[0]},{value:stats.losses,color:COLORS[1]},{value:stats.be,color:"#777"}]);
 const exitGradient=gradient(stats.exits.map((x,i)=>({value:x[1],color:COLORS[i%COLORS.length]})));
 return<main className={styles.page}>
  <div className={styles.top}><a className={styles.brand} href="/"><img src="/labnarrative-mark.svg" alt=""/><strong>LabNarrative</strong></a><span className={styles.topNote}>Shared Paper bot analytics · read only</span></div>
  <section className={styles.workspace}>
   <header className={styles.header}><div className={styles.identity}><span className={styles.eyebrow}>LIVE PAPER RESULTS</span><h1>{data.bot.name}</h1><div className={styles.meta}><span>DCA</span><span>{data.bot.market}</span><span>Paper simulation</span><b className={styles.status}>{statusText(data.bot.status)}</b></div></div><div className={styles.actions}><div className={styles.ranges}>{(["7d","30d","90d","all"] as Range[]).map(x=><button key={x} onClick={()=>setRange(x)} className={range===x?styles.rangeActive:""}>{x==="all"?"ALL":x.toUpperCase()}</button>)}</div><button className={styles.ghost} onClick={async()=>{try{await navigator.clipboard.writeText(publicUrl);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{}}}>{copied?"Copied ✓":"Share"}</button><a className={styles.primary} href={cloneUrl}>Clone Bot</a></div></header>
   <div className={styles.scroll}>
    <nav className={styles.tabs}><button className={`${styles.tab} ${tab==="overview"?styles.tabActive:""}`} onClick={()=>setTab("overview")}>Overview</button><button className={`${styles.tab} ${tab==="configuration"?styles.tabActive:""}`} onClick={()=>setTab("configuration")}>Configuration</button><button className={`${styles.tab} ${tab==="trades"?styles.tabActive:""}`} onClick={()=>setTab("trades")}>Trades</button></nav>
    <div className={styles.notice}><strong>Forward Paper simulation using virtual funds.</strong><span>Live analytics refresh every 30 seconds · Shared {when(data.share.sharedAt)}</span></div>
    {tab==="overview"?<>
     <section className={styles.kpis}><article><span>Realized PnL</span><strong className={pnlClass}>{money(stats.pnl)}</strong><small>{stats.count} closed</small></article><article><span>ROI</span><strong className={stats.roi&&stats.roi>0?styles.positive:stats.roi&&stats.roi<0?styles.negative:styles.neutral}>{pct(stats.roi)}</strong><small>on max capital</small></article><article><span>Trades</span><strong>{stats.count}</strong><small>{stats.active.length} active now</small></article><article><span>Win rate</span><strong>{stats.winRate==null?"—":`${stats.winRate.toFixed(1)}%`}</strong><small>{stats.wins}W · {stats.losses}L</small></article><article><span>Profit factor</span><strong>{stats.pf===Infinity?"∞":stats.pf==null?"—":stats.pf.toFixed(2)}</strong><small>gross profit ÷ loss</small></article><article><span>Max drawdown</span><strong className={styles.negative}>{money(-stats.maxDd)}</strong><small>realized curve</small></article><article><span>Expectancy</span><strong className={stats.expectancy&&stats.expectancy>0?styles.positive:styles.neutral}>{money(stats.expectancy)}</strong><small>per closed trade</small></article><article><span>Avg hold</span><strong>{duration(stats.avgHold)}</strong><small>{range.toUpperCase()}</small></article></section>
     <div className={styles.grid}><article className={styles.card}><div className={styles.sectionHead}><div><small>PERFORMANCE EXPLORER</small><h2>Cumulative realized PnL</h2></div><span>{stats.series.length} observations</span></div><div className={styles.chartMeta}><strong className={pnlClass}>{money(stats.pnl)}</strong><span>Selected range: {range.toUpperCase()}</span></div><div className={styles.chart}>{stats.series.length?<svg viewBox="0 0 920 250" preserveAspectRatio="none"><defs><linearGradient id="sharedArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#55d99a" stopOpacity=".24"/><stop offset="100%" stopColor="#55d99a" stopOpacity="0"/></linearGradient></defs>{[55,105,155,205].map(y=><line key={y} x1="18" x2="902" y1={y} y2={y} className={styles.gridLine}/>) }<line x1="18" x2="902" y1={chart.zero} y2={chart.zero} className={styles.zeroLine}/><path d={chart.area} className={styles.area}/><path d={chart.line} className={styles.line}/></svg>:<div className={styles.loading}>No closed trades in this period yet.</div>}</div></article>
      <div className={styles.analyticsSide}><article className={styles.donutCard}><div className={styles.sectionHead}><div><small>OUTCOME MIX</small><h2>Winning behavior</h2></div></div><div className={styles.donutWrap}><div className={styles.donut} style={{background:outcomeGradient}}><div className={styles.donutCenter}><strong>{stats.count}</strong><small>closed</small></div></div><div className={styles.legend}>{[["Wins",stats.wins,COLORS[0]],["Losses",stats.losses,COLORS[1]],["Breakeven",stats.be,"#777"]].map(([label,value,color])=><div className={styles.legendRow} key={String(label)}><i style={{background:String(color)}}/><span>{String(label)}</span><b>{Number(value)}</b></div>)}</div></div></article>
      <article className={styles.donutCard}><div className={styles.sectionHead}><div><small>EXIT DISTRIBUTION</small><h2>How trades ended</h2></div></div><div className={styles.donutWrap}><div className={styles.donut} style={{background:exitGradient}}><div className={styles.donutCenter}><strong>{stats.exits.reduce((s,x)=>s+x[1],0)}</strong><small>exits</small></div></div><div className={styles.legend}>{stats.exits.slice(0,5).map((x,i)=><div className={styles.legendRow} key={x[0]}><i style={{background:COLORS[i%COLORS.length]}}/><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div></article></div>
     </div>
     <section className={styles.cloneBand}><div><strong>Like this configuration?</strong><p>Clone the exact setup into your own LabNarrative Paper workspace. The clone starts paused with fresh performance history.</p></div><a className={styles.primary} href={cloneUrl}>Clone & review →</a></section>
    </>:null}
    {tab==="configuration"?<><div className={styles.sectionHead} style={{marginTop:12}}><div><small>PUBLIC CONFIGURATION</small><h2>Exact DCA setup</h2></div><span>Read only · current bot settings</span></div><section className={styles.config}>{[
      ["Pairs",data.bot.allPairs?"All USDT Spot":data.bot.pairs.join(", ")||"—",true],["Base order",`${money(data.bot.baseOrder)} · ${data.bot.baseOrderType}`,false],["DCA order",money(data.bot.safetyOrder),false],["Max DCA orders",String(data.bot.maxSafetyOrders),false],["Active DCA orders",String(data.bot.limitSafetyOrders),false],["Max active trades",String(data.bot.maxActiveTrades),false],["Initial deviation",pct(data.bot.deviation,2),false],["Step scale",String(data.bot.stepScale),false],["Volume scale",String(data.bot.volumeScale),false],["Take profit",pct(data.bot.takeProfit,2),false],["Trailing TP",data.bot.takeProfitTrailingEnabled?`On · ${pct(data.bot.takeProfitTrailingDeviation,2)} deviation`:"Off",false],["Stop loss",data.bot.stopEnabled?`${pct(data.bot.stopPct,2)}${data.bot.stopLossTrailingEnabled?" · trailing":""}`:"Off",false],["SL timeout",data.bot.stopEnabled&&data.bot.stopLossTimeoutEnabled?`${data.bot.stopLossTimeoutSeconds}s`:"Off",false],["Max capital",money(stats.ceiling),false]
     ].map(([label,value,wide])=><article key={String(label)} className={`${styles.configItem} ${wide?styles.configWide:""}`}><span>{String(label)}</span><strong>{String(value)}</strong></article>)}</section>
     {data.bot.takeProfitLevels?.length>1?<><div className={styles.sectionHead} style={{marginTop:14}}><div><small>TAKE-PROFIT LADDER</small><h2>Partial exits</h2></div></div><section className={styles.config}>{data.bot.takeProfitLevels.map((level,i)=><article className={styles.configItem} key={i}><span>TP {i+1}</span><strong>{pct(n(level.targetPct),2)} · close {pct(n(level.closePct),1,false)}</strong></article>)}</section></>:null}
     <div className={styles.sectionHead} style={{marginTop:14}}><div><small>CONDITIONS</small><h2>Entry / exit logic</h2></div><span>{data.bot.conditions.length} configured</span></div><div className={styles.conditions}>{data.bot.conditions.length?data.bot.conditions.map((c,i)=><div className={styles.condition} key={String(c.id||i)}><strong>{String(c.purpose||"entry").toUpperCase()} · {String(c.kind||"Condition")}</strong><span>{String(c.timeframe||"—")}</span><span>{String(c.comparator||"")} {c.signal!=null?String(c.signal):""}</span></div>):<div className={styles.configItem}><span>Entry logic</span><strong>No indicator conditions configured</strong></div>}</div>
    </>:null}
    {tab==="trades"?<><div className={styles.sectionHead} style={{marginTop:12}}><div><small>TRADE HISTORY</small><h2>Recent Paper trades</h2></div><span>Newest first · up to 40 shown</span></div><div className={styles.tableWrap}><div className={styles.tradeTable}><div className={styles.tradeHead}><span>Pair</span><span>Status</span><span>Capital</span><span>PnL</span><span>Avg entry</span><span>DCA</span><span>Closed</span><span>Reason</span></div>{recent.map((t,i)=><div className={styles.tradeRow} key={`${t.opened_at}-${i}`}><strong>{t.pair}</strong><span>{t.status}</span><span>{money(n(t.invested_quote),2)}</span><span className={n(t.realized_pnl)>0?styles.positive:n(t.realized_pnl)<0?styles.negative:styles.neutral}>{t.status==="closed"?money(n(t.realized_pnl),2):"—"}</span><span>{n(t.average_price).toLocaleString("en-US",{maximumFractionDigits:6})}</span><span>{Math.max(0,Math.round(n(t.averaging_filled)))}</span><span>{when(t.closed_at)}</span><span>{t.status==="closed"?reason(t.close_reason):"Open"}</span></div>)}</div></div></>:null}
   </div>
  </section>
  <footer className={styles.footer}><span>Paper simulation uses virtual funds. These results do not represent live-money execution and are not investment advice.</span><span>{data.share.views} views · {data.share.clones} clones · <a href="https://app.labnarrative.com">LabNarrative Trading</a></span></footer>
 </main>
}
