"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {Badge,Tabs,Help} from "../_components";
import {usePVOS} from "../_provider";
import {pvosSupabase} from "../_pvos-supabase";
import {authorityStatus,loadAuthority,latestNotices,noticeInPeriod,suggestedProducts,sourceNeedsRecheck,saveAuthorityJSON,riyadhDay,type AuthorityData,type AuthorityRow as Row} from "../_authority";
import styles from "../pvos.module.css";
const roles=["admin","qppv","deputy_qppv"];
function when(v?:string){return v?new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Riyadh",dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"Not recorded";}
function month(v:string){return new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Riyadh",month:"long",year:"numeric"}).format(new Date(v+"T12:00:00Z"));}
function MonitoringBadge({period}:{period:Row}){return <Badge tone={period.status==="approved"?"green":period.status==="returned"?"red":"amber"}>{authorityStatus[period.status]}</Badge>;}
type Action=(name:string,args:Row,message:string)=>Promise<void>;
export default function AuthorityMonitoring(){
 const {organizationId,session}=usePVOS(),userId=session?.user.id;
 const [data,setData]=useState<AuthorityData|null>(null),[view,setView]=useState<"due"|"records"|"settings">("due"),[company,setCompany]=useState("all"),[selected,setSelected]=useState<string|null>(null);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),request=useRef(0);
 const load=useCallback(async()=>{
  if(!organizationId)return;const id=++request.current;
  try{const next=await loadAuthority(pvosSupabase,organizationId);if(id===request.current){setData(next);setError(null);}}
  catch(e){if(id===request.current){setError((e as {message?:string}).message||"Could not load monitoring records");throw e;}}
  finally{if(id===request.current)setLoading(false);}
 },[organizationId]);
 useEffect(()=>{setData(null);setLoading(true);setSelected(null);setCompany(new URLSearchParams(window.location.search).get("company")||"all");load().catch(()=>{});const id=new URLSearchParams(window.location.search).get("authorityPeriod");if(id)setSelected(id);return()=>{request.current++;};},[load]);
 async function action(name:string,args:Row,message:string){
  if(busy)return;setBusy(true);setError(null);setNotice(null);
  try{const result=await pvosSupabase.rpc(name,args);if(result.error)throw result.error;await load();setNotice(message);}
  catch(e){setError((e as {message?:string}).message||"Save or refresh failed. Refresh before retrying.");}
  finally{setBusy(false);}
 }
 function open(id:string|null){setSelected(id);const url=new URL(window.location.href);url.searchParams.set("view","authority");if(id)url.searchParams.set("authorityPeriod",id);else url.searchParams.delete("authorityPeriod");window.history.replaceState(window.history.state,"",url);}
 const canConfigure=roles.includes(data?.members.find(m=>m.user_id===userId)?.role||"");
 const scope=(data?.periods||[]).filter(p=>company==="all"||p.company_id===company),period=data?.periods.find(p=>p.id===selected);
 return <>
  <Tabs label="Authority monitoring areas" value={view} onChange={v=>{if(busy)return;setView(v as typeof view);open(null)}} items={[{id:"due",label:"Due for review"},{id:"records",label:"Records"},{id:"settings",label:"Settings"}]}/><div className={styles.quietActions}><button className={styles.buttonGhost} disabled={busy||loading} onClick={()=>{setLoading(true);load().catch(()=>{});}}>Refresh</button></div>
  {error?<div className={styles.errorBox} role="alert">Monitoring records could not be fully loaded or saved: {error}</div>:null}{notice?<div className={styles.notice} role="status">{notice}</div>:null}
  {loading&&!data?<div className={styles.empty}>Loading authority monitoring…</div>:data?<>
   <label>Company<select className={styles.input} value={company} disabled={busy} onChange={e=>{setCompany(e.target.value);const u=new URL(window.location.href);if(e.target.value==="all")u.searchParams.delete("company");else u.searchParams.set("company",e.target.value);window.history.replaceState({},"",u);open(null);}}><option value="all">All companies</option>{data.companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
   {view==="settings"?<MonitoringSettings key={company} data={data} company={company} organizationId={organizationId!} canConfigure={canConfigure} busy={busy} action={action}/>:period?<PeriodWorkspace key={period.id} period={period} data={data} userId={userId} busy={busy} action={action} onBack={()=>open(null)}/>:<>
    <Help>Monthly company records · named independent review · times shown in Riyadh. Automatic collection covers the named feeds only; human source checks remain required.</Help>
    {view==="due"?<div className={styles.notice}>Prepare source checks during the month. Submit after the period ends. Required sources that are unavailable or unchecked keep the record outstanding.</div>:null}
    <section className={styles.panel}><div className={styles.panelHeader}><h2>{view==="records"?"Approved monitoring records":"Outstanding monitoring periods"}</h2></div>
     {scope.filter(p=>view==="records"?p.status==="approved":p.status!=="approved").length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Company / period</th><th>Status</th><th>Owner → reviewer</th><th>Source checks</th><th></th></tr></thead><tbody>{scope.filter(p=>view==="records"?p.status==="approved":p.status!=="approved").sort((a,b)=>a.due_at.localeCompare(b.due_at)).map(p=>{
      const checks=data.checks.filter(c=>c.period_id===p.id),done=checks.filter(c=>['findings','no_relevant_findings'].includes(c.outcome)&&(p.status==='approved'||!sourceNeedsRecheck(c,p,data.notices,data.products))).length;
      return <tr key={p.id}><td><strong>{p.settings_snapshot.company_name}</strong><div>{month(p.period_start)}</div><div className={styles.muted}>Monitoring {p.id.slice(0,8).toUpperCase()} · due {when(p.due_at)}</div></td><td><MonitoringBadge period={p}/></td><td>{p.settings_snapshot.owner_email}<div>→ {p.settings_snapshot.reviewer_email}</div></td><td>{done} / {checks.length}{checks.some(c=>c.outcome==="unavailable")?<div><Badge tone="red">Source unavailable</Badge></div>:null}</td><td><button className={styles.buttonGhost} onClick={()=>open(p.id)}>Open {view==="records"?"record":"period"} →</button></td></tr>;
     })}</tbody></table></div>:<div className={styles.empty}>{view==="records"?"No approved records yet.":"No outstanding periods in this scope. Use Settings to configure company monitoring."}</div>}
    </section>
   </>}
  </>:null}
 </>;
}

function MonitoringSettings({data,company,organizationId,canConfigure,busy,action}:{data:AuthorityData,company:string,organizationId:string,canConfigure:boolean,busy:boolean,action:Action}){
 const config=data.settings.find(s=>s.company_id===company);
 const [owner,setOwner]=useState(config?.owner_user_id||""),[reviewer,setReviewer]=useState(config?.reviewer_user_id||""),[sources,setSources]=useState<string[]>(config?.source_ids||data.sources.map(s=>s.id));
 const [sop,setSop]=useState(config?.sop_reference||""),[form,setForm]=useState(config?.form_reference||""),[scope,setScope]=useState(config?.scope_rationale||""),[start,setStart]=useState(config?.start_month?.slice(0,7)||riyadhDay(new Date().toISOString()).slice(0,7)),[enabled,setEnabled]=useState(config?.enabled??true);
 const [name,setName]=useState(""),[url,setUrl]=useState(""),[coverage,setCoverage]=useState("");
 const products=data.products.filter(p=>p.company_id===company);
 return <section className={styles.panel} style={{padding:20}}><h2>Company monitoring setup</h2>{company==="all"?<p>Choose a company above to confirm its monitoring scope.</p>:<>
  <p>{products.length} company products · <Link href={`/pvos/companies/${company}`}>Open product catalogue →</Link></p>
  {!canConfigure?<div className={styles.notice}>An administrator, QPPV or Deputy QPPV confirms the source scope and reviewer.</div>:null}
  <fieldset disabled={!canConfigure||busy} style={{border:0,padding:0}}>
   <div className={styles.formGrid}><label>Monitoring owner<select className={styles.input} value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Choose owner</option>{data.members.map(m=><option key={m.user_id} value={m.user_id}>{m.email} · {m.role}</option>)}</select></label><label>Independent QPPV reviewer<select className={styles.input} value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">Choose reviewer</option>{data.members.filter(m=>roles.includes(m.role)&&m.user_id!==owner).map(m=><option key={m.user_id} value={m.user_id}>{m.email} · {m.role}</option>)}</select></label></div>
   <div className={styles.formGrid}><label>SOP identifier and version<input className={styles.input} value={sop} maxLength={10000} onChange={e=>setSop(e.target.value)}/></label><label>Company monitoring form and version<input className={styles.input} value={form} maxLength={10000} onChange={e=>setForm(e.target.value)}/></label></div>
   <h3>Required sources</h3><p className={styles.muted}>Confirm authority/product scope against the <a href="https://www.who.int/publications/m/item/list-of-who-listed-authorities-wlas" target="_blank" rel="noreferrer">WHO list</a> and your SOP. These candidates are a starting set; add other required authorities below.</p>
   {data.sources.map(s=>{const run=data.collections.filter(r=>r.source_id===s.id).sort((a,b)=>b.completed_at.localeCompare(a.completed_at))[0];return <label key={s.id} style={{display:"block",padding:"10px 0"}}><input type="checkbox" checked={sources.includes(s.id)} onChange={e=>setSources(e.target.checked?[...sources,s.id]:sources.filter(id=>id!==s.id))}/> <strong>{s.name}</strong> <Badge tone={s.method==="manual"?"amber":run?.status==="error"?"red":"default"}>{s.method==="manual"?"Manual check required":run?.status==="error"?"Automatic collection unavailable":"Automatic feed collection"}</Badge><div className={styles.muted}>{s.coverage_note}</div>{s.method!=="manual"?<div className={styles.muted}>Last check: {when(run?.completed_at)}{run?.status==="ok"?` · ${run.entry_count} feed entries`:run?.error?` · ${run.error}`:" · not yet collected"}</div>:null}</label>;})}
   <label>Authority selection and applicability rationale<textarea className={styles.input} rows={3} value={scope} maxLength={10000} onChange={e=>setScope(e.target.value)} placeholder="Confirm required authorities, product scope, WHO list/version consulted and any additional channels or archive checks."/></label>
   <div className={styles.formGrid}><label>Starting month<input type="month" className={styles.input} value={start} onChange={e=>setStart(e.target.value)}/></label><label style={{alignSelf:"center"}}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enable monthly monitoring tasks</label></div>
   <Help>Changes apply to newly created periods. Existing periods retain their recorded source scope, SOP, form and participants. Historical months may require manual archive checks.</Help>
   <button className={styles.button} disabled={!owner||!reviewer||owner===reviewer||!sources.length||!sop.trim()||!form.trim()||!scope.trim()||!start||(enabled&&!products.length)} onClick={()=>action("pvos_configure_authority_monitoring",{p_company_id:company,p_owner_id:owner,p_reviewer_id:reviewer,p_source_ids:sources,p_sop:sop,p_form:form,p_scope:scope,p_start_month:start+"-01",p_enabled:enabled},`Monitoring scope saved. Records will be sent to ${data.members.find(m=>m.user_id===reviewer)?.email}.`)}>Save company monitoring</button>
   {enabled&&!products.length?<p className={styles.muted}>Add the company’s products before enabling monitoring.</p>:null}
   <details style={{marginTop:20}}><summary>Add another authority for manual monitoring</summary><label>Authority name<input className={styles.input} value={name} maxLength={500} onChange={e=>setName(e.target.value)}/></label><label>Official HTTPS source URL<input className={styles.input} value={url} maxLength={4000} onChange={e=>setUrl(e.target.value)}/></label><label>Scope / channels to check<textarea className={styles.input} value={coverage} maxLength={10000} onChange={e=>setCoverage(e.target.value)}/></label><button className={styles.buttonGhost} disabled={!name.trim()||!url.trim()||!coverage.trim()} onClick={()=>action("pvos_add_manual_authority_source",{p_organization_id:organizationId,p_name:name,p_url:url.trim(),p_coverage_note:coverage},"Manual authority added. Select it in the company scope and save.")}>Add manual authority</button></details>
  </fieldset>
 </>}</section>;
}

function PeriodWorkspace({period:p,data,userId,busy,action,onBack}:{period:Row,data:AuthorityData,userId?:string,busy:boolean,action:Action,onBack:()=>void}){
 const [source,setSource]=useState<string|null>(null),[conclusion,setConclusion]=useState(""),[newReviewer,setNewReviewer]=useState(p.reviewer_user_id),[changeReason,setChangeReason]=useState(""),[withdrawReason,setWithdrawReason]=useState("");
 const checks=data.checks.filter(c=>c.period_id===p.id),findings=data.findings.filter(f=>f.period_id===p.id),reviews=data.reviews.filter(r=>r.period_id===p.id).sort((a,b)=>b.cycle-a.cycle),pending=reviews.find(r=>r.status==="pending"),record=data.records.find(r=>r.period_id===p.id);
 const role=data.members.find(m=>m.user_id===userId)?.role,canPrepare=['draft','returned'].includes(p.status)&&p.reviewer_user_id!==userId&&(p.owner_user_id===userId||roles.includes(role||"")),closed=Date.now()>=new Date(p.due_at).getTime(),gaps=checks.filter(c=>['not_checked','unavailable'].includes(c.outcome)||(p.status!=='approved'&&sourceNeedsRecheck(c,p,data.notices,data.products)));
 const frozenData=record?{...data,notices:data.notices.filter(n=>n.first_seen_at<=record.completed_at),collections:data.collections.filter(c=>c.completed_at<=record.completed_at)}:data;
 const check=checks.find(c=>c.id===source),canSend=canPrepare&&p.reviewer_user_id!==userId&&closed&&!gaps.length&&!findings.some(f=>f.assessment==="needs_review");
 return <>
  <button className={styles.buttonGhost} disabled={busy} onClick={onBack}>← Back to monitoring periods</button>
  <section className={styles.panel} style={{padding:20,marginTop:12}}><h2>{p.settings_snapshot.company_name} · {month(p.period_start)}</h2><MonitoringBadge period={p}/><p className={styles.muted}>Monitoring {p.id.slice(0,8).toUpperCase()} · {p.period_start} → {p.period_end} · due {when(p.due_at)}</p><div>Owner: {p.settings_snapshot.owner_email} → Reviewer: {p.settings_snapshot.reviewer_email}</div><div className={styles.muted}>SOP: {p.settings_snapshot.sop_reference} · Form: {p.settings_snapshot.form_reference}</div><p className={styles.muted}>Products at period setup: {(p.product_snapshot||[]).map((x:Row)=>x.brand_name).join(", ")||"None recorded"}</p>
   {p.task_id?<Link href={`/pvos/tasks/${p.task_id}`}>Open monitoring task →</Link>:null}
   {record?<div className={styles.notice}><strong>Approved evidence retained</strong><p>{record.snapshot.first_review.email} · submitted {when(record.snapshot.first_review.submitted_at)}<br/>{record.snapshot.second_review.email} · approved {when(record.snapshot.second_review.decided_at)}</p><button className={styles.buttonGhost} onClick={()=>saveAuthorityJSON(record,`PVOS-authority-${p.id.slice(0,8)}.json`)}>Export approved record JSON</button><div className={styles.muted}>SHA-256: {record.snapshot_sha256}</div></div>:null}
  </section>
  {canPrepare?<details className={styles.panel} style={{padding:16,marginTop:14}}><summary>Change this period’s reviewer</summary><label>Named QPPV reviewer<select className={styles.input} value={newReviewer} onChange={e=>setNewReviewer(e.target.value)}>{data.members.filter(m=>roles.includes(m.role)&&m.user_id!==p.owner_user_id).map(m=><option key={m.user_id} value={m.user_id}>{m.email}</option>)}</select></label><label>Change reason<input className={styles.input} value={changeReason} maxLength={10000} onChange={e=>setChangeReason(e.target.value)}/></label><button className={styles.buttonGhost} disabled={busy||!newReviewer||newReviewer===p.reviewer_user_id||!changeReason.trim()} onClick={()=>action("pvos_change_authority_reviewer",{p_period_id:p.id,p_revision:p.revision,p_reviewer_id:newReviewer,p_reason:changeReason},"Current reviewer changed. Previous submission cycles retain their original recipient.")}>Change named reviewer</button></details>:null}
  {pending&&p.reviewer_user_id!==userId&&(p.owner_user_id===userId||roles.includes(role||""))?<details className={styles.panel} style={{padding:16,marginTop:14}}><summary>Withdraw this submission for correction</summary><label>Withdrawal reason<input className={styles.input} value={withdrawReason} maxLength={10000} onChange={e=>setWithdrawReason(e.target.value)}/></label><button className={styles.buttonGhost} disabled={busy||!withdrawReason.trim()} onClick={()=>action("pvos_withdraw_authority_submission",{p_period_id:p.id,p_revision:p.revision,p_reason:withdrawReason},"Submission withdrawn. Its evidence and recipient remain in review history; preparation is open again.")}>Withdraw submission</button></details>:null}
  <section className={styles.panel} style={{marginTop:14}}><div className={styles.panelHeader}><h2>Source checks</h2><span>{checks.length-gaps.length} / {checks.length} ready</span></div>{checks.map(c=>{const collection=data.collections.filter(r=>r.source_id===c.source_id).sort((a,b)=>b.completed_at.localeCompare(a.completed_at))[0],recheck=p.status!=="approved"&&sourceNeedsRecheck(c,p,data.notices,data.products);return <div key={c.id} style={{padding:14,borderTop:"1px solid #334155"}}><div className={styles.inlineActions} style={{justifyContent:"space-between",flexWrap:"wrap"}}><strong>{c.source_snapshot.name}</strong><Badge tone={c.outcome==="unavailable"?"red":recheck||c.outcome==="not_checked"?"amber":"green"}>{c.outcome==="unavailable"?"Source unavailable":recheck&&c.checked_at?"Source needs another check":c.outcome==="not_checked"?"Not checked":c.outcome==="findings"?"Findings recorded":"No relevant findings recorded"}</Badge><button className={styles.buttonGhost} disabled={busy} onClick={()=>setSource(source===c.id?null:c.id)}>{source===c.id?"Close source":"Open source"}</button></div><div className={styles.muted}>{c.source_snapshot.method==="manual"?"Manual check required":`Automatic feed · last check ${when(collection?.completed_at)} · ${collection?.status||"not yet collected"}`}</div>{c.checked_at?<div className={styles.muted}>Human check: {c.checked_email} · {when(c.checked_at)}</div>:null}{check?.id===c.id?<SourceWorkspace key={c.id+":"+p.revision} period={p} check={c} data={frozenData} canPrepare={canPrepare} busy={busy} action={action}/>:null}</div>;})}</section>
  {pending?<ReviewDecision key={pending.id} review={pending} userId={userId} canReview={roles.includes(role||"")} busy={busy} action={action}/>:canPrepare?<section className={styles.panel} style={{padding:20,marginTop:14}}><h2>Send to named reviewer</h2><p>Destination: <strong>{p.settings_snapshot.reviewer_email}</strong> · their Due for review queue</p>{!closed?<p className={styles.muted}>This period is still open. Prepare evidence now; submit after {when(p.due_at)}.</p>:gaps.length?<p className={styles.muted}>{gaps.length} source checks remain outstanding. Unavailable sources must be resolved before submission.</p>:null}{findings.some(f=>f.assessment==="needs_review")?<p className={styles.muted}>Resolve findings marked Needs review before submission.</p>:null}<label>Monitoring conclusion<textarea className={styles.input} rows={3} value={conclusion} maxLength={10000} onChange={e=>setConclusion(e.target.value)}/></label><button className={styles.button} disabled={busy||!canSend||!conclusion.trim()} onClick={()=>action("pvos_submit_authority_period",{p_period_id:p.id,p_revision:p.revision,p_note:conclusion},`Sent to ${p.settings_snapshot.reviewer_email}. The period remains pending until their decision.`)}>Send to {p.settings_snapshot.reviewer_email}</button></section>:null}
  <details className={styles.panel} style={{padding:16,marginTop:14}}><summary>Review history · {reviews.length} cycles</summary>{reviews.map(r=><article key={r.id}><h3>Cycle {r.cycle} · {r.status}</h3><div>{r.sent_email} → {r.assigned_email} · {when(r.sent_at)}</div><p>{r.submission_note}</p>{r.decided_at?<><div>{r.decided_email} · {r.decided_role} · {when(r.decided_at)}</div><p>{r.decision_note}</p></>:null}<details><summary>Submitted evidence snapshot</summary><pre style={{maxHeight:300,overflow:"auto",whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{JSON.stringify(r.snapshot,null,2)}</pre></details></article>)}</details>
 </>;
}

function SourceWorkspace({period:p,check:c,data,canPrepare,busy,action}:{period:Row,check:Row,data:AuthorityData,canPrepare:boolean,busy:boolean,action:Action}){
 const [candidate,setCandidate]=useState<Row|null>(null),[outcome,setOutcome]=useState(c.outcome==="not_checked"?(data.findings.some(f=>f.check_id===c.id&&f.assessment!=="not_relevant")?"findings":"no_relevant_findings"):c.outcome),[note,setNote]=useState(c.notes||""),[all,setAll]=useState(false),[page,setPage]=useState(0);
 const companyProducts=data.products.filter(x=>x.company_id===p.company_id),notices=latestNotices(data.notices.filter(n=>n.source_id===c.source_id)).filter(n=>all||noticeInPeriod(n,p)).map((n):Row&{matches:Row[]}=>({...n,matches:suggestedProducts(n,companyProducts)})).sort((a,b)=>b.matches.length-a.matches.length||String(b.published_at||b.first_seen_at).localeCompare(String(a.published_at||a.first_seen_at)));
 const findings=data.findings.filter(f=>f.check_id===c.id),collections=data.collections.filter(r=>r.source_id===c.source_id).sort((a,b)=>b.completed_at.localeCompare(a.completed_at));
 return <div style={{paddingTop:14}}><p><a href={c.source_snapshot.url} target="_blank" rel="noreferrer">Open official source / archives →</a></p><div className={styles.notice}>{c.source_snapshot.coverage_note}</div>
  {c.source_snapshot.method!=="manual"?<><p className={styles.muted}>Automatic collection every 4h · {collections[0]?.status==="ok"?`${collections[0].entry_count} entries in latest feed; published range ${when(collections[0].oldest_published_at)} → ${when(collections[0].newest_published_at)}`:collections[0]?.error||"No successful collection recorded yet"}. A successful feed fetch does not establish complete website or period coverage.</p><label><input type="checkbox" checked={all} onChange={e=>{setAll(e.target.checked);setPage(0);}}/> Show all dates, including older baseline notices</label><p className={styles.muted}>{notices.length} notice URLs · latest captured versions · suggested matches appear first; unmatched notices remain available.</p>
   {notices.slice(page*10,page*10+10).map(n=><article key={n.id} style={{padding:"12px 0",borderBottom:"1px solid #334155"}}><strong><a href={n.url} target="_blank" rel="noreferrer">{n.title}</a></strong><div className={styles.muted}>Published: {when(n.published_at)} · collected {when(n.first_seen_at)}{n.baseline?" · initial baseline":""}</div>{n.matches.length?<div className={styles.muted}>Suggested: {n.matches.map((x:Row)=>x.brand_name).join(", ")}</div>:null}{n.summary?<details><summary>Publisher summary</summary><p>{n.summary}</p></details>:null}{canPrepare?<button className={styles.buttonGhost} disabled={busy||findings.some(f=>f.notice_id===n.id)} onClick={()=>setCandidate({notice:n})}>{findings.some(f=>f.notice_id===n.id)?"Finding already recorded":"Record finding"}</button>:null}</article>)}
   <div className={styles.inlineActions}><button className={styles.buttonGhost} disabled={page===0} onClick={()=>setPage(page-1)}>Previous notices</button><button className={styles.buttonGhost} disabled={(page+1)*10>=notices.length} onClick={()=>setPage(page+1)}>Next notices</button></div></>:null}
  <h3>Recorded findings</h3>{findings.length?findings.map(f=>{const signal=data.signals.find(s=>s.authority_finding_id===f.id);return <article key={f.id} style={{padding:"10px 0"}}><strong><a href={f.url} target="_blank" rel="noreferrer">{f.title}</a></strong><div>{f.assessment.replaceAll("_"," ")} · {f.product_ids.map((id:string)=>companyProducts.find(x=>x.id===id)?.brand_name||id).join(", ")}</div><p>{f.rationale}</p>{signal?<Link href="/pvos/signal?view=review">In Signal Review · {signal.status} →</Link>:canPrepare?<div className={styles.inlineActions}><button className={styles.buttonGhost} disabled={busy} onClick={()=>setCandidate({finding:f})}>Edit finding</button>{f.assessment==="relevant"?<button className={styles.buttonGhost} disabled={busy} onClick={()=>action("pvos_escalate_authority_finding",{p_finding_id:f.id,p_revision:p.revision},"Relevant finding added to Signal Review. This does not validate a signal.")}>Send to Signal Review</button>:null}</div>:null}</article>;}):<p className={styles.muted}>No findings recorded for this source.</p>}
  {canPrepare?<button className={styles.buttonGhost} disabled={busy} onClick={()=>setCandidate({manual:true})}>Add finding from manual check</button>:null}
  {candidate?<FindingEditor key={candidate.finding?.id||candidate.notice?.id||"manual"} candidate={candidate} period={p} check={c} products={companyProducts} busy={busy} action={action} onClose={()=>setCandidate(null)}/>:null}
  {canPrepare?<fieldset disabled={busy} style={{border:0,padding:0,marginTop:18}}><legend><strong>Human source check</strong></legend><label>Outcome<select className={styles.input} value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="no_relevant_findings">No relevant findings</option><option value="findings">Findings recorded</option><option value="unavailable">Source unavailable — follow-up required</option></select></label><label>Scope, period, evidence and conclusion / failure note<textarea className={styles.input} rows={3} value={note} maxLength={10000} onChange={e=>setNote(e.target.value)} placeholder="Record what you checked, including any manual archive/additional-channel checks, and your conclusion."/></label><button className={styles.buttonGhost} disabled={!note.trim()} onClick={()=>action("pvos_record_authority_check",{p_period_id:p.id,p_revision:p.revision,p_check_id:c.id,p_outcome:outcome,p_notes:note},"Source check recorded with your identity and timestamp.")}>Record source check</button></fieldset>:<p style={{whiteSpace:"pre-wrap"}}>{c.notes}</p>}
 </div>;
}

function FindingEditor({candidate,period,check,products,busy,action,onClose}:{candidate:Row,period:Row,check:Row,products:Row[],busy:boolean,action:Action,onClose:()=>void}){
 const f=candidate.finding,n=candidate.notice;
 const [title,setTitle]=useState(f?.title||n?.title||""),[url,setUrl]=useState(f?.url||n?.url||""),[assessment,setAssessment]=useState(f?.assessment||"needs_review"),[rationale,setRationale]=useState(f?.rationale||""),[ids,setIds]=useState<string[]>(f?.product_ids||(n?suggestedProducts(n,products).map(x=>x.id):[]));
 return <section className={styles.info} style={{padding:16,marginTop:14}}><h3>{f?"Edit finding":"Record finding"}</h3><fieldset disabled={busy} style={{border:0,padding:0}}><label>Finding title<input className={styles.input} value={title} disabled={!!n} maxLength={2000} onChange={e=>setTitle(e.target.value)}/></label><label>HTTPS evidence URL<input className={styles.input} value={url} disabled={!!n} maxLength={4000} onChange={e=>setUrl(e.target.value)}/></label><label>Human relevance assessment<select className={styles.input} value={assessment} onChange={e=>setAssessment(e.target.value)}><option value="needs_review">Needs review</option><option value="relevant">Relevant</option><option value="not_relevant">Not relevant</option></select></label><p>Affected company products</p>{products.map(x=><label key={x.id} style={{display:"block"}}><input type="checkbox" checked={ids.includes(x.id)} onChange={e=>setIds(e.target.checked?[...ids,x.id]:ids.filter(id=>id!==x.id))}/> {x.brand_name} · {x.active_ingredient}</label>)}<label>Assessment rationale<textarea className={styles.input} rows={3} value={rationale} maxLength={10000} onChange={e=>setRationale(e.target.value)}/></label><div className={styles.inlineActions}><button className={styles.button} disabled={!title.trim()||!url.trim()||!rationale.trim()||(assessment==="relevant"&&!ids.length)} onClick={()=>action("pvos_record_authority_finding",{p_period_id:period.id,p_revision:period.revision,p_check_id:check.id,p_finding_id:f?.id||null,p_notice_id:f?.notice_id||n?.id||null,p_title:title,p_url:url.trim(),p_product_ids:ids,p_assessment:assessment,p_rationale:rationale},"Finding saved. Confirm the source check after assessing its findings.")}>Save finding</button><button className={styles.buttonGhost} onClick={onClose}>Cancel finding</button></div></fieldset></section>;
}
function ReviewDecision({review:r,userId,canReview,busy,action}:{review:Row,userId?:string,canReview:boolean,busy:boolean,action:Action}){
 const [reason,setReason]=useState("");const allowed=canReview&&r.assigned_to===userId&&r.sent_by!==userId;
 return <section className={styles.panel} style={{padding:20,marginTop:14}}><h2>Independent review</h2><p>{r.sent_email} → <strong>{r.assigned_email}</strong> · submitted {when(r.sent_at)}</p><p>{r.submission_note}</p><button className={styles.buttonGhost} onClick={()=>saveAuthorityJSON(r.snapshot,`PVOS-authority-submission-${r.id.slice(0,8)}.json`)}>Export submitted evidence JSON</button><div style={{marginTop:14}}>{(r.snapshot.checks||[]).map((c:Row)=><article key={c.id} style={{padding:"10px 0"}}><strong>{c.source_snapshot.name}</strong> · {c.outcome.replaceAll("_"," ")}<p style={{whiteSpace:"pre-wrap"}}>{c.notes}</p><div className={styles.muted}>{c.checked_email} · {when(c.checked_at)}</div></article>)}{(r.snapshot.findings||[]).map((f:Row)=><article key={f.id} style={{padding:"10px 0"}}><strong><a href={f.url} target="_blank" rel="noreferrer">{f.title}</a></strong> · {f.assessment.replaceAll("_"," ")}<p>{f.rationale}</p><div className={styles.muted}>Products: {f.product_ids.map((id:string)=>(r.snapshot.products_at_submission||r.snapshot.period.product_snapshot).find((p:Row)=>p.id===id)?.brand_name||id).join(", ")}{f.signal_review_id?" · sent to Signal Review":""}</div></article>)}</div><details><summary>Full submitted evidence snapshot</summary><pre style={{maxHeight:400,overflow:"auto",whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{JSON.stringify(r.snapshot,null,2)}</pre></details>{allowed?<fieldset disabled={busy} style={{border:0,padding:0,marginTop:14}}><label>Reviewer conclusion / return reason<textarea className={styles.input} rows={3} value={reason} maxLength={10000} onChange={e=>setReason(e.target.value)}/></label><div className={styles.inlineActions}><button className={styles.button} disabled={!reason.trim()} onClick={()=>action("pvos_decide_authority_review",{p_review_id:r.id,p_decision:"approved",p_reason:reason},"Monitoring approved. Both reviewers and the frozen evidence record are retained.")}>Approve monitoring record</button><button className={styles.buttonGhost} disabled={!reason.trim()} onClick={()=>action("pvos_decide_authority_review",{p_review_id:r.id,p_decision:"returned",p_reason:reason},"Returned to the monitoring owner with your reason. The submitted cycle remains retained.")}>Return to owner</button></div></fieldset>:<p className={styles.muted}>Waiting for the named reviewer: {r.assigned_email}.</p>}</section>;
}
