"use client";

import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { browserSupabase as supabase } from "@/lib/supabase-browser";
import styles from "./handover.module.css";

type Data={handover:{status:string;launched_at?:string|null;handover_sent_at?:string|null;acknowledged_at?:string|null;client_name?:string|null};prospect:{pi_name:string;institution:string;department?:string|null};site:{slug:string;url:string;domain_status:string};domain:{choice:string;preferred_domain?:string|null};payment:{status:string;amount:number|string;currency:string;paid_at?:string|null};care?:{token:string;status:string;valid_until:string;included?:boolean;coverage_end?:string|null}|null;support:{email:string;provider:string};error?:string};
function fmt(v?:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"long",year:"numeric"}).format(d)}
function money(v:number|string,c:string){const n=Number(v||0)||0;try{return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD",maximumFractionDigits:2}).format(n)}catch{return`${c||"USD"} ${n.toFixed(2)}`}}
function label(v?:string|null){return(v||"—").replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase())}

export default function HandoverPage(){
 const params=useParams<{token:string}>();const token=String(params?.token||"");const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[name,setName]=useState("");const[email,setEmail]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");const{data:res,error:e}=await supabase.rpc("sales_client_handover_public_get",{p_token:token});if(e)setError(e.message);else if(res&&typeof res==="object"&&"error" in res)setError(String((res as {error?:string}).error||"Handover unavailable."));else setData(res as Data);setLoading(false)},[token]);useEffect(()=>{void load()},[load]);
 async function acknowledge(){if(name.trim().length<2)return;setBusy(true);setError("");const{data:res,error:e}=await supabase.rpc("sales_client_handover_public_acknowledge",{p_token:token,p_name:name.trim(),p_email:email.trim()||null});setBusy(false);if(e)setError(e.message);else if(res&&typeof res==="object"&&"error" in res)setError(String((res as {error?:string}).error));else{setNotice("Handover confirmed. Thank you.");await load()}}
 if(loading)return <main className={styles.state}><section><div className={styles.logo}>LabNarrative</div><h1>Opening project handover…</h1><p>Loading the final website delivery record.</p></section></main>;
 if(!data)return <main className={styles.state}><section><div className={styles.logo}>LabNarrative</div><h1>Handover unavailable.</h1><p>{error||"This private handover link is unavailable."}</p><a href="mailto:khaled@labnarrative.com">Contact LabNarrative</a></section></main>;
 const complete=data.handover.status==="completed";
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.header}><div className={styles.logo}>LabNarrative</div><span>Client project handover</span></header>
  <section className={styles.hero}><div><p className={styles.eyebrow}>Website delivered</p><h1>Your laboratory website is live.</h1><p>{data.prospect.pi_name} · {data.prospect.institution}</p></div><a className={styles.siteButton} href={data.site.url} target="_blank" rel="noreferrer">Open live website ↗</a></section>
  <section className={styles.summary}><article><span>Launch date</span><strong>{fmt(data.handover.launched_at)}</strong></article><article><span>Project payment</span><strong>Paid in full</strong><small>{money(data.payment.amount,data.payment.currency)} final balance received {fmt(data.payment.paid_at)}</small></article><article><span>Website</span><strong>{data.site.url.replace(/^https?:\/\//,"")}</strong><small>{label(data.site.domain_status)}</small></article><article><span>Domain plan</span><strong>{label(data.domain.choice)}</strong><small>{data.domain.preferred_domain||"Final live address shown above"}</small></article></section>
  <section className={styles.delivery}><div><p className={styles.eyebrow}>Handover notes</p><h2>What happens from here</h2></div><div className={styles.steps}><article><span>01</span><h3>Your website is live</h3><p>The approved website version has been launched after final payment and delivery checks.</p></article><article><span>02</span><h3>Keep your lab information current</h3><p>When team members, publications, opportunities or contact information change, LabNarrative Care can keep the website current.</p></article><article><span>03</span><h3>Support</h3><p>For website questions or future changes, email <a href={`mailto:${data.support.email}`}>{data.support.email}</a>.</p></article></div></section>
  <section className={styles.record}><div><p className={styles.eyebrow}>Delivery record</p><h2>Confirm receipt of your website handover.</h2><p>This confirmation records that the final live website and handover information have been received. It does not add any new commercial commitment.</p></div>{complete?<div className={styles.confirmed}><span>Handover confirmed ✓</span><strong>{data.handover.client_name||"Client"}</strong><small>{fmt(data.handover.acknowledged_at)}</small></div>:<div className={styles.form}><label><span>Your name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/></label><label><span>Email (optional)</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@institution.edu"/></label><button type="button" disabled={busy||name.trim().length<2} onClick={()=>void acknowledge()}>{busy?"Confirming…":"Confirm handover received"}</button>{notice?<p className={styles.notice}>{notice}</p>:null}{error?<p className={styles.error}>{error}</p>:null}</div>}</section>
  {complete&&data.care?.token?(data.care.included?<section className={styles.care}><div><p className={styles.eyebrow}>LabNarrative Care</p><h2>Annual Care is active.</h2><p>Annual Care was included with your website project. Your managed website support is active through {fmt(data.care.coverage_end||data.care.valid_until)} with no additional Care payment and no automatic PayPal renewal.</p></div><div className={styles.careAction}><span>Included with project</span><strong>{label(data.care.status)}</strong><small>Coverage through {fmt(data.care.coverage_end||data.care.valid_until)}</small><a href={`/care/${data.care.token}`}>Open Care portal →</a></div></section>:<section className={styles.care}><div><p className={styles.eyebrow}>Optional ongoing support</p><h2>Keep your website current with LabNarrative Care.</h2><p>Your project is complete. Care is an optional recurring service for managed website health, monitoring and routine updates as your research group evolves.</p></div><div className={styles.careAction}><span>Private Care offer</span><strong>{label(data.care.status)}</strong><small>Available until {fmt(data.care.valid_until)}</small><a href={`/care/${data.care.token}`}>Explore LabNarrative Care →</a></div></section>):null}
  <footer className={styles.footer}><div><strong>LabNarrative</strong><span>Scientific websites for research groups</span></div><a href={`mailto:${data.support.email}`}>{data.support.email}</a></footer>
 </div></main>
}
