import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"https://platform.labnarrative.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
type Db=ReturnType<typeof createClient>;
type Json=Record<string,unknown>;
type Account={id:string;owner_user_id:string;account_kind:"paper"|"real";mode:"paper"|"shadow"|"live";status:string};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}})}
function n(v:unknown,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function obj(v:unknown):Json{return v&&typeof v==="object"&&!Array.isArray(v)?v as Json:{}}
function cleanPair(v:unknown){const raw=String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(!raw.endsWith("USDT")||raw.length<=4)return"";const base=raw.slice(0,-4);return /^[A-Z0-9]{1,20}$/.test(base)?`${base}/USDT`:""}
function strategyState(row:Record<string,unknown>){return String(obj(row.client_state).automationType||"")==="tradingview_strategy"}
async function ownedAccount(db:Db,userId:string,accountId:string){const{data,error}=await db.from("trader_accounts").select("id,owner_user_id,account_kind,mode,status").eq("id",accountId).eq("owner_user_id",userId).eq("status","active").maybeSingle();if(error)throw error;if(!data)throw new Error("trader_account_not_owned");return data as Account}
async function requireExchange(db:Db,account:Account){if(account.account_kind!=="real")return;const{data,error}=await db.from("trader_binance_connections").select("status").eq("account_id",account.id).maybeSingle();if(error)throw error;if(!data||data.status!=="connected")throw new Error("exchange_connection_required")}
async function maxOrder(db:Db,account:Account){if(account.account_kind!=="real")return null;const{data,error}=await db.from("trader_execution_controls").select("max_single_order").eq("account_id",account.id).maybeSingle();if(error)throw error;const value=n(data?.max_single_order);return value>0?value:null}
async function activeCount(db:Db,accountId:string,dbBotId:string){const{count,error}=await db.from("trader_trades").select("id",{count:"exact",head:true}).eq("account_id",accountId).eq("bot_id",dbBotId).eq("status","Active");if(error)throw error;return count??0}
function detail(row:Record<string,unknown>,cap:number|null){const state=obj(row.client_state);return{id:String(row.client_id),name:String(row.name),pair:String(row.pair),orderAmount:n(row.base_order),status:String(row.status),lifecycle:row.is_archived===true?"closed":"active",executionMode:String(row.execution_mode||"paper"),automationType:"tradingview_strategy",tradingViewEnabled:row.tradingview_enabled===true,maxSingleOrder:cap,createdAt:String(row.created_at),updatedAt:String(row.updated_at)} }
async function getStrategy(db:Db,account:Account,botId:string){const{data,error}=await db.from("trader_bots").select("*").eq("account_id",account.id).eq("client_id",botId).maybeSingle();if(error)throw error;if(!data||!strategyState(data as Record<string,unknown>))throw new Error("strategy_not_found");return data as Record<string,unknown>}
function validateAmount(value:unknown,current=25){const amount=Math.max(0,n(value,current));if(!(amount>0))throw new Error("invalid_order_amount");return amount}
async function validateLiveAmount(db:Db,account:Account,amount:number){const cap=await maxOrder(db,account);if(account.account_kind==="real"&&account.mode==="live"&&cap!=null&&amount>cap+1e-9)throw new Error("order_amount_exceeds_execution_limit");return cap}
async function createStrategy(db:Db,account:Account,body:Json){await requireExchange(db,account);const name=String(body.name||"").trim();if(!name)throw new Error("strategy_name_required");const pair=cleanPair(body.pair);if(!pair)throw new Error("strategy_pair_required");const orderAmount=validateAmount(body.orderAmount,25),cap=await validateLiveAmount(db,account,orderAmount),clientId=`tvs-${Date.now()}-${crypto.randomUUID().slice(0,8)}`,now=new Date().toISOString(),executionMode=account.account_kind==="real"?(account.mode==="live"?"live":"shadow"):"paper",condition={id:`tv-signal-strategy-${Date.now()}-${crypto.randomUUID().slice(0,8)}`,kind:"RSI",timeframe:"1 minute",length:14,comparator:"Greater Than",signal:1000000,aux1:0,aux2:0,aux3:0},clientState={automationType:"tradingview_strategy",strategyVersion:1,name,pair,orderAmount,positionModel:"one_long_position",entrySizing:"fixed_quote",exitSizing:"full_position",status:"Running",startCondition:"TradingView Strategy",createdAt:now,executionMode,takeProfitTargets:[{profitPct:999999,allocationPct:100}]};const{data,error}=await db.from("trader_bots").insert({account_id:account.id,client_id:clientId,name,status:"Running",pair,pairs:[pair],all_pairs:false,base_order:orderAmount,safety_order:orderAmount,max_safety_orders:0,limit_safety_orders:0,max_active_trades:1,deviation:1,step_scale:1,volume_scale:1,take_profit_pct:999999,stop_enabled:false,stop_pct:0,trailing_pct:0,max_hold_enabled:false,max_hold_hours:null,averaging_enabled:false,order_type:"Market",conditions:[condition],client_state:clientState,is_archived:false,scan_cursor:0,next_scan_at:null,execution_mode:executionMode,tradingview_enabled:false,tradingview_token:null}).select("*").single();if(error||!data)throw error||new Error("strategy_create_failed");return detail(data as Record<string,unknown>,cap)}
async function updateStrategy(db:Db,account:Account,botId:string,body:Json){const row=await getStrategy(db,account,botId);if(row.is_archived===true)throw new Error("strategy_archived");const name=String(body.name??row.name??"").trim();if(!name)throw new Error("strategy_name_required");const pair=cleanPair(body.pair??row.pair);if(!pair)throw new Error("strategy_pair_required");const orderAmount=validateAmount(body.orderAmount,n(row.base_order)),cap=await validateLiveAmount(db,account,orderAmount),active=await activeCount(db,account.id,String(row.id));if(active>0&&pair!==String(row.pair))throw new Error("strategy_pair_locked_by_active_position");const state={...obj(row.client_state),automationType:"tradingview_strategy",strategyVersion:1,name,pair,orderAmount,positionModel:"one_long_position",entrySizing:"fixed_quote",exitSizing:"full_position",startCondition:"TradingView Strategy",takeProfitTargets:[{profitPct:999999,allocationPct:100}]};const{data,error}=await db.from("trader_bots").update({name,pair,pairs:[pair],all_pairs:false,base_order:orderAmount,safety_order:orderAmount,max_safety_orders:0,limit_safety_orders:0,max_active_trades:1,take_profit_pct:999999,stop_enabled:false,stop_pct:0,trailing_pct:0,max_hold_enabled:false,max_hold_hours:null,averaging_enabled:false,order_type:"Market",client_state:state,updated_at:new Date().toISOString()}).eq("id",String(row.id)).select("*").single();if(error||!data)throw error||new Error("strategy_update_failed");return detail(data as Record<string,unknown>,cap)}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return json({error:"server_configuration_missing"},500);const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),bearer=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!bearer)return json({error:"unauthorized"},401);const{data:userData,error:userError}=await db.auth.getUser(bearer),user=userData.user;if(userError||!user)return json({error:"unauthorized"},401);try{const body=await req.json().catch(()=>({})) as Json,accountId=String(body.accountId||"").trim();if(!accountId)return json({error:"account_id_required"},400);const account=await ownedAccount(db,user.id,accountId),action=String(body.action||"strategy_detail");if(action==="strategy_detail"){const botId=String(body.botId||"").trim();if(!botId)return json({error:"strategy_id_required"},400);const row=await getStrategy(db,account,botId);return json({ok:true,strategy:detail(row,await maxOrder(db,account))})}if(action==="create_strategy"){const strategy=await createStrategy(db,account,body);return json({ok:true,botId:strategy.id,strategy})}if(action==="update_strategy"){const botId=String(body.botId||"").trim();if(!botId)return json({error:"strategy_id_required"},400);const strategy=await updateStrategy(db,account,botId,body);return json({ok:true,botId:strategy.id,strategy})}return json({error:"unknown_action"},400)}catch(error){const message=error instanceof Error?error.message:String(error);console.error("trader-tradingview-strategy-control",message);const safe=new Set(["trader_account_not_owned","exchange_connection_required","strategy_name_required","strategy_pair_required","invalid_order_amount","order_amount_exceeds_execution_limit","strategy_not_found","strategy_archived","strategy_pair_locked_by_active_position"]);return json({error:safe.has(message)?message:"tradingview_strategy_control_failed"},message==="trader_account_not_owned"?403:400)}});