"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { browserSupabase as supabase } from "@/lib/supabase-browser";
import styles from "./onboarding-admin.module.css";

type Asset={id:string;kind:string;label:string;public_url:string;original_filename:string};
type Onboarding={id:string;share_token:string;status:string;lab_name:string;preferred_title:string;pi_bio:string;homepage_changes:string;research_changes:string;publication_changes:string;general_changes:string;team_members:Record<string,unknown>[];contact_email:string;contact_phone:string;contact_address:string;official_profile_url:string;linkedin_url:string;x_url:string;other_links:Record<string,unknown>[];domain_choice:string;preferred_domain:string;domain_notes:string;logo_url:string;brand_colors:string;branding_notes:string;hiring_status:string;hiring_items:Record<string,unknown>[];final_notes:string;identity_reviewed:boolean;content_reviewed:boolean;team_reviewed:boolean;contact_reviewed:boolean;domain_reviewed:boolean;branding_reviewed:boolean;hiring_reviewed:boolean;opened_at?:string|null;last_saved_at?:string|null;submitted_at?:string|null;reviewed_at?:string|null;approved_at?:string|null;completed_at?:string|null;admin_notes:string};
type Data={prospect:{id:string;pi_name:string;institution:string;department?:string|null;email?:string|null};site?:{id:string;slug:string;domain_url?:string|null;status:string}|null;payment?:{id:string;amount:number|string;currency:string;paid_at?:string|null}|null;onboarding:Onboarding|null;progress?:number;assets?:Asset[]};
function fmt(v?:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function money(v:number|string,c:string){const n=Number(v||0)||0;try{return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD"}).format(n)}catch{return`${c} ${n.toFixed(2)}`}}
function Value({label,value}:{label:string;value:unknown}){const text=typeof value==="string"?value:value==null?"":JSON.stringify(value,null,2);return <div className={styles.field}><span>{label}</span><p className={!text?styles.empty:""}>{text||"No changes supplied"}</p></div>}
function Reviewed({ok}:{ok:boolean}){return <span className={`${styles.reviewed} ${ok?styles.ok:""}`}>{ok?"Reviewed ✓":"Not reviewed"}</span>}

export default function OnboardingAdminPage(){
 const params=useParams<{prospectId:string}>();const prospectId=String(params?.prospectId||"");const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[adminNotes,setAdminNotes]=useState("");const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!prospectId)return;setLoading(true);setError("");const{data:session}=await supabase.auth.getSession();if(!session.session){setError("Administrator sign-in is required.");setLoading(false);return}const{data:res,error:e}=await supabase.rpc("sales_client_onboarding_admin_get",{p_prospect_id:prospectId});if(e)setError(e.message);else{const next=res as Data;setData(next);setAdminNotes(next.onboarding?.admin_notes||"")}setLoading(false)},[prospectId]);useEffect(()=>{void load()},[load]);
 async function copyLink(){if(!data?.onboarding)return;await navigator.clipboard.writeText(`https://labnarrative.com/onboarding/${data.onboarding.share_token}`);setNotice("Private onboarding link copied.");setTimeout(()=>setNotice(""),1800)}
 async function regenerate(){if(!confirm("Generate a new private onboarding link? The previous link will stop working."))return;setBusy(true);const{error:e}=await supabase.rpc("sales_client_onboarding_admin_regenerate_link",{p_prospect_id:prospectId});setBusy(false);if(e)setError(e.message);else{setNotice("A new onboarding link was created.");await load()}}
 async function status(next:string){setBusy(true);setError("");const{error:e}=await supabase.rpc("sales_client_onboarding_admin_status",{p_prospect_id:prospectId,p_status:next,p_admin_notes:adminNotes||null});setBusy(false);if(e)setError(e.message);else{setNotice(`Onboarding moved to ${next.replaceAll("_"," ")}.`);await load()}}
 if(loading)return <main className={styles.page}><div className={styles.state}><section className={styles.stateBox}>Loading client onboarding…</section></div></main>;
 if(!data||error&&!data)return <main className={styles.page}><div className={styles.state}><section className={styles.stateBox}><h1>Onboarding unavailable</h1><p>{error||"Could not load this client."}</p><Link href={`/admin/sales/${prospectId}`}>Back to Sales workspace</Link></section></div></main>;
 if(!data.onboarding)return <main className={styles.page}><div className={styles.state}><section className={styles.stateBox}><p className={styles.eyebrow}>Client onboarding</p><h1>Not opened yet.</h1><p>An onboarding workspace is created automatically after the project deposit is recorded as received.</p><Link href={`/admin/sales/${prospectId}`}>Back to Sales workspace</Link></section></div></main>;
 const o=data.onboarding;const assets=data.assets||[];const siteUrl=data.site?.domain_url||(data.site?.slug?`https://${data.site.slug}.labnarrative.com`:"");
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.top}><div><Link className={styles.back} href={`/admin/sales/${prospectId}`}>← Sales workspace</Link><p className={styles.eyebrow}>Client onboarding review</p><h1>{data.prospect.pi_name}</h1><p>{data.prospect.institution}{data.prospect.department?` · ${data.prospect.department}`:""}</p></div><aside className={styles.progress}><span>Client review progress</span><strong>{data.progress||0}%</strong><div className={styles.track}><div className={styles.fill} style={{width:`${data.progress||0}%`}}/></div></aside></header>
  <div className={styles.toolbar}><button className={styles.primary} onClick={()=>void copyLink()}>Copy onboarding link</button><a href={`https://labnarrative.com/onboarding/${o.share_token}`} target="_blank" rel="noreferrer">Open client view ↗</a>{siteUrl?<a href={siteUrl} target="_blank" rel="noreferrer">Open website ↗</a>:null}{data.site?.slug?<Link href={`/admin/sites/${data.site.slug}/edit`}>Open visual editor</Link>:null}<button disabled={busy} onClick={()=>void regenerate()}>Regenerate private link</button></div>
  {notice?<p className={styles.notice}>{notice}</p>:null}{error?<p className={styles.error}>{error}</p>:null}
  <section className={styles.meta}><article><span>Status</span><strong>{o.status.replaceAll("_"," ")}</strong></article><article><span>Deposit</span><strong>{data.payment?money(data.payment.amount,data.payment.currency):"—"}</strong></article><article><span>Submitted</span><strong>{fmt(o.submitted_at)}</strong></article><article><span>Last saved</span><strong>{fmt(o.last_saved_at)}</strong></article></section>
  <div className={styles.grid}>
   <section className={styles.section}><div className={styles.sectionHead}><h2>Identity & lab</h2><Reviewed ok={o.identity_reviewed}/></div><Value label="Lab name" value={o.lab_name}/><Value label="Preferred title" value={o.preferred_title}/><Value label="PI biography / introduction" value={o.pi_bio}/></section>
   <section className={styles.section}><div className={styles.sectionHead}><h2>Contact & links</h2><Reviewed ok={o.contact_reviewed}/></div><Value label="Email" value={o.contact_email}/><Value label="Phone" value={o.contact_phone}/><Value label="Address" value={o.contact_address}/><Value label="Official profile" value={o.official_profile_url}/><Value label="LinkedIn" value={o.linkedin_url}/><Value label="X / Twitter" value={o.x_url}/><Value label="Other links" value={o.other_links}/></section>
   <section className={`${styles.section} ${styles.full}`}><div className={styles.sectionHead}><h2>Website content changes</h2><Reviewed ok={o.content_reviewed}/></div><Value label="Homepage" value={o.homepage_changes}/><Value label="Research" value={o.research_changes}/><Value label="Publications" value={o.publication_changes}/><Value label="Other website changes" value={o.general_changes}/></section>
   <section className={styles.section}><div className={styles.sectionHead}><h2>Team</h2><Reviewed ok={o.team_reviewed}/></div><div className={styles.items}>{o.team_members?.length?o.team_members.map((m,i)=><article className={styles.item} key={i}><strong>{String(m.name||"Unnamed member")}</strong><small>{String(m.role||m.title||"")}</small>{m.bio?<p>{String(m.bio)}</p>:null}{m.photo_url?<p>{String(m.photo_url)}</p>:null}</article>):<p className={styles.empty}>No team members supplied.</p>}</div></section>
   <section className={styles.section}><div className={styles.sectionHead}><h2>Domain</h2><Reviewed ok={o.domain_reviewed}/></div><Value label="Choice" value={o.domain_choice}/><Value label="Preferred domain" value={o.preferred_domain}/><Value label="Notes" value={o.domain_notes}/></section>
   <section className={styles.section}><div className={styles.sectionHead}><h2>Branding</h2><Reviewed ok={o.branding_reviewed}/></div><Value label="Logo URL" value={o.logo_url}/><Value label="Preferred colours" value={o.brand_colors}/><Value label="Design notes" value={o.branding_notes}/></section>
   <section className={styles.section}><div className={styles.sectionHead}><h2>Hiring & notes</h2><Reviewed ok={o.hiring_reviewed}/></div><Value label="Hiring status" value={o.hiring_status}/><Value label="Positions" value={o.hiring_items}/><Value label="Final notes" value={o.final_notes}/></section>
   <section className={`${styles.section} ${styles.full}`}><div className={styles.sectionHead}><h2>Uploaded images</h2><span className={styles.reviewed}>{assets.length} files</span></div>{assets.length?<div className={styles.assets}>{assets.map(a=><a className={styles.asset} href={a.public_url} target="_blank" rel="noreferrer" key={a.id}><img src={a.public_url} alt={a.label||a.original_filename}/><div><strong>{a.label||a.original_filename}</strong><small>{a.kind.replaceAll("_"," ")}</small></div></a>)}</div>:<p className={styles.empty}>No images uploaded.</p>}</section>
  </div>
  <section className={styles.reviewBox}><h2>Review decision</h2><p>Nothing here changes the website automatically. Approval means the submitted information is ready for you to apply through the visual Site Editor.</p><textarea value={adminNotes} onChange={e=>setAdminNotes(e.target.value)} placeholder="Private review notes…"/><div className={styles.reviewActions}><button disabled={busy} onClick={()=>void status("reviewing")}>Mark reviewing</button><button disabled={busy} onClick={()=>void status("changes_requested")}>Request changes</button><button className={styles.approve} disabled={busy} onClick={()=>void status("approved")}>Approve onboarding</button><button disabled={busy} onClick={()=>void status("completed")}>Mark onboarding complete</button></div></section>
 </div></main>
}
