import { createClient } from "@supabase/supabase-js";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import styles from "../proposal.module.css";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!;

type Prospect={company_name:string;slug:string;demo_status:string;demo_config:Record<string,unknown>|null;industry:string|null;city:string|null;country:string|null};
type Conversion={status:string;path:string;title:string;objective:string;pilotEvidence:string;clientFeedback:string;productionScope:string;modules:string;rolesPermissions:string;integrations:string;migration:string;implementationPhases:string;timeline:string;recommendedPrice:number;subscriptionSar:number;exclusions:string;groupExpansion:string;nextStep:string};
function obj(v:unknown):Record<string,unknown>{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function str(v:unknown){return typeof v==="string"?v:"";}
function num(v:unknown,f=0){return typeof v==="number"&&Number.isFinite(v)?v:f;}
function lines(v:string){return v.split(/\n+/).map(x=>x.trim()).filter(Boolean);}
function read(config:Record<string,unknown>|null):Conversion|null{const c=obj(config?.fullSystemConversion);const status=str(c.status);if(status!=="approved"&&status!=="sent")return null;return{status,path:str(c.path)||"full_system",title:str(c.title),objective:str(c.objective),pilotEvidence:str(c.pilotEvidence),clientFeedback:str(c.clientFeedback),productionScope:str(c.productionScope),modules:str(c.modules),rolesPermissions:str(c.rolesPermissions),integrations:str(c.integrations),migration:str(c.migration),implementationPhases:str(c.implementationPhases),timeline:str(c.timeline),recommendedPrice:num(c.recommendedPrice),subscriptionSar:num(c.subscriptionSar),exclusions:str(c.exclusions),groupExpansion:str(c.groupExpansion),nextStep:str(c.nextStep)};}
async function getProspect(slug:string):Promise<{prospect:Prospect;conversion:Conversion}|null>{const supabase=createClient(supabaseUrl,supabaseKey,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await supabase.from("systems_outreach_prospects").select("company_name,slug,demo_status,demo_config,industry,city,country").eq("slug",slug).maybeSingle();if(error||!data?.demo_config)return null;const conversion=read(data.demo_config as Record<string,unknown>);return conversion?{prospect:data as Prospect,conversion}:null;}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const result=await getProspect(slug);return{title:result?`Private Production Proposal — ${result.prospect.company_name} | LabNarrative Systems`:"Private Production Proposal | LabNarrative Systems",description:result?`A private LabNarrative Systems production proposal for ${result.prospect.company_name}.`:"Private LabNarrative Systems production proposal.",robots:{index:false,follow:false,nocache:true}};}

export default async function FullSystemProposalPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const result=await getProspect(slug);if(!result)notFound();const{prospect,conversion}=result;const location=[prospect.city,prospect.country].filter(Boolean).join(" · ");const pathLabel=conversion.path==="group_platform"?"Group Platform":"Full Operational System";return <main className={styles.page}>
<section className={styles.hero}><div className={styles.heroTop}><div className={styles.brand}><span>Lab</span>Narrative <b>Systems</b></div><div className={styles.private}>Private Production Proposal</div></div><div className={styles.heroGrid}><div><p className={styles.eyebrow}>Pilot validated → production</p><h1>{conversion.title||`${prospect.company_name} — ${pathLabel}`}</h1><p className={styles.lead}>{conversion.objective}</p><div className={styles.meta}>{prospect.industry?<span>{prospect.industry}</span>:null}{location?<span>{location}</span>:null}<span>{pathLabel}</span><span>Prepared by LabNarrative Systems</span></div></div><div className={styles.priceCard}><span>Production implementation</span><strong>SAR {conversion.recommendedPrice.toLocaleString("en-US")}</strong><small>Final scope and commercial terms follow the approved production scope.</small></div></div></section>
<section className={styles.flow}><span>Validated path</span><b>Pilot evidence</b><i>→</i><b>Production scope</b><i>→</i><b>Implementation</b><i>→</i><b>Go-live & support</b></section>
<section className={styles.twoCol}><article className={styles.card}><p className={styles.kicker}>What the Pilot proved</p><h2>Evidence before expansion</h2>{conversion.pilotEvidence?<ul>{lines(conversion.pilotEvidence).map(item=><li key={item}>{item}</li>)}</ul>:<p className={styles.note}>Pilot evidence was reviewed during the production conversion process.</p>}{conversion.clientFeedback?<p className={styles.note}><strong>Client feedback:</strong> {conversion.clientFeedback}</p>:null}</article><article className={styles.card}><p className={styles.kicker}>Production scope</p><h2>{pathLabel}</h2><p className={styles.body}>{conversion.productionScope}</p><p className={styles.note}>{conversion.timeline}</p></article></section>
<section className={styles.section}><div className={styles.sectionTitle}><span>01</span><div><p>Production modules</p><h2>What moves into the live system</h2></div></div><div className={styles.listGrid}>{lines(conversion.modules).map(item=><div className={styles.listItem} key={item}><b>✓</b><span>{item}</span></div>)}</div></section>
<section className={styles.twoCol}><article className={styles.card}><p className={styles.kicker}>Roles & permissions</p><h2>Controlled access</h2><ul>{lines(conversion.rolesPermissions).map(item=><li key={item}>{item}</li>)}</ul></article><article className={styles.card}><p className={styles.kicker}>Existing systems</p><h2>Integrations</h2><p className={styles.body}>{conversion.integrations}</p><p className={styles.note}>{conversion.migration}</p></article></section>
<section className={styles.section}><div className={styles.sectionTitle}><span>02</span><div><p>Implementation</p><h2>Controlled production rollout</h2></div></div><div className={styles.listGrid}>{lines(conversion.implementationPhases).map(item=><div className={styles.listItem} key={item}><b>◆</b><span>{item}</span></div>)}</div></section>
<section className={styles.twoCol}><article className={`${styles.card} ${styles.boundaryCard}`}><p className={styles.kicker}>Separately scoped</p><h2>Commercial boundaries</h2><ul>{lines(conversion.exclusions).map(item=><li key={item}>{item}</li>)}</ul></article><article className={styles.card}><p className={styles.kicker}>Production operation</p><h2>SAR {conversion.subscriptionSar.toLocaleString("en-US")} / month</h2><p className={styles.note}>Recurring production service covers the agreed hosting, operation, maintenance, support and ordinary AI usage for the approved production scope. Material scope changes are priced separately.</p></article></section>
<section className={styles.expansion}><div><p className={styles.kicker}>Future expansion</p><h2>Expand only after the core production system is stable</h2><p>{conversion.groupExpansion}</p></div><div className={styles.steps}><span>01 <b>Pilot</b></span><span>02 <b>Production</b></span><span>03 <b>Integrations</b></span><span>04 <b>Group expansion</b></span></div></section>
<section className={styles.next}><p>Recommended next step</p><h2>{conversion.nextStep}</h2><div className={styles.contact}><strong>Dr. Khaled Azzahrani</strong><span>Founder · LabNarrative</span><span>khaled@labnarrative.com · +966-570575261</span></div></section>
<footer><div className={styles.brand}><span>Lab</span>Narrative <b>Systems</b></div><p>This private proposal reflects the approved production conversion scope. Final technical implementation details, third-party dependencies and contractual terms are confirmed before production kickoff.</p></footer>
</main>;}
