import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const EXPECTED_GATEWAY_ORIGIN = "https://trader-gateway.labnarrative.com";
const PUBLIC_BINANCE = "https://data-api.binance.vision";
const cors = {
  "Access-Control-Allow-Origin": "https://platform.labnarrative.com",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

type Json = Record<string, unknown>;
type Db = ReturnType<typeof createClient>;
type Creds = { apiKey: string; apiSecret: string };
type Trade = {
  id: string;
  account_id: string;
  bot_id: string;
  client_id: string;
  pair: string;
  status: string;
  average_price: number|string;
  quantity: number|string;
  invested: number|string;
  total_invested: number|string;
  realized_pnl: number|string|null;
  last_price: number|string|null;
  close_reason: string|null;
  client_state: Json;
  execution_mode: string;
};
type Rule = { symbol:string; baseAsset:string; minQty:number; stepSize:number; minNotional:number };
type Accounting = { buyQty:number; buyCost:number; sellDebit:number; sellProceeds:number; residual:number };

let signingKeyCache: CryptoKey | null = null;
const n = (value:unknown, fallback=0) => { const x=Number(value); return Number.isFinite(x)?x:fallback; };
const obj = (value:unknown):Json => value&&typeof value==="object"&&!Array.isArray(value)?value as Json:{};
const clean = (error:unknown) => error instanceof Error?error.message:String(error||"unknown_error");
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}})}
function floorStep(value:number,step:number){if(!(step>0))return value;const p=Math.max(0,Math.min(12,(String(step).split(".")[1]??"").replace(/0+$/,"").length));return Number((Math.floor((value+1e-14)/step)*step).toFixed(p))}
function clientId(prefix:string){return `${prefix}-${Date.now().toString(36)}-${crypto.randomUUID().replace(/-/g,"").slice(0,10)}`.slice(0,36)}
function nonce(){const a=new Uint8Array(24);crypto.getRandomValues(a);return Array.from(a).map(x=>x.toString(16).padStart(2,"0")).join("")}
function pemBytes(pem:string){const b=pem.replace(/-----BEGIN [^-]+-----/g,"").replace(/-----END [^-]+-----/g,"").replace(/\s+/g,"");const s=atob(b),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
function b64(buffer:ArrayBuffer){let s="";for(const x of new Uint8Array(buffer))s+=String.fromCharCode(x);return btoa(s)}
async function hmac(secret:string,message:string){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const r=await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(message));return Array.from(new Uint8Array(r)).map(x=>x.toString(16).padStart(2,"0")).join("")}

async function gatewayConfig(db:Db){const{data,error}=await db.from("trader_gateway_config").select("base_url,status").eq("name","binance").single();if(error||!data)throw new Error("gateway_not_configured");return data as{base_url:string|null;status:string}}
async function signingKey(db:Db){if(signingKeyCache)return signingKeyCache;const{data,error}=await db.rpc("trader_gateway_read_signing_private_key");if(error||!data)throw new Error("gateway_signing_key_not_configured");signingKeyCache=await crypto.subtle.importKey("pkcs8",pemBytes(String(data)),{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);return signingKeyCache}
async function relay(db:Db,payload:Json){const cfg=await gatewayConfig(db);if(cfg.status!=="ready"||!cfg.base_url)throw new Error("gateway_not_ready");const origin=new URL(cfg.base_url).origin;if(origin!==EXPECTED_GATEWAY_ORIGIN)throw new Error("gateway_origin_not_allowed");const raw=JSON.stringify(payload),timestamp=Date.now(),nn=nonce(),key=await signingKey(db),sig=b64(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,new TextEncoder().encode(`${timestamp}\n${nn}\n${raw}`)));const response=await fetch(`${origin}/relay`,{method:"POST",headers:{"content-type":"application/json","x-ln-timestamp":String(timestamp),"x-ln-nonce":nn,"x-ln-signature":sig},body:raw,signal:AbortSignal.timeout(12000)}),envelope=await response.json().catch(()=>({})) as Json;if(!response.ok)throw new Error(`gateway_${response.status}:${String(envelope.error||"relay_failed")}`);const upstream=n(envelope.upstreamStatus),rawBody=String(envelope.upstreamBody||"");let body:Json={};try{body=rawBody?JSON.parse(rawBody):{}}catch{throw new Error("binance_invalid_json")}if(upstream<200||upstream>=300)throw new Error(`binance_${String(body.code??upstream)}:${String(body.msg??"request_failed")}`);return body}
async function credentials(db:Db,accountId:string){const{data,error}=await db.rpc("trader_binance_read_secret",{p_account_id:accountId});if(error||!data)throw new Error("credential_not_found");const c=JSON.parse(String(data)) as{apiKey?:string;apiSecret?:string};if(!c.apiKey||!c.apiSecret)throw new Error("credential_not_found");return{apiKey:c.apiKey,apiSecret:c.apiSecret}}
async function signedAt(db:Db,c:Creds,method:"GET"|"POST"|"DELETE",path:string,params:Record<string,string|number|boolean>,timestamp:number){const q=new URLSearchParams();for(const[k,v]of Object.entries(params))q.set(k,String(v));q.set("timestamp",String(timestamp));q.set("recvWindow","10000");q.set("signature",await hmac(c.apiSecret,q.toString()));return relay(db,{requestId:crypto.randomUUID(),method,path,query:q.toString(),apiKey:c.apiKey})}
async function signed(db:Db,c:Creds,method:"GET"|"POST"|"DELETE",path:string,params:Record<string,string|number|boolean>={}){try{return await signedAt(db,c,method,path,params,Date.now())}catch(error){if(!clean(error).includes("-1021"))throw error;const t=await relay(db,{requestId:crypto.randomUUID(),method:"GET",path:"/api/v3/time",query:""});return signedAt(db,c,method,path,params,n(t.serverTime,Date.now()))}}

async function ownedTrade(db:Db,userId:string,accountId:string,tradeId:string){
  const{data:account,error:accountError}=await db.from("trader_accounts").select("id,mode,status").eq("id",accountId).eq("owner_user_id",userId).eq("account_kind","real").eq("status","active").maybeSingle();if(accountError)throw accountError;if(!account)throw new Error("real_account_required");
  const{data:controls,error:controlsError}=await db.from("trader_execution_controls").select("global_live_enabled,kill_switch").eq("account_id",accountId).single();if(controlsError||!controls)throw new Error("execution_controls_missing");if(account.mode!=="live"||controls.global_live_enabled!==true||controls.kill_switch!==false)throw new Error("live_trading_not_enabled");
  const{data:connection,error:connectionError}=await db.from("trader_binance_connections").select("status,environment,permission_read,permission_trade,permission_withdraw,permission_internal_transfer,ip_restricted").eq("account_id",accountId).single();if(connectionError||!connection)throw new Error("binance_not_connected");if(connection.status!=="connected"||connection.environment!=="mainnet"||!connection.permission_read||!connection.permission_trade)throw new Error("binance_trade_permission_required");if(connection.permission_withdraw||connection.permission_internal_transfer||connection.ip_restricted!==true)throw new Error("binance_connection_not_safe");
  const{data:trade,error:tradeError}=await db.from("trader_trades").select("id,account_id,bot_id,client_id,pair,status,average_price,quantity,invested,total_invested,realized_pnl,last_price,close_reason,client_state,execution_mode").eq("account_id",accountId).eq("client_id",tradeId).maybeSingle();if(tradeError)throw tradeError;if(!trade)throw new Error("trade_not_found");if(trade.execution_mode!=="live")throw new Error("trade_not_live");return trade as Trade;
}
async function ruleFor(pair:string){const symbol=pair.replace("/",""),response=await fetch(`${PUBLIC_BINANCE}/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`exchange_info_${response.status}`);const payload=await response.json() as{symbols?:Json[]},row=payload.symbols?.[0];if(!row||row.status!=="TRADING")throw new Error("spot_symbol_not_tradeable");const filters=(row.filters??[]) as Json[],find=(type:string)=>filters.find(x=>x.filterType===type),lot=find("LOT_SIZE"),notional=find("NOTIONAL")??find("MIN_NOTIONAL");return{symbol,baseAsset:String(row.baseAsset),minQty:n(lot?.minQty),stepSize:n(lot?.stepSize),minNotional:n(notional?.minNotional)} as Rule}
async function acquire(db:Db,accountId:string){const id=crypto.randomUUID();for(let i=0;i<45;i++){const{data,error}=await db.rpc("trader_begin_command",{p_account_id:accountId,p_lock_id:id,p_lease_seconds:45});if(error)throw error;if(data===true)return id;await new Promise(r=>setTimeout(r,350))}throw new Error("account_busy")}
async function release(db:Db,accountId:string,id:string){try{await db.rpc("trader_release_account",{p_account_id:accountId,p_worker_id:id})}catch{}}
async function freeBalance(db:Db,c:Creds,asset:string){const account=await signed(db,c,"GET","/api/v3/account",{omitZeroBalances:true}),balances=Array.isArray(account.balances)?account.balances as Json[]:[];return n(balances.find(x=>String(x.asset||"")===asset)?.free)}
async function marketPrice(symbol:string){const response=await fetch(`${PUBLIC_BINANCE}/api/v3/ticker/price?symbol=${encodeURIComponent(symbol)}`,{signal:AbortSignal.timeout(7000)});if(!response.ok)return 0;return n((await response.json() as Json).price)}

async function cancelDcaOrders(db:Db,trade:Trade,c:Creds,rule:Rule){const{data,error}=await db.from("trader_orders").select("id,client_order_id,exchange_order_id,status").eq("trade_id",trade.id).eq("exchange","binance").eq("side","BUY").in("status",["OPEN","PENDING","NEW","PARTIALLY_FILLED"]);if(error)throw error;for(const row of data??[]){const xid=String(row.exchange_order_id||"");let remote:Json|null=null;if(xid)try{remote=await signed(db,c,"GET","/api/v3/order",{symbol:rule.symbol,orderId:xid})}catch{}const status=String(remote?.status||row.status||"").toUpperCase();if(status==="FILLED"){await db.from("trader_orders").update({status:"FILLED",reserved_quote:0,updated_at:new Date().toISOString()}).eq("id",row.id);continue}if(xid&&["NEW","PARTIALLY_FILLED"].includes(status)){try{const canceled=await signed(db,c,"DELETE","/api/v3/order",{symbol:rule.symbol,orderId:xid});await db.from("trader_orders").update({status:String(canceled.status||"CANCELED"),reserved_quote:0,cancelled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",row.id);continue}catch{}}if(xid)try{remote=await signed(db,c,"GET","/api/v3/order",{symbol:rule.symbol,orderId:xid})}catch{}const finalStatus=String(remote?.status||status||"").toUpperCase();if(["NEW","PARTIALLY_FILLED","PENDING","OPEN"].includes(finalStatus))throw new Error("dca_cancel_pending");await db.from("trader_orders").update({status:finalStatus||"CANCELED",reserved_quote:0,updated_at:new Date().toISOString()}).eq("id",row.id)}}

async function reconcileTrade(db:Db,trade:Trade,c:Creds,rule:Rule):Promise<Accounting>{const[{data:orders,error:orderError},{data:events,error:eventError}]=await Promise.all([db.from("trader_orders").select("exchange_order_id").eq("trade_id",trade.id).eq("exchange","binance"),db.from("trader_broker_events").select("exchange_order_id").eq("trade_id",trade.id).not("exchange_order_id","is",null)]);if(orderError)throw orderError;if(eventError)throw eventError;const ids=new Set<string>();for(const x of orders??[]){const id=String(x.exchange_order_id||"");if(id)ids.add(id)}for(const x of events??[]){const id=String(x.exchange_order_id||"");if(id)ids.add(id)}const seen=new Set<string>();let buyQty=0,buyCost=0,sellDebit=0,sellProceeds=0;for(const id of ids){let rows:unknown;try{rows=await signed(db,c,"GET","/api/v3/myTrades",{symbol:rule.symbol,orderId:id,limit:100})}catch{continue}for(const x of Array.isArray(rows)?rows as Json[]:[]){const key=`${String(x.orderId||id)}:${String(x.id||"")}`;if(seen.has(key))continue;seen.add(key);const qty=n(x.qty),quote=n(x.quoteQty,n(x.price)*qty),commission=n(x.commission),asset=String(x.commissionAsset||"");if(x.isBuyer===true){buyQty+=qty-(asset===rule.baseAsset?commission:0);buyCost+=quote+(asset==="USDT"?commission:0)}else{sellDebit+=qty+(asset===rule.baseAsset?commission:0);sellProceeds+=quote-(asset==="USDT"?commission:0)}}}return{buyQty:Math.max(0,buyQty),buyCost:Math.max(0,buyCost),sellDebit:Math.max(0,sellDebit),sellProceeds,residual:Math.max(0,buyQty-sellDebit)}}
async function brokerEvent(db:Db,trade:Trade,eventType:string,payload:Json,cid:string|null=null,xid:string|null=null,orderId:string|null=null){await db.from("trader_broker_events").insert({account_id:trade.account_id,bot_id:trade.bot_id,trade_id:trade.id,order_id:orderId,mode:"live",event_type:eventType,pair:trade.pair,client_order_id:cid,exchange_order_id:xid,payload})}
async function persistSellFills(db:Db,trade:Trade,orderId:string,response:Json){const fills=Array.isArray(response.fills)?response.fills as Json[]:[];if(!fills.length)return;const now=new Date().toISOString();await db.from("trader_fills").insert(fills.map(fill=>({account_id:trade.account_id,bot_id:trade.bot_id,trade_id:trade.id,order_id:orderId,pair:trade.pair,side:"SELL",kind:"Manual Close",price:n(fill.price),quantity:n(fill.qty),quote_amount:n(fill.price)*n(fill.qty),fee_asset:String(fill.commissionAsset||"")||null,fee_amount:n(fill.commission),exchange_trade_id:String(fill.tradeId||"")||null,filled_at:now,metadata:{exchange:"binance",manualClose:true}})))}
function residualTolerance(rule:Rule){return Math.max(1e-12,(rule.stepSize||0)*1e-6)}
function minimumError(rule:Rule,value:number,qty:number){return `live_exit_below_exchange_minimum:${Math.max(0,rule.minNotional)}:${Math.max(0,value)}:${Math.max(0,qty)}:${Math.max(0,rule.minQty)}`}
function assertSellableResidual(accounting:Accounting,free:number,price:number,rule:Rule){if(accounting.residual<=residualTolerance(rule))return 0;const qty=floorStep(Math.min(accounting.residual,free),rule.stepSize);if(!(qty>0)){if(free+residualTolerance(rule)<accounting.residual)throw new Error(`live_exit_insufficient_free_balance:${accounting.residual}:${free}`);throw new Error(minimumError(rule,0,qty))}const value=price*qty;if((rule.minQty&&qty<rule.minQty-1e-15)||(rule.minNotional&&value<rule.minNotional-1e-9))throw new Error(minimumError(rule,value,qty));return qty}

async function closeTrade(db:Db,trade:Trade,finish:boolean){if(!["Active","Closed"].includes(trade.status))throw new Error("trade_not_closable");if(trade.status==="Closed"&&!finish)throw new Error("trade_already_closed");const rule=await ruleFor(trade.pair),c=await credentials(db,trade.account_id),price=await marketPrice(rule.symbol);let accounting=await reconcileTrade(db,trade,c,rule),free=await freeBalance(db,c,rule.baseAsset);if(trade.status==="Active")assertSellableResidual(accounting,free,price,rule);
  if(trade.status==="Active"){const{data,error}=await db.from("trader_trades").update({status:"Closing",updated_at:new Date().toISOString()}).eq("id",trade.id).eq("status","Active").select("id").maybeSingle();if(error)throw error;if(!data)throw new Error("trade_not_active")}
  try{
    await cancelDcaOrders(db,trade,c,rule);
    accounting=await reconcileTrade(db,trade,c,rule);free=await freeBalance(db,c,rule.baseAsset);
    let qty=assertSellableResidual(accounting,free,price,rule);
    if(qty>0){const ci=clientId(`LNC${trade.id.slice(0,5)}`),now=new Date().toISOString(),{data:ledger,error:ledgerError}=await db.from("trader_orders").insert({account_id:trade.account_id,bot_id:trade.bot_id,trade_id:trade.id,client_order_id:ci,pair:trade.pair,kind:finish?"residual_exit":"manual_exit",side:"SELL",order_type:"MARKET",status:"PENDING",requested_quote:0,requested_qty:qty,reserved_quote:0,exchange:"binance",opened_at:now,metadata:{source:"manual_live_reconciled_close_v2"}}).select("id").single();if(ledgerError||!ledger)throw ledgerError||new Error("live_exit_ledger_failed");let response:Json|null=null;try{response=await signed(db,c,"POST","/api/v3/order",{symbol:rule.symbol,side:"SELL",type:"MARKET",quantity:qty,newClientOrderId:ci,newOrderRespType:"FULL"})}catch(error){const message=clean(error);if(message.includes("timeout")||message.startsWith("gateway_500")){for(let i=0;i<4&&!response;i++){await new Promise(x=>setTimeout(x,450*(i+1)));try{response=await signed(db,c,"GET","/api/v3/order",{symbol:rule.symbol,origClientOrderId:ci})}catch{}}}if(!response){await db.from("trader_orders").update({status:"PENDING",metadata:{source:"manual_live_reconciled_close_v2",placement_uncertain:true,error:message},updated_at:new Date().toISOString()}).eq("id",ledger.id);throw new Error("close_order_pending_reconciliation")}}
      const status=String(response.status||""),executed=n(response.executedQty),gross=n(response.cummulativeQuoteQty),average=executed>0?gross/executed:price,xid=String(response.orderId||"");if(!(executed>0))throw new Error("close_order_not_filled");await db.from("trader_orders").update({status:status||"FILLED",price:average,filled_qty:executed,filled_quote:gross,average_fill_price:average,exchange_order_id:xid||null,filled_at:status==="FILLED"?now:null,updated_at:now}).eq("id",ledger.id);await persistSellFills(db,trade,String(ledger.id),response);await brokerEvent(db,trade,finish?"residual_trade_closed":"manual_trade_closed_reconciled",{requestedQty:qty,executedQty:executed,reconciledResidualBefore:accounting.residual,freeBaseBefore:free},ci,xid,String(ledger.id));
      accounting=await reconcileTrade(db,trade,c,rule);free=await freeBalance(db,c,rule.baseAsset);const afterPrice=await marketPrice(rule.symbol);if(accounting.residual>residualTolerance(rule))assertSellableResidual(accounting,free,afterPrice||price,rule);
    }
    accounting=await reconcileTrade(db,trade,c,rule);free=await freeBalance(db,c,rule.baseAsset);const dust=accounting.residual;if(dust>residualTolerance(rule)){const afterPrice=await marketPrice(rule.symbol);assertSellableResidual(accounting,free,afterPrice||price,rule);throw new Error("close_residual_still_open")}
    const pnl=accounting.sellProceeds-accounting.buyCost,state={...obj(trade.client_state),reconciledClose:true,reconciledCloseAt:new Date().toISOString(),reconciledBuyQty:accounting.buyQty,reconciledSellQty:accounting.sellDebit,residualDustQty:dust,residualCloseSuspected:false};delete state.stopLossTriggeredAt;const{error:updateError}=await db.from("trader_trades").update({status:"Closed",quantity:0,invested:0,total_invested:accounting.buyCost,average_price:accounting.buyQty>0?accounting.buyCost/accounting.buyQty:n(trade.average_price),realized_pnl:pnl,close_reason:finish?"Manual close (residual completed)":"Manual close",closed_at:new Date().toISOString(),client_state:state,updated_at:new Date().toISOString()}).eq("id",trade.id);if(updateError)throw updateError;return{soldQty:qty,totalInvested:accounting.buyCost,totalPnl:pnl,residualDustQty:dust,reconciled:true}
  }catch(error){if(trade.status==="Active")await db.from("trader_trades").update({status:"Active",updated_at:new Date().toISOString()}).eq("id",trade.id).eq("status","Closing");throw error}
}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!service)return json({error:"server_configuration_missing"},500);const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({error:"unauthorized"},401);const{data:userData,error:userError}=await db.auth.getUser(token);if(userError||!userData.user)return json({error:"unauthorized"},401);let accountId="",lockId="";try{const body=await req.json().catch(()=>({})) as Json,action=String(body.action||"");accountId=String(body.accountId||"");const tradeId=String(body.tradeId||"");if(!accountId)throw new Error("account_id_required");if(!tradeId)throw new Error("trade_id_required");if(!["close_trade","finish_close"].includes(action))throw new Error("unknown_action");await ownedTrade(db,userData.user.id,accountId,tradeId);lockId=await acquire(db,accountId);const trade=await ownedTrade(db,userData.user.id,accountId,tradeId);return json({ok:true,action,result:await closeTrade(db,trade,action==="finish_close")})}catch(error){const message=clean(error);console.error("trader-live-close-control-v2",message);const safe=["real_account_required","execution_controls_missing","binance_not_connected","binance_trade_permission_required","binance_connection_not_safe","live_trading_not_enabled","trade_not_found","trade_not_live","trade_not_active","trade_not_closable","trade_already_closed","account_id_required","trade_id_required","account_busy","spot_symbol_not_tradeable","close_order_pending_reconciliation","close_order_not_filled","close_residual_still_open","dca_cancel_pending","unknown_action"].includes(message)||message.startsWith("live_exit_below_exchange_minimum:")||message.startsWith("live_exit_insufficient_free_balance:")||message.startsWith("binance_")||message.startsWith("gateway_")?message:"live_close_control_failed";return json({error:safe},safe==="real_account_required"?403:400)}finally{if(accountId&&lockId)await release(db,accountId,lockId)}});
