"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { browserSupabase as supabase } from "@/lib/supabase-browser";
import styles from "./launch.module.css";

type Launch={id:string;status:string;handover_token:string;handover_link_enabled:boolean;approved_site_updated_at:string;domain_ready:boolean;https_ready:boolean;website_health_ready:boolean;mobile_reviewed:boolean;contact_links_reviewed:boolean;analytics_ready:boolean;branding_reviewed:boolean;launch_notes:string;launched_at?:string|null;handover_sent_at?:string|null;handover_view_count:number;handover_acknowledged_at?:string|null;handover_client_name?:string|null};
type Data={prospect:{id:string;pi_name:string;institution:string;department?:string|null};site?:{id:string;slug:string;status:string;updated_at:string;domain_status:string;domain_url?:string|null}|null;onboarding?:{status:string;domain_choice:string;preferred_domain?:string|null}|null;final_review?:{version:number;status:string;approved_at?:string|null;site_updated_at:string}|null;balance_payment?:{status:string;amount:number|string;currency:string;paid_at?:string|null}|null;launch:Launch|null;checks_complete?:boolean;system_ready?:boolean;ready_to_launch?:boolean};
type Checks=Pick<Launch,"domain_ready"|"https_ready"|"website_health_ready"|"mobile_reviewed"|"contact_links_reviewed"|"analytics_ready"|"branding_reviewed">;
const empty:Checks={domain_ready:false,https_ready:false,website_health_ready:false,mobile_reviewed:false,contact_links_reviewed:false,analytics_ready:false,branding_reviewed:false};
function label(v?:string|null){return(v||"—").replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase())}
function fmt(v?:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function money(v:number|string,c:string){const n=Number(v||0)||0;try{return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD",maximumFractionDigits:2}).format(n)}catch{return`${c} ${n.toFixed(2)}`}}

export default function LaunchWorkspace(){
 const params=useParams<{prospectId:string}>();const prospectId=String(params?.prospectId||"");
 const[data,setData]=useState<Data|null>(null);const[checks,setChecks]=useState<Checks>(empty);const[notes,setNotes]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[health,setHealth]=useState<{ok:boolean;status:number;error?:string}|null>(null);
 const load=useCallback(async()=>{if(!prospectId)return;setLoading(true);setError("");const{data:res,error:e}=await supabase.rpc("sales_client_launch_admin_get",{p_prospect_id:prospectId});if(e)setError(e.message);else{const next=res as Data;setData(next);if(next.launch){setChecks({domain_ready:next.launch.domain_ready,https_ready:next.launch.https_ready,website_health_ready:next.launch.website_health_ready,mobile_reviewed:next.launch.mobile_reviewed,contact_links_reviewed:next.launch.contact_links_reviewed,analytics_ready:next.launch.analytics_ready,branding_reviewed:next.launch.branding_reviewed});setNotes(next.launch.launch_notes||"")}}setLoading(false)},[prospectId]);
 useEffect(()=>{void load()},[load]);
 const siteUrl=useMemo(()=>data?.site?.domain_url||(data?.site?.slug?`https://${data.site.slug}.labnarrative.com`:""),[data]);
 async function save(){setBusy(true);setError("");const{error:e}=await supabase.rpc("sales_client_launch_admin_save",{p_prospect_id:prospectId,p_domain_ready:checks.domain_ready,p_https_ready:checks.https_ready,p_website_health_ready:checks.website_health_ready,p_mobile_reviewed:checks.mobile_reviewed,p_contact_links_reviewed:checks.contact_links_reviewed,p_analytics_ready:checks.analytics_ready,p_branding_reviewed:checks.branding_reviewed,p_launch_notes:notes||null});setBusy(false);if(e)setError(e.message);else{setNotice("Launch checklist saved.");await load()}}
 async function runHealth(){if(!siteUrl)return;setBusy(true);setHealth(null);try{const r=await fetch("/api/admin/site-health",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targets:[{id:"launch",url:siteUrl}]})});const j=await r.json();const result=j?.results?.[0];setHealth(result||{ok:false,status:0,error:"No health result"});if(result?.ok)setChecks(v=>({...v,website_health_ready:true}))}catch(e){setHealth({ok:false,status:0,error:e instanceof Error?e.message:"Health check failed"})}finally{setBusy(false)}}
 async function launch(){if(!confirm("Launch this client website now? This records the final launch and opens the client handover link."))return;setBusy(true);setError("");const{data:res,error:e}=await supabase.rpc("sales_client_launch_admin_launch",{p_prospect_id:prospectId});setBusy(false);if(e)setError(e.message);else{setNotice("Website launched. Client handover is ready.");await load();const url=(res as {site_url?:string})?.site_url;if(url)window.open(url,"_blank","noopener,noreferrer")}}
 async function copyHandover(){if(!data?.launch)return;await navigator.clipboard.writeText(`https://labnarrative.com/handover/${data.launch.handover_token}`);setNotice("Handover link copied.")}
 async function markSent(){setBusy(true);const{error:e}=await supabase.rpc("sales_client_launch_admin_mark_handover_sent",{p_prospect_id:prospectId});setBusy(false);if(e)setError(e.message);else{setNotice("Handover marked as sent.");await load()}}
 if(loading)return <main className={styles.page}><div className={styles.state}>Loading launch workspace…</div></main>;
 if(!data)return <main className={styles.page}><div className={styles.state}><h1>Launch workspace unavailable</h1><p>{error||"Could not load this client."}</p></div></main>;
 if(!data.launch)return <main className={styles.page}><div className={styles.state}><p className={styles.eyebrow}>Client delivery</p><h1>Launch is not open yet.</h1><p>The launch workspace opens automatically after the final website is approved and the remaining balance is paid.</p><Link href={`/admin/sales/${prospectId}`}>Back to Sales workspace</Link></div></main>;
 const l=data.launch;const launched=["launched","handover_sent","completed"].includes(l.status);const ready=Boolean(data.ready_to_launch);
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.hero}><div><Link href={`/admin/sales/${prospectId}`} className={styles.back}>← Sales workspace</Link><p className={styles.eyebrow}>Launch workspace</p><h1>{data.prospect.pi_name}</h1><p>{data.prospect.institution}{data.prospect.department?` · ${data.prospect.department}`:""}</p></div><div className={styles.statusCard}><span>Status</span><strong>{label(l.status)}</strong><small>{launched?`Launched ${fmt(l.launched_at)}`:ready?"All launch gates passed":"Complete the gates below"}</small></div></header>
  {notice?<p className={styles.notice}>{notice}</p>:null}{error?<p className={styles.error}>{error}</p>:null}
  <section className={styles.system}><h2>System gates</h2><div className={styles.systemGrid}><article className={data.final_review?.status==="approved"?styles.pass:""}><span>Client approval</span><strong>{data.final_review?.status==="approved"?`Approved · v${data.final_review.version}`:label(data.final_review?.status)}</strong><small>{fmt(data.final_review?.approved_at)}</small></article><article className={data.balance_payment?.status==="paid"?styles.pass:""}><span>Final payment</span><strong>{data.balance_payment?`${money(data.balance_payment.amount,data.balance_payment.currency)} · ${label(data.balance_payment.status)}`:"Not available"}</strong><small>{fmt(data.balance_payment?.paid_at)}</small></article><article className={data.onboarding?.status==="completed"?styles.pass:""}><span>Onboarding</span><strong>{label(data.onboarding?.status)}</strong><small>{data.onboarding?.domain_choice?`Domain: ${label(data.onboarding.domain_choice)}`:""}</small></article><article className={data.system_ready?styles.pass:styles.warn}><span>Approved revision</span><strong>{data.system_ready?"Website unchanged ✓":"Needs fresh client review"}</strong><small>{data.system_ready?"Current site matches the approved version.":"The live site changed after approval."}</small></article></div></section>
  <section className={styles.workspace}><div><h2>Launch checklist</h2><p>Confirm each operational item after checking the real website. These are deliberately human-controlled.</p></div><div className={styles.checks}>{([
    ["domain_ready","Domain decision resolved and target domain is ready"],["https_ready","HTTPS opens correctly without certificate warnings"],["website_health_ready","Website loads successfully and key pages respond"],["mobile_reviewed","Mobile layout reviewed on a phone-sized viewport"],["contact_links_reviewed","Email, contact, social and external links checked"],["analytics_ready","Analytics / visit tracking is active"],["branding_reviewed","Final logo, colours, images and lab naming checked"]
   ] as [keyof Checks,string][]).map(([key,text])=><label key={key} className={checks[key]?styles.checked:""}><input type="checkbox" disabled={launched} checked={checks[key]} onChange={e=>setChecks(v=>({...v,[key]:e.target.checked}))}/><span><strong>{text}</strong><small>{checks[key]?"Confirmed":"Pending"}</small></span></label>)}</div>
   <div className={styles.tools}>{siteUrl?<a href={siteUrl} target="_blank" rel="noreferrer">Open live website ↗</a>:null}<button type="button" disabled={busy||!siteUrl||launched} onClick={()=>void runHealth()}>Run website health check</button>{data.site?.slug?<Link href={`/admin/sites/${data.site.slug}/edit`}>Open visual editor</Link>:null}{health?<span className={health.ok?styles.healthOk:styles.healthBad}>{health.ok?`HTTP ${health.status} · healthy`:`Health check failed${health.error?` · ${health.error}`:""}`}</span>:null}</div>
   <textarea disabled={launched} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Private launch notes, domain details, checks performed…"/>
   {!launched?<div className={styles.actions}><button type="button" disabled={busy} onClick={()=>void save()}>Save checklist</button><button type="button" className={styles.launchButton} disabled={busy||!ready} onClick={()=>void launch()}>Launch website</button></div>:null}
  </section>
  {launched?<section className={styles.handover}><div><p className={styles.eyebrow}>Client handover</p><h2>The website is live.</h2><p>Share the private handover page after confirming the launch. The client can open the final URL, see the completed payment/delivery record and acknowledge handover.</p></div><div className={styles.handoverMeta}><span>Handover views <strong>{l.handover_view_count||0}</strong></span><span>Acknowledged <strong>{l.handover_acknowledged_at?fmt(l.handover_acknowledged_at):"Not yet"}</strong></span></div><div className={styles.handoverActions}><a href={`https://labnarrative.com/handover/${l.handover_token}`} target="_blank" rel="noreferrer">Open handover ↗</a><button onClick={()=>void copyHandover()}>Copy handover link</button>{l.status==="launched"?<button disabled={busy} onClick={()=>void markSent()}>Mark handover sent</button>:null}</div></section>:null}
 </div></main>
}
