"use client";

import { createClient, type Session } from "@supabase/supabase-js";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./pilot.module.css";

type Prospect={id:string;company_name:string;slug:string;status:string;demo_status:string;demo_config:Record<string,unknown>|null;fit_score:number;industry:string|null;city:string|null;country:string|null};
type Proposal={version:string;status:"draft"|"approved"|"sent";title:string;objective:string;priceSar:number;timeline:string;pilotWorkflow:string;deliverables:string;successMetrics:string;included:string;exclusions:string;integrationAssumptions:string;expansionPath:string;ongoingSubscriptionSar:string;ongoingSubscriptionNote:string;vatNote:string;nextStep:string;generatedAt?:string;updatedAt?:string;approvedAt?:string;sentAt?:string};

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const obj=(v:unknown):Record<string,unknown>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};
const str=(v:unknown)=>typeof v==="string"?v:"";
const num=(v:unknown,f=0)=>typeof v==="number"&&Number.isFinite(v)?v:f;
const list=(v:string)=>v.split(/\n+/).map(x=>x.trim()).filter(Boolean);
const uniq=(xs:string[])=>Array.from(new Set(xs.filter(Boolean))).join("\n");

function discovery(config:Record<string,unknown>|null){const d=obj(config?.discovery);return{phase:str(d.phase),confirmedPains:str(d.confirmedPains),currentSystems:str(d.currentSystems),manualWorkflows:str(d.manualWorkflows),errorPoints:str(d.errorPoints),managementNeeds:str(d.managementNeeds),requestedModules:str(d.requestedModules),pilotWorkflow:str(d.pilotWorkflow),integrationRequirements:str(d.integrationRequirements),companyStructure:str(d.companyStructure),expansionPotential:str(d.expansionPotential),nextAction:str(d.nextAction),pilotStatus:str(d.pilotStatus)}}
function savedProposal(config:Record<string,unknown>|null):Proposal|null{const p=obj(config?.pilotProposal);if(!Object.keys(p).length)return null;const s=str(p.status);return{version:str(p.version)||"pilot-v1",status:s==="approved"||s==="sent"?s:"draft",title:str(p.title),objective:str(p.objective),priceSar:num(p.priceSar,7500),timeline:str(p.timeline),pilotWorkflow:str(p.pilotWorkflow),deliverables:str(p.deliverables),successMetrics:str(p.successMetrics),included:str(p.included),exclusions:str(p.exclusions),integrationAssumptions:str(p.integrationAssumptions),expansionPath:str(p.expansionPath),ongoingSubscriptionSar:str(p.ongoingSubscriptionSar),ongoingSubscriptionNote:str(p.ongoingSubscriptionNote),vatNote:str(p.vatNote),nextStep:str(p.nextStep),generatedAt:str(p.generatedAt),updatedAt:str(p.updatedAt),approvedAt:str(p.approvedAt),sentAt:str(p.sentAt)}}

function generate(p:Prospect):Proposal{
 const d=discovery(p.demo_config),t=Object.values(d).join("\n").toLowerCase(),has=(...x:string[])=>x.some(k=>t.includes(k));
 const tender=has("tender","مناقصة","مناقصات"),quote=has("quotation","quote","عرض سعر","عروض الأسعار"),warehouse=has("warehouse","stock","مستودع","مخزون"),supply=has("supply","line item","missing","توريد","بند","بنود","نقص","خطأ"),collection=has("collection","invoice","تحصيل","فاتورة","فواتير","مالية"),management=has("overview","management","dashboard","إدارة","الادارة","الإدارة","لوحة"),integration=has("odoo","zoho","erp","crm","تكامل","ربط"),group=has("factory","multi-company","group","شركة ثانية","شركات","مصنع","مجموعة"),manual=has("excel","whatsapp","manual","إكسل","اكسل","واتساب","يدوي");
 const workflow=d.pilotWorkflow||[tender?"Tender / enquiry":"Enquiry",quote?"Quotation":"Commercial review","Order",warehouse?"Warehouse":"Fulfilment",supply?"Supply completeness":"Delivery","Invoice",collection?"Collection":"Payment follow-up",management?"Management Overview":"Management visibility"].join(" → ");
 return{version:"pilot-v1",status:"draft",title:`${p.company_name} — Operational Pilot`,objective:`Validate one focused, real operating workflow for ${p.company_name} before committing to a larger company-wide implementation. The Pilot is built around confirmed discovery, not a generic CRM template.`,priceSar:7500,timeline:"Estimated 2–4 weeks after final Pilot scope and required access/data are confirmed.",pilotWorkflow:workflow,
 deliverables:uniq(["Bilingual operational Pilot workspace (English / Arabic)",tender?"Tender/enquiry tracking with owner, deadline, readiness and missing requirements":"Enquiry and commercial-work tracking",quote?"Quotation tracking with line-item and review visibility":"Commercial review and approval visibility",warehouse?"Warehouse availability and shortage visibility linked to the affected order":"Fulfilment readiness visibility",supply?"Item-level completeness gate so incomplete orders are clearly blocked before dispatch":"Delivery-readiness control","Invoice and payment-status tracking for the agreed Pilot workflow",collection?"Collection follow-up with owner, due/overdue status and next action":"Payment follow-up visibility",management?"Management Overview highlighting active work, risks, delays and outstanding actions":"Management summary of the Pilot workflow","Configuration around the agreed Pilot users and workflow","Pilot environment hosting during the agreed validation period"]),
 successMetrics:uniq([tender?"Every Pilot tender/enquiry has a visible owner, deadline and readiness state":"Every Pilot work item has a visible owner and current state",quote?"Every Pilot quotation shows its current review/status and next action":"Commercial actions are visible with a clear next step",supply?"No Pilot order is shown as dispatch-ready while required line items remain incomplete":"Delivery readiness is visible before release",warehouse?"Shortages are visible against the affected Pilot order rather than tracked separately":"Fulfilment blockers are visible against the affected work item",collection?"Every Pilot invoice/collection item has a visible status, owner and next action":"Payment follow-up items are visible with ownership",management?"Management can see the Pilot workflow and its highest-priority exceptions in one Overview":"Management can review the Pilot workflow from one screen",manual?"Identify which Excel/WhatsApp/manual follow-up steps can be removed or reduced during the Pilot":"Validate whether the Pilot reduces fragmented manual follow-up"]),
 included:uniq(["Pilot discovery and final scope confirmation","Configuration of the agreed Pilot workflow","Illustrative/sample data setup, followed by agreed Pilot operating data as available","Reasonable adjustments within the agreed Pilot scope","Basic onboarding for the Pilot users","Pilot validation and feedback review"]),
 exclusions:uniq(["Company-wide full-system rollout beyond the agreed Pilot scope",integration?"Deep/live Odoo or Zoho integration unless explicitly added to the Pilot scope":"Deep/live ERP or CRM integration unless explicitly added to the Pilot scope","Large-scale historical data migration or data cleansing",group?"Multi-company / group-wide deployment (kept as a later expansion phase)":"Multi-company / group-wide deployment","Replacement of the company's accounting/ERP system","Third-party software, messaging, ERP or paid API/license fees not supplied by LabNarrative","Major new modules requested after Pilot scope approval; these are quoted separately"]),
 integrationAssumptions:integration?"The Pilot is designed to prove the specialized workflow first. Existing Odoo/Zoho can remain in place. Any live synchronization, API integration, system-of-record mapping or write-back is scoped separately after we confirm exactly what should stay in each system.":"The Pilot can run as a focused operational layer. Any live ERP/CRM integration is added only after the required system-of-record boundaries and APIs are confirmed.",
 expansionPath:group?"If the Pilot proves value, the next phase can expand into the full operational system, deeper integrations, additional companies/branches and a consolidated Group Overview while preserving permissions and separation between companies.":"If the Pilot proves value, the next phase can expand into the full operational system, deeper integrations, additional teams/branches, permissions, automation and company-wide management visibility.",ongoingSubscriptionSar:"",ongoingSubscriptionNote:"Ongoing hosting, support, maintenance and AI usage after the Pilot are agreed separately before production operation. Leave the monthly price blank until the commercial model is confirmed.",vatNote:"VAT, if applicable, is handled separately.",nextStep:d.nextAction||"Confirm Pilot scope with the team, approve the proposal, then schedule kickoff.",generatedAt:new Date().toISOString()};
}

function Field({label,value,onChange,rows=4,hint}:{label:string;value:string;onChange:(v:string)=>void;rows?:number;hint?:string}){return <label className={styles.field}><span>{label}</span>{hint?<small>{hint}</small>:null}<textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)}/></label>}

export default function PilotProposalBuilder(){
 const[session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false),[role,setRole]=useState<string|null>(null),[prospects,setProspects]=useState<Prospect[]>([]),[selectedId,setSelectedId]=useState(""),[search,setSearch]=useState(""),[proposal,setProposal]=useState<Proposal|null>(null),[saved,setSaved]=useState(""),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 const load=useCallback(async(s:Session)=>{setLoading(true);const r=await supabase.from("user_roles").select("role").eq("user_id",s.user.id).maybeSingle();if(r.error||r.data?.role!=="admin"){setRole(r.data?.role??null);setNotice(r.error?.message??"Administrator access required.");setLoading(false);return}setRole("admin");const q=await supabase.from("systems_outreach_prospects").select("id,company_name,slug,status,demo_status,demo_config,fit_score,industry,city,country").order("updated_at",{ascending:false});if(q.error){setNotice(q.error.message);setLoading(false);return}const next=(q.data??[])as Prospect[];setProspects(next);const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("prospect"):null;setSelectedId(cur=>{const match=requested?next.find(x=>x.id===requested||x.slug===requested):null;return match?.id||(cur&&next.some(x=>x.id===cur)?cur:next.find(x=>Object.keys(obj(x.demo_config?.discovery)).length>0)?.id??next[0]?.id??"")});setLoading(false)},[]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true);if(data.session)void load(data.session)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,n)=>{setSession(n);setAuthReady(true);if(n)void load(n)});return()=>subscription.unsubscribe()},[load]);
 const selected=prospects.find(x=>x.id===selectedId)??null,d=useMemo(()=>discovery(selected?.demo_config??null),[selected]),demoV2=useMemo(()=>obj(selected?.demo_config?.demoV2),[selected]);
 useEffect(()=>{if(!selected){setProposal(null);setSaved("");return}const existing=savedProposal(selected.demo_config),next=existing??generate(selected);setProposal(next);setSaved(existing?JSON.stringify(existing):"");setNotice("")},[selectedId,selected?.demo_config]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return prospects.filter(x=>Object.keys(obj(x.demo_config?.discovery)).length>0&&(!q||[x.company_name,x.industry,x.city,x.country,x.status].filter(Boolean).join(" ").toLowerCase().includes(q)))},[prospects,search]);
 const dirty=proposal?JSON.stringify(proposal)!==saved:false;
 const update=(key:keyof Proposal,value:string|number)=>setProposal(cur=>cur?({...cur,[key]:value} as Proposal):cur);
 const saveProposal=async(status:Proposal["status"],sent=false)=>{if(!selected||!proposal||!session||saving)return;setSaving(true);setNotice("");const now=new Date().toISOString(),current=obj(selected.demo_config),nextProposal:{[key:string]:unknown}={...proposal,version:"pilot-v1",status,updatedAt:now,approvedAt:status==="approved"||status==="sent"?(proposal.approvedAt||now):undefined,sentAt:sent?now:proposal.sentAt},nextDiscovery={...obj(current.discovery),phase:sent?"pilot_proposed":d.phase||"internal_review",pilotStatus:sent?"proposed":d.pilotStatus||"candidate",updatedAt:now,updatedBy:session.user.id},patch:Record<string,unknown>={demo_config:{...current,pilotProposal:nextProposal,discovery:nextDiscovery},updated_at:now};if(sent)patch.status="proposal";const result=await supabase.from("systems_outreach_prospects").update(patch).eq("id",selected.id);if(result.error){setNotice(result.error.message);setSaving(false);return}await supabase.from("systems_outreach_events").insert({prospect_id:selected.id,channel:"internal",event_type:sent?"pilot_proposal_sent_recorded":status==="approved"?"pilot_proposal_approved":"pilot_proposal_saved",status:"recorded",content:sent?`Pilot proposal recorded as sent. Price SAR ${proposal.priceSar}.`:status==="approved"?`Pilot proposal approved at human gate. Price SAR ${proposal.priceSar}.`:`Pilot proposal draft saved. Price SAR ${proposal.priceSar}.`});setNotice(sent?"Proposal recorded as sent. Prospect moved to Pilot Proposed.":status==="approved"?"Proposal approved. Private client link is ready.":"Pilot proposal draft saved.");await load(session);setSaving(false)};
 const regenerate=()=>{if(!selected)return;setProposal(generate(selected));setNotice("Regenerated from the latest Discovery. Review before saving or approving.")};
 if(!authReady)return <main className={styles.page}><div className={styles.center}>Preparing Pilot Proposal Builder…</div></main>;if(!session)return <main className={styles.page}><div className={styles.center}><h1>Administrator sign-in required.</h1><Link href="/admin">Go to admin →</Link></div></main>;if(role!=="admin")return <main className={styles.page}><div className={styles.center}><h1>Administrator permission required.</h1><p>{notice}</p></div></main>;
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.header}><div><div className={styles.brand}><span>Lab</span>Narrative</div><p className={styles.eyebrow}>Systems · discovery → pilot</p><h1>Pilot Proposal Builder</h1><p>Turn confirmed discovery and Demo V2 into a tightly scoped paid Pilot. The Pilot proves value first; the full system and deep integrations are priced separately after validation.</p></div><div className={styles.headerActions}><Link className={styles.secondaryButton} href="/admin/systems-outreach/discovery">Discovery</Link><Link className={styles.secondaryButton} href="/admin/systems-outreach/discovery/demo-v2">Demo V2</Link>{selected?.demo_status==="ready"?<Link className={styles.secondaryButton} target="_blank" href={`/systems/demos/${selected.slug}`}>Open demo ↗</Link>:null}</div></header>
  {notice?<div className={styles.notice}>{notice}</div>:null}
  <section className={styles.layout}><aside className={styles.sidebar}><div className={styles.sideHead}><div><span>Discovery prospects</span><strong>{visible.length}</strong></div><button onClick={()=>session&&void load(session)} disabled={loading}>{loading?"…":"Refresh"}</button></div><input className={styles.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company…"/><div className={styles.prospectList}>{visible.map(x=>{const p=savedProposal(x.demo_config);return <button key={x.id} onClick={()=>setSelectedId(x.id)} className={`${styles.prospect} ${x.id===selectedId?styles.prospectActive:""}`}><span><strong>{x.company_name}</strong><b>{x.fit_score}</b></span><small>{p?`proposal ${p.status}`:"proposal not saved"}</small></button>})}</div></aside>
  <section className={styles.workspace}>{selected&&proposal?<><div className={styles.companyHead}><div><p>{selected.industry||"Systems prospect"}</p><h2>{selected.company_name}</h2><span>{[selected.city,selected.country].filter(Boolean).join(" · ")}</span></div><div className={styles.statusBox}><span>Proposal status</span><strong>{proposal.status}</strong><small>{proposal.sentAt?"Recorded as sent":proposal.approvedAt?"Human-approved":"Human review required"}</small></div></div>
  <section className={styles.snapshot}><div><span>Discovery phase</span><strong>{(d.phase||"discovery").replaceAll("_"," ")}</strong></div><div><span>Demo V2</span><strong>{Object.keys(demoV2).length?"Built":"Not built"}</strong></div><div><span>Pilot price</span><strong>SAR {proposal.priceSar.toLocaleString("en-US")}</strong></div><div><span>Full system</span><strong>Separate scope</strong></div></section>
  <div className={styles.builderActions}><button className={styles.secondaryButton} onClick={regenerate}>Regenerate from Discovery</button>{proposal.status!=="draft"?<button className={styles.secondaryButton} onClick={()=>update("status","draft")}>Return to draft</button>:null}{proposal.status==="approved"||proposal.status==="sent"?<Link className={styles.primaryButton} target="_blank" href={`/systems/proposals/${selected.slug}`}>Open client proposal ↗</Link>:null}</div>
  <section className={styles.section}><div className={styles.sectionHead}><span>01</span><div><h3>Commercial frame</h3><p>Keep the Pilot small enough to buy and real enough to prove value.</p></div></div><div className={styles.twoCol}><Field label="Proposal title" value={proposal.title} onChange={v=>update("title",v)} rows={2}/><label className={styles.inputField}><span>Pilot price · SAR</span><input type="number" min="0" value={proposal.priceSar} onChange={e=>update("priceSar",Number(e.target.value)||0)}/></label><Field label="Objective" value={proposal.objective} onChange={v=>update("objective",v)} rows={5}/><Field label="Estimated timeline" value={proposal.timeline} onChange={v=>update("timeline",v)} rows={3} hint="Final timing follows scope/data confirmation."/></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><span>02</span><div><h3>Pilot scope</h3><p>Derived from the workflow the prospect actually cares about.</p></div></div><Field label="Pilot workflow" value={proposal.pilotWorkflow} onChange={v=>update("pilotWorkflow",v)} rows={4}/><div className={styles.twoCol}><Field label="Deliverables · one per line" value={proposal.deliverables} onChange={v=>update("deliverables",v)} rows={11}/><Field label="Success metrics · one per line" value={proposal.successMetrics} onChange={v=>update("successMetrics",v)} rows={11}/></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><span>03</span><div><h3>Boundaries</h3><p>Protect the Pilot from becoming a full enterprise implementation for SAR 7,500.</p></div></div><div className={styles.twoCol}><Field label="Included · one per line" value={proposal.included} onChange={v=>update("included",v)} rows={9}/><Field label="Not included / separately scoped · one per line" value={proposal.exclusions} onChange={v=>update("exclusions",v)} rows={9}/></div><Field label="Integration assumptions" value={proposal.integrationAssumptions} onChange={v=>update("integrationAssumptions",v)} rows={5}/></section>
  <section className={styles.section}><div className={styles.sectionHead}><span>04</span><div><h3>After the Pilot</h3><p>Show the expansion path without pricing the full system too early.</p></div></div><Field label="Expansion path" value={proposal.expansionPath} onChange={v=>update("expansionPath",v)} rows={5}/><div className={styles.twoCol}><label className={styles.inputField}><span>Optional ongoing subscription · SAR/month</span><small>Leave blank until we formally decide it.</small><input inputMode="numeric" value={proposal.ongoingSubscriptionSar} onChange={e=>update("ongoingSubscriptionSar",e.target.value.replace(/[^0-9]/g,""))} placeholder="Not set"/></label><Field label="Subscription note" value={proposal.ongoingSubscriptionNote} onChange={v=>update("ongoingSubscriptionNote",v)} rows={4}/></div><div className={styles.twoCol}><Field label="VAT note" value={proposal.vatNote} onChange={v=>update("vatNote",v)} rows={2}/><Field label="Next step" value={proposal.nextStep} onChange={v=>update("nextStep",v)} rows={3}/></div></section>
  <section className={styles.preview}><div className={styles.previewHead}><div><span>Client preview</span><h3>{proposal.title}</h3></div><strong>SAR {proposal.priceSar.toLocaleString("en-US")}</strong></div><p>{proposal.objective}</p><div className={styles.previewGrid}><div><span>Workflow</span><strong>{proposal.pilotWorkflow}</strong></div><div><span>Timeline</span><strong>{proposal.timeline}</strong></div></div><div className={styles.previewLists}><div><h4>Core deliverables</h4><ul>{list(proposal.deliverables).slice(0,6).map(x=><li key={x}>{x}</li>)}</ul></div><div><h4>Success criteria</h4><ul>{list(proposal.successMetrics).slice(0,6).map(x=><li key={x}>{x}</li>)}</ul></div></div><small>Full implementation, deep integrations and multi-company rollout remain separate scopes unless explicitly added above.</small></section>
  <div className={styles.saveBar}><div><strong>{dirty?"Unsaved proposal changes":`Proposal ${proposal.status}`}</strong><span>Approval is a human gate. Recording “sent” moves the prospect to Pilot Proposed.</span></div><div className={styles.saveActions}><button className={styles.secondaryButton} disabled={saving||!dirty} onClick={()=>void saveProposal("draft")}>{saving?"Saving…":"Save Draft"}</button><button className={styles.primaryButton} disabled={saving||dirty||proposal.status!=="draft"||!saved} onClick={()=>void saveProposal("approved")}>Approve Proposal</button><button className={styles.sentButton} disabled={saving||dirty||proposal.status!=="approved"} onClick={()=>void saveProposal("sent",true)}>Record Sent</button></div></div>
  </>:<div className={styles.empty}>Select a prospect with Discovery data to build the Pilot proposal.</div>}</section></section>
 </div></main>;
}
