import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { PDFDocument, PDFString, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";

const W=595.28,H=841.89,M=44;
const C={
  paper:rgb(246/255,247/255,242/255), white:rgb(1,1,1), cream:rgb(250/255,250/255,247/255),
  ink:rgb(16/255,24/255,20/255), muted:rgb(111/255,121/255,115/255), line:rgb(216/255,220/255,215/255),
  green:rgb(18/255,55/255,43/255), green2:rgb(31/255,79/255,61/255), softGreen:rgb(225/255,235/255,228/255),
  lime:rgb(220/255,254/255,121/255), black:rgb(7/255,9/255,8/255), black2:rgb(18/255,21/255,19/255), grayDark:rgb(150/255,160/255,154/255)
};
const arr=(v:any)=>Array.isArray(v)?v:[];
const clean=(v:any)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[–—−]/g,'-').replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/→/g,'->').replace(/[\u0000-\u001f]/g,' ').replace(/[^\x20-\x7E\xA0-\xFF]/g,'?');
const num=(v:any)=>Number(v||0);
function wrap(text:any,font:any,size:number,max:number){const words=clean(text).split(/\s+/).filter(Boolean),out:string[]=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(test,size)<=max)line=test;else{if(line)out.push(line);line=word}}if(line)out.push(line);return out}
function lines(page:any,text:any,x:number,y:number,font:any,size:number,color:any,max:number,leading=size*1.35,maxLines=99){let yy=y;for(const line of wrap(text,font,size,max).slice(0,maxLines)){page.drawText(line,{x,y:yy,size,font,color});yy-=leading}return yy}
function rule(page:any,x1:number,y1:number,x2:number,y2:number,color=C.line,th=.55){page.drawLine({start:{x:x1,y:y1},end:{x:x2,y:y2},color,thickness:th})}
function addLink(pdf:any,page:any,url:string,x:number,y:number,w:number,h:number){if(!url)return;try{const ref=pdf.context.register(pdf.context.obj({Type:'Annot',Subtype:'Link',Rect:[x,y,x+w,y+h],Border:[0,0,0],A:{Type:'Action',S:'URI',URI:PDFString.of(url)}}));page.node.addAnnot(ref)}catch{}}
function wordmark(page:any,bold:any,regular:any,onDark=false){page.drawText('LabNarrative',{x:M,y:H-46,size:10.4,font:bold,color:onDark?C.white:C.green});page.drawText('Intelligence',{x:M+72,y:H-46,size:9.6,font:regular,color:onDark?C.grayDark:C.muted})}
function eyebrow(page:any,t:string,x:number,y:number,bold:any,onDark=false){page.drawText(clean(t).toUpperCase(),{x,y,size:6.2,font:bold,color:onDark?C.lime:C.green,characterSpacing:.85})}
function footer(page:any,regular:any,n:number,onDark=false,label='LabIntelligence by LabNarrative'){const c=onDark?rgb(.42,.50,.45):C.line,tc=onDark?C.grayDark:C.muted;rule(page,M,29,W-M,29,c,.45);page.drawText(label,{x:M,y:15,size:6.2,font:regular,color:tc});const s=String(n);page.drawText(s,{x:W-M-regular.widthOfTextAtSize(s,6.2),y:15,size:6.2,font:regular,color:tc})}
function fill(page:any,color=C.paper){page.drawRectangle({x:0,y:0,width:W,height:H,color})}
function metric(page:any,label:string,value:string,x:number,y:number,w:number,bold:any,regular:any,onDark=false){const lc=onDark?rgb(.34,.46,.39):C.line,tc=onDark?rgb(.72,.79,.74):C.muted,vc=onDark?C.white:C.ink;rule(page,x,y+45,x+w,y+45,lc);page.drawText(label,{x,y:y+25,size:5,font:bold,color:tc,characterSpacing:.38});page.drawText(value,{x,y:y+5,size:12.5,font:bold,color:vc})}
async function json(url:string,key:string){const r=await fetch(url,{headers:{apikey:key,authorization:`Bearer ${key}`,accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
async function evidence(base:string,key:string,ids:string[]){if(!ids.length)return[];const out:any[]=[];for(let i=0;i<ids.length;i+=30){const q=ids.slice(i,i+30).join(',');out.push(...arr(await json(`${base}/rest/v1/prospect_evidence?prospect_id=in.(${encodeURIComponent(q)})&verified=eq.true&select=prospect_id,evidence_type,source_url,source_title,source_date,evidence_note&order=source_date.desc.nullslast`,key)))}return out}
function platformPageOne(pdf:any,bold:any,regular:any,italic:any,n:number){const p=pdf.addPage([W,H]);fill(p,C.black);wordmark(p,bold,regular,true);eyebrow(p,'Platform appendix',M,H-102,bold,true);p.drawText('THE PLATFORM',{x:M,y:H-156,size:31,font:bold,color:C.white});p.drawText('BEHIND THE REPORT',{x:M,y:H-191,size:31,font:bold,color:C.white});p.drawText('This PDF is one output of a living scientific-sales intelligence workspace.',{x:M,y:H-227,size:9.5,font:italic,color:C.lime});let y=H-282;const blocks=[
['01','MAP THE PRODUCT','The platform starts with the exact target, applications, species and experimental context - not a generic market segment.'],
['02','DISCOVER + VERIFY','Recent scientific activity is searched, weak matches are excluded, and every retained laboratory is backed by source evidence.'],
['03','PRIORITIZE','Laboratories are ranked by scientific fit so commercial teams can focus first on the most defensible opportunities.'],
['04','ACTIVATE','Decision-makers, source context and outreach angles turn research intelligence into a practical sales workflow.']
];
for(const [i,h,b] of blocks){rule(p,M,y+11,W-M,y+11,rgb(.18,.23,.20),.7);p.drawText(i,{x:M,y:y-18,size:9,font:italic,color:C.lime});p.drawText(h,{x:M+48,y:y-17,size:9.2,font:bold,color:C.white});lines(p,b,M+48,y-36,regular,7.8,rgb(.68,.72,.69),W-M-(M+48),10.8,4);y-=108}footer(p,regular,n,true,'LabNarrative Intelligence · Platform');return p}
function platformPageTwo(pdf:any,bold:any,regular:any,italic:any,n:number){const p=pdf.addPage([W,H]);fill(p,C.black);wordmark(p,bold,regular,true);eyebrow(p,'A continuous commercial system',M,H-102,bold,true);p.drawText('FROM ONE PRODUCT',{x:M,y:H-158,size:31,font:bold,color:C.white});p.drawText('TO A LIVING PIPELINE.',{x:M,y:H-194,size:31,font:italic,color:C.lime});let y=H-250;lines(p,'Inside the LabNarrative Intelligence workspace, the report remains connected to the product portfolio, laboratory inventory, evidence audit, decision-makers, outreach workflow and future refreshes.',M,y,regular,9.4,rgb(.78,.82,.79),W-2*M,13.5,6);y-=102;
const cols=[['PORTFOLIO','Products and coverage'],['PROSPECTS','Ranked laboratories'],['EVIDENCE','Source-by-source audit'],['CONTACTS','Decision-makers'],['OUTREACH','Email + LinkedIn angles'],['MONITORING','New scientific signals']];const cw=(W-2*M-18)/2;
for(let i=0;i<cols.length;i++){const x=M+(i%2)*(cw+18),row=Math.floor(i/2),yy=y-row*92;rule(p,x,yy+18,x+cw,yy+18,rgb(.18,.23,.20),.7);p.drawText(cols[i][0],{x,y:yy-6,size:7.5,font:bold,color:C.lime,characterSpacing:.45});p.drawText(cols[i][1],{x,y:yy-27,size:9.4,font:bold,color:C.white})}
y-=302;rule(p,M,y+20,W-M,y+20,rgb(.18,.23,.20),.7);eyebrow(p,'Why the platform matters',M,y-4,bold,true);y-=34;lines(p,'A static report answers: who looks relevant now? The platform adds the operating layer: what changed, which products deserve attention, who should be contacted, what evidence supports the approach, and where the next opportunity appears.',M,y,regular,8.8,rgb(.75,.79,.76),W-2*M,12.6,7);y-=115;p.drawText('LABNARRATIVE.COM/INTELLIGENCE',{x:M,y,size:9,font:bold,color:C.white,characterSpacing:.5});p.drawText('Scientific intelligence that stays usable after the PDF closes.',{x:M,y:y-25,size:8.6,font:italic,color:C.lime});addLink(pdf,p,'https://labnarrative.com/intelligence',M,y-8,240,34);footer(p,regular,n,true,'LabNarrative Intelligence · Platform');return p}

Deno.serve(async(req:Request)=>{
 if(!['GET','HEAD'].includes(req.method))return new Response('Method not allowed',{status:405});
 const u=new URL(req.url),reportId=u.searchParams.get('report_id')||'';if(!/^[0-9a-f-]{36}$/i.test(reportId))return new Response('Invalid report',{status:400});
 const base=Deno.env.get('SUPABASE_URL')||'',raw=Deno.env.get('SUPABASE_SECRET_KEYS')||'',legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';let key=legacy;try{key=JSON.parse(raw).default||key}catch{}if(!base||!key)return new Response('Backend not configured',{status:500});
 try{
  const reports=await json(`${base}/rest/v1/intelligence_reports?id=eq.${reportId}&select=*`,key);if(!reports?.length)return new Response('Report not found',{status:404});const report=reports[0];if(!['final_review','approved','sent'].includes(String(report.status)))return new Response('Report is not reviewable',{status:409});
  const cycles=await json(`${base}/rest/v1/sales_cycles?report_id=eq.${reportId}&select=*`,key),cycle=cycles?.[0]||{};if(!cycle.run_id)return new Response('Report is not linked to a cycle',{status:409});
  const companies=cycle.company_id?await json(`${base}/rest/v1/companies?id=eq.${cycle.company_id}&select=id,name,website_url`,key):[];
  const products=cycle.product_id?await json(`${base}/rest/v1/products?id=eq.${cycle.product_id}&select=*`,key):[];
  const company=companies?.[0]||{},product=products?.[0]||{};
  const prospects=arr(await json(`${base}/rest/v1/lab_prospects?run_id=eq.${cycle.run_id}&qualification_status=eq.qualified&evidence_status=eq.verified&select=*&order=fit_score.desc.nullslast,publication_date.desc.nullslast`,key));
  const ev=await evidence(base,key,prospects.map((p:any)=>p.id));const by=new Map<string,any[]>();for(const e of ev){const a=by.get(e.prospect_id)||[];a.push(e);by.set(e.prospect_id,a)}for(const p of prospects)p.evidence=by.get(p.id)||[];
  const payload=report.report_payload||{},count=prospects.length;
  const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),italic=await pdf.embedFont(StandardFonts.TimesRomanItalic);let no=1;

  let page=pdf.addPage([W,H]);fill(page,C.green);wordmark(page,bold,regular,true);eyebrow(page,'Scientific sales intelligence · complete product report',M,H-108,bold,true);let y=H-154;
  for(const l of wrap(company.name||payload.company||'Life-science supplier',bold,30,W-2*M).slice(0,2)){page.drawText(l,{x:M,y,size:30,font:bold,color:C.white});y-=33}
  y-=2;for(const l of wrap(product.name||payload.product?.name||'Scientific product',italic,22,W-2*M).slice(0,3)){page.drawText(l,{x:M,y,size:22,font:italic,color:C.lime});y-=25}
  y-=4;page.drawText(clean([product.catalog_number?`Catalog ${product.catalog_number}`:'',product.target?`Target ${product.target}`:''].filter(Boolean).join('  ·  ')),{x:M,y,size:7.2,font:regular,color:rgb(.72,.80,.75)});y-=54;
  const sw=(W-2*M-18)/3;metric(page,'VERIFIED OPPORTUNITIES',String(count),M,y-42,sw,bold,regular,true);metric(page,'EVIDENCE','Source-backed',M+sw+9,y-42,sw,bold,regular,true);metric(page,'REPORT SCOPE','Complete',M+2*(sw+9),y-42,sw,bold,regular,true);y-=92;
  eyebrow(page,'What this report found',M,y,bold,true);y-=23;y=lines(page,payload.summary||`LabNarrative identified ${count} independently verified laboratory opportunities whose current scientific work appears compatible with this product. Each retained opportunity is supported by current PI identity, recent scientific activity, experimental-method relevance and source-backed fit evidence.`,M,y,regular,9.4,C.white,W-2*M,13.2,7);y-=20;
  rule(page,M,y,W-M,y,rgb(.34,.46,.39),.8);y-=23;eyebrow(page,'Top ranked opportunities',M,y,bold,true);y-=17;for(let i=0;i<Math.min(5,count);i++){const p=prospects[i];page.drawText(String(i+1).padStart(2,'0'),{x:M,y,size:7,font:italic,color:C.lime});page.drawText(clean(p.pi_name||'Principal Investigator').slice(0,31),{x:M+37,y,size:7.8,font:bold,color:C.white});page.drawText(clean(p.institution||p.lab_name||'').slice(0,48),{x:M+210,y,size:6.2,font:regular,color:rgb(.68,.76,.71)});const s=String(Math.round(num(p.fit_score)||0));page.drawText(s,{x:W-M-bold.widthOfTextAtSize(s,7.8),y,size:7.8,font:bold,color:C.lime});y-=23}
  y-=6;rule(page,M,y,W-M,y,rgb(.34,.46,.39),.8);y-=20;lines(page,'Scientific relevance is not purchase intent, budget, or confirmed product need.',M,y,regular,6.4,rgb(.64,.71,.67),W-2*M,8.5,2);footer(page,regular,no++,true);

  page=pdf.addPage([W,H]);fill(page);wordmark(page,bold,regular);eyebrow(page,`Ranked prospect overview · ${count} verified`,M,H-96,bold);page.drawText('Opportunity map',{x:M,y:H-135,size:25,font:bold,color:C.ink});let yy=H-174;
  for(let i=0;i<count;i++){if(yy<72){footer(page,regular,no++);page=pdf.addPage([W,H]);fill(page);wordmark(page,bold,regular);eyebrow(page,'Ranked prospect overview · continued',M,H-96,bold);yy=H-128}const p=prospects[i];rule(page,M,yy+7,W-M,yy+7,C.line,.55);page.drawText(String(i+1).padStart(2,'0'),{x:M,y:yy-15,size:7.2,font:italic,color:C.green});page.drawText(clean(p.pi_name||'Principal Investigator').slice(0,34),{x:M+39,y:yy-13,size:7.8,font:bold,color:C.ink});page.drawText(clean(`${p.institution||p.lab_name||''}${p.country?' · '+p.country:''}`).slice(0,62),{x:M+205,y:yy-13,size:5.9,font:regular,color:C.muted});const s=(num(p.fit_score)||0).toFixed(1);page.drawText(s,{x:W-M-bold.widthOfTextAtSize(s,7.8),y:yy-13,size:7.8,font:bold,color:C.green});yy-=36}footer(page,regular,no++);

  for(let i=0;i<count;i++){
    const p=prospects[i];page=pdf.addPage([W,H]);fill(page);wordmark(page,bold,regular);let py=H-95;eyebrow(page,`${String(i+1).padStart(2,'0')} · Ranked laboratory`,M,py,bold);const score=(num(p.fit_score)||0).toFixed(1);page.drawText(score,{x:W-M-bold.widthOfTextAtSize(score,18),y:py-5,size:18,font:bold,color:C.green});page.drawText('FIT / 100',{x:W-M-37,y:py-18,size:4.8,font:regular,color:C.muted});py-=43;
    for(const l of wrap(p.pi_name||'Principal Investigator',bold,23,W-2*M-85).slice(0,2)){page.drawText(l,{x:M,y:py,size:23,font:bold,color:C.ink});py-=25}
    py=lines(page,`${p.institution||p.lab_name||''}${p.country?' · '+p.country:''}`,M,py-1,regular,7.6,C.muted,W-2*M-85,9.8,2);py-=20;rule(page,M,py,W-M,py);py-=24;
    eyebrow(page,'Why this laboratory matters',M,py,bold);py-=18;py=lines(page,p.fit_rationale||p.relevance_summary||'Verified scientific product fit.',M,py,regular,9.1,C.ink,W-2*M,12.5,6);py-=16;
    const labels=['TARGET FIT','METHOD FIT','RECENCY','RESEARCH ACTIVITY','EVIDENCE QUALITY'],vals=[p.score_target_fit,p.score_method_fit,p.score_recency,p.score_research_activity,p.score_evidence_quality],cw=(W-2*M)/5;for(let j=0;j<5;j++){const x=M+j*cw;if(j)rule(page,x,py-48,x,py,C.line,.5);page.drawText(String(Math.round(num(vals[j])||0)),{x:x+9,y:py-19,size:11.5,font:bold,color:C.ink});page.drawText(labels[j],{x:x+9,y:py-38,size:4.5,font:regular,color:C.muted,characterSpacing:.25})}rule(page,M,py,W-M,py,C.line,.5);rule(page,M,py-48,W-M,py-48,C.line,.5);py-=72;
    eyebrow(page,'Experimental-method match',M,py,bold);py-=15;py=lines(page,arr(p.experimental_methods).join(' · ')||'Verified experimental compatibility',M,py,bold,7.6,C.ink,W-2*M,10.1,3);py-=12;
    eyebrow(page,'Recent publication signal',M,py,bold);py-=15;py=lines(page,p.publication_title||'Verified recent publication',M,py,bold,8.1,C.ink,W-2*M,10.8,4);py=lines(page,`${p.publication_date||''}${p.publication_identifier?' · '+p.publication_identifier:''}`,M,py-1,regular,6.3,C.muted,W-2*M,8.1,2);py-=14;
    eyebrow(page,'Evidence audit',M,py,bold);py-=13;for(const e of arr(p.evidence).slice(0,4)){if(py<103)break;rule(page,M,py+4,W-M,py+4,C.line,.4);const typ=clean(e.evidence_type||'Evidence').replace(/_/g,' ').toUpperCase();page.drawText(typ,{x:M,y:py-11,size:4.8,font:bold,color:C.green,characterSpacing:.28});py=lines(page,e.evidence_note||e.source_title||'',M,py-24,regular,6.25,C.ink,W-2*M-115,8.1,2);if(e.source_url){let h='source';try{h=new URL(e.source_url).hostname.replace(/^www\./,'')}catch{}page.drawText(clean(h).slice(0,28),{x:W-M-105,y:py+8,size:5.2,font:regular,color:C.green});addLink(pdf,page,e.source_url,W-M-112,py,112,24)}py-=13}
    page.drawText('Interpretation boundary: scientific relevance is not purchase intent, budget, or confirmed product need.',{x:M,y:42,size:5.7,font:regular,color:C.muted});footer(page,regular,no++);
  }

  page=pdf.addPage([W,H]);fill(page,C.green);wordmark(page,bold,regular,true);eyebrow(page,'Continue with LabNarrative Intelligence',M,H-105,bold,true);let fy=H-157;page.drawText('TURN ONE PRODUCT',{x:M,y:fy,size:28,font:bold,color:C.white});fy-=34;page.drawText('INTO A LIVING SALES PIPELINE.',{x:M,y:fy,size:25,font:italic,color:C.lime});fy-=49;lines(page,'This report is the proof layer. The Intelligence platform keeps the same product-specific evidence connected to a continuously usable commercial workspace.',M,fy,regular,9.5,C.white,W-2*M,13.2,6);fy-=103;
  const plans=[['STARTER','5 active products','$249/mo'],['GROWTH','15 active products','$489/mo'],['PRO','40 active products','$889/mo'],['ENTERPRISE','Custom portfolio','Custom']];for(const [name,scope,price] of plans){rule(page,M,fy+12,W-M,fy+12,rgb(.34,.46,.39),.65);page.drawText(name,{x:M,y:fy-10,size:7,font:bold,color:C.lime,characterSpacing:.55});page.drawText(scope,{x:M+120,y:fy-10,size:7.5,font:regular,color:C.white});page.drawText(price,{x:W-M-bold.widthOfTextAtSize(price,8.2),y:fy-10,size:8.2,font:bold,color:C.white});fy-=43}fy-=19;eyebrow(page,'Optional managed commercial pilot',M,fy,bold,true);fy-=25;page.drawText('10 products · $489 one-time',{x:M,y:fy,size:9.2,font:bold,color:C.white});page.drawText('20 products · $789 one-time',{x:M+250,y:fy,size:9.2,font:bold,color:C.white});fy-=65;rule(page,M,fy+14,W-M,fy+14,rgb(.34,.46,.39),.8);page.drawText('VIEW PLANS + PLATFORM',{x:M,y:fy-12,size:9,font:bold,color:C.lime,characterSpacing:.45});page.drawText('labnarrative.com/intelligence',{x:M,y:fy-36,size:7.8,font:regular,color:C.white});addLink(pdf,page,'https://labnarrative.com/intelligence',M,fy-48,250,52);footer(page,regular,no++,true);

  platformPageOne(pdf,bold,regular,italic,no++);platformPageTwo(pdf,bold,regular,italic,no++);

  pdf.setTitle(`${clean(company.name)} - ${clean(product.name)} - LabNarrative`);pdf.setAuthor('LabNarrative');pdf.setSubject('Complete Product Opportunity Report');
  const bytes=await pdf.save(),filename=`LabNarrative_${clean(company.name).replace(/[^a-z0-9]+/gi,'_')}_${clean(product.catalog_number||'Report').replace(/[^a-z0-9]+/gi,'-')}_Complete.pdf`;
  return new Response(req.method==='HEAD'?null:bytes,{status:200,headers:{'content-type':'application/pdf','content-disposition':`inline; filename="${filename}"`,'cache-control':'no-store','x-content-type-options':'nosniff','x-report-opportunity-count':String(count),'x-labnarrative-brand':'classic-editorial-v7'}})
 }catch(e){console.error(e);return new Response(e instanceof Error?e.message:String(e),{status:500})}
});