"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { browserSupabase } from "@/lib/supabase-browser";
import styles from "./awaed-screenshot.module.css";

type Holding = { name:string; type:string; value:number; confidence:string; source:string; included:boolean };
type Shot = { file:File; url:string };
type OcrMessage = { progress?:number };
type TesseractApi = { recognize:(image:File,langs:string,options?:{logger?:(m:OcrMessage)=>void})=>Promise<{data:{text:string}}> };
declare global { interface Window { Tesseract?:TesseractApi } }

const SCRIPT_ID="tharwa-tesseract";
const SCRIPT_URL="https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js";
const PENDING_KEY="tharwa:pending:awaed:screenshot";
const TYPES=["سهم","صندوق","مرابحة","صك","نقد","أصل آخر"];
const digits:Record<string,string>={"٠":"0","١":"1","٢":"2","٣":"3","٤":"4","٥":"5","٦":"6","٧":"7","٨":"8","٩":"9","۰":"0","۱":"1","۲":"2","۳":"3","۴":"4","۵":"5","۶":"6","۷":"7","۸":"8","۹":"9"};

function normalize(v:string){return v.replace(/[٠-٩۰-۹]/g,d=>digits[d]??d).replaceAll("٬",",").replaceAll("٫",".").replace(/\u00a0/g," ")}
function num(v:string){const n=Number(normalize(v).replace(/,/g,"").replace(/[^0-9.-]/g,""));return Number.isFinite(n)?n:0}
function sar(v:number){return new Intl.NumberFormat("ar-SA",{maximumFractionDigits:0}).format(v)}
function typeOf(v:string){const s=v.toLowerCase();if(/مرابح|murabaha/.test(s))return"مرابحة";if(/صندوق|fund|mutual|etf/.test(s))return"صندوق";if(/صك|sukuk|bond/.test(s))return"صك";if(/نقد|سيول|cash|balance/.test(s))return"نقد";if(/سهم|أسهم|stock|share|equity|شركة/.test(s))return"سهم";return"أصل آخر"}
function dbType(v:string){return v==="سهم"?"saudi_stock":v==="صندوق"?"fund":v==="مرابحة"?"murabaha":v==="صك"?"sukuk":v==="نقد"?"cash":"other"}
function today(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function cleanName(v:string){return normalize(v).replace(/(?:ر\.?\s?س|SAR|ريال(?:\s+سعودي)?)/gi," ").replace(/(?:القيمة\s*(?:الحالية|السوقية)?|قيمة\s*الاستثمار|market\s*value|current\s*value|الكمية|quantity|السعر|price|العائد|return|الربح|الخسارة)/gi," ").replace(/[+-]?\d[\d,\s]*(?:\.\d+)?%?/g," ").replace(/[|•·:]+/g," ").replace(/\s+/g," ").trim().slice(0,120)}
function goodName(v:string){return v.length>1&&/[A-Za-z\u0600-\u06ff]/.test(v)&&!/^(?:القيمة|السعر|الكمية|التكلفة|العائد|الربح|الخسارة|المحفظة|استثماراتي|الأصول|الاستثمارات|total|portfolio|value|price|quantity)$/i.test(v)}
function numbers(line:string){return[...normalize(line).matchAll(/[+-]?\d[\d,]*(?:\.\d+)?/g)].map(m=>num(m[0])).filter(v=>v>0&&v<1e12)}
function extract(text:string){
  const rows=text.split(/\r?\n/).map(x=>x.replace(/\s+/g," ").trim()).filter(Boolean);const out:Holding[]=[];let pending="";
  for(const original of rows){const line=normalize(original);if(/^(?:الإجمالي|المجموع|إجمالي|صافي|قيمة المحفظة|إجمالي المحفظة|total|portfolio value|net worth)/i.test(line)){pending="";continue}const ns=numbers(line);const direct=cleanName(line);if(!ns.length){if(goodName(direct)&&direct.length<90)pending=direct;continue}const value=Math.max(...ns);if(value<5)continue;const name=goodName(direct)?direct:pending;if(!goodName(name))continue;const cue=/ر\.?\s?س|SAR|ريال|القيمة|value/i.test(line);out.push({name,type:typeOf(`${name} ${line}`),value,confidence:cue&&goodName(direct)?"مرتفع":goodName(direct)?"متوسط":"منخفض",source:original,included:true});pending=""}
  const seen=new Set<string>();return out.filter(h=>{const k=`${h.name.toLowerCase().replace(/\s+/g," ")}|${Math.round(h.value*100)}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,120)
}
function loadOcr(){if(window.Tesseract)return Promise.resolve(window.Tesseract);return new Promise<TesseractApi>((resolve,reject)=>{const old=document.getElementById(SCRIPT_ID) as HTMLScriptElement|null;if(old){const done=()=>window.Tesseract?resolve(window.Tesseract):reject(new Error("تعذر تشغيل قارئ الصور."));if(window.Tesseract)return done();old.addEventListener("load",done,{once:true});old.addEventListener("error",()=>reject(new Error("تعذر تحميل قارئ الصور.")),{once:true});return}const s=document.createElement("script");s.id=SCRIPT_ID;s.src=SCRIPT_URL;s.async=true;s.crossOrigin="anonymous";s.onload=()=>window.Tesseract?resolve(window.Tesseract):reject(new Error("تعذر تشغيل قارئ الصور."));s.onerror=()=>reject(new Error("تعذر تحميل قارئ الصور. تحقق من الاتصال وحاول مجددًا."));document.head.appendChild(s)})}

export default function AwaedScreenshotClient(){
  const[shots,setShots]=useState<Shot[]>([]);const[holdings,setHoldings]=useState<Holding[]>([]);const[processing,setProcessing]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[saved,setSaved]=useState(false);const[email,setEmail]=useState("");const[progress,setProgress]=useState({current:0,total:0,pct:0});
  const total=useMemo(()=>holdings.filter(h=>h.included).reduce((s,h)=>s+h.value,0),[holdings]);

  useEffect(()=>{void browserSupabase.auth.getSession().then(({data})=>{if(data.session)setEmail(data.session.user.email??"");const pending=localStorage.getItem(PENDING_KEY);if(data.session&&pending){try{const parsed=JSON.parse(pending) as Holding[];setHoldings(parsed);void save(parsed)}catch{localStorage.removeItem(PENDING_KEY)}}})},[]);
  useEffect(()=>()=>shots.forEach(x=>URL.revokeObjectURL(x.url)),[shots]);

  function choose(files:FileList|null){shots.forEach(x=>URL.revokeObjectURL(x.url));const chosen=Array.from(files??[]).filter(f=>f.type.startsWith("image/")).slice(0,6);if(chosen.some(f=>f.size>10*1024*1024)){setError("حجم كل صورة يجب أن يكون أقل من 10 MB.");setShots([]);return}setShots(chosen.map(file=>({file,url:URL.createObjectURL(file)})));setHoldings([]);setError("");setSaved(false)}

  async function analyze(){if(!shots.length)return;setProcessing(true);setError("");setHoldings([]);setProgress({current:0,total:shots.length,pct:0});try{const ocr=await loadOcr();let text="";for(let i=0;i<shots.length;i++){setProgress({current:i+1,total:shots.length,pct:0});const r=await ocr.recognize(shots[i].file,"ara+eng",{logger:m=>{if(typeof m.progress==="number")setProgress({current:i+1,total:shots.length,pct:Math.round(m.progress*100)})}});text+=`\n${r.data.text??""}`}const found=extract(text);setHoldings(found);if(!found.length)setError("لم نكتشف أصولًا واضحة. جرّب صورًا أوضح أو استخدم الإدخال السريع أسفل الصفحة.")}catch(e){setError(e instanceof Error?e.message:"تعذر تحليل الصور.")}finally{setProcessing(false)}}

  function update(i:number,patch:Partial<Holding>){setHoldings(current=>current.map((h,index)=>index===i?{...h,...patch}:h));setSaved(false)}

  async function save(items=holdings){const selected=items.filter(h=>h.included&&h.value>0);if(!selected.length)return;setSaving(true);setError("");setSaved(false);try{const{data,error:sessionError}=await browserSupabase.auth.getSession();if(sessionError)throw sessionError;const session=data.session;if(!session){localStorage.setItem(PENDING_KEY,JSON.stringify(selected));location.href="/wealth/login?next=%2Fwealth%2Fconnect%2Fawaed";return}const uid=session.user.id;setEmail(session.user.email??"");const{error:profileError}=await browserSupabase.from("wealth_profiles").upsert({user_id:uid,display_name:session.user.user_metadata?.full_name??null,base_currency:"SAR",updated_at:new Date().toISOString()},{onConflict:"user_id"});if(profileError)throw profileError;
    const{data:existing,error:lookupError}=await browserSupabase.from("wealth_accounts").select("id").eq("user_id",uid).eq("provider","Awaed").neq("status","archived").limit(1).maybeSingle();if(lookupError)throw lookupError;let accountId=existing?.id as string|undefined;if(!accountId){const{data:created,error:createError}=await browserSupabase.from("wealth_accounts").insert({user_id:uid,provider:"Awaed",account_name:"محفظة عوائد",account_type:"investment",connection_mode:"statement",status:"active",currency:"SAR",metadata:{read_only:true,latest_import_mode:"screenshot"}}).select("id").single();if(createError)throw createError;accountId=created.id as string}else{const{error:updateError}=await browserSupabase.from("wealth_accounts").update({connection_mode:"statement",status:"active",metadata:{read_only:true,latest_import_mode:"screenshot"},updated_at:new Date().toISOString()}).eq("id",accountId);if(updateError)throw updateError}
    const{data:old,error:oldError}=await browserSupabase.from("wealth_holdings").select("id").eq("account_id",accountId);if(oldError)throw oldError;const categories=selected.reduce<Record<string,number>>((a,h)=>{a[h.type]=(a[h.type]??0)+h.value;return a},{});const{data:imp,error:impError}=await browserSupabase.from("wealth_imports").insert({user_id:uid,account_id:accountId,source:"Awaed",file_name:`لقطات عوائد (${shots.length||1} صور)`,file_type:"image",parse_status:"reviewed",detected_count:selected.length,total_value:selected.reduce((s,h)=>s+h.value,0),currency:"SAR",parser_version:"awaed-screenshot-ocr-v1",summary:{categories,mode:"screenshot",image_storage:"none"}}).select("id").single();if(impError)throw impError;
    const rows=selected.map(h=>({user_id:uid,account_id:accountId,import_id:imp.id,asset_name:h.name.trim()||"أصل من عوائد",asset_type:dbType(h.type),market_value:h.value,currency:"SAR",as_of_date:today(),metadata:{parser_type:h.type,confidence:h.confidence,source_line:h.source,import_mode:"screenshot",needs_market_classification:h.type==="سهم"||h.type==="أصل آخر"}}));const{error:rowsError}=await browserSupabase.from("wealth_holdings").insert(rows);if(rowsError)throw rowsError;const ids=(old??[]).map(x=>x.id as string).filter(Boolean);if(ids.length){const{error:deleteError}=await browserSupabase.from("wealth_holdings").delete().in("id",ids);if(deleteError)throw deleteError}
    const{data:all,error:allError}=await browserSupabase.from("wealth_holdings").select("market_value,asset_type").eq("user_id",uid);if(allError)throw allError;let net=0,liquid=0;const allocation:Record<string,number>={};for(const h of all??[]){const v=Number(h.market_value)||0;const t=String(h.asset_type||"other");net+=v;allocation[t]=(allocation[t]??0)+v;if(t!=="real_estate"&&t!=="private_asset")liquid+=v}const{error:snapError}=await browserSupabase.from("wealth_snapshots").upsert({user_id:uid,snapshot_date:today(),net_worth:net,liquid_assets:liquid,annual_income_estimate:0,currency:"SAR",allocation,metadata:{last_source:"Awaed",last_import_mode:"screenshot"}},{onConflict:"user_id,snapshot_date"});if(snapError)throw snapError;await browserSupabase.from("wealth_imports").update({parse_status:"saved",updated_at:new Date().toISOString()}).eq("id",imp.id);localStorage.removeItem(PENDING_KEY);setSaved(true)}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ المحفظة.")}finally{setSaving(false)}}

  return <section className={styles.card}>
    <div className={styles.top}><div><span>الطريقة الأسهل</span><h2>ارفع صور محفظتك من عوائد.</h2><p>خذ لقطة أو عدة لقطات من صفحة استثماراتك. نقرأ النص داخل متصفحك بالعربية والإنجليزية، ثم تراجع كل أصل قبل الحفظ.</p></div><div className={styles.badge}>الصور لا تُخزّن</div></div>
    <div className={styles.account}><span>{email?"الحفظ السحابي مفعّل":"الحفظ الآمن"}</span><strong>{email||"سجّل الدخول فقط عند الاعتماد"}</strong>{email?<b>متصل</b>:<Link href="/wealth/login?next=%2Fwealth%2Fconnect%2Fawaed">تسجيل الدخول</Link>}</div>
    <label className={styles.upload}><input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>choose(e.target.files)}/><span>{shots.length?`تم اختيار ${new Intl.NumberFormat("ar-SA").format(shots.length)} صور`:"اختر لقطات الشاشة"}</span><strong>PNG · JPG · WEBP — حتى ٦ صور</strong></label>
    {shots.length?<div className={styles.images}>{shots.map(x=><div className={styles.image} key={`${x.file.name}-${x.file.lastModified}`}><img src={x.url} alt="لقطة من عوائد"/><span>{x.file.name}</span></div>)}</div>:null}
    {shots.length&&!holdings.length?<button className={styles.primary} type="button" onClick={analyze} disabled={processing}>{processing?"جاري قراءة الصور…":"قراءة الصور الآن"}</button>:null}
    {processing&&progress.total?<div className={styles.progress}><div><span>الصورة {progress.current} من {progress.total}</span><strong>{progress.pct}%</strong></div><div><span style={{width:`${progress.pct}%`}}/></div></div>:null}
    {error?<div className={styles.error}>{error}</div>:null}
    {holdings.length?<div className={styles.review}><div className={styles.summary}><div><span>راجع قبل الاعتماد</span><h3>اكتشفنا {new Intl.NumberFormat("ar-SA").format(holdings.length)} عنصرًا</h3><p>صحح الاسم أو النوع أو القيمة إذا احتاجت قراءة الصورة لذلك.</p></div><strong>{sar(total)} <small>ر.س</small></strong></div><div className={styles.rows}><div className={styles.head}><span>✓</span><span>الأصل</span><span>النوع</span><span>القيمة</span><span>الثقة</span></div>{holdings.map((h,i)=><div className={`${styles.row} ${!h.included?styles.off:""}`} key={`${h.name}-${i}`}><input type="checkbox" checked={h.included} onChange={()=>update(i,{included:!h.included})}/><input type="text" value={h.name} onChange={e=>update(i,{name:e.target.value})}/><select value={h.type} onChange={e=>update(i,{type:e.target.value})}>{TYPES.map(t=><option key={t}>{t}</option>)}</select><label><input inputMode="decimal" value={String(h.value)} onChange={e=>update(i,{value:num(e.target.value)})}/><span>ر.س</span></label><small>{h.confidence}</small></div>)}</div><div className={styles.actions}><button type="button" className={styles.secondary} onClick={()=>{setHoldings([]);setError("");setSaved(false)}}>إعادة القراءة</button><button type="button" className={styles.primary} onClick={()=>void save()} disabled={total<=0||saving}>{saving?"جاري الحفظ…":"إضافة إلى ثروتي"}</button></div>{saved?<div className={styles.saved}><span>تم حفظ محفظة عوائد بأمان.</span><Link href="/wealth">مشاهدة لوحة الثروة</Link></div>:null}</div>:null}
  </section>
}
