"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { browserSupabase as supabase } from "@/lib/supabase-browser";
import styles from "./care.module.css";

type Provider={environment:string;paypal_product_id?:string|null;paypal_webhook_id?:string|null;webhook_status:string;last_verified_at?:string|null;last_error?:string|null};
type Plan={id:string;code:string;name:string;description:string;billing_interval:"month"|"year";price_amount:number|string;currency:string;features:string[];is_active:boolean;display_order:number;paypal_plan_id?:string|null;provider_status:string;provider_synced_at?:string|null;provider_error?:string|null};
type Sub={id:string;prospectId:string;siteId?:string|null;status:string;provider?:string|null;included?:boolean;planName:string;billingInterval:string;priceAmount:number|string;currency:string;subscriberName?:string|null;subscriberEmail?:string|null;startedAt?:string|null;nextBillingAt?:string|null;lastPaymentAt?:string|null;piName:string;institution:string;slug?:string|null};
type Req={id:string;prospectId:string;status:string;category:string;subject:string;details:string;clientName?:string|null;clientEmail?:string|null;submittedAt:string;completedAt?:string|null;piName:string;institution:string};
type Data={provider:Provider;counts:{active:number;approvalPending:number;suspended:number;openRequests:number;offers:number};mrr:number|string;arr:number|string;plans:Plan[];subscriptions:Sub[];requests:Req[]};
function money(v:number|string,c="USD"){const n=Number(v||0)||0;try{return new Intl.NumberFormat("en-US",{style:"currency",currency:c,maximumFractionDigits:2}).format(n)}catch{return`${c} ${n.toFixed(2)}`}}
function fmt(v?:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(d)}
function label(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase())}

export default function CareDashboard(){
 const[data,setData]=useState<Data|null>(null);const[plans,setPlans]=useState<Plan[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const{data:r,error:e}=await supabase.rpc("care_admin_dashboard");if(e)setError(e.message);else{const d=r as Data;setData(d);setPlans((d.plans||[]).map(p=>({...p,features:Array.isArray(p.features)?p.features:[]})))}setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const activeSubs=useMemo(()=>data?.subscriptions?.filter(s=>s.status==="active")||[],[data]);
 const includedActive=useMemo(()=>activeSubs.filter(s=>s.included||s.provider==="proposal_included").length,[activeSubs]);
 function patch(id:string,key:keyof Plan,value:unknown){setPlans(v=>v.map(p=>p.id===id?{...p,[key]:value}:p))}
 async function savePlan(plan:Plan){setBusy(plan.id);setError("");const{error:e}=await supabase.rpc("care_admin_plan_save",{p_plan_id:plan.id,p_name:plan.name,p_description:plan.description,p_price_amount:Number(plan.price_amount),p_currency:plan.currency,p_features:plan.features,p_is_active:plan.is_active,p_display_order:plan.display_order});setBusy("");if(e)setError(e.message);else{setNotice(`${plan.name} saved.`);await load()}}
 async function syncPayPal(){setBusy("sync");setError("");const{data:r,error:e}=await supabase.functions.invoke("paypal-care",{body:{action:"sync_plans"}});setBusy("");if(e)setError(e.message);else if(r?.error)setError(String(r.error));else{setNotice(`PayPal Care synced: ${r?.synced||0} active billing plans.`);await load()}}
 async function updateRequest(id:string,status:string){setBusy(id);setError("");const{error:e}=await supabase.rpc("care_admin_request_update",{p_request_id:id,p_status:status,p_admin_notes:null});setBusy("");if(e)setError(e.message);else await load()}
 if(loading)return <main className={styles.state}><div><h1>Loading LabNarrative Care…</h1><p>Reading Care clients, plans and maintenance requests.</p></div></main>;
 if(!data)return <main className={styles.state}><div><h1>Care dashboard unavailable</h1><p>{error||"Could not load LabNarrative Care."}</p></div></main>;
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.top}><div><p className={styles.eyebrow}>Client website care</p><h1>LabNarrative Care</h1><p>Manage included Care entitlements, recurring subscriptions, website monitoring and scientific content updates after project handover.</p></div><div className={styles.nav}><Link href="/admin/sales">Sales</Link><Link href="/admin/sites">Websites</Link><button onClick={()=>void load()}>Refresh</button></div></header>
  {notice?<p className={styles.notice}>{notice}</p>:null}{error?<p className={styles.error}>{error}</p>:null}
  <section className={styles.stats}><article className={styles.stat}><span>Active Care clients</span><strong>{data.counts.active}</strong><small>{includedActive} included with project</small></article><article className={styles.stat}><span>Recurring MRR</span><strong>{money(data.mrr)}</strong></article><article className={styles.stat}><span>Recurring ARR</span><strong>{money(data.arr)}</strong></article><article className={styles.stat}><span>Open requests</span><strong>{data.counts.openRequests}</strong></article><article className={styles.stat}><span>Open offers</span><strong>{data.counts.offers}</strong></article></section>
  <section className={`${styles.card} ${styles.wide}`}><div className={styles.cardHead}><div><p className={styles.eyebrow}>PayPal subscriptions</p><h2>Provider connection</h2><p>Standalone Care subscriptions use the same verified LIVE PayPal credentials as project payments. Included project Care does not create a recurring PayPal agreement.</p></div><span className={styles.badge} data-state={data.provider?.webhook_status||"pending"}>{data.provider?.environment||"live"} · {data.provider?.webhook_status||"pending"}</span></div><div className={styles.provider}><dl><div><dt>Product</dt><dd>{data.provider?.paypal_product_id||"Created on first sync"}</dd></div><div><dt>Webhook</dt><dd>{data.provider?.paypal_webhook_id?"Registered":"Pending"}</dd></div><div><dt>Last verified</dt><dd>{fmt(data.provider?.last_verified_at)}</dd></div></dl><button className={styles.primary} disabled={busy==="sync"} onClick={()=>void syncPayPal()}>{busy==="sync"?"Syncing…":"Sync Care with PayPal"}</button></div>{data.provider?.last_error?<p className={styles.error}>{data.provider.last_error}</p>:null}</section>
  <div className={styles.grid}>
   <section className={`${styles.card} ${styles.wide}`}><div className={styles.cardHead}><div><p className={styles.eyebrow}>Commercial settings</p><h2>Care plans</h2><p>Standalone Care pricing. Existing recurring subscriptions keep their accepted snapshot; project-included Annual Care does not create a second charge.</p></div></div><div className={styles.plans}>{plans.map(plan=><article className={styles.plan} key={plan.id}><div className={styles.cardHead}><div><span className={styles.badge} data-state={plan.provider_status}>{label(plan.billing_interval)} · {label(plan.provider_status)}</span></div><small>{plan.paypal_plan_id||"Not synced yet"}</small></div><label><span>Plan name</span><input value={plan.name} onChange={e=>patch(plan.id,"name",e.target.value)}/></label><label><span>Description</span><textarea rows={3} value={plan.description} onChange={e=>patch(plan.id,"description",e.target.value)}/></label><div className={styles.priceRow}><label><span>Price</span><input type="number" min="1" step="0.01" value={plan.price_amount} onChange={e=>patch(plan.id,"price_amount",e.target.value)}/></label><label><span>Currency</span><input value={plan.currency} maxLength={3} onChange={e=>patch(plan.id,"currency",e.target.value.toUpperCase())}/></label></div><label><span>Included services · one per line</span><textarea rows={6} value={plan.features.join("\n")} onChange={e=>patch(plan.id,"features",e.target.value.split("\n").map(x=>x.trim()).filter(Boolean))}/></label><div className={styles.planActions}><label className={styles.toggle}><input type="checkbox" checked={plan.is_active} onChange={e=>patch(plan.id,"is_active",e.target.checked)}/><span>Offer this plan</span></label><button className={styles.primary} disabled={busy===plan.id} onClick={()=>void savePlan(plan)}>{busy===plan.id?"Saving…":"Save plan"}</button></div></article>)}</div></section>
   <section className={`${styles.card} ${styles.wide}`}><div className={styles.cardHead}><div><p className={styles.eyebrow}>Portfolio</p><h2>Care clients</h2><p>{activeSubs.length} active · {includedActive} included · {data.counts.approvalPending} awaiting PayPal approval · {data.counts.suspended} suspended</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Client</th><th>Plan</th><th>Status</th><th>Last payment</th><th>Coverage / next billing</th><th>Workspace</th></tr></thead><tbody>{data.subscriptions.length===0?<tr><td colSpan={6}>No Care clients yet.</td></tr>:data.subscriptions.map(s=>{const included=s.included||s.provider==="proposal_included";return <tr key={s.id}><td><strong>{s.piName}</strong><small>{s.institution}</small></td><td><strong>{s.planName}</strong><small>{included?"Included with project":`${money(s.priceAmount,s.currency)} / ${s.billingInterval}`}</small></td><td><span className={styles.badge} data-state={s.status}>{label(s.status)}</span></td><td>{included?"Included":fmt(s.lastPaymentAt)}</td><td>{fmt(s.nextBillingAt)}</td><td><Link href={`/admin/sales/${s.prospectId}/care`}>Open Care →</Link></td></tr>})}</tbody></table></div></section>
   <section className={`${styles.card} ${styles.wide}`}><div className={styles.cardHead}><div><p className={styles.eyebrow}>Maintenance inbox</p><h2>Client update requests</h2><p>Requests submitted from active Care portals appear here immediately.</p></div></div>{data.requests.length===0?<p className={styles.empty}>No Care update requests yet.</p>:data.requests.map(r=><article className={styles.request} key={r.id}><div><div className={styles.requestMeta}><span className={styles.badge} data-state={r.status}>{label(r.status)}</span><span>{label(r.category)}</span><span>{fmt(r.submittedAt)}</span><span>{r.piName}</span></div><h3>{r.subject}</h3><p>{r.details}</p><Link href={`/admin/sales/${r.prospectId}/care`}>Open client Care workspace →</Link></div><div className={styles.requestActions}>{r.status!=="reviewing"?<button disabled={busy===r.id} onClick={()=>void updateRequest(r.id,"reviewing")}>Reviewing</button>:null}{r.status!=="scheduled"?<button disabled={busy===r.id} onClick={()=>void updateRequest(r.id,"scheduled")}>Schedule</button>:null}{r.status!=="completed"?<button disabled={busy===r.id} onClick={()=>void updateRequest(r.id,"completed")}>Complete</button>:null}</div></article>)}</section>
  </div>
 </div></main>
}
