"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { browserSupabase as supabase } from "@/lib/supabase-browser";
import styles from "./care-workspace.module.css";

type Plan={id:string;name:string;billing_interval:string;price_amount:number|string;currency:string;provider_status:string};
type Offer={id:string;token:string;status:string;valid_until:string;view_count:number;shared_at?:string|null;selected_plan_id?:string|null;client_name?:string|null;client_email?:string|null};
type Sub={id:string;status:string;provider_subscription_id?:string|null;plan_name:string;billing_interval:string;price_amount:number|string;currency:string;subscriber_name?:string|null;subscriber_email?:string|null;started_at?:string|null;next_billing_at?:string|null;last_payment_at?:string|null};
type Req={id:string;status:string;category:string;subject:string;details:string;submitted_at:string;completed_at?:string|null;admin_notes?:string|null};
type Data={prospect:{id:string;pi_name:string;institution:string;department?:string|null};site?:{id:string;slug:string;domain_url?:string|null}|null;launch?:{status:string;handover_acknowledged_at?:string|null}|null;offer?:Offer|null;subscription?:Sub|null;plans:Plan[];requests:Req[]};
function fmt(v?:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function money(v:number|string,c:string){const n=Number(v||0)||0;try{return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD",maximumFractionDigits:2}).format(n)}catch{return`${c} ${n.toFixed(2)}`}}
function label(v?:string|null){return(v||"—").replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase())}

export default function ClientCareWorkspace(){
 const params=useParams<{prospectId:string}>();const prospectId=String(params?.prospectId||"");const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=useCallback(async()=>{if(!prospectId)return;setLoading(true);setError("");const{data:r,error:e}=await supabase.rpc("care_admin_get",{p_prospect_id:prospectId});if(e)setError(e.message);else setData(r as Data);setLoading(false)},[prospectId]);useEffect(()=>{void load()},[load]);
 const portal=useMemo(()=>data?.offer?`https://labnarrative.com/care/${data.offer.token}`:"",[data]);
 async function copy(){if(!portal)return;await navigator.clipboard.writeText(portal);setNotice("Care portal link copied.")}
 async function markShared(){setBusy("shared");const{error:e}=await supabase.rpc("care_admin_mark_shared",{p_prospect_id:prospectId});setBusy("");if(e)setError(e.message);else{setNotice("Care offer marked as shared.");await load()}}
 async function regenerate(){if(!confirm("Regenerate the Care link? The previous private link will stop working."))return;setBusy("regen");const{error:e}=await supabase.rpc("care_admin_regenerate_link",{p_prospect_id:prospectId});setBusy("");if(e)setError(e.message);else{setNotice("New Care link generated.");await load()}}
 async function cancelSub(){const sub=data?.subscription;if(!sub?.provider_subscription_id)return;if(!confirm("Cancel this recurring PayPal Care subscription? This stops future renewals."))return;setBusy("cancel");const{data:r,error:e}=await supabase.functions.invoke("paypal-care",{body:{action:"cancel_subscription",subscriptionId:sub.provider_subscription_id,reason:"Cancelled from LabNarrative Care workspace"}});setBusy("");if(e)setError(e.message);else if(r?.error)setError(String(r.error));else{setNotice("Care subscription cancelled in PayPal.");await load()}}
 async function updateRequest(id:string,status:string){setBusy(id);const{error:e}=await supabase.rpc("care_admin_request_update",{p_request_id:id,p_status:status,p_admin_notes:null});setBusy("");if(e)setError(e.message);else await load()}
 if(loading)return <main className={styles.state}><div><h1>Loading Care workspace…</h1></div></main>;
 if(!data)return <main className={styles.state}><div><h1>Care workspace unavailable</h1><p>{error||"Could not load this client."}</p></div></main>;
 if(!data.offer)return <main className={styles.state}><div><p className={styles.eyebrow}>LabNarrative Care</p><h1>Care is not open yet.</h1><p>The Care offer becomes available after the client acknowledges final website handover.</p><Link href={`/admin/sales/${prospectId}`}>Back to Sales workspace</Link></div></main>;
 const o=data.offer,s=data.subscription;
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.hero}><div><Link className={styles.back} href={`/admin/sales/${prospectId}`}>← Sales workspace</Link><p className={styles.eyebrow}>LabNarrative Care</p><h1>{data.prospect.pi_name}</h1><p>{data.prospect.institution}{data.prospect.department?` · ${data.prospect.department}`:""}</p></div><div className={styles.status}><span>Care status</span><strong>{label(s?.status||o.status)}</strong><small>{s?`${money(s.price_amount,s.currency)} / ${s.billing_interval}`:`Offer valid until ${fmt(o.valid_until)}`}</small></div></header>
  {notice?<p className={styles.notice}>{notice}</p>:null}{error?<p className={styles.error}>{error}</p>:null}
  <section className={styles.card}><div className={styles.cardHead}><div><p className={styles.eyebrow}>Private client portal</p><h2>{s?.status==="active"?"Care portal":"Care offer"}</h2><p>The same private link begins as the Care offer and becomes the maintenance-request portal after activation.</p></div><span className={styles.badge} data-state={s?.status||o.status}>{label(s?.status||o.status)}</span></div><div className={styles.meta}><article><span>Views</span><strong>{o.view_count||0}</strong></article><article><span>Shared</span><strong>{fmt(o.shared_at)}</strong></article><article><span>Client</span><strong>{s?.subscriber_name||o.client_name||"—"}</strong></article><article><span>Email</span><strong>{s?.subscriber_email||o.client_email||"—"}</strong></article></div><div className={styles.actions}><a className={styles.primary} href={portal} target="_blank" rel="noreferrer">Open client portal ↗</a><button onClick={()=>void copy()}>Copy portal link</button>{!s||s.status==="approval_pending"?<button disabled={busy==="shared"} onClick={()=>void markShared()}>{busy==="shared"?"Saving…":"Mark offer shared"}</button>:null}{!s||!["active","suspended"].includes(s.status)?<button disabled={busy==="regen"} onClick={()=>void regenerate()}>Regenerate link</button>:null}<Link href="/admin/care">Open Care dashboard</Link></div></section>
  <section className={styles.card}><div className={styles.cardHead}><div><p className={styles.eyebrow}>Subscription</p><h2>{s?s.plan_name:"No subscription yet"}</h2><p>{s?`PayPal subscription ${label(s.status)}.`:"The client can choose any active Care billing option from the private portal."}</p></div>{s?<span className={styles.badge} data-state={s.status}>{label(s.status)}</span>:null}</div>{s?<div className={styles.meta}><article><span>Price</span><strong>{money(s.price_amount,s.currency)} / {s.billing_interval}</strong></article><article><span>Started</span><strong>{fmt(s.started_at)}</strong></article><article><span>Last payment</span><strong>{fmt(s.last_payment_at)}</strong></article><article><span>Next billing</span><strong>{fmt(s.next_billing_at)}</strong></article></div>:<div className={styles.planGrid}>{data.plans.map(p=><article className={styles.plan} key={p.id}><span className={styles.badge}>{label(p.billing_interval)}</span><h3>{p.name}</h3><div className={styles.price}>{money(p.price_amount,p.currency)} / {p.billing_interval}</div><p>Provider: {label(p.provider_status)}</p></article>)}</div>}{s&&["active","suspended"].includes(s.status)?<div className={styles.actions}><button className={styles.danger} disabled={busy==="cancel"} onClick={()=>void cancelSub()}>{busy==="cancel"?"Cancelling…":"Cancel recurring subscription"}</button></div>:null}</section>
  <section className={styles.card}><div className={styles.cardHead}><div><p className={styles.eyebrow}>Care requests</p><h2>Website maintenance queue</h2><p>Client requests submitted from the Care portal appear here and in the global Care dashboard.</p></div></div>{data.requests.length===0?<p>No Care update requests yet.</p>:data.requests.map(r=><article className={styles.request} key={r.id}><div><div className={styles.requestMeta}><span className={styles.badge} data-state={r.status}>{label(r.status)}</span><span>{label(r.category)}</span><span>{fmt(r.submitted_at)}</span></div><h3>{r.subject}</h3><p>{r.details}</p></div><div className={styles.requestActions}>{r.status!=="reviewing"?<button disabled={busy===r.id} onClick={()=>void updateRequest(r.id,"reviewing")}>Reviewing</button>:null}{r.status!=="scheduled"?<button disabled={busy===r.id} onClick={()=>void updateRequest(r.id,"scheduled")}>Scheduled</button>:null}{r.status!=="completed"?<button disabled={busy===r.id} onClick={()=>void updateRequest(r.id,"completed")}>Complete</button>:null}</div></article>)}</section>
 </div></main>
}
