"use client";

import { useMemo, useState } from "react";
import styles from "../medical-masar/v2.module.css";

type Lang = "en" | "ar";
type Theme = "light" | "dark";
type View = "overview" | "tenders" | "quotes" | "orders" | "warehouse" | "supply" | "invoices" | "collection" | "management" | "accounts" | "automation" | "ai";
type Bi = string | { en?: string; ar?: string };
type Account = { name: Bi; type?: Bi; region?: Bi; division?: Bi; owner?: Bi; health?: number; value?: number; contacts?: number };
type Opportunity = { account?: Bi; title: Bi; value?: number; score?: number; stage?: Bi; division?: Bi };
type LegacyRow = { title: Bi; account?: Bi; status?: Bi; value?: number; when?: Bi; owner?: Bi; meta?: Bi };
type Workflow = { name: Bi; detail?: Bi; enabled?: boolean };
type Tender = { id: string; customerId: number; title: Bi; value: number; items: number; deadline: Bi; daysLeft: number; readiness: number; missing: number; owner: Bi; status: Bi };
type Quote = { id: string; customerId: number; value: number; items: number; verified: number; errors: number; status: Bi; next: Bi };
type Order = { id: string; customerId: number; source: string; value: number; items: number; ready: number; missing: number; due: Bi; status: Bi };
type StockLine = { sku: string; name: Bi; stock: number; reserved: number; needed: number; available: number; status: Bi };
type SupplyLine = { no: number; sku: string; item: Bi; qty: number; allocated: number; source: Bi; status: Bi };
type Invoice = { id: string; customerId: number; order: string; amount: number; issued: Bi; due: Bi; paid: number; status: Bi };
type CollectionAction = { invoice: string; customerId: number; amount: number; overdue: number; owner: Bi; action: Bi; status: Bi };
type DemoConfig = {
  shortName?: Bi; tagline?: Bi; conceptLabel?: Bi; currency?: string; aiBrief?: Bi; reportSummary?: Bi;
  accounts?: Account[]; opportunities?: Opportunity[]; quotes?: LegacyRow[]; tenders?: LegacyRow[]; workflows?: Workflow[];
  orders?: Order[]; warehouse?: StockLine[]; supplyLines?: SupplyLine[]; invoices?: Invoice[]; collectionActions?: CollectionAction[];
};

const B = (en: string, ar: string): { en: string; ar: string } => ({ en, ar });
const nav: Array<{ id: View; icon: string; label: { en: string; ar: string }; core?: boolean }> = [
  { id: "overview", icon: "◫", label: B("Overview", "نظرة عامة") },
  { id: "tenders", icon: "◇", label: B("Tenders", "المناقصات"), core: true },
  { id: "quotes", icon: "▤", label: B("Quotations", "عروض الأسعار"), core: true },
  { id: "orders", icon: "▦", label: B("Orders", "الطلبات"), core: true },
  { id: "warehouse", icon: "▧", label: B("Warehouse", "المستودع"), core: true },
  { id: "supply", icon: "↗", label: B("Supply", "التوريد"), core: true },
  { id: "invoices", icon: "▱", label: B("Invoices", "الفواتير"), core: true },
  { id: "collection", icon: "◉", label: B("Collection", "التحصيل"), core: true },
  { id: "management", icon: "▥", label: B("Management", "الإدارة") },
  { id: "accounts", icon: "◎", label: B("Customers", "العملاء") },
  { id: "automation", icon: "↯", label: B("Automation", "الأتمتة") },
  { id: "ai", icon: "✦", label: B("AI Command Center", "مركز الذكاء الاصطناعي") },
];

const fallbackAccounts: Account[] = [
  { name: B("Priority institutional laboratory", "مختبر مؤسسي ذو أولوية"), type: B("Institutional customer", "عميل مؤسسي"), region: B("Central region", "المنطقة الوسطى"), division: B("Core solutions", "الحلول الأساسية"), owner: B("Sales team", "فريق المبيعات"), value: 176000, contacts: 3 },
  { name: B("Regional laboratory group", "مجموعة مختبرات إقليمية"), type: B("Commercial account", "حساب تجاري"), region: B("Western region", "المنطقة الغربية"), division: B("Specialized solutions", "الحلول المتخصصة"), owner: B("Regional sales", "المبيعات الإقليمية"), value: 310000, contacts: 4 },
  { name: B("University research center", "مركز أبحاث جامعي"), type: B("Research account", "حساب بحثي"), region: B("Central region", "المنطقة الوسطى"), division: B("Scientific products", "المنتجات العلمية"), owner: B("Key accounts", "الحسابات الرئيسية"), value: 128000, contacts: 3 },
  { name: B("Government laboratory", "مختبر حكومي"), type: B("Government account", "حساب حكومي"), region: B("Western region", "المنطقة الغربية"), division: B("Projects", "المشاريع"), owner: B("Projects team", "فريق المشاريع"), value: 142000, contacts: 3 },
];

const fallbackWorkflows: Workflow[] = [
  { name: B("Tender deadline countdown & escalation", "العد التنازلي للمناقصات والتصعيد"), detail: B("Surface deadlines, owners, readiness and missing requirements before risk appears.", "إظهار المواعيد والمسؤولين والجاهزية والمتطلبات الناقصة قبل ظهور المخاطر."), enabled: true },
  { name: B("Quotation validation before send", "التحقق من عرض السعر قبل الإرسال"), detail: B("Validate requested lines, quantities and technical review before customer delivery.", "التحقق من البنود والكميات والمراجعة الفنية قبل إرسال العرض للعميل."), enabled: true },
  { name: B("Order completeness gate before dispatch", "بوابة اكتمال الطلب قبل الشحن"), detail: B("Block incomplete orders until every required line is allocated.", "منع خروج الطلب غير المكتمل حتى يتم تخصيص كل البنود المطلوبة."), enabled: true },
  { name: B("Warehouse shortage & supplier alert", "تنبيه نقص المستودع والمورد"), detail: B("Connect shortages directly to the affected customer order and supplier action.", "ربط النقص مباشرة بطلب العميل وإجراء المورد المطلوب."), enabled: true },
  { name: B("Invoice and collection reminders", "تذكيرات الفواتير والتحصيل"), detail: B("Surface due and overdue balances with clear owners and next actions.", "إظهار المستحق والمتأخر مع المسؤول والإجراء التالي بوضوح."), enabled: true },
];

const safe = (value: number | undefined, fallback: number) => typeof value === "number" && Number.isFinite(value) ? value : fallback;

export default function MasterOperationsDemoClient({ companyName, industry, location, config: rawConfig }: { companyName: string; industry: string; location: string; config: Record<string, unknown> }) {
  const config = rawConfig as DemoConfig;
  const [lang, setLang] = useState<Lang>("en");
  const [theme, setTheme] = useState<Theme>("light");
  const [active, setActive] = useState<View>("overview");
  const [selectedOrder, setSelectedOrder] = useState("SO-2026-041");
  const [toast, setToast] = useState("");
  const [automationState, setAutomationState] = useState<Record<number, boolean>>(() => Object.fromEntries((config.workflows ?? fallbackWorkflows).map((_, i) => [i, true])));
  const [aiMode, setAiMode] = useState<"risk" | "tender" | "supply" | "cash">("risk");

  const L = (value: Bi | undefined): string => !value ? "" : typeof value === "string" ? value : value[lang] ?? value.en ?? value.ar ?? "";
  const num = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value);
  const money = (value: number) => new Intl.NumberFormat("en-SA", { style: "currency", currency: config.currency ?? "SAR", maximumFractionDigits: 0 }).format(value);
  const pct = (value: number) => `${num(value)}%`;
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 1600); };

  const accounts = config.accounts?.length ? config.accounts : fallbackAccounts;
  const opportunities = config.opportunities?.length ? config.opportunities : [];
  const legacyTenders = config.tenders ?? [];
  const legacyQuotes = config.quotes ?? [];
  const workflows = config.workflows?.length ? config.workflows : fallbackWorkflows;
  const shortName = L(config.shortName) || companyName;
  const accountName = (id: number) => L(accounts[id - 1]?.name) || (lang === "ar" ? `عميل ${id}` : `Customer ${id}`);
  const accountByBi = (value: Bi | undefined, fallbackId: number) => {
    const en = typeof value === "string" ? value : value?.en;
    const idx = accounts.findIndex((a) => (typeof a.name === "string" ? a.name : a.name.en) === en);
    return idx >= 0 ? idx + 1 : fallbackId;
  };

  const tenders: Tender[] = legacyTenders.length ? legacyTenders.slice(0, 3).map((t, i) => ({
    id: `TND-2026-${String(i + 14).padStart(3, "0")}`, customerId: accountByBi(t.account, Math.min(i + 1, accounts.length)), title: t.title,
    value: safe(t.value, safe(accounts[i]?.value, [176000, 310000, 142000][i] ?? 142000)), items: [24, 41, 18][i] ?? 20,
    deadline: t.when ?? B(["22 Aug 2026", "31 Aug 2026", "7 Sep 2026"][i] ?? "7 Sep 2026", ["22 أغسطس 2026", "31 أغسطس 2026", "7 سبتمبر 2026"][i] ?? "7 سبتمبر 2026"),
    daysLeft: [8, 17, 24][i] ?? 20, readiness: [83, 68, 52][i] ?? 70, missing: [2, 5, 4][i] ?? 2, owner: t.owner ?? B("Tender team", "فريق المناقصات"), status: t.status ?? B("In progress", "قيد العمل")
  })) : [
    { id: "TND-2026-014", customerId: 1, title: opportunities[0]?.title ?? B("Priority laboratory tender", "مناقصة مختبرية ذات أولوية"), value: safe(accounts[0]?.value, 176000), items: 24, deadline: B("22 Aug 2026", "22 أغسطس 2026"), daysLeft: 8, readiness: 83, missing: 2, owner: B("Tender team", "فريق المناقصات"), status: B("Documents in progress", "المستندات قيد التجهيز") },
    { id: "TND-2026-019", customerId: Math.min(2, accounts.length), title: opportunities[1]?.title ?? B("Scientific equipment framework", "إطار توريد أجهزة علمية"), value: safe(accounts[1]?.value, 310000), items: 41, deadline: B("31 Aug 2026", "31 أغسطس 2026"), daysLeft: 17, readiness: 68, missing: 5, owner: B("Applications + Sales", "التطبيقات + المبيعات"), status: B("Technical review", "مراجعة فنية") },
    { id: "TND-2026-023", customerId: Math.min(3, accounts.length), title: opportunities[2]?.title ?? B("Laboratory consumables package", "حزمة مستهلكات مختبرية"), value: safe(accounts[2]?.value, 142000), items: 18, deadline: B("7 Sep 2026", "7 سبتمبر 2026"), daysLeft: 24, readiness: 52, missing: 4, owner: B("Regional sales", "المبيعات الإقليمية"), status: B("Preparing", "قيد التحضير") },
  ];

  const quotes: Quote[] = legacyQuotes.length ? legacyQuotes.slice(0, 3).map((q, i) => ({
    id: `Q-2026-${[84, 79, 71][i] ?? 70 - i}`, customerId: accountByBi(q.account, Math.min(i + 1, accounts.length)), value: safe(q.value, safe(accounts[i]?.value, 128000)), items: [24, 18, 32][i] ?? 20,
    verified: [24, 18, 31][i] ?? 20, errors: [0, 0, 1][i] ?? 0, status: q.status ?? B("Sent", "مرسل"), next: q.when ?? B("Follow up today", "متابعة اليوم")
  })) : [
    { id: "Q-2026-084", customerId: 1, value: safe(accounts[0]?.value, 128000), items: 24, verified: 24, errors: 0, status: B("Viewed by customer", "شاهده العميل"), next: B("Follow up today", "متابعة اليوم") },
    { id: "Q-2026-079", customerId: Math.min(2, accounts.length), value: safe(accounts[1]?.value, 98000), items: 18, verified: 18, errors: 0, status: B("Sent", "مرسل"), next: B("Follow up in 2 days", "متابعة بعد يومين") },
    { id: "Q-2026-071", customerId: Math.min(3, accounts.length), value: safe(accounts[2]?.value, 215000), items: 32, verified: 31, errors: 1, status: B("Technical revision", "مراجعة فنية"), next: B("Resolve one line mismatch", "حل اختلاف في بند واحد") },
  ];

  const orders: Order[] = config.orders?.length ? config.orders : [
    { id: "SO-2026-041", customerId: 1, source: tenders[0].id, value: tenders[0].value, items: 24, ready: 21, missing: 3, due: B("19 Aug 2026", "19 أغسطس 2026"), status: B("At risk · incomplete", "معرض للخطر · غير مكتمل") },
    { id: "SO-2026-038", customerId: Math.min(2, accounts.length), source: quotes[2]?.id ?? quotes[0].id, value: quotes[2]?.value ?? quotes[0].value, items: 32, ready: 32, missing: 0, due: B("18 Aug 2026", "18 أغسطس 2026"), status: B("Ready to dispatch", "جاهز للشحن") },
    { id: "SO-2026-034", customerId: Math.min(3, accounts.length), source: quotes[1]?.id ?? quotes[0].id, value: quotes[1]?.value ?? quotes[0].value, items: 18, ready: 18, missing: 0, due: B("Delivered 12 Aug", "تم التسليم 12 أغسطس"), status: B("Delivered", "تم التسليم") },
  ];

  const warehouse: StockLine[] = config.warehouse?.length ? config.warehouse : [
    { sku: "LAB-SYS-112", name: B("Primary instrument / kit line", "بند الجهاز / الطقم الرئيسي"), stock: 9, reserved: 8, needed: 8, available: 1, status: B("Ready", "جاهز") },
    { sku: "LAB-BUF-204", name: B("Core consumable", "مستهلك أساسي"), stock: 4, reserved: 4, needed: 4, available: 0, status: B("Ready", "جاهز") },
    { sku: "LAB-CRIT-037", name: B("Critical specialist item", "صنف تخصصي حرج"), stock: 1, reserved: 1, needed: 2, available: 0, status: B("1 unit missing", "وحدة واحدة ناقصة") },
    { sku: "LAB-ACC-082", name: B("Accessory pack", "حزمة ملحقات"), stock: 12, reserved: 10, needed: 10, available: 2, status: B("Ready", "جاهز") },
    { sku: "LAB-RGT-051", name: B("Specialist reagent / component", "كاشف / مكوّن تخصصي"), stock: 0, reserved: 0, needed: 2, available: 0, status: B("2 units missing", "وحدتان ناقصتان") },
  ];

  const supplyLines: SupplyLine[] = config.supplyLines?.length ? config.supplyLines : [
    { no: 1, sku: warehouse[0].sku, item: warehouse[0].name, qty: 8, allocated: 8, source: B("Main warehouse", "المستودع الرئيسي"), status: B("Ready", "جاهز") },
    { no: 2, sku: warehouse[1].sku, item: warehouse[1].name, qty: 4, allocated: 4, source: B("Main warehouse", "المستودع الرئيسي"), status: B("Ready", "جاهز") },
    { no: 3, sku: warehouse[2].sku, item: warehouse[2].name, qty: 2, allocated: 1, source: B("Supplier PO pending", "طلب المورد قيد الانتظار"), status: B("Missing 1", "ناقص 1") },
    { no: 4, sku: warehouse[3].sku, item: warehouse[3].name, qty: 10, allocated: 10, source: B("Regional warehouse", "المستودع الإقليمي"), status: B("Ready", "جاهز") },
    { no: 5, sku: warehouse[4].sku, item: warehouse[4].name, qty: 2, allocated: 0, source: B("Supplier ETA 17 Aug", "وصول المورد 17 أغسطس"), status: B("Missing 2", "ناقص 2") },
    { no: 6, sku: "LAB-QC-008", item: B("QC / control item", "صنف ضبط جودة"), qty: 3, allocated: 3, source: B("Main warehouse", "المستودع الرئيسي"), status: B("Ready", "جاهز") },
  ];

  const invoices: Invoice[] = config.invoices?.length ? config.invoices : [
    { id: "INV-260811", customerId: Math.min(2, accounts.length), order: orders[1]?.id ?? orders[0].id, amount: orders[1]?.value ?? 215000, issued: B("11 Aug 2026", "11 أغسطس 2026"), due: B("29 Aug 2026", "29 أغسطس 2026"), paid: 0, status: B("Issued", "صادرة") },
    { id: "INV-260804", customerId: Math.min(3, accounts.length), order: orders[2]?.id ?? orders[0].id, amount: Math.min(98000, orders[2]?.value ?? 98000), issued: B("4 Aug 2026", "4 أغسطس 2026"), due: B("18 Aug 2026", "18 أغسطس 2026"), paid: 24000, status: B("Partially paid", "مدفوعة جزئيًا") },
    { id: "INV-260715", customerId: 1, order: "SO-2026-027", amount: 86000, issued: B("15 Jul 2026", "15 يوليو 2026"), due: B("30 Jul 2026", "30 يوليو 2026"), paid: 0, status: B("Overdue", "متأخرة") },
    { id: "INV-260703", customerId: Math.min(3, accounts.length), order: "SO-2026-023", amount: 128000, issued: B("3 Jul 2026", "3 يوليو 2026"), due: B("3 Aug 2026", "3 أغسطس 2026"), paid: 0, status: B("Overdue", "متأخرة") },
  ];

  const collections: CollectionAction[] = config.collectionActions?.length ? config.collectionActions : [
    { invoice: invoices[2].id, customerId: invoices[2].customerId, amount: invoices[2].amount - invoices[2].paid, overdue: 15, owner: B("Finance", "المالية"), action: B("Call procurement + resend statement", "الاتصال بالمشتريات + إعادة إرسال كشف الحساب"), status: B("Escalated", "تم التصعيد") },
    { invoice: invoices[3].id, customerId: invoices[3].customerId, amount: invoices[3].amount - invoices[3].paid, overdue: 11, owner: B("Collection team", "فريق التحصيل"), action: B("Finance manager follow-up today", "متابعة مدير المالية اليوم"), status: B("Due today", "مستحق اليوم") },
    { invoice: invoices[1].id, customerId: invoices[1].customerId, amount: invoices[1].amount - invoices[1].paid, overdue: 0, owner: B("Finance", "المالية"), action: B("Balance reminder before due date", "تذكير بالرصيد قبل الاستحقاق"), status: B("Scheduled", "مجدول") },
  ];

  const outstanding = invoices.reduce((sum, x) => sum + (x.amount - x.paid), 0);
  const overdue = invoices.filter((x) => L(x.status).toLowerCase().includes(lang === "ar" ? "متأخرة" : "overdue")).reduce((sum, x) => sum + (x.amount - x.paid), 0);
  const totalInvoiced = invoices.reduce((sum, x) => sum + x.amount, 0);
  const openTenderValue = tenders.reduce((sum, x) => sum + x.value, 0);
  const selected = useMemo(() => orders.find((x) => x.id === selectedOrder) ?? orders[0], [orders, selectedOrder]);
  const title = nav.find((n) => n.id === active)?.label ?? nav[0].label;

  const aiText = aiMode === "tender"
    ? (lang === "ar" ? `المناقصة ${tenders[0].id} تغلق خلال ${num(tenders[0].daysLeft)} أيام وجاهزيتها ${pct(tenders[0].readiness)} مع نقص ${num(tenders[0].missing)} متطلبات. يجب أن تكون أول تصعيد اليوم.` : `${tenders[0].id} closes in ${num(tenders[0].daysLeft)} days and is ${pct(tenders[0].readiness)} ready with ${num(tenders[0].missing)} missing requirements. It should be the first escalation today.`)
    : aiMode === "cash"
      ? (lang === "ar" ? `إجمالي المبالغ غير المحصلة ${money(outstanding)}، منها ${money(overdue)} متأخرة. أعطِ الأولوية للفواتير المتأخرة ثم حافظ على متابعة الأرصدة الجزئية.` : `Outstanding receivables are ${money(outstanding)}, including ${money(overdue)} overdue. Prioritise overdue invoices and keep partial balances on schedule.`)
      : aiMode === "supply"
        ? (lang === "ar" ? `الطلب ${selected.id} هو أوضح استثناء في التوريد: يوجد ${num(selected.missing)} وحدات ناقصة. اربط متابعة المورد مباشرة ببنود الطلب ولا تسمح بالشحن قبل اكتماله.` : `${selected.id} is the clearest supply exception: ${num(selected.missing)} units are missing. Tie supplier follow-up directly to the order lines and do not release dispatch until complete.`)
        : (lang === "ar" ? `لا تشحن الطلب ${selected.id} الآن. تم تجهيز ${num(selected.ready)} من ${num(selected.items)} بندًا، وما زالت ${num(selected.missing)} وحدات ناقصة. عالج البنود الناقصة أولًا ثم حرر الطلب.` : `Do not dispatch ${selected.id} yet. ${num(selected.ready)} of ${num(selected.items)} items are ready and ${num(selected.missing)} units are still missing. Resolve the missing lines first, then release the order.`);

  const Head = ({ eyebrow, heading, copy }: { eyebrow: Bi; heading: Bi; copy: Bi }) => <div className={styles.sectionHeader}><div><small>{L(eyebrow)}</small><h2>{L(heading)}</h2><p>{L(copy)}</p></div></div>;
  const Metric = ({ a, b, c, danger = false }: { a: string; b: string; c: string; danger?: boolean }) => <article className={`${styles.metric} ${danger ? styles.metricDanger : ""}`}><span>{a}</span><strong>{b}</strong><small>{c}</small></article>;
  const Report = ({ a, b, c, danger = false }: { a: string; b: string; c: string; danger?: boolean }) => <article className={`${styles.reportCard} ${danger ? styles.metricDanger : ""}`}><span>{a}</span><strong>{b}</strong><small>{c}</small></article>;
  const flow = <div className={styles.flowRail}>{nav.filter((n) => n.core || n.id === "management").map((n, i, arr) => <div key={n.id} className={styles.flowStepWrap}><button className={styles.flowStep} onClick={() => setActive(n.id)}><i>{n.icon}</i><strong>{L(n.label)}</strong></button>{i < arr.length - 1 ? <span className={styles.flowArrow}>{lang === "ar" ? "←" : "→"}</span> : null}</div>)}</div>;

  const renderOverview = () => <>
    <section className={styles.heroStrip}><div><span>{lang === "ar" ? "نظام تشغيل مخصص للأعمال والتوريد" : "Tailored commercial operations system"}</span><h2>{L(config.tagline) || (lang === "ar" ? "من المناقصة إلى التحصيل — بدون فقدان بند واحد" : "From tender to collection — without losing a single line item")}</h2><p>{lang === "ar" ? "تصور يربط المناقصات وعروض الأسعار والطلبات والمستودع والتوريد والفواتير والتحصيل في رحلة واحدة أمام الفريق والإدارة." : "A tailored concept connecting tenders, quotations, orders, warehouse, supply, invoicing and collections in one continuous workflow for teams and management."}</p></div><button className={styles.primary} onClick={() => setActive("supply")}>{lang === "ar" ? "شاهد طلبًا فيه نواقص" : "See an incomplete order"}</button></section>
    {flow}
    <section className={styles.metricGrid}><Metric a={lang === "ar" ? "المناقصات المفتوحة" : "Open tenders"} b={num(tenders.length)} c={money(openTenderValue)} /><Metric a={lang === "ar" ? "طلبات تحت التوريد" : "Orders in supply"} b={num(orders.filter((o) => !L(o.status).includes(lang === "ar" ? "تم التسليم" : "Delivered")).length)} c={lang === "ar" ? "متابعة مباشرة لكل بند" : "Line-by-line tracking"} /><Metric a={lang === "ar" ? "وحدات ناقصة" : "Missing units"} b={num(orders.reduce((s, o) => s + o.missing, 0))} c={lang === "ar" ? "يمنع الشحن حتى الحل" : "Dispatch blocked until resolved"} danger /><Metric a={lang === "ar" ? "مبالغ غير محصلة" : "Outstanding receivables"} b={money(outstanding)} c={`${money(overdue)} ${lang === "ar" ? "متأخرة" : "overdue"}`} /></section>
    <section className={styles.grid2}><article className={styles.panel}><div className={styles.panelHead}><div><small>{lang === "ar" ? "استثناء تشغيلي" : "OPERATING EXCEPTION"}</small><h2>{lang === "ar" ? "طلب لا يجب أن يخرج ناقصًا" : "An order that must not leave incomplete"}</h2></div><button onClick={() => { setSelectedOrder(orders[0].id); setActive("supply"); }}>{lang === "ar" ? "فتح الطلب" : "Open order"}</button></div><div className={styles.exceptionCard}><div className={styles.exceptionTop}><div><strong>{orders[0].id}</strong><p>{accountName(orders[0].customerId)} · {money(orders[0].value)}</p></div><span className={styles.badgeDanger}>{lang === "ar" ? "لا تشحن" : "DO NOT DISPATCH"}</span></div><div className={styles.bigProgress}><i style={{ width: `${(orders[0].ready / orders[0].items) * 100}%` }} /></div><div className={styles.progressMeta}><span>{lang === "ar" ? `${num(orders[0].ready)} من ${num(orders[0].items)} بند جاهز` : `${num(orders[0].ready)} of ${num(orders[0].items)} items ready`}</span><strong>{lang === "ar" ? `${num(orders[0].missing)} وحدات ناقصة` : `${num(orders[0].missing)} units missing`}</strong></div><div className={styles.shortages}><span>{warehouse[2].sku} · {lang === "ar" ? "ناقص 1" : "missing 1"}</span><span>{warehouse[4].sku} · {lang === "ar" ? "ناقص 2" : "missing 2"}</span></div></div></article><article className={styles.aiCard}><small>{lang === "ar" ? "ملخص الإدارة بالذكاء الاصطناعي" : "AI MANAGEMENT BRIEF"}</small><h2>{lang === "ar" ? "ما الذي يحتاج تدخل اليوم؟" : "What needs intervention today?"}</h2><p>{aiText}</p><div className={styles.quickPrompts}><button onClick={() => setAiMode("risk")}>{lang === "ar" ? "مخاطر التشغيل" : "Operational risk"}</button><button onClick={() => setAiMode("tender")}>{lang === "ar" ? "المناقصات" : "Tenders"}</button><button onClick={() => setAiMode("cash")}>{lang === "ar" ? "التحصيل" : "Collections"}</button></div></article></section>
  </>;

  const renderTenders = () => <><Head eyebrow={B("Replace spreadsheet tracking", "بديل متابعة الإكسل")} heading={B("Tenders", "المناقصات")} copy={B("One shared board with countdowns, owners, readiness, missing work and management visibility.", "لوحة مشتركة تعرض الوقت المتبقي والمسؤول ونسبة الجاهزية والنواقص أمام الفريق والإدارة.")} /><section className={styles.tenderGrid}>{tenders.map((t) => <article className={styles.tenderCard} key={t.id}><header><div><small>{t.id}</small><h3>{L(t.title)}</h3><p>{accountName(t.customerId)}</p></div><div className={styles.countdown}><strong>{num(t.daysLeft)}</strong><span>{lang === "ar" ? "يوم متبقي" : "days left"}</span></div></header><div className={styles.tenderStats}><div><span>{lang === "ar" ? "القيمة" : "Value"}</span><strong>{money(t.value)}</strong></div><div><span>{lang === "ar" ? "البنود" : "Items"}</span><strong>{num(t.items)}</strong></div><div><span>{lang === "ar" ? "النواقص" : "Missing"}</span><strong className={t.missing ? styles.textDanger : ""}>{num(t.missing)}</strong></div></div><div className={styles.readiness}><div><span>{lang === "ar" ? "الجاهزية" : "Readiness"}</span><strong>{pct(t.readiness)}</strong></div><div className={styles.progress}><i style={{ width: `${t.readiness}%` }} /></div></div><footer><div><span>{L(t.deadline)}</span><small>{L(t.owner)}</small></div><button className={styles.secondary} onClick={() => notify(lang === "ar" ? "تم فتح قائمة النواقص" : "Checklist opened")}>{lang === "ar" ? "قائمة النواقص" : "Checklist"}</button></footer></article>)}</section></>;
  const renderQuotes = () => <><Head eyebrow={B("Error prevention before send", "منع الخطأ قبل الإرسال")} heading={B("Quotations", "عروض الأسعار")} copy={B("Validate every requested line, quantity and technical requirement before the quotation reaches the customer.", "التحقق من كل بند وكمية ومتطلب فني قبل وصول عرض السعر للعميل.")} /><article className={styles.panel}>{quotes.map((q) => <div className={styles.dataRow} key={q.id}><div className={styles.rowTitle}><strong>{q.id}</strong><small>{accountName(q.customerId)}</small></div><div className={styles.rowCell}><span>{lang === "ar" ? "القيمة" : "Value"}</span><strong>{money(q.value)}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "البنود" : "Lines"}</span><strong>{num(q.items)}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "تم التحقق" : "Verified"}</span><strong>{num(q.verified)}/{num(q.items)}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "الأخطاء" : "Errors"}</span><strong className={q.errors ? styles.textDanger : styles.textGood}>{num(q.errors)}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "الحالة" : "Status"}</span><strong>{L(q.status)}</strong><small>{L(q.next)}</small></div></div>)}</article></>;
  const renderOrders = () => <><Head eyebrow={B("Won work becomes execution", "تحويل الفوز إلى تنفيذ")} heading={B("Orders", "الطلبات")} copy={B("Every won tender or accepted quotation becomes a controlled fulfilment record with item-level completeness.", "كل مناقصة فائزة أو عرض مقبول يتحول إلى سجل تنفيذ مضبوط مع متابعة اكتمال كل بند.")} /><div className={styles.orderGrid}>{orders.map((o) => <button key={o.id} className={`${styles.orderCard} ${o.missing ? styles.orderRisk : ""}`} onClick={() => { setSelectedOrder(o.id); setActive("supply"); }}><header><div><small>{o.source} →</small><h3>{o.id}</h3><p>{accountName(o.customerId)}</p></div><span className={o.missing ? styles.badgeDanger : styles.badgeGood}>{L(o.status)}</span></header><div className={styles.orderValue}>{money(o.value)}</div><div className={styles.bigProgress}><i style={{ width: `${(o.ready / o.items) * 100}%` }} /></div><footer><span>{lang === "ar" ? `${num(o.ready)} / ${num(o.items)} بند جاهز` : `${num(o.ready)} / ${num(o.items)} items ready`}</span><strong className={o.missing ? styles.textDanger : styles.textGood}>{o.missing ? `${num(o.missing)} ${lang === "ar" ? "ناقص" : "missing"}` : (lang === "ar" ? "مكتمل" : "Complete")}</strong></footer></button>)}</div></>;
  const renderWarehouse = () => <><Head eyebrow={B("Stock connected to customer commitments", "المخزون مرتبط بالتزامات العملاء")} heading={B("Warehouse", "المستودع")} copy={B("See what is available, reserved and which order line will fail before dispatch.", "اعرف ما هو متوفر ومحجوز وأي بند سيسبب مشكلة قبل الشحن.")} /><article className={styles.panel}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>SKU</th><th>{lang === "ar" ? "الصنف" : "Item"}</th><th>{lang === "ar" ? "المخزون" : "Stock"}</th><th>{lang === "ar" ? "محجوز" : "Reserved"}</th><th>{lang === "ar" ? "مطلوب" : "Needed"}</th><th>{lang === "ar" ? "متاح" : "Available"}</th><th>{lang === "ar" ? "الحالة" : "Status"}</th></tr></thead><tbody>{warehouse.map((w) => <tr key={w.sku}><td><strong>{w.sku}</strong></td><td>{L(w.name)}</td><td>{num(w.stock)}</td><td>{num(w.reserved)}</td><td>{num(w.needed)}</td><td>{num(w.available)}</td><td><span className={w.status && L(w.status).includes(lang === "ar" ? "جاهز" : "Ready") ? styles.badgeGood : styles.badgeDanger}>{L(w.status)}</span></td></tr>)}</tbody></table></div></article></>;
  const renderSupply = () => <><Head eyebrow={B("No incomplete delivery", "لا توريد ناقص")} heading={B("Supply & fulfilment", "التوريد والتنفيذ")} copy={B("Track every line until the complete customer order is ready. Missing lines remain visible and can block dispatch.", "متابعة كل بند حتى يكتمل طلب العميل بالكامل. البنود الناقصة تبقى ظاهرة ويمكنها منع الشحن.")} /><section className={styles.supplyHero}><div><small>{lang === "ar" ? "الطلب المحدد" : "SELECTED ORDER"}</small><h2>{selected.id}</h2><p>{accountName(selected.customerId)} · {money(selected.value)} · {L(selected.due)}</p></div><div className={styles.completionBox}><strong>{num(selected.ready)}/{num(selected.items)}</strong><span>{lang === "ar" ? "بند جاهز" : "items ready"}</span></div><div className={selected.missing ? styles.dispatchBlocked : styles.dispatchReady}><strong>{selected.missing ? (lang === "ar" ? "الشحن محظور" : "DISPATCH BLOCKED") : (lang === "ar" ? "جاهز للشحن" : "READY TO DISPATCH")}</strong><span>{selected.missing ? `${num(selected.missing)} ${lang === "ar" ? "وحدات ناقصة" : "units missing"}` : (lang === "ar" ? "كل البنود مكتملة" : "All lines complete")}</span></div></section>{selected.id === orders[0].id ? <article className={styles.panel}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>#</th><th>SKU</th><th>{lang === "ar" ? "البند" : "Line item"}</th><th>{lang === "ar" ? "الكمية" : "Qty"}</th><th>{lang === "ar" ? "المخصص" : "Allocated"}</th><th>{lang === "ar" ? "المصدر" : "Source"}</th><th>{lang === "ar" ? "الحالة" : "Status"}</th></tr></thead><tbody>{supplyLines.map((x) => <tr key={x.no} className={x.allocated < x.qty ? styles.riskRow : ""}><td>{num(x.no)}</td><td><strong>{x.sku}</strong></td><td>{L(x.item)}</td><td>{num(x.qty)}</td><td>{num(x.allocated)}</td><td>{L(x.source)}</td><td><span className={x.allocated < x.qty ? styles.badgeDanger : styles.badgeGood}>{L(x.status)}</span></td></tr>)}</tbody></table></div><div className={styles.tableNote}>{lang === "ar" ? "النظام الفعلي يتابع كل بند حتى اكتماله ويربط النقص مباشرة بالمورد والطلب." : "A production system tracks every line to completion and ties shortages directly to the supplier and order."}</div></article> : <article className={styles.successPanel}><strong>✓</strong><h3>{lang === "ar" ? "كل البنود مكتملة" : "All order lines are complete"}</h3><p>{lang === "ar" ? "يمكن تحرير الطلب للشحن بعد مراجعة المستخدم المخول." : "The order can be released for dispatch after authorised human review."}</p></article>}</>;
  const renderInvoices = () => <><Head eyebrow={B("Billing tied to fulfilment", "الفوترة مرتبطة بالتنفيذ")} heading={B("Invoices", "الفواتير")} copy={B("Every invoice stays connected to the customer and source order.", "كل فاتورة تبقى مرتبطة بالعميل والطلب الأصلي.")} /><article className={styles.panel}>{invoices.map((x) => <div className={styles.invoiceRow} key={x.id}><div className={styles.rowTitle}><strong>{x.id}</strong><small>{accountName(x.customerId)} · {x.order}</small></div><div className={styles.rowCell}><span>{lang === "ar" ? "المبلغ" : "Amount"}</span><strong>{money(x.amount)}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "تاريخ الإصدار" : "Issued"}</span><strong>{L(x.issued)}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "الاستحقاق" : "Due"}</span><strong>{L(x.due)}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "تم دفع" : "Paid"}</span><strong>{money(x.paid)}</strong></div><span className={L(x.status).includes(lang === "ar" ? "متأخرة" : "Overdue") ? styles.badgeDanger : styles.badgeNeutral}>{L(x.status)}</span></div>)}</article></>;
  const renderCollection = () => <><Head eyebrow={B("Cash follow-up", "متابعة النقد")} heading={B("Collection", "التحصيل")} copy={B("A live receivables queue showing what is due, overdue, who owns the follow-up and the next action.", "قائمة مباشرة توضح المبالغ المستحقة والمتأخرة ومن المسؤول وما الإجراء التالي.")} /><section className={styles.metricGrid}><Metric a={lang === "ar" ? "إجمالي غير المحصل" : "Total outstanding"} b={money(outstanding)} c={lang === "ar" ? "رصيد فواتير مفتوحة" : "Open invoice balance"} /><Metric a={lang === "ar" ? "متأخر" : "Overdue"} b={money(overdue)} c={lang === "ar" ? "يحتاج تدخل" : "Needs intervention"} danger /><Metric a={lang === "ar" ? "مدفوع جزئيًا" : "Partial balance"} b={money(invoices[1].amount - invoices[1].paid)} c={invoices[1].id} /><Metric a={lang === "ar" ? "إجراءات اليوم" : "Actions today"} b={num(collections.filter((x) => x.overdue > 0).length)} c={lang === "ar" ? "مالية + تحصيل" : "Finance + collection"} /></section><article className={styles.panel} style={{ marginTop: 12 }}>{collections.map((x) => <div className={styles.collectionRow} key={x.invoice}><div className={styles.rowTitle}><strong>{x.invoice}</strong><small>{accountName(x.customerId)}</small></div><div className={styles.rowCell}><span>{lang === "ar" ? "المبلغ" : "Balance"}</span><strong>{money(x.amount)}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "التأخير" : "Overdue"}</span><strong>{x.overdue ? `${num(x.overdue)} ${lang === "ar" ? "يوم" : "days"}` : "—"}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "المسؤول" : "Owner"}</span><strong>{L(x.owner)}</strong></div><div className={styles.rowCell}><span>{lang === "ar" ? "الإجراء التالي" : "Next action"}</span><strong>{L(x.action)}</strong></div><span className={x.overdue ? styles.badgeDanger : styles.badgeNeutral}>{L(x.status)}</span></div>)}</article></>;
  const renderManagement = () => <><Head eyebrow={B("One view for leadership", "شاشة واحدة للإدارة العليا")} heading={B("Management Dashboard", "لوحة الإدارة")} copy={B("Leadership can see tenders, fulfilment risk, warehouse shortages, invoicing and collections without asking every department for an update.", "تستطيع الإدارة رؤية المناقصات ومخاطر التوريد ونواقص المستودع والفواتير والتحصيل دون سؤال كل قسم عن آخر تحديث.")} /><section className={styles.reportGrid}><Report a={lang === "ar" ? "مناقصات مفتوحة" : "Open tenders"} b={num(tenders.length)} c={money(openTenderValue)} /><Report a={lang === "ar" ? "عروض قيد المتابعة" : "Quotes in follow-up"} b={num(quotes.length)} c={money(quotes.reduce((s, q) => s + q.value, 0))} /><Report a={lang === "ar" ? "طلبات نشطة" : "Active orders"} b={num(orders.length)} c={money(orders.reduce((s, o) => s + o.value, 0))} /><Report a={lang === "ar" ? "نواقص توريد" : "Supply shortages"} b={num(orders.reduce((s, o) => s + o.missing, 0))} c={lang === "ar" ? "تحتاج معالجة قبل الشحن" : "resolve before dispatch"} danger /><Report a={lang === "ar" ? "إجمالي الفوترة" : "Total invoiced"} b={money(totalInvoiced)} c={lang === "ar" ? "في هذا النموذج" : "in this demo view"} /><Report a={lang === "ar" ? "غير محصل" : "Outstanding"} b={money(outstanding)} c={`${money(overdue)} ${lang === "ar" ? "متأخرة" : "overdue"}`} danger /></section><section className={styles.grid2}><article className={styles.panel}><div className={styles.panelHead}><div><small>{lang === "ar" ? "مؤشرات التشغيل" : "OPERATING KPIs"}</small><h2>{lang === "ar" ? "الصورة التشغيلية اليوم" : "Today’s operating picture"}</h2></div></div>{[[lang === "ar" ? "جاهزية أقرب مناقصة" : "Nearest tender readiness", tenders[0].readiness],[lang === "ar" ? "اكتمال الطلبات" : "Order completeness", 96],[lang === "ar" ? "توفر البنود الحرجة" : "Critical item availability", 88],[lang === "ar" ? "التحصيل في الموعد" : "On-time collection", 72]].map(([label, value]) => <div className={styles.kpi} key={String(label)}><div><span>{label}</span><strong>{pct(Number(value))}</strong></div><div className={styles.progress}><i style={{ width: `${value}%` }} /></div></div>)}</article><article className={styles.aiCard}><small>{lang === "ar" ? "تفسير الإدارة" : "EXECUTIVE INTERPRETATION"}</small><h2>{lang === "ar" ? "ما الذي يجب أن تعرفه الإدارة؟" : "What should management know?"}</h2><p>{L(config.reportSummary) || aiText}</p></article></section></>;
  const renderAccounts = () => <><Head eyebrow={B("Customer context", "سياق العميل")} heading={B("Customers", "العملاء")} copy={B("Commercial commitments and receivables connected to each customer.", "الالتزامات التجارية والمبالغ المستحقة مرتبطة بكل عميل.")} /><div className={styles.customerGrid}>{accounts.map((c, i) => <article className={styles.customerCard} key={i}><small>{L(c.type)} · {L(c.region)}</small><h3>{L(c.name)}</h3><div><span>{lang === "ar" ? "فرص والتزامات" : "Pipeline & commitments"}</span><strong>{money(safe(c.value, 0))}</strong></div><div><span>{lang === "ar" ? "القسم / المسؤول" : "Division / owner"}</span><strong>{L(c.division) || L(c.owner) || "—"}</strong></div></article>)}</div></>;
  const renderAutomation = () => <><Head eyebrow={B("Controlled workflow automation", "أتمتة سير العمل بضوابط")} heading={B("Automation", "الأتمتة")} copy={B("Business rules reduce manual follow-up while critical decisions remain visible to humans.", "قواعد العمل تقلل المتابعة اليدوية مع إبقاء القرارات الحرجة واضحة للمستخدمين.")} /><div className={styles.automationGrid}>{workflows.map((w, i) => <article className={styles.automationCard} key={i}><header><div><h3>{L(w.name)}</h3><p>{L(w.detail) || (lang === "ar" ? "قاعدة تشغيلية تربط الحدث بالتنبيه أو الإجراء المناسب." : "Operating rule connecting an event to the right alert or action.")}</p></div><button className={`${styles.switch} ${automationState[i] ? styles.switchOn : ""}`} onClick={() => setAutomationState((v) => ({ ...v, [i]: !v[i] }))}>{automationState[i] ? (lang === "ar" ? "مفعّل" : "ON") : (lang === "ar" ? "متوقف" : "OFF")}</button></header><div className={styles.miniFlow}><span>{lang === "ar" ? "حدث" : "Event"}</span><b>{lang === "ar" ? "←" : "→"}</b><span>AI / Rule</span><b>{lang === "ar" ? "←" : "→"}</b><span>{lang === "ar" ? "إجراء" : "Action"}</span></div></article>)}</div></>;
  const renderAi = () => <><Head eyebrow={B("Ask across the whole operation", "اسأل عن كامل العملية")} heading={B("AI Command Center", "مركز الذكاء الاصطناعي")} copy={B("Ask what is late, incomplete, at risk or unpaid across tenders, supply and finance.", "اسأل عما هو متأخر أو ناقص أو معرض للخطر أو غير محصل عبر المناقصات والتوريد والمالية.")} /><div className={styles.aiWorkspace}><article className={styles.aiChat}><h2>{lang === "ar" ? "مساعد العمليات والإدارة" : "Operations & management assistant"}</h2><p>{lang === "ar" ? "بيانات العرض توضيحية وليست سجلات حقيقية للشركة." : "Demo data is illustrative and does not represent actual company records."}</p><div className={styles.bubble}>{lang === "ar" ? "ما أهم شيء يحتاج تدخل الآن؟" : "What needs intervention right now?"}</div><div className={`${styles.bubble} ${styles.bubbleAI}`}>{aiText}</div><div className={styles.quickPrompts}><button onClick={() => setAiMode("risk")}>{lang === "ar" ? "المخاطر" : "Risk"}</button><button onClick={() => setAiMode("tender")}>{lang === "ar" ? "المناقصة الأقرب" : "Nearest tender"}</button><button onClick={() => setAiMode("supply")}>{lang === "ar" ? "نواقص التوريد" : "Supply shortages"}</button><button onClick={() => setAiMode("cash")}>{lang === "ar" ? "التحصيل" : "Collections"}</button></div></article><aside className={styles.panel}><div className={styles.panelHead}><div><small>{lang === "ar" ? "تنبيهات استباقية" : "PROACTIVE ALERTS"}</small><h2>{lang === "ar" ? "استثناءات تحتاج اهتمام" : "Exceptions needing attention"}</h2></div></div><div className={styles.activityItem}><i>◇</i><div><strong>{lang === "ar" ? `مناقصة خلال ${num(tenders[0].daysLeft)} أيام` : `Tender closes in ${num(tenders[0].daysLeft)} days`}</strong><p>{lang === "ar" ? `نقص ${num(tenders[0].missing)} متطلبات في ${tenders[0].id}.` : `${num(tenders[0].missing)} requirements missing in ${tenders[0].id}.`}</p></div></div><div className={styles.activityItem}><i>↗</i><div><strong>{lang === "ar" ? "منع شحن طلب ناقص" : "Incomplete order blocked"}</strong><p>{lang === "ar" ? `${orders[0].id} ما زال ينقصه ${num(orders[0].missing)} وحدات.` : `${orders[0].id} is still missing ${num(orders[0].missing)} units.`}</p></div></div><div className={styles.activityItem}><i>◉</i><div><strong>{lang === "ar" ? "تحصيل متأخر" : "Overdue collections"}</strong><p>{lang === "ar" ? `مبالغ متأخرة بقيمة ${money(overdue)}.` : `${money(overdue)} is overdue.`}</p></div></div></aside></div></>;

  const renderActive = () => ({ overview: renderOverview, tenders: renderTenders, quotes: renderQuotes, orders: renderOrders, warehouse: renderWarehouse, supply: renderSupply, invoices: renderInvoices, collection: renderCollection, management: renderManagement, accounts: renderAccounts, automation: renderAutomation, ai: renderAi }[active]());

  return <main className={styles.page} data-theme={theme} dir={lang === "ar" ? "rtl" : "ltr"} lang={lang}>
    {toast ? <div className={styles.toast}>{toast}</div> : null}
    <aside className={styles.sidebar}><a className={styles.brand} href="/systems"><span>Lab</span>Narrative<b>Systems</b></a><div className={styles.conceptTag}>{lang === "ar" ? `تصور خاص · ${shortName}` : `Private concept · ${shortName}`}</div><nav className={styles.nav}>{nav.map((n) => <button key={n.id} className={`${active === n.id ? styles.active : ""} ${n.core ? styles.coreNav : ""}`} onClick={() => setActive(n.id)}><i>{n.icon}</i>{L(n.label)}</button>)}</nav><div className={styles.sidebarFoot}><strong>{lang === "ar" ? "مصمم حول المناقصات والتوريد والتحصيل" : "Built around tenders, supply and collections"}</strong><p>{lang === "ar" ? "الأسماء والقيم والسجلات توضيحية. الفكرة هي توحيد رحلة العمل وتخصيصها حسب أنظمة الشركة الحالية بدل افتراض استبدالها." : "Names, values and records are illustrative. The concept unifies the operating workflow and can connect with the company’s existing systems rather than assuming replacement."}</p><a href={`mailto:hello@labnarrative.com?subject=${encodeURIComponent(`${companyName} Systems concept`)}`}>{lang === "ar" ? "ناقش هذا التصور ↗" : "Discuss this concept ↗"}</a></div></aside>
    <section className={styles.main}><header className={styles.topbar}><div className={styles.titleBlock}><small>{L(config.conceptLabel) || `${shortName} · ${industry}${location ? ` · ${location}` : ""}`}</small><h1>{L(title)}</h1></div><div className={styles.topActions}><div className={styles.seg}><button className={lang === "en" ? styles.selected : ""} onClick={() => setLang("en")}>EN</button><button className={lang === "ar" ? styles.selected : ""} onClick={() => setLang("ar")}>عربي</button></div><div className={styles.seg}><button className={theme === "light" ? styles.selected : ""} onClick={() => setTheme("light")}>☀ {lang === "ar" ? "فاتح" : "Light"}</button><button className={theme === "dark" ? styles.selected : ""} onClick={() => setTheme("dark")}>☾ {lang === "ar" ? "داكن" : "Dark"}</button></div><span className={styles.live}><i />{lang === "ar" ? "الأتمتة مفعلة" : "Automation live"}</span><button className={styles.primary} onClick={() => setActive("management")}>{lang === "ar" ? "لوحة الإدارة" : "Management view"}</button></div></header><div className={styles.content}>{renderActive()}</div></section>
  </main>;
}
