"use client";

import { useEffect, useMemo, useState } from "react";
import { browserSupabase } from "@/lib/supabase-browser";
import styles from "./creator-rewards.module.css";

type Submission={id:string;user_id:string;email:string;platform:string;package_key:string;content_urls:string[];notes:string|null;status:"pending"|"approved"|"rejected";base_max_months:number;performance_max_months:number;total_max_months:number;review_note:string|null;reviewed_at:string|null;created_at:string};
type PerformanceClaim={id:string;user_id:string;email:string;submission_id:string;content_url:string;platform:string;package_key:string;claimed_views:number;verified_views:number;bonus_months:number;status:"pending"|"approved"|"rejected";review_note:string|null;reviewed_at:string|null;updated_at:string};
type Queue={submissions:Submission[];performanceClaims:PerformanceClaim[]};

const date=(value?:string|null)=>value?new Date(value).toLocaleString(undefined,{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
const packageName=(key:string)=>({youtube_long:"YouTube long-form",youtube_standard:"YouTube standard videos",youtube_shorts:"YouTube Shorts",tiktok:"TikTok",instagram_reels:"Instagram Reels",reddit:"Reddit",x_posts:"X posts",x_threads:"X threads",linkedin:"LinkedIn",article:"Medium / Substack",communities:"Telegram / Discord / Facebook"} as Record<string,string>)[key]||key;
const packageRequirement=(key:string)=>({youtube_long:"1 long-form video (5+ min)",youtube_standard:"2 standard videos (<5 min)",youtube_shorts:"4 approved Shorts",tiktok:"4 approved videos",instagram_reels:"4 approved Reels",reddit:"3 high-quality original posts + 5 permitted relevant shares/reposts",x_posts:"6 substantial posts",x_threads:"3 substantial threads",linkedin:"6 substantial posts",article:"1 original detailed article",communities:"6 substantial posts across relevant communities"} as Record<string,string>)[key]||key;
async function rpc<T>(name:string,args:Record<string,unknown>={}){const{data,error}=await (browserSupabase as any).rpc(name,args);if(error)throw error;return data as T}

export default function CreatorRewardsAdmin(){
 const[queue,setQueue]=useState<Queue|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(""),[notes,setNotes]=useState<Record<string,string>>({}),[verified,setVerified]=useState<Record<string,string>>({}),[showAll,setShowAll]=useState(false);
 const load=async()=>{setLoading(true);setError("");try{setQueue(await rpc<Queue>("admin_creator_rewards_queue"))}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load creator rewards queue.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const submissions=queue?.submissions??[],claims=queue?.performanceClaims??[];
 const pendingSubmissions=useMemo(()=>submissions.filter(item=>item.status==="pending"),[submissions]);
 const pendingClaims=useMemo(()=>claims.filter(item=>item.status==="pending"),[claims]);
 const reviewPackage=async(id:string,decision:"approved"|"rejected")=>{setBusy(`package:${id}`);setError("");try{await rpc("admin_review_creator_package",{p_submission_id:id,p_decision:decision,p_review_note:notes[`package:${id}`]||null});await load()}catch(caught){setError(caught instanceof Error?caught.message:"Review failed.")}finally{setBusy("")}};
 const reviewPerformance=async(id:string,decision:"approved"|"rejected")=>{const views=Math.max(0,Number(verified[id]||0));if(decision==="approved"&&!views){setError("Enter verified views or impressions before approving a performance claim.");return}setBusy(`claim:${id}`);setError("");try{await rpc("admin_review_creator_performance",{p_claim_id:id,p_decision:decision,p_verified_views:views,p_review_note:notes[`claim:${id}`]||null});await load()}catch(caught){setError(caught instanceof Error?caught.message:"Performance review failed.")}finally{setBusy("")}};
 const visibleSubmissions=showAll?submissions:pendingSubmissions,visibleClaims=showAll?claims:pendingClaims;
 if(loading)return <main className={styles.page}><div className={styles.shell}><p className={styles.state}>Loading Creator Rewards…</p></div></main>;
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.header}><div><a href="/admin">← Control Center</a><small>LABNARRATIVE TRADING · INTERNAL</small><h1>Creator Rewards</h1><p>Review creator packages, verify public performance, and grant Max access. Approved rewards extend the creator's Max entitlement automatically.</p></div><button onClick={()=>void load()}>Refresh</button></header>
  {error&&<button className={styles.error} onClick={()=>setError("")}>{error}<span>×</span></button>}
  <section className={styles.metrics}><article><span>Pending packages</span><strong>{pendingSubmissions.length}</strong></article><article><span>Pending performance claims</span><strong>{pendingClaims.length}</strong></article><article><span>Approved packages</span><strong>{submissions.filter(item=>item.status==="approved").length}</strong></article><article><span>Approved performance claims</span><strong>{claims.filter(item=>item.status==="approved").length}</strong></article></section>
  <div className={styles.toolbar}><div><strong>Review queue</strong><span>Pending items first. Rewards are calculated server-side from the approved program rules.</span></div><button onClick={()=>setShowAll(value=>!value)}>{showAll?"Pending only":"Show full history"}</button></div>

  <section className={styles.section}><div className={styles.sectionHead}><div><small>CONTENT PACKAGES</small><h2>1 month Max when approved</h2></div><span>{visibleSubmissions.length} shown</span></div>{visibleSubmissions.length===0?<p className={styles.empty}>No content packages waiting for review.</p>:<div className={styles.list}>{visibleSubmissions.map(item=><article className={styles.card} key={item.id}><div className={styles.cardHead}><div><strong>{item.email}</strong><span>{item.platform} · {packageName(item.package_key)} · {packageRequirement(item.package_key)} · submitted {date(item.created_at)}</span></div><b className={`${styles.badge} ${styles[item.status]}`}>{item.status}</b></div><div className={styles.links}>{(item.content_urls??[]).map(url=><a key={url} href={url} target="_blank" rel="noreferrer">Open content ↗ <span>{url}</span></a>)}</div>{item.notes&&<p className={styles.creatorNote}><b>Creator note:</b> {item.notes}</p>}<label className={styles.reviewNote}><span>Internal review note</span><input value={notes[`package:${item.id}`]??item.review_note??""} onChange={e=>setNotes(current=>({...current,[`package:${item.id}`]:e.target.value}))} placeholder="Optional note shown to the creator"/></label><div className={styles.actions}><button className={styles.reject} disabled={busy===`package:${item.id}`} onClick={()=>void reviewPackage(item.id,"rejected")}>{item.status==="approved"?"Revoke package reward":"Reject"}</button><button className={styles.approve} disabled={busy===`package:${item.id}`} onClick={()=>void reviewPackage(item.id,"approved")}>{busy===`package:${item.id}`?"Saving…":item.status==="approved"?"Keep approved · 1 mo":"Approve · +1 month Max"}</button></div></article>)}</div>}</section>

  <section className={styles.section}><div className={styles.sectionHead}><div><small>PERFORMANCE</small><h2>Verify views or impressions</h2></div><span>{visibleClaims.length} shown</span></div>{visibleClaims.length===0?<p className={styles.empty}>No performance claims waiting for review.</p>:<div className={styles.list}>{visibleClaims.map(item=><article className={styles.card} key={item.id}><div className={styles.cardHead}><div><strong>{item.email}</strong><span>{item.platform} · creator claims {item.claimed_views.toLocaleString()} views/impressions · {date(item.updated_at)}</span></div><b className={`${styles.badge} ${styles[item.status]}`}>{item.status}{item.status==="approved"?` · +${item.bonus_months} mo`:""}</b></div><div className={styles.links}><a href={item.content_url} target="_blank" rel="noreferrer">Open content ↗ <span>{item.content_url}</span></a></div><div className={styles.performanceReview}><label><span>Verified views / impressions</span><input type="number" min="0" value={verified[item.id]??(item.verified_views?String(item.verified_views):"")} onChange={e=>setVerified(current=>({...current,[item.id]:e.target.value}))} placeholder={item.claimed_views.toString()}/></label><label><span>Review note</span><input value={notes[`claim:${item.id}`]??item.review_note??""} onChange={e=>setNotes(current=>({...current,[`claim:${item.id}`]:e.target.value}))} placeholder="Optional note shown to creator"/></label></div><p className={styles.rule}>Bonus is calculated automatically: YouTube non-Shorts 1K/5K/10K/50K/100K → +1/+2/+3/+6/+12 mo; Shorts/Reels/TikTok 10K/50K/100K/500K/1M → +1/+2/+3/+6/+12 mo; Reddit/X/LinkedIn 10K/50K/100K → +1/+3/+6 mo.</p><div className={styles.actions}><button className={styles.reject} disabled={busy===`claim:${item.id}`} onClick={()=>void reviewPerformance(item.id,"rejected")}>Reject claim</button><button className={styles.approve} disabled={busy===`claim:${item.id}`} onClick={()=>void reviewPerformance(item.id,"approved")}>{busy===`claim:${item.id}`?"Saving…":"Verify & award Max"}</button></div></article>)}</div>}</section>
 </div></main>;
}
