"use client";
import {Badge} from "../_components";
import styles from "../pvos.module.css";
type Props={run:any,label:string,company:string,stats:any,record:any,second:any,members:any[],userId?:string,firstReviewerIds:string[],reviewer:string,onReviewer:(id:string)=>void,busy:boolean,onReview:()=>void,onSecond:()=>void,onSend:()=>void,onComplete:()=>void,onExport:()=>void,onClose:()=>void,onManageReviewers:()=>void};
export function ScreeningWorkspace(p:Props){
  const stage=p.record?3:p.second?.status==="approved"?2:p.second?.status==="pending"?1:0;
  const eligible=p.members.filter(m=>m.user_id!==p.userId&&!p.firstReviewerIds.includes(m.user_id));
  return <section className={styles.screeningWorkspace} aria-label="Screening progress">
    <div className={styles.panelHeader}><div><h2>{p.company}</h2><div className={styles.muted}>{p.label}</div><div className={styles.muted}>{p.run.period_start} → {p.run.period_end} · {p.stats.total} article-product records</div></div><button className={styles.buttonGhost} onClick={p.onClose} disabled={p.busy}>Change screening</button></div>
    <ol className={styles.screeningStages} aria-label="Screening stages">{['First screening','Second review','Completion'].map((label,i)=><li key={label} aria-current={stage===i?'step':undefined}><Badge tone={stage>i?'green':stage===i?'lime':'default'}>{stage>i?'✓':i+1}</Badge> {label}</li>)}</ol>
    <div className={styles.screeningNext}>
      <div>
        {p.record?<><strong>Screening record completed</strong><p>Both reviewer decisions and earlier cycles remain in the evidence record.</p></>:p.second?.status==='pending'?<><strong>Awaiting {p.members.find(m=>m.user_id===p.second.assigned_to)?.email||p.second.assigned_to}</strong><p>First-review decisions are locked while second review is pending.</p></>:p.second?.status==='approved'?<><strong>Second review approved</strong><p>{p.members.find(m=>m.user_id===p.second.reviewed_by)?.email||p.second.reviewed_by} · Ready for the final completion action.</p></>:p.second?.status==='returned'?<><strong>Returned for correction</strong><p>{p.second.note}</p></>:p.stats.unreviewed?<><strong>{p.stats.open} decision{p.stats.open===1?'':'s'} still open</strong><p>Review the articles below. Needs more information remains unfinished.</p></>:<><strong>First screening finished</strong><p>Choose a second reviewer to verify the focused decisions.{p.stats.open>0?' Needs more information is included; it must be resolved before approval and completion.':''}</p></>}
      </div>
      <div className={styles.inlineActions}>
        {p.record?<button className={styles.button} onClick={p.onExport} disabled={p.busy}>Export screening record</button>:p.second?.status==='approved'?<button className={styles.button} onClick={p.onComplete} disabled={p.busy||p.stats.open>0}>Complete & create screening record</button>:p.second?.status==='pending'?<button className={styles.button} onClick={p.onSecond} disabled={p.busy}>{p.second.assigned_to===p.userId?'Open your second review':'View pending review'}</button>:p.stats.unreviewed?<button className={styles.buttonGhost} onClick={p.onReview} disabled={p.busy}>Continue screening</button>:<>
          <label>Second reviewer <select className={styles.input} value={p.reviewer} onChange={e=>p.onReviewer(e.target.value)} disabled={p.busy}><option value="">Choose workspace member</option>{eligible.map(m=><option key={m.user_id} value={m.user_id}>{m.email}</option>)}</select></label><button className={styles.button} onClick={p.onSend} disabled={p.busy||!eligible.some(m=>m.user_id===p.reviewer)}>Send for second review</button>
        </>}
      </div>
    </div>
    {!p.record&&p.second?.status!=='pending'&&p.second?.status!=='approved'?<div style={{padding:"0 16px 16px"}}>{!eligible.length?<p className={styles.muted}>No independent reviewer is available. Add a workspace member who did not make first-review decisions in this screening.</p>:null}<button className={styles.buttonGhost} onClick={p.onManageReviewers} disabled={p.busy}>Manage reviewer access</button></div>:null}
    <details style={{padding:"0 16px 16px"}}><summary>Screening details and history</summary><p>{p.stats.reviewed} final decisions · {p.stats.relevant} Relevant · {p.stats.notRelevant} Not relevant · {p.stats.psur} PSUR selections · {p.stats.signal} Signal escalations</p><p className={styles.muted}>Record ID: {p.record?.id||'Not completed'} · Run ID: {p.run.id}</p>{p.second?.reviewed_at?<p>Second review: {p.second.status} · {p.members.find(m=>m.user_id===p.second.reviewed_by)?.email||p.second.reviewed_by} · {p.second.reviewed_at}</p>:null}{(p.second?.metadata?.history||[]).map((h:any,i:number)=><p key={i}>Cycle {h.cycle} · {h.status} · {h.note} · {h.reviewed_at}</p>)}</details>
    {p.record?<details style={{padding:"0 16px 16px"}}><summary>Frozen article decisions and first reviewers</summary>{(p.record.decision_snapshot||[]).map((d:any,i:number)=><div key={d.literature_item_id||i} className={styles.notice} style={{marginTop:8}}><strong>{d.title}</strong><p>{d.product} · {d.review_status} · {p.members.find(m=>m.user_id===d.reviewer_user_id)?.email||d.reviewer_user_id} · {d.reviewed_at}</p>{d.decision_note?<p>{d.decision_note}</p>:null}</div>)}</details>:null}
  </section>;
}
