import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const USD_SAR = 3.75;
type Market = "SA" | "US" | "CRYPTO";
type Holding = { id:string; user_id:string; portfolio_kind:"real"|"paper"; asset_type:string; symbol:string|null; quantity:number|string|null; connection_id:string|null; metadata:Record<string,unknown>|null };
type Quote = { market:Market; symbol:string; assetClass:string; currency:string; price:number; fx:number; priceSar:number; source:string; delayed:boolean; observedAt:string; staleAfter:string; previousClose:number|null; changePercent:number|null };

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const num=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
function digits(v:string){return v.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)))}
function norm(v:string|null|undefined){return digits(String(v||"")).trim().toUpperCase().replace(/\.SR$/," ").trim().replace(/[^0-9A-Z.^=-]/g,"")}
function riyadhDate(date=new Date()){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`}

async function yahoo(symbol:string,market:Market):Promise<Quote|null>{try{const ticker=market==="SA"?`${symbol}.SR`:symbol;const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(ticker)}?interval=1d&range=5d&includePrePost=false`,{headers:{Accept:"application/json","User-Agent":"Tharwa-Market-Engine/1.2"},signal:AbortSignal.timeout(8000)});if(!r.ok)return null;const b=await r.json();const meta=b?.chart?.result?.[0]?.meta??{};const price=Number(meta.regularMarketPrice);if(!Number.isFinite(price)||price<=0)return null;const previousRaw=Number(meta.previousClose??meta.chartPreviousClose);const previous=Number.isFinite(previousRaw)&&previousRaw>0?previousRaw:null;const ts=Number(meta.regularMarketTime);const observed=Number.isFinite(ts)&&ts>0?new Date(ts*1000):new Date();const currency=market==="SA"?"SAR":"USD";const fx=currency==="USD"?USD_SAR:1;return{market,symbol,assetClass:market==="SA"?"equity_sa":"equity_us",currency,price,fx,priceSar:price*fx,source:"Yahoo Finance delayed fallback",delayed:true,observedAt:observed.toISOString(),staleAfter:new Date(observed.getTime()+45*60*1000).toISOString(),previousClose:previous,changePercent:previous?((price-previous)/previous)*100:null}}catch{return null}}
async function sahmk(symbol:string,key:string):Promise<Quote|null>{try{const r=await fetch(`https://api.sahmk.sa/api/v1/quote/${encodeURIComponent(symbol)}/`,{headers:{"X-API-Key":key,Accept:"application/json"},signal:AbortSignal.timeout(8000)});if(!r.ok)return null;const b=await r.json();const price=Number(b?.price);if(!Number.isFinite(price)||price<=0)return null;const cp=Number(b?.change_percent);const observed=new Date();return{market:"SA",symbol,assetClass:"equity_sa",currency:"SAR",price,fx:1,priceSar:price,source:"SAHMK",delayed:Boolean(b?.is_delayed),observedAt:observed.toISOString(),staleAfter:new Date(observed.getTime()+30*60*1000).toISOString(),previousClose:null,changePercent:Number.isFinite(cp)?cp:null}}catch{return null}}
async function crypto(symbol:string):Promise<Quote|null>{try{if(["USDT","USDC","FDUSD","TUSD","DAI","BUSD"].includes(symbol)){const now=new Date();return{market:"CRYPTO",symbol,assetClass:"crypto",currency:"USD",price:1,fx:USD_SAR,priceSar:USD_SAR,source:"Binance public ticker",delayed:false,observedAt:now.toISOString(),staleAfter:new Date(now.getTime()+20*60*1000).toISOString(),previousClose:null,changePercent:null}}const r=await fetch(`https://api.binance.com/api/v3/ticker/24hr?symbol=${encodeURIComponent(symbol+"USDT")}`,{signal:AbortSignal.timeout(8000)});if(!r.ok)return null;const b=await r.json();const price=Number(b?.lastPrice);if(!Number.isFinite(price)||price<=0)return null;const now=new Date();const cp=Number(b?.priceChangePercent);return{market:"CRYPTO",symbol,assetClass:"crypto",currency:"USD",price,fx:USD_SAR,priceSar:price*USD_SAR,source:"Binance public ticker",delayed:false,observedAt:now.toISOString(),staleAfter:new Date(now.getTime()+20*60*1000).toISOString(),previousClose:null,changePercent:Number.isFinite(cp)?cp:null}}catch{return null}}
async function rebuild(admin:ReturnType<typeof createClient>,userId:string,kind:"real"|"paper"){const{data,error}=await admin.rpc("wealth_rebuild_snapshot",{p_user_id:userId,p_portfolio_kind:kind});if(error)throw error;return data}

Deno.serve(async(req)=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return json({error:"server_configuration_missing"},500);const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const secret=(req.headers.get("X-Wealth-Market-Secret")||"").trim();const{data:verified}=await admin.rpc("wealth_verify_saudi_market_worker_secret",{p_secret:secret});if(!secret||verified!==true)return json({error:"unauthorized"},401);const body=await req.json().catch(()=>({}));const market=String(body.market||"ALL").toUpperCase();const markets:Market[]=market==="ALL"?["SA","US","CRYPTO"]:[market as Market];if(markets.some(m=>!["SA","US","CRYPTO"].includes(m)))return json({error:"invalid_market"},400);
const{data,error}=await admin.from("wealth_holdings").select("id,user_id,portfolio_kind,asset_type,symbol,quantity,connection_id,metadata").not("symbol","is",null);if(error)throw error;const holdings=(data||[]) as Holding[];const selected=holdings.filter(h=>{const m=String(h.metadata?.market||"").toUpperCase();if(markets.includes("SA")&&(h.asset_type==="saudi_stock"||h.asset_type==="reit")&&(m==="SA"||/^\d+$/.test(norm(h.symbol))))return true;if(markets.includes("US")&&h.asset_type==="global_stock"&&(m==="US"||String(h.metadata?.original_currency||"").toUpperCase()==="USD"))return true;if(markets.includes("CRYPTO")&&h.asset_type==="crypto")return true;return false});
const jobs=new Map<string,{market:Market;symbol:string}>();for(const h of selected){const s=norm(h.symbol);if(!s)continue;const m:Market=h.asset_type==="crypto"?"CRYPTO":h.asset_type==="global_stock"?"US":"SA";if(markets.includes(m))jobs.set(`${m}:${s}`,{market:m,symbol:s})}
const sahmkKey=Deno.env.get("SAHMK_API_KEY")?.trim();const quotes=new Map<string,Quote>();for(const j of jobs.values()){let q:Quote|null=null;if(j.market==="SA"){if(sahmkKey)q=await sahmk(j.symbol,sahmkKey);if(!q)q=await yahoo(j.symbol,"SA")}else if(j.market==="US")q=await yahoo(j.symbol,"US");else q=await crypto(j.symbol);if(q)quotes.set(`${j.market}:${j.symbol}`,q)}
let cacheUpserts=0,holdingUpdates=0,historyWrites=0;const changed=new Map<string,{userId:string;kind:"real"|"paper"}>();for(const q of quotes.values()){const isStale=new Date(q.staleAfter).getTime()<Date.now();const{error:e}=await admin.from("wealth_market_quotes").upsert({market:q.market,symbol:q.symbol,asset_class:q.assetClass,native_currency:q.currency,price:q.price,fx_to_sar:q.fx,price_sar:q.priceSar,source:q.source,is_delayed:q.delayed,observed_at:q.observedAt,stale_after:q.staleAfter,metadata:{previous_close:q.previousClose,change_percent:q.changePercent,is_stale:isStale},updated_at:new Date().toISOString()},{onConflict:"market,symbol"});if(e)throw e;cacheUpserts++}
for(const h of selected){const s=norm(h.symbol);const m:Market=h.asset_type==="crypto"?"CRYPTO":h.asset_type==="global_stock"?"US":"SA";const q=quotes.get(`${m}:${s}`);if(!q)continue;const qty=num(h.quantity);if(!h.connection_id){const isStale=new Date(q.staleAfter).getTime()<Date.now();const marketValue=qty*q.priceSar;const meta={...(h.metadata||{}),market:m,market_price_managed:true,original_currency:q.currency,original_market_price:q.price,original_market_value:qty*q.price,fx_to_sar:q.fx,price_source:q.source,price_delayed:q.delayed,price_is_stale:isStale,price_observed_at:q.observedAt,price_stale_after:q.staleAfter,previous_close:q.previousClose,change_percent:q.changePercent};const{error:e}=await admin.from("wealth_holdings").update({unit_price:q.priceSar,market_value:marketValue,as_of_date:riyadhDate(new Date(q.observedAt)),metadata:meta,updated_at:new Date().toISOString()}).eq("id",h.id).eq("user_id",h.user_id).eq("portfolio_kind",h.portfolio_kind);if(e)throw e;holdingUpdates++;changed.set(`${h.user_id}:${h.portfolio_kind}`,{userId:h.user_id,kind:h.portfolio_kind});const{error:he}=await admin.from("wealth_price_history").upsert({user_id:h.user_id,holding_id:h.id,portfolio_kind:h.portfolio_kind,symbol:s,price:q.price,currency:q.currency,source:q.source,is_delayed:q.delayed,price_date:riyadhDate(new Date(q.observedAt)),observed_at:q.observedAt,metadata:{market:m,price_sar:q.priceSar,fx_to_sar:q.fx,is_stale:isStale,stale_after:q.staleAfter,previous_close:q.previousClose,change_percent:q.changePercent}},{onConflict:"user_id,holding_id,price_date"});if(he)throw he;historyWrites++}}
for(const x of changed.values())await rebuild(admin,x.userId,x.kind);return json({ok:true,engine:"market-v1.2+snapshot-central-v2",markets,holdings_considered:selected.length,quotes:quotes.size,cache_upserts:cacheUpserts,holding_updates:holdingUpdates,history_writes:historyWrites,portfolios_updated:changed.size,at:new Date().toISOString()})});
