"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import type { FormEvent } from "react";
import { browserSupabase } from "@/lib/supabase-browser";
import styles from "./ask.module.css";

type Holding={id:string;account_id:string;asset_name:string;symbol:string|null;asset_type:string|null;market_value:number|string|null;cost_basis:number|string|null};
type Account={id:string;provider:string|null;account_name:string|null;status:string|null};
type Income={event_date:string;total_amount_sar:number|string|null};
type Shariah={holding_id:string;status:string};
type Tone="positive"|"negative"|"neutral"|"review";
type Stat={label:string;value:string;tone?:Tone};
type Answer={text:string;stats?:Stat[];link?:{href:string;label:string}};
type Msg=Answer&{id:number;role:"user"|"assistant"};

const suggestions=["كم صافي ثروتي؟","كم عندي في السوق السعودي؟","ما نسبة الكريبتو؟","ما أكبر مخاطرة في المحفظة؟","كم دخلت توزيعات آخر 12 شهر؟","ما الأصول الخاسرة؟","كم عندي في Binance؟","ما حالة الالتزام الشرعي؟"];
const typeNames:Record<string,string>={saudi_stock:"سهم سعودي",global_stock:"سهم عالمي",etf:"ETF",fund:"صندوق",reit:"ريت",crypto:"أصل رقمي",cash:"نقد",murabaha:"مرابحة",real_estate:"عقار",gold:"ذهب"};
const num=(v:number|string|null|undefined)=>{const x=Number(v??0);return Number.isFinite(x)?x:0};
const fmt=(v:number,d=2)=>new Intl.NumberFormat("ar-SA-u-nu-arab",{maximumFractionDigits:d}).format(v);
const sar=(v:number)=>`${fmt(v)} ر.س`;
const pct=(v:number)=>`${v>0?"+":""}${fmt(v,1)}٪`;
const share=(v:number,t:number)=>t>0?v/t*100:0;
const norm=(v:string)=>v.toLowerCase().normalize("NFKD").replace(/[\u064B-\u065F\u0670]/g,"").replace(/[أإآٱ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[،؟?!.:,؛;()\[\]{}]/g," ").replace(/\s+/g," ").trim();
const has=(q:string,terms:string[])=>terms.some(t=>q.includes(norm(t)));

function facts(holdings:Holding[],accounts:Account[],income:Income[],shariah:Shariah[]){
  const total=holdings.reduce((s,h)=>s+num(h.market_value),0),cost=holdings.reduce((s,h)=>s+num(h.cost_basis),0),pnl=total-cost;
  const sorted=[...holdings].sort((a,b)=>num(b.market_value)-num(a.market_value));
  const saudi=holdings.filter(h=>!["global_stock","crypto","etf"].includes(h.asset_type||"")).reduce((s,h)=>s+num(h.market_value),0);
  const global=holdings.filter(h=>["global_stock","etf"].includes(h.asset_type||"")).reduce((s,h)=>s+num(h.market_value),0);
  const crypto=holdings.filter(h=>h.asset_type==="crypto").reduce((s,h)=>s+num(h.market_value),0);
  const cash=holdings.filter(h=>["cash","murabaha"].includes(h.asset_type||"")).reduce((s,h)=>s+num(h.market_value),0);
  const realEstate=holdings.filter(h=>h.asset_type==="real_estate").reduce((s,h)=>s+num(h.market_value),0);
  const gold=holdings.filter(h=>h.asset_type==="gold").reduce((s,h)=>s+num(h.market_value),0);
  const winners=holdings.filter(h=>num(h.cost_basis)>0&&num(h.market_value)>num(h.cost_basis)).sort((a,b)=>(num(b.market_value)-num(b.cost_basis))-(num(a.market_value)-num(a.cost_basis)));
  const losers=holdings.filter(h=>num(h.cost_basis)>0&&num(h.market_value)<num(h.cost_basis)).sort((a,b)=>(num(a.market_value)-num(a.cost_basis))-(num(b.market_value)-num(b.cost_basis)));
  const accountMap=new Map(accounts.map(a=>[a.id,a]));
  const accountTotals=accounts.map(a=>{const hs=holdings.filter(h=>h.account_id===a.id),v=hs.reduce((s,h)=>s+num(h.market_value),0),c=hs.reduce((s,h)=>s+num(h.cost_basis),0);return{a,hs,v,c,p:v-c}}).sort((a,b)=>b.v-a.v);
  const now=new Date(),cut=new Date(now);cut.setDate(cut.getDate()-365);const cut12=cut.toISOString().slice(0,10),yearStart=new Date(now.getFullYear(),0,1).toISOString().slice(0,10);
  const income12=income.filter(x=>x.event_date>=cut12).reduce((s,x)=>s+num(x.total_amount_sar),0),incomeYtd=income.filter(x=>x.event_date>=yearStart).reduce((s,x)=>s+num(x.total_amount_sar),0);
  const sm=new Map(shariah.map(s=>[s.holding_id,s.status]));const sv={ok:0,review:0,bad:0,unknown:0};holdings.forEach(h=>{const v=num(h.market_value),st=sm.get(h.id);if(st==="likely_compliant")sv.ok+=v;else if(st==="review_required")sv.review+=v;else if(st==="likely_non_compliant")sv.bad+=v;else sv.unknown+=v});
  return{total,cost,pnl,pnlPct:cost>0?pnl/cost*100:0,sorted,saudi,global,crypto,cash,realEstate,gold,winners,losers,accountMap,accountTotals,income12,incomeYtd,sm,sv};
}
type Facts=ReturnType<typeof facts>;

function findAsset(q:string,holdings:Holding[]){return [...holdings].sort((a,b)=>b.asset_name.length-a.asset_name.length).find(h=>[h.asset_name,h.symbol||""].map(norm).some(x=>x.length>=2&&q.includes(x)))||null}
function findAccount(q:string,accounts:Account[]){return [...accounts].sort((a,b)=>(b.account_name||b.provider||"").length-(a.account_name||a.provider||"").length).find(a=>[a.provider||"",a.account_name||""].map(norm).some(x=>x.length>=3&&q.includes(x)))||null}

function reply(raw:string,holdings:Holding[],accounts:Account[],f:Facts,paper:boolean):Answer{
  const q=norm(raw),suffix=paper?"?portfolio=paper":"",asset=findAsset(q,holdings),account=findAccount(q,accounts);
  if(asset){const v=num(asset.market_value),c=num(asset.cost_basis),p=v-c,pp=c>0?p/c*100:0,st=f.sm.get(asset.id),sl=st==="likely_compliant"?"متوافق":st==="review_required"?"يحتاج مراجعة":st==="likely_non_compliant"?"غير متوافق مبدئيًا":"غير مصنف";return{text:`${asset.asset_name} يمثل ${pct(share(v,f.total))} من المحفظة، وقيمته الحالية ${sar(v)}${f.accountMap.get(asset.account_id)?.provider?` داخل ${f.accountMap.get(asset.account_id)?.provider}`:""}.`,stats:[{label:"القيمة",value:sar(v)},{label:"الوزن",value:pct(share(v,f.total))},...(c>0?[{label:"الربح/الخسارة",value:`${sar(p)} · ${pct(pp)}`,tone:(p>=0?"positive":"negative") as Tone}]:[]),{label:"النوع",value:typeNames[asset.asset_type||""]||"أصل"},{label:"التصنيف الشرعي",value:sl,tone:(st==="likely_compliant"?"positive":st==="review_required"?"review":st==="likely_non_compliant"?"negative":"neutral") as Tone}],link:{href:`/wealth/assets/${asset.id}${suffix}`,label:"فتح صفحة الأصل"}}}
  if(account){const a=f.accountTotals.find(x=>x.a.id===account.id),top=a?.hs.slice().sort((x,y)=>num(y.market_value)-num(x.market_value))[0],pp=a&&a.c>0?a.p/a.c*100:0;return{text:`${account.provider||account.account_name||"الحساب"} يحتوي على ${a?.hs.length||0} أصل بقيمة ${sar(a?.v||0)}.`,stats:[{label:"قيمة الحساب",value:sar(a?.v||0)},{label:"عدد الأصول",value:fmt(a?.hs.length||0,0)},...(a&&a.c>0?[{label:"الربح/الخسارة",value:`${sar(a.p)} · ${pct(pp)}`,tone:(a.p>=0?"positive":"negative") as Tone}]:[]),{label:"أكبر أصل",value:top?.asset_name||"—"}],link:{href:`/wealth/accounts${suffix}`,label:"فتح الحسابات"}}}
  if(has(q,["ملخص","لخص","summary","وضعي"]))return{text:`صافي المحفظة ${sar(f.total)} عبر ${accounts.length} حساب و${holdings.length} أصل. أكبر مركز هو ${f.sorted[0]?.asset_name||"—"}.`,stats:[{label:"صافي الثروة",value:sar(f.total)},{label:"الربح/الخسارة",value:`${sar(f.pnl)} · ${pct(f.pnlPct)}`,tone:f.pnl>=0?"positive":"negative"},{label:"السعودية / محلي",value:pct(share(f.saudi,f.total))},{label:"الكريبتو",value:pct(share(f.crypto,f.total))}]};
  if(has(q,["صافي ثروتي","كم ثروتي","اجمالي ثروتي","net worth","قيمة المحفظة"]))return{text:`صافي قيمة الأصول المسجلة حاليًا هو ${sar(f.total)}.`,stats:[{label:"القيمة الحالية",value:sar(f.total)},{label:"التكلفة المسجلة",value:sar(f.cost)},{label:"الربح/الخسارة",value:`${sar(f.pnl)} · ${pct(f.pnlPct)}`,tone:f.pnl>=0?"positive":"negative"}]};
  if(has(q,["السوق السعودي","السعوديه","السعودية","محلي","saudi","tadawul"]))return{text:`التعرض السعودي/المحلي ${sar(f.saudi)}، أي ${pct(share(f.saudi,f.total))} من المحفظة.`,stats:[{label:"السعودية / محلي",value:sar(f.saudi)},{label:"النسبة",value:pct(share(f.saudi,f.total))},{label:"العالمي",value:pct(share(f.global,f.total))},{label:"الكريبتو",value:pct(share(f.crypto,f.total))}],link:{href:`/wealth/analytics${suffix}`,label:"فتح التحليلات"}};
  if(has(q,["كريبتو","عملات رقمية","crypto"]))return{text:`إجمالي الأصول الرقمية ${sar(f.crypto)} وتمثل ${pct(share(f.crypto,f.total))}.`,stats:[{label:"الكريبتو",value:sar(f.crypto)},{label:"النسبة",value:pct(share(f.crypto,f.total))}]};
  if(has(q,["عالمي","امريكي","أمريكي","global","us stocks"]))return{text:`التعرض العالمي ${sar(f.global)}، أي ${pct(share(f.global,f.total))}.`,stats:[{label:"عالمي",value:sar(f.global)},{label:"النسبة",value:pct(share(f.global,f.total))}]};
  if(has(q,["نقد","سيوله","سيولة","cash","مرابحه","مرابحة"]))return{text:`النقد والمرابحة ${sar(f.cash)}، أي ${pct(share(f.cash,f.total))}.`,stats:[{label:"نقد ومرابحة",value:sar(f.cash)},{label:"النسبة",value:pct(share(f.cash,f.total))}]};
  if(has(q,["عقار","real estate"]))return{text:`قيمة العقار ${sar(f.realEstate)} وتمثل ${pct(share(f.realEstate,f.total))}.`,stats:[{label:"العقار",value:sar(f.realEstate)},{label:"النسبة",value:pct(share(f.realEstate,f.total))}]};
  if(has(q,["ذهب","gold"]))return{text:`قيمة الذهب ${sar(f.gold)} وتمثل ${pct(share(f.gold,f.total))}. في الفحص الحالي بقي ضمن «يحتاج مراجعة».`,stats:[{label:"الذهب",value:sar(f.gold)},{label:"النسبة",value:pct(share(f.gold,f.total))},{label:"الحالة",value:"يحتاج مراجعة",tone:"review"}],link:{href:`/wealth/shariah${suffix}`,label:"فتح الالتزام الشرعي"}};
  if(has(q,["توزيعات","دخل","dividend","income"]))return{text:`إجمالي الدخل والتوزيعات خلال آخر 12 شهرًا ${sar(f.income12)}.`,stats:[{label:"آخر 12 شهر",value:sar(f.income12),tone:"positive"},{label:"منذ بداية السنة",value:sar(f.incomeYtd),tone:"positive"}],link:{href:`/wealth/income${suffix}`,label:"فتح الدخل والتوزيعات"}};
  if(has(q,["شرعي","الشريعة","متوافق","حلال","shariah"]))return{text:`وفق التصنيفات المسجلة، ${pct(share(f.sv.ok,f.total))} متوافق و${pct(share(f.sv.review,f.total))} يحتاج مراجعة.`,stats:[{label:"متوافق",value:`${sar(f.sv.ok)} · ${pct(share(f.sv.ok,f.total))}`,tone:"positive"},{label:"يحتاج مراجعة",value:`${sar(f.sv.review)} · ${pct(share(f.sv.review,f.total))}`,tone:"review"},{label:"غير متوافق مبدئيًا",value:`${sar(f.sv.bad)} · ${pct(share(f.sv.bad,f.total))}`,tone:"negative"}],link:{href:`/wealth/shariah${suffix}`,label:"فتح الالتزام الشرعي"}};
  if(has(q,["الخاسره","الخاسرة","خاسره","خاسرة","losses","الخسائر"])){const loss=f.losers.reduce((s,h)=>s+num(h.market_value)-num(h.cost_basis),0);return{text:f.losers.length?`يوجد ${f.losers.length} أصل بخسارة غير محققة بإجمالي ${sar(loss)}.`:"لا توجد أصول خاسرة ذات تكلفة مسجلة.",stats:f.losers.slice(0,4).map(h=>{const x=num(h.market_value)-num(h.cost_basis),r=num(h.cost_basis)>0?x/num(h.cost_basis)*100:0;return{label:h.asset_name,value:`${sar(x)} · ${pct(r)}`,tone:"negative" as Tone}}),link:{href:`/wealth/assets${suffix}`,label:"فتح الأصول"}}}
  if(has(q,["الرابحه","الرابحة","رابحه","رابحة","winners","الارباح","الأرباح"])){const p=f.winners.reduce((s,h)=>s+num(h.market_value)-num(h.cost_basis),0);return{text:f.winners.length?`يوجد ${f.winners.length} أصل بربح غير محقق بإجمالي ${sar(p)}.`:"لا توجد أصول رابحة ذات تكلفة مسجلة.",stats:f.winners.slice(0,4).map(h=>{const x=num(h.market_value)-num(h.cost_basis),r=num(h.cost_basis)>0?x/num(h.cost_basis)*100:0;return{label:h.asset_name,value:`${sar(x)} · ${pct(r)}`,tone:"positive" as Tone}}),link:{href:`/wealth/assets${suffix}`,label:"فتح الأصول"}}}
  if(has(q,["مخاطره","مخاطرة","مخاطر","تركيز","اكبر اصل","أكبر أصل","risk","concentration"])){const t=f.sorted[0]?share(num(f.sorted[0].market_value),f.total):0,t3=share(f.sorted.slice(0,3).reduce((s,h)=>s+num(h.market_value),0),f.total),cr=share(f.crypto,f.total);return{text:`أكبر مركز هو ${f.sorted[0]?.asset_name||"—"} بنسبة ${pct(t)}، وأكبر 3 مراكز تمثل ${pct(t3)}. هذا وصف للتركيز وليس توصية بيع أو شراء.`,stats:[{label:"أكبر أصل",value:pct(t)},{label:"أكبر 3 أصول",value:pct(t3)},{label:"الكريبتو",value:pct(cr)}],link:{href:`/wealth/analytics${suffix}`,label:"فتح التحليلات"}}}
  if(has(q,["الحسابات","كم حساب","accounts"]))return{text:`لديك ${accounts.length} حسابات في هذه المحفظة.`,stats:f.accountTotals.slice(0,5).map(x=>({label:x.a.provider||x.a.account_name||"حساب",value:`${sar(x.v)} · ${pct(share(x.v,f.total))}`})),link:{href:`/wealth/accounts${suffix}`,label:"فتح الحسابات"}};
  return{text:"أستطيع الإجابة عن صافي الثروة، الأصول والحسابات، السعودية والعالمي والكريبتو، الأرباح والخسائر، الدخل، التركّز، والتصنيف الشرعي. جرّب سؤالًا مباشرًا أو أحد الاقتراحات."};
}

export default function AskWealthClient(){
  const [paper,setPaper]=useState(false),[holdings,setHoldings]=useState<Holding[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[income,setIncome]=useState<Income[]>([]),[shariah,setShariah]=useState<Shariah[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[input,setInput]=useState(""),[messages,setMessages]=useState<Msg[]>([]);const id=useRef(1),end=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{let active=true;(async()=>{try{const mode=new URLSearchParams(location.search).get("portfolio")==="paper";setPaper(mode);const {data:u,error:e}=await browserSupabase.auth.getUser();if(e||!u.user){location.replace(`/wealth/login?next=${encodeURIComponent(location.pathname+location.search)}`);return}if(mode){const {error:se}=await browserSupabase.rpc("ensure_wealth_paper_portfolio");if(se)throw se}const uid=u.user.id,k=mode?"paper":"real",[h,a,i,s]=await Promise.all([browserSupabase.from("wealth_holdings").select("id,account_id,asset_name,symbol,asset_type,market_value,cost_basis").eq("user_id",uid).eq("portfolio_kind",k),browserSupabase.from("wealth_accounts").select("id,provider,account_name,status").eq("user_id",uid).eq("portfolio_kind",k).neq("status","archived"),browserSupabase.from("wealth_income_events").select("event_date,total_amount_sar").eq("user_id",uid).eq("portfolio_kind",k),browserSupabase.from("wealth_shariah_assessments").select("holding_id,status").eq("user_id",uid).eq("portfolio_kind",k)]);if(h.error)throw h.error;if(a.error)throw a.error;if(i.error)throw i.error;if(s.error)throw s.error;if(!active)return;setHoldings((h.data||[]) as Holding[]);setAccounts((a.data||[]) as Account[]);setIncome((i.data||[]) as Income[]);setShariah((s.data||[]) as Shariah[]);setMessages([{id:id.current++,role:"assistant",text:mode?"أنا جاهز لقراءة المحفظة التجريبية. اسألني عن أي أصل، حساب، توزيع أو نسبة.":"أنا جاهز لقراءة محفظتك. اسألني عن أي أصل، حساب، توزيع أو نسبة."}])}catch(x){if(active)setError(x instanceof Error?x.message:"تعذر تحميل البيانات.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
  useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth",block:"end"})},[messages]);const f=useMemo(()=>facts(holdings,accounts,income,shariah),[holdings,accounts,income,shariah]),suffix=paper?"?portfolio=paper":"";
  const ask=(q:string)=>{const x=q.trim();if(!x)return;const a=reply(x,holdings,accounts,f,paper);setMessages(m=>[...m,{id:id.current++,role:"user",text:x},{id:id.current++,role:"assistant",...a}]);setInput("")};const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();ask(input)};
  if(loading)return <main className={styles.page}><div className={styles.state}>جاري قراءة المحفظة…</div></main>;if(error)return <main className={styles.page}><div className={styles.state}><strong>تعذر تشغيل اسأل ثروتي.</strong><span>{error}</span></div></main>;
  return <main className={styles.page} dir="rtl"><aside className={styles.sidebar}><div><div className={styles.brand}>ثروة</div><div className={styles.brandSub}>{paper?"محفظة تجريبية":"إدارة الثروة"}</div></div><nav className={styles.nav}><Link href={`/wealth${suffix}`} className={styles.navItem}>نظرة عامة</Link><Link href={`/wealth/assets${suffix}`} className={styles.navItem}>الأصول</Link><Link href={`/wealth/income${suffix}`} className={styles.navItem}>الدخل</Link><Link href={`/wealth/analytics${suffix}`} className={styles.navItem}>التحليلات</Link><Link href={`/wealth/shariah${suffix}`} className={styles.navItem}>الالتزام الشرعي</Link><Link href={`/wealth/accounts${suffix}`} className={styles.navItem}>الحسابات</Link><Link href={`/wealth/ask${suffix}`} className={`${styles.navItem} ${styles.active}`}>اسأل ثروتي</Link></nav></aside><section className={styles.workspace}><header className={styles.topbar}><div><p>{paper?"بيئة الاختبار":"المحفظة الحقيقية"}</p><h1>اسأل ثروتي</h1></div><div className={styles.actions}><Link href={paper?"/wealth/ask":"/wealth/ask?portfolio=paper"} className={styles.ghost}>{paper?"محفظتي الحقيقية":"محفظة تجريبية"}</Link><Link href={`/wealth/accounts${suffix}`} className={styles.primary}>الحسابات</Link></div></header><div className={styles.content}><section className={styles.contextBar}><div><small>يقرأ الآن</small><b>{paper?"المحفظة التجريبية":"المحفظة الحقيقية"}</b></div><div><small>صافي الثروة</small><b>{sar(f.total)}</b></div><div><small>الأصول</small><b>{fmt(holdings.length,0)}</b></div><div><small>الحسابات</small><b>{fmt(accounts.length,0)}</b></div><span>إجابات مباشرة من بيانات المحفظة الحالية — بدون تكلفة API إضافية.</span></section><section className={styles.chatShell}><div className={styles.chatHeader}><div><small>مساعد المحفظة</small><h2>اسأل عن أموالك بصيغة طبيعية</h2></div><span className={styles.liveDot}>بيانات حية</span></div><div className={styles.suggestions}>{suggestions.map(x=><button type="button" key={x} onClick={()=>ask(x)}>{x}</button>)}</div><div className={styles.messages}>{messages.map(m=><article key={m.id} className={`${styles.message} ${m.role==="user"?styles.user:styles.assistant}`}><div className={styles.messageLabel}>{m.role==="user"?"أنت":"ثروتي"}</div><p>{m.text}</p>{m.stats?.length?<div className={styles.answerStats}>{m.stats.map(s=><div key={`${m.id}-${s.label}`} className={s.tone?styles[s.tone]:""}><small>{s.label}</small><b>{s.value}</b></div>)}</div>:null}{m.link?<Link className={styles.answerLink} href={m.link.href}>{m.link.label}<span>←</span></Link>:null}</article>)}<div ref={end}/></div><form className={styles.composer} onSubmit={submit}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="مثال: كم نسبة أرامكو من ثروتي؟" aria-label="اسأل ثروتي"/><button type="submit" disabled={!input.trim()}>اسأل</button></form><div className={styles.disclaimer}>المساعد يصف ويحلل بيانات المحفظة المسجلة ولا يصدر توصيات شراء أو بيع.</div></section></div></section></main>;
}
